### ISSUE TITLE
Calling seqkit from other go programs

### ISSUE THREAD

**Issue by aboffin** [shenwei356/seqkit#10]
Hi Wei Shen,

Thank you for your hard work in developing seqkit. It's really a nice set of tools for handing various sequence formats.

I want to use seqkit functions inside my go program just like I would do from the command-line.

For example, from the command line: 
``` 
seqkit grep -p "header" big.fasta -o small.fasta
```
Now, I would like to do the same from inside my go program, something similar to:
```
import (
..
..
..
	"github.com/shenwei356/bio/seq"
	"github.com/shenwei356/bio/seqio/fastx"
	"github.com/shenwei356/breader"
	"github.com/shenwei356/xopen"
	"github.com/spf13/cobra"
)
..
..
..
seqkit.grep("header", bigFasta, smallFasta)
```

Is this possible?

**Comment by shenwei356** [comment]
of cause you can use the bio library (https://github.com/shenwei356/bio/tree/master/seqio/fastx ) to parse fasta/q seqs. but you need write the searching logic by youself of copy code in grep.go
