### ISSUE TITLE
Extra tabs inserted when running fx2tab on seqkit v0.11.0

### ISSUE THREAD

**Issue by OscarAspelin** [shenwei356/seqkit#104]
Hi, I use the seqkit (v0.11.0) software regularly and find it very useful. I have a question though about the tab output from fx2tab. When I run the following command "seqkit fx2tab --name --only-id --length --avg-qual <file.fastq>" the output contains two extra tabs (see below, although the formatting in github might mess up the tabs and spaces) between the read id and the read-length column. This became apparent when I loaded the tab file into pandas since there are two extra "NaN" columns between the id and length columns. Might it be an artefact from that the nucleotide and quality sequence are located there in the "full" output but that the tabs are still there when the nucleotide and quality sequences are suppressed (e.g., by the "--name" or "--length" or "--avg-qual" flags?) or that there is something wrong with my fastq file? Thanks in advance!

```
Sequence10			14	30.00
Sequence9			45	30.00
Sequence8			18	30.00
Sequence7			71	30.00
Sequence6			77	30.00
Sequence5			78	30.00
Sequence4			95	30.00
Sequence3			90	30.00
Sequence2			22	30.00
Sequence1			17	30.00

```

**Comment by shenwei356** [comment]
It's fixed three columns (header, seq, quality) for format compatibility, so `seqkit tab2fx` can recognize this and convert them back to FASTA/FASTQ

**Comment by shenwei356** [comment]
Hi @OscarAspelin , I've fixed this.  See #115
