### ISSUE TITLE
error when try rmdup

### ISSUE THREAD

**Issue by CaroleBelliardo** [shenwei356/seqkit#105]
Hello, 
I try to use your tool for remove duplicated sequence but i have an error message with both install ( classic and conda) 
$ seqkit rmdup ensembl_genome_20200130
output is : 
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x985d07]

goroutine 1 [running]:
github.com/shenwei356/seqkit/seqkit/cmd.glob..func20(0x1228bc0, 0xc0001e8c20, 0x1, 0x1)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/rmdup.go:118 +0x967
github.com/spf13/cobra.(*Command).execute(0x1228bc0, 0xc0001e8be0, 0x1, 0x1, 0x1228bc0, 0xc0001e8be0)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:833 +0x2aa
github.com/spf13/cobra.(*Command).ExecuteC(0x1228e40, 0xc00000d320, 0xc0003a1860, 0xc0000a8008)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:917 +0x2fb
github.com/spf13/cobra.(*Command).Execute(...)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:867
github.com/shenwei356/seqkit/seqkit/cmd.Execute()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/root.go:52 +0x31
main.main()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/main.go:58 +0x20

**Comment by shenwei356** [comment]
Please paste or upload few lines of sequences.

**Comment by shenwei356** [comment]
Any progress? @CaroleBelliardo

**Comment by CaroleBelliardo** [comment]
Sorry, i forgot to answer. I have make my own script...

**Comment by CaroleBelliardo** [comment]
thanks
