### ISSUE TITLE
feature request for fx2tab

### ISSUE THREAD

**Issue by devonorourke** [shenwei356/seqkit#108]
Thank you for developing and supporting a great piece of software!

I'm comparing the same input genome that has been softmasked by a few different parameters. I'd like to figure out the global degree of softmasking in each, per each nucleotide character.  

I was wondering if there was a way to change the behavior in the `fx2tab` command so that the case of the nucleotide could be discriminated in the output. At the moment, I believe the only option is for upper and lower case of the same letter character to be combined:
```
-B, --base-content value   print base content. (case ignored, multiple values supported) e.g. -B AT -B N (default [])
```

Perhaps this is a silly feature request, but I would love to have an option where a `--case-specific` flag option available so that the `--base-content` flag would be aware of the difference between an **A** and an **a**.  

For example, the current behavior of:
```
printf ">string1\nAAaa" | \
seqkit fx2tab -H -n -i -B A
```
...generates this output:
```
#name	seq	qual	A
string1			100.00
```

It would be great if there was a way to pass an additional flag (`--case-specific`):
```
printf ">string1\nAAaa" | \
seqkit fx2tab -H -n -i -B A --case-specific
```
... so that the output looked like this:
```
#name	seq	qual	A        a
string1			50.00.   50.00
```

many thanks!

**Comment by shenwei356** [comment]
A new flag:

    -I, --case-sensitive         calculate case sensitive base content


- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4236801/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4236806/seqkit_darwin_amd64.tar.gz)

**Comment by devonorourke** [comment]
Thanks very much - the new flag appears to be working as expected!
I think this feature can also find some use as a sanity check to make sure your input file has the expected character content (and not some unintended character). For example, in a genomic fasta file, I'd expect nothing but ACGTN (regardless of case). You can check on that now with something like:
```
cat dna.fasta | seqkit fx2tab -H -n -i --case-sensitive \
-B ACGTNacgt -B BDEFHIJKLMOPQRSUVWXYZbdefhijklmnopqrsuvwxyz
```

For some genome assemblies I've found that there can be distinct characters to indicate gaps (often `N`) and masked sites (also often `N`! but sometimes `X` or something entirely different). Having the ability to both check for character and upper/lower case content in one shot will save some headaches when you work with these patchwork assemblies.

Thanks again!

**Comment by devonorourke** [comment]
One other related feature request would be to have the capacity to report the absolute counts of the characters queried, rather than their frequencies. Perhaps there is already a seqkit tool available for this, but it would be great to know the per-character counts for each sequence.
As it is now, I could take the fraction reported and multiply by the length for each sequence to get a rough estimate, but it would be great to know the exact value.

:) cheers

**Comment by bsipos** [comment]
@devonorourke I guess the best way would be to enable checking of bases by regex. Then one could use character classes, which would describe the constraints in a more compact way.

**Comment by shenwei356** [comment]
Hi @devonorourke , @bsipos is right, you can use `seqkit locate` to find these bases.

see also: https://bioinf.shenwei.me/seqkit/faq/#how-to-find-fastaq-sequences-containing-degenerate-bases-and-locate-them
