### ISSUE TITLE
seqkit grep -r not working consistently between -f and -p

### ISSUE THREAD

**Issue by photocyte** [shenwei356/seqkit#11]
Hi there, 

I'm trying to extract a set of FASTA records by matching a string in the record descriptions.  It seems to work with a single string using "-p", but if I put the same string in a file and use "-f", it doesn't work.  See below.  Using seqkit v0.5.2 on linux.  Same issue happens on Mac OS X.

```
seqkit grep -n -r -p "DN12594_" latest_peptides.fasta | seqkit stat
file  format  type     num_seqs  sum_len  min_len  avg_len  max_len
-     FASTA   Protein         1      513      513      513      513

```
(working as intended)

```
less IDs.txt
DN12594_

```

```
hexdump IDs.txt
0000000 4e44 3231 3935 5f34 000a               
0000009
```

```
seqkit grep -n -r -f DNelson_ids3.txt latest_peptides.fasta | seqkit stat
file  format  type     num_seqs     sum_len  min_len  avg_len  max_len
-     FASTA   Protein    68,107  25,884,756       99    380.1    8,773
```
(Now it pulls out all the records, not intended behavior)

```
seqkit stat  latest_peptides
file                                                      format  type     num_seqs     sum_len  min_len  avg_len  max_len
151_Ppyr_v5_Trinity.fasta.transdecoder.pep_cleaned.fasta  FASTA   Protein    68,107  25,884,756       99    380.1    8,773
```

**Comment by shenwei356** [comment]
Hi Timothy, thanks for you feedback. 

It's a bug that I never tested. It's fixed now, and you can use the dev version: [v0.5.3-dev](https://github.com/shenwei356/seqkit/releases/tag/v0.5.3-dev)
