### ISSUE TITLE
Table header wrong in `seqkit fx2tab`

### ISSUE THREAD

**Issue by mptrsen** [shenwei356/seqkit#115]
The table header in the output of `seqkit fx2tab -H` (version 0.12.0) includes "seq" and "qual" even if these are suppressed by the `-n` option. If given the options `-Hnlq`, the order of the columns is wrong: "name seq qual length" in the header, "name NOSEQ length qual" in the table.

Expected: Table header according to the requested columns.

Example: 

```
$ seqkit fx2tab -Hn tests/Illimina1.5.fq
#name   seq     qual
HWI-EAS209_0006_FC706VJ:5:58:5894:21141#ATCACG/1
$ seqkit fx2tab -Hnlq tests/Illimina1.5.fq
#name   seq     qual    length
HWI-EAS209_0006_FC706VJ:5:58:5894:21141#ATCACG/1         100     37.55
```

### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

**Comment by shenwei356** [comment]
Thank you for feed backup. 

Fixed three columns (ID, sequence, quality) are outputted for either FASTA or FASTQ, even when flag -n/--name is on. It's for format compatibility. [Similar issue](https://github.com/shenwei356/seqkit/issues/104)  was submitted before.

```
$ seqkit fx2tab -Hn tests/Illimina1.5.fq | cat -A
#name^Iseq^Iqual$
HWI-EAS209_0006_FC706VJ:5:58:5894:21141#ATCACG/1^I^I$
```


You can just ignore the empty sequence and quality or discard them.



Column name for average quality is wrongly missing, fixed here.

**Comment by mptrsen** [comment]
I'm not sure a fixed column format is sensible, especially when two out of three are empty and when the documentation/help message implies that the sequence and quality columns can be disabled. It is obvious that `tab2fx` cannot convert columns that aren't there, so I would leave it to the user to make sure the format is right.

I understand that you don't want to change the format; please at least add some additional information to the documentation and help message to clarify.

You can close this issue if you consider it resolved.

**Comment by shenwei356** [comment]
You're very right, I fixed it. 

And `-i` and `-n` can be given simultaneously, producing same result with  `seqkit seq -n/-i`.

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4355453/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4355452/seqkit_darwin_amd64.tar.gz)
