### ISSUE TITLE
seqkit rmdup bus error

### ISSUE THREAD

**Issue by Lesdormis** [shenwei356/seqkit#116]
seqkit version v0.12.0

I am trying to remove duplicate sequences from a fastq.gz file that I concatenate from multiple fastq.gz files. 
I am using the seqkit rmdup and here is my code
zcat new_mRNA58_S1_L004_R2_001.fastq.gz | seqkit rmdup -s -o rmdup_new_mRNA58_S1_L004_R2_001.fastq.gz -D dup_R2.txt

I get an OOM error when I ran this on my local computer with 20GB memory.
So I transferred it onto the server and requested 96GB memory this time but got a new Bus error this time. 
/cm/local/apps/slurm/var/spool/job6669710/slurm_script: line 17: 350958 Done                    zcat new_mRNA58_S1_L004_R2_001.fastq.gz
     350959 Bus error               | seqkit rmdup -s -o rmdup_new_mRNA58_S1_L004_R2_001.fastq.gz -D dup_R2.txt

Thanks advance for your help!

**Comment by shenwei356** [comment]
bus error is not from seqkit. see https://github.com/marbl/canu/issues/62

**Comment by Lesdormis** [comment]
Thanks for the reply!
