### ISSUE TITLE
使用seqkit split的功能，结果文件输出问题

### ISSUE THREAD

**Issue by moruikang** [shenwei356/seqkit#12]
我想均等切分fq文件，使用seqkit split -p fq，结果输出的fa格式变成了如下格式：
@CL100006359L1C001R001_1/2
AAAAATTGAACATCAGGATGCAGCTAGGAAAAGGGGTTCCTGGAAACACCCTCACAAGCT
TTGTAAGTAATACAACTAAGTAGAAATAAACTAATATAAA
+
FDDFBDF:9A8CF;D7=DDF8F*ADF>@;DE07?<7FF>'E6FEC8CFD568DFFDFFAC
E4E@DEEBFE?F(EE4FF>@<D&A:FDF,D1F@F7D;'EA
@CL100006359L1C001R001_11/2
CCTAGTTTTCTGCTGAGCCTGCCGTAAAGTATTTTCAGCACCTTCGACCGTGACAAAGCT
CCAACCTGACTGGAGGCATTGTGTAGCGAAGGGAGCTTGG
+
24=9>89446=1686&B-;6=*638C60?=17<7*,65):?7)8'1,%))+8'&(:6=95
3=&,&3/.'183F0=(.&<'C/B19=19)A9-3=9>;1.&

也就是说不是标准的fq格式了，这个要怎么设置才能换换成标准fq格式？

**Comment by shenwei356** [comment]
Forgot not to wrap sequence and quality in output for FASTQ format. You can fix this by adding option `-w 0`.
