### ISSUE TITLE
Addition of (C)Python bridge/API, via gopy [feature request]

### ISSUE THREAD

**Issue by cviner** [shenwei356/seqkit#123]
This exceptionally useful package is currently limited to mainly end-user applications or Bash/GO developers, due its being implemented in the GO programming language. For instance, I am currently starting a new project, that would benefit from an advanced FASTQ parser, like this, but will be using Python 3.8.

Since much of bioinformatics is currently being developed in Python or C/C++, the ability to directly integrate this into large development projects would be greatly facilitated by the provision of CPython bindings. This could be implemented via [`gopy`](https://github.com/go-python/gopy). Ideally, this would also include the ability to portably parse FASTQs and transfer them into native Python data structures, perhaps even including [Pandas](https://pandas.pydata.org/) compatibility. 

With careful attention to the bindings, with respect to this software's design, this could be used to provide a comprehensive set of Python bindings. This could greatly facilitate additional use of this software, across new application domains!

**Comment by shenwei356** [comment]
Thanks. But this tools is designed for end-user.

For efficiently parsing FASTQ, I think htslib interface for python like pysam is a better choice.

**Comment by cviner** [comment]
Fair enough—thanks!
