### ISSUE TITLE
mismatches don't work with grep on amino acid sequences

### ISSUE THREAD

**Issue by mptrsen** [shenwei356/seqkit#124]
`seqkit grep` (v0.12.1) doesn't allow mismatches (`-m`) when working on amino acid sequences.

Example:

```
$ seqkit version
seqkit v0.12.1
$ cat test.fa
>test
AVKCMLLHSFH
$ seqkit grep -s -m 2 -p 'AVKCMLLHSFQ' test.fa
$ seqkit grep -s -m 2 -p 'AVKCMLLHSFH' test.fa 
>test
AVKCMLLHSFH
```

Expected:
- Find the sequence despite the single amino acid mismatch at the end

### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

**Comment by shenwei356** [comment]
Thanks for reporting this, it's a bug of the FMI package, I'll fix this.

**Comment by shenwei356** [comment]
Fixed

- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/4496867/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4496864/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4496866/seqkit_linux_amd64.tar.gz)

**Comment by mptrsen** [comment]
Thanks for fixing this so quickly!

**Comment by shenwei356** [comment]
The bug is compeletely fixed. #179
