### ISSUE TITLE
Not able to generate compressed output when using `>`

### ISSUE THREAD

**Issue by matrs** [shenwei356/seqkit#126]
Hello, 
thanks for this software, it's been very useful to me.
I'm using `seqkit v0.12.1` in `linux arch 5.5.18`

I just noticed that compressed output isn't generated when using bash redirection:
```bash
$ seqkit sample -n 1000 viral.2.1.genomic.fna.gz > viral.2.1.sub.genomic.fna.gz
$ seqkit sample -n 1000 viral.2.1.genomic.fna.gz -o viral.2.1.subo.genomic.fna.gz

$ seqkit locate --degenerate --ignore-case --pattern-file enzymas.fa \
viral.2.1.sub.genomic.fna.gz -o pattern_enzymes.tsv.gz

$seqkit locate --degenerate --ignore-case --pattern-file enzymas.fa \
viral.2.1.sub.genomic.fna.gz > pattern_enzymes.tsv.gz

$ file viral.2.1.sub*
viral.2.1.sub.genomic.fna.gz:  ASCII text
viral.2.1.subo.genomic.fna.gz: gzip compressed data, original size modulo 2^32 23199426

$ file pattern_enzymes*
pattern_enzymes.o.tsv.gz: gzip compressed data, original size modulo 2^32 2326237
pattern_enzymes.tsv.gz:   ASCII text
```
Which isn't a problem by itself, but It isn't mentioned in the documentation in any way. Is this the expected behaviour or has to do with bash redirection in some (technical) way?, because it's really surprising to me but maybe I'm missing something.

**Comment by shenwei356** [comment]
seqkit xxx | gzip -c > a.gz

**Comment by shenwei356** [comment]
Outputing to stdout in plain text is for readability, just like cat, cut, awk and most CLI tools. You can compress by yourself if needed.

**Comment by matrs** [comment]
Ok, thanks
