### ISSUE TITLE
Grep without regular expression

### ISSUE THREAD

**Issue by MichWeb75** [shenwei356/seqkit#128]
The search with grep only returns results if one uses a regular expression

Does not work 
seqkit grep -p "tet" resfinder.fasta

Does wotk:
seqkit grep -rp "tet" resfinder.fasta

**Comment by shenwei356** [comment]
yes, it is how the command works, check help message:

https://bioinf.shenwei.me/seqkit/usage/#grep

**Comment by MichWeb75** [comment]
Thanks , so used to Linux grep!
