### ISSUE TITLE
seqkit sample: line length

### ISSUE THREAD

**Issue by psaxcode** [shenwei356/seqkit#13]
Hi Wei, 
Is there a rationale for breaking the reads in a FASTQ file into 60-bp lines? I find that some downstream tools can not correctly recognize the  sequence sections of the FASTQ files generated by seqkit sample command.  
Thank you

**Comment by shenwei356** [comment]
Hi, please make sure you're using the latest version by run `seqkit version`.

**Comment by psaxcode** [comment]
I upgraded the software and now it is seqkit v0.5.3. But seqkit sample -n 100 my.fastq.gz gave me the same result, i.e. the sequence of a read is stored in lines of 60nt long.

**Comment by shenwei356** [comment]
Oh right, I see. For now, just add an option `-w 0`. And I'll fix it. Thanks for your feedback.

**Comment by shenwei356** [comment]
fix in [v0.5.4](https://github.com/shenwei356/seqkit/releases/tag/v0.5.4)
