### ISSUE TITLE
seqkit rename --mapfile rename.tsv ?

### ISSUE THREAD

**Issue by tseemann** [shenwei356/seqkit#131]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

I want to rename all the sequences in my FASTA
I have a TSV/SSV file of   `old_id  \t new_id \n` 
i don't think `seqtk rename` can do this?

**Comment by shenwei356** [comment]
Use `seqkit replace`, [usage](https://bioinf.shenwei.me/seqkit/usage/#replace) Example 7.

I'll add guide in help message of `seqkit rename` to classify relationship of `seqkit rename` and `seqkit replace`.

**Comment by tseemann** [comment]
Thank you for explaining. I understand now that I can use a regexp and a key-value map to do the renaming. Be good to have a simpler method, as it is a common thing to do.
