### ISSUE TITLE
seqkit seq -s option is breaking down the single line sequence

### ISSUE THREAD

**Issue by cpad0112** [shenwei356/seqkit#132]
seqkit version: seqkit v0.12.0

Input fasta:
 ```
 >419759601_1
GTCTTGCATCTATAGTATTTTTACCCTGGTGGATATCTCTATCATTTCAAAAAAGTCTGGAATCTTGGGTTACTGATTCGTGGAATATTAAACAATCTGCAACTTTTTTGAATGATATTCTAGAAACTAGTCTTCTAGAAAAATTCAACGA

```
issue:

1. Input fasta copy/pasted above is a single line fasta.
2. Seqkit -s is supposed to print sequence as a sequence without changing the input format. Otherwise, user has to type in `seqkit -sw0` for extracting sequences in a single line from a flattened fasta file.
3. Seqkit -s is printing sequence in 3 lines (probably at 60 characters per line- not sure of this) as below:
```
$ seqkit seq -s test.fa 
GTCTTGCATCTATAGTATTTTTACCCTGGTGGATATCTCTATCATTTCAAAAAAGTCTGG
AATCTTGGGTTACTGATTCGTGGAATATTAAACAATCTGCAACTTTTTTGAATGATATTC
TAGAAACTAGTCTTCTAGAAAAATTCAACGA

```
To check if sequence is indeed is broken into 3 lines, into three lines, following code was run:

```
seqkit seq -w 0 test.fa | seqkit seq -s | sed -n '3p'
TAGAAACTAGTCTTCTAGAAAAATTCAACGA
```
Third line is `TAGAAACTAGTCTTCTAGAAAAATTCAACGA`

Expected behaviour:

```
$seqkit seq -s test.fa
GTCTTGCATCTATAGTATTTTTACCCTGGTGGATATCTCTATCATTTCAAAAAAGTCTGGAATCTTGGGTTACTGATTCGTGGAATATTAAACAATCTGCAACTTTTTTGAATGATATTCTAGAAACTAGTCTTCTAGAAAAATTCAACGA
```

sequence should be printed without gaps, in a single line.

**Comment by shenwei356** [comment]
It makes sense, I'll fix this.
