### ISSUE TITLE
"1 1" at the top of translation results

### ISSUE THREAD

**Issue by YiweiZhu** [shenwei356/seqkit#133]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
Hi, Dr. Shen,
Why does it always print "1 1" at the top of translation results? What does it mean? How can I avoid it?
* [x] provide a reproducible example
>echo -e ">seq\nATGCCC\n" | seqkit translate -T 11 --trim
>1 1
>seq_frame=1 
>MP

**Comment by shenwei356** [comment]
Sorry, it's a debug behavior forgotten to delete.
Here are the fixed version.


[seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4672083/seqkit_linux_amd64.tar.gz)
[seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/4672084/seqkit_windows_amd64.exe.tar.gz)

**Comment by YiweiZhu** [comment]
Thank you, Dr. Shen!
