### ISSUE TITLE
Combining multiple UCE baits by name

### ISSUE THREAD

**Issue by Deco313** [shenwei356/seqkit#136]
HI,
I am new to the software and I cannot seem to figure out how to concatenate lines within a single fasta by ID. for example 

```
>uce-1111268_p1 
seq
>uce-1111268_p2 
seq
all the way to 
>uce-1111268_p9

```
How to I combine to get

```
>uce-1111268
long sequence. 

```

I have thousands in the same file.

Sorry if this is vague. I can only see options for joining multiple fasta files together rather than edit a single one.

**Comment by jmonroynieto** [comment]
assuming you just want to concatenate them, I suggest we work around it with basic tooling. I am not sure if there is a more streamlined feature but I hope it still helps.

Use the following command:
`echo ">whateverID" >> file.fasta; seqkit seq -s test.fasta | awk '{printf$0}' >> file.fasta`

This will concatenate all sequences.
I used it in the [15 Scaffold, 17Mbp genome of Cryptococcus neoformans](https://www.ncbi.nlm.nih.gov/genome/61?genome_assembly_id=52487), and that took very little time.

```
time echo ">whateverID" >> outTest.fasta; seqkit seq -s H99.fasta | awk '{printf$0}' >> outTest.fasta

real	0m0.004s
user	0m0.000s
sys	0m0.000s
```

**Comment by Deco313** [comment]
Thanks @jmonroynieto. So using seqkit split -i --id-regexp "(.*)_" test.fasta i now have a folder with 6000 files all named like test.fasta.id_uce-IDnumber.fasta

However i have 6000 ID numbers. How can i loop this to end up with 

>uce-IDXXX
AGTCGTCGCTGCTCT
>UCE-ANotherID
ATGCATGCTAGC
...
etc

in one large fasta file. 
I do not want to have to constantly change the below ID manually
time echo ">whateverID" >> outTest.fasta; seqkit seq -s H99.fasta | awk '{printf$0}' >> outTest.fasta

Sorry if this is not the most appropriate forum. Looping is just one of the things I am not good at,

**Comment by jmonroynieto** [comment]
Loops are easy_er_ when you understand 

- how to modify strings with [bash or awk or sed](https://www-users.york.ac.uk/~mijp1/teaching/2nd_year_Comp_Lab/guides/grep_awk_sed.pdf)
- how to use bash [parameter expansions](https://www.gnu.org/software/bash/manual/html_node/Shell-Parameter-Expansion.html)
- you need to be organized/lucky enough to have regular patterns in the filename or contents. 

I'll iterate through all the files that you want to analyse. I'll use the filename to formulate what the ID should look like and the rest is the same.

```
for file in test.fasta.id_uce*fasta; do number=${file%%.fasta}; number=${filename##test.fasta.id_uc-ID}; echo ">uce-ID${number}" >> out-${number}.fasta; seqkit seq -s $file | awk '{printf$0}' >> out-${number}.fasta
```

if you need other info for the ID; change the parameter expansions (The two commands after the "do" keyword) and add whatever other information you need.

For me, loops became clearer when I had [this question](https://unix.stackexchange.com/questions/430402/recursively-move-specific-files-in-nested-directories-to-a-name-derived-from-the) answered. Understanding it as an example might be enriching to you.

**Comment by Deco313** [comment]
Thank you, 
I got this to work! Thanks for your help and for the link.
