### ISSUE TITLE
Utilizing FM-index in "locate"  and "grep"

### ISSUE THREAD

**Issue by shenwei356** [shenwei356/seqkit#14]
So we can make the searching faster and allow [mismatch](https://godoc.org/github.com/shenwei356/bwt/fmi#FMIndex.Locate).

I've written a package, [bwt](https://github.com/shenwei356/bwt) (Burrows-Wheeler Transform, and FM-index in golang). So it won't be too long.

update: there are some bugs...

**Comment by ctava** [comment]
@shenwei356 see the [bwt](https://github.com/shenwei356/bwt) repo. have the following questions:

whats the difference between the locate and grep commands?

could this be done for the locate command first?
https://github.com/shenwei356/bwt/blob/master/fmi/fmi.go#L62
https://github.com/shenwei356/bwt/blob/master/fmi/fmi.go#L102

How do you envision this struct fitting in?
https://godoc.org/github.com/shenwei356/bwt/fmi#FMIndex

why limit region?
https://github.com/shenwei356/seqkit/blob/master/seqkit/cmd/grep.go#L115

noticed burrows , wheeler is a compression algorithm:
https://en.wikipedia.org/wiki/Burrows%E2%80%93Wheeler_transform

whats the goal to make search faster? how does compression help?
assuming benchmarking before and after is needed?

to what degree should mismatch be allowed?
locate already supports mismatches..
https://github.com/shenwei356/seqkit/blob/master/seqkit/cmd/locate.go#L72

**Comment by shiva1387** [comment]
Hi, question pertaining to memory and speed. I would like to use locate on an ncbi database (~50 to 100 million sequences), for finding sequences that match specific patterns. Currently locate does not make use of the fasta index, can i make use of that to increase speed? Any other suggestions? Thankis

**Comment by shenwei356** [comment]
Try BLAST?

**Comment by shiva1387** [comment]
Sorry to be clear, i am searching for either degenerate sequence or using regular expressions (for protein motifs) so blast wont help for either case..
