### ISSUE TITLE
seqkit amplicon - option for BED file ?

### ISSUE THREAD

**Issue by tseemann** [shenwei356/seqkit#141]
seqkit amplicon currently outputs a FASTA file
Could it also output a BED file?
eg.
`SEQID \t START \t END \t . \t NAME \t SCORE \t STRAND  \t AMPLICON_SEQ`

https://en.wikipedia.org/wiki/BED_(file_format)#Description

**Comment by shenwei356** [comment]
output in BED6+1 format with amplicon as 7th column.

see #142
