### ISSUE TITLE
seqkit amplicon - --infile list of named primer pairs?

### ISSUE THREAD

**Issue by tseemann** [shenwei356/seqkit#142]
seqkit amplicon only works with one primer pair
could it take a primer table TSV
```
primer_name \t  left_primer \t right_primer \n
```
And run each of them.

The primer name could go in the `NAME` column on the proposed BED file.

The SCORE could be how well it matched.

**Comment by shenwei356** [comment]
1. Load primers from 3- or 2-column tabular primer file, with first column as primer name.
        
        $ cat seqs4amplicon.fa 
        >seq1
        acgcccactgaaatga
        >seq2
        acgtacggtcaga
        
        $ cat primers.tsv 
        p1      ccc     ttt
        p2      ttt     ccc
        p3      CG      TG
        
        $ cat seqs4amplicon.fa | seqkit amplicon -p primers.tsv --bed
        seq1    3       13      p1      0       +       cccactgaaa
        seq1    1       7       p3      0       +       cgccca
        seq1    3       13      p2      0       -       tttcagtggg
        seq2    1       11      p3      0       +       cgtacggtca
