### ISSUE TITLE
Feature request: faidx could return reverse complement when start>end

### ISSUE THREAD

**Issue by Shellfishgene** [shenwei356/seqkit#143]
Hi!

Currently faidx returns no sequence when the coordinates given are reversed, i.e. `scf123:20-15`. It would be convenient if faidx in that case returned the reverse complement of the sequence from bases 15 to 20.

Cheers

**Comment by shenwei356** [comment]
I'm sorry, I won't add this feature, because it's not compatible to protein sequence. 

You can pipe the subsequence to `seqkit seq -r -p ` for reverse complement sequence.

**Comment by Shellfishgene** [comment]
Makes sense, thanks.
