### ISSUE TITLE
DNA sequence hashing

### ISSUE THREAD

**Issue by avilella** [shenwei356/seqkit#144]
Feature request:

Given a DNA sequence, convert into a number by hashing in base 2 as shown below:

mapping = {'A': '00', 'T' = '01', 'G': '10', 'C' = '11'}

produce a value of zero if there are non-ACGT values.
For RNA, we could have T=U in case there are Us.

Example:
```
cat file.fasta | seqkit hash -t DNA
>foo
348128344908321234
>bar
32049201394320
```

Maybe the output should be tabular as the output of `seqkit fx2tab`?

Maybe this is already somehow implemented internally in the deduplication code, not sure. It's useful (for me) when wanting to give a short(ish) numerical value that would be unique to each unique DNA sequence. Thx

**Comment by shenwei356** [comment]
Yes, it's easy to implement. Just call a fast hash function on any sequence (string), but it's irreversible.
Similarly, [unikmer encode](https://github.com/shenwei356/unikmer) can convert dna/rna (<=32bp）to reversible uint64 values.

**Comment by shenwei356** [comment]
Implemented in `seqkit fx2tab -s/--seq-hash`.

**Comment by jolespin** [comment]
I use this to get [id]<tab>[hash]

```
pv query.fasta.gz | seqkit fx2tab -s -n > id_to_hash.tsv
```
