### ISSUE TITLE
Remove duplicates by ID, retaining longest sequence

### ISSUE THREAD

**Issue by rspreafico-vir** [shenwei356/seqkit#145]
It would be handy for certain applications to make sure that when removing duplicates by name/id, the longest sequence is retained. That would require to pre-sort by length, which however fails in the presence of duplicated name/id.

**Comment by shenwei356** [comment]
`seqkit sort` should allow duplicated name/id, I'll fix this.

A workaround solution for now:

```
cat seqs.fa  \
    | seqkit replace -p '^' -r '{nr} ' \
    | seqkit sort -lr | seqkit rmdup --id-regexp '^\S (.+)' \
    | seqkit replace -p '^\S '
```
