### ISSUE TITLE
Error with --pattern N+

### ISSUE THREAD

**Issue by foala** [shenwei356/seqkit#146]
Hi,
I am trying to locate all the Ns in my fasta file. Some of them are very long stretches of Ns.
I used 
`seqkit locate --ignore-case --only-positive-strand --pattern K+ --pattern N+ my.fasta`
as shown in https://bioinf.shenwei.me/seqkit/faq/
But I get the following error 

> [ERRO] illegal DNA/RNA/Protein sequence: n+, you may switch on -d/--degenerate or -r/--use-regexp

Please assist
Thank you,

**Comment by shenwei356** [comment]
seems a bug

**Comment by foala** [comment]
Thanks.
Can you suggest a way to locate all the stretches of gaps (Ns) and their coordinates?
Thank you very much,

**Comment by shenwei356** [comment]
oh! you just need switch on option `-r`! the doc was not updated.
