### ISSUE TITLE
Extend functionality to subseq as replace when handling headers (enhancement/ feature request)

### ISSUE THREAD

**Issue by ssvbio** [shenwei356/seqkit#154]
Seqkit version v0.12.0, Ubuntu focal, 64bit

I am referring to https://www.biostars.org/p/452821/ issue. Here user wanted to extract peptide fragments based on name, start and end coordinate. It would have helped if there is a provision to define header as replace. In FAQ section of seqkit, replace is shown to reuse replacement pair and captured key index. (copy/pasted: --replacement "\${1}{kv} " --key-capt-idx 2). In subseq, is it possible to use the header with captured key indices and also to use combination of indices as --key-capt-idx?

**Comment by shenwei356** [comment]
How about adding a global flag `--key-capt-idx` for sekqit?

**Comment by cpad0112** [comment]
Sounds good to me. Thanks for the response.

**Comment by shenwei356** [comment]
Wait a minute, I don't get the point.  Seems there's no need. Could you please give a example?
