### ISSUE TITLE
Can't generate output file

### ISSUE THREAD

**Issue by jrede** [shenwei356/seqkit#155]
### Prerequisites

- [X] make sure you're are using the latest version by `seqkit version`
- [X] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [X] describe the problem
I receive the following error message when trying to generate an output file - [ERRO] open LSUParc_dna.fasta.gz: no such file or directory

The file doesn't exist because I am trying to create the file. So I'm not sure why this is causing an error.

* [x] provide a reproducible example

code:

    seqkit seq --rna2dna SILVA_132_LSUParc_tax_silva_trunc.fasta.gz --out-file LSUParc_dna.fasta.gz

**Comment by shenwei356** [comment]
Thank you very much, you've found a [bug](https://github.com/shenwei356/seqkit/commit/1add3d2834fdbb040f0a225a2a9c5b1bbb6d249f) that may has been existed for 4 years.

`seqkit seq` outputs file using an independent way, so all other commands are not affected. And I am used to outputting using redirecting `>` , so did not find this for 4 years... Thank you @jrede  !

**Comment by shenwei356** [comment]
By the way, it's a stupid bug that should never happen.

**Comment by jrede** [comment]
Thank you for responding! And I didn't know about the > and >> methods for writing files, so thanks for that too!
