### ISSUE TITLE
Can you add a "Pairing Fastq or Fasta" to the seqkit?

### ISSUE THREAD

**Issue by Zea1nfO** [shenwei356/seqkit#156]
Hi sir
At first , i wanna say the seqkit is great tools to handle fasta and fastq file. And I really like it.
But i got little advice for you guys.
When i use seqkit`s grep function to filt my paired-end reads file, i always got two not-total-paired reads file.
Then i must write some script to make it paired(filt out the unpaired reads and sort the reads by id).
So can we add some thing into the grep command or just add a module to make paired-end reads paired?
Thanks a lot.
:)

**Comment by shenwei356** [comment]
See this: https://bioinf.shenwei.me/seqkit/faq/#how-to-extract-paired-reads-from-two-paired-end-reads-file

**Comment by Zea1nfO** [comment]
Thank you sir.
Best regards.
:)

**Comment by shenwei356** [comment]
@Zea1nfO  A new command `seqkit pair` added for this.

#157

**Comment by Zea1nfO** [comment]
@shenwei356 That`s really great. Thanks a lot.
