### ISSUE TITLE
seqkit translate now appends the frame to the name

### ISSUE THREAD

**Issue by ryandward** [shenwei356/seqkit#159]
After 0.11.0 seqkit now appends the frame to the name of the amino acid sequence

`seqkit translate -f1 -x -w0 -T11 -x -M some.fasta` used to yield something like this:

``>ABUW_3904
MVRILRWFIRLYQIAISPLLGPRCRYIPTCSQYALEALQTHGAIKGVWLSSKRICRCHPWGGSGYDPVPPKAIRFISFHQIDSQTHHVAVPFRDRLMKQNLSNHLG*``
 
instead, now it yields:

``>ABUW_3904_frame=1
MVRILRWFIRLYQIAISPLLGPRCRYIPTCSQYALEALQTHGAIKGVWLSSKRICRCHPWGGSGYDPVPPKAIRFISFHQIDSQTHHVAVPFRDRLMKQNLSNHLG*``

I was wondering if there is a switch to turn this off, since using the newest version breaks compatibility with downstream scripts on my end.

Thanks
Ryan

**Comment by shenwei356** [comment]
It's optional now, with a new flag:

```
  -F, --append-frame                            append frame information to sequence ID
```
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/5252862/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5252860/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5252859/seqkit_darwin_amd64.tar.gz)

**Comment by ryandward** [comment]
Thank you, that must've been my oversight!

**Comment by YiweiZhu** [comment]
Hi @shenwei356 ,
I find in this new edition, the translation result lack the symbol ">" before sequence name, if not add the new flag "-F".
`echo -e ">seq\nATGCCC\n" | seqkit translate`
`seq`
`MP`
`echo -e ">seq\nATGCCC\n" | seqkit translate -F`
`>seq_frame=1`
`MP`

**Comment by shenwei356** [comment]
Oh, sorry! it's a stupid bug.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5286254/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5286255/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/5286256/seqkit_windows_amd64.exe.tar.gz)
