### ISSUE TITLE
[Feature] duplicating sequences XX times

### ISSUE THREAD

**Issue by germelcar** [shenwei356/seqkit#16]
Hi there:

I think that a great feature that can be added to `seqkit sample` is duplicating the samples, that is, if I want to copy XX times the whole multifasta or the sampled sequences, for example:

`seqkit sample -s 10 -t 2`

Thinking as the `t` argument as `times`. With that option, I am sampling 10 sequences two times. Something similar can be used for duplicating the whole multifasta XX times. Currently, I need to generate a multifasta copying the initial multifasta 675 times, only for testing purposes.

By now, I couldn't find an option for doing that, so... I will use the shell.

Thanks in advance.
Best.
~g

**Comment by shenwei356** [comment]
Right, duplicating sequences records is useful in some cases.

I once have this need in preparing testing data. I used `cat file file > 2file`  but that need some steps.

We can add a command `dup` for duplicating sequences records N times.

Thank you @germelcar .

**Comment by shenwei356** [comment]
supported in v0.6.0 https://github.com/shenwei356/seqkit/releases/tag/v0.6.0
