### ISSUE TITLE
Add flag for "rmdup" to also report singletons

### ISSUE THREAD

**Issue by ms-gx** [shenwei356/seqkit#160]
It would be helpful for me if command `rmdup` would have a flag to also output singletons if needed. This would change the command to kind of a "clustering" on 100% identity.

This would probably mean that one has to modify bit of code around line 151 of `rmdup.go`:
`if len(l) > 1 {`

Since it is such a small adjustment I will not implement this and do a pull request. Probably easier for you if you do this by yourself if you think it makes sense.

**Comment by ms-gx** [comment]
I changed the `1` above to `0` and compiled. That results in a good workaround in the meantime.

**Comment by shenwei356** [comment]
Just retrieve sequence ID from result.

    seqkit rmdup | seqkit seq -n -i

**Comment by ms-gx** [comment]
Thanks Wei!

The problem is that I also would like to have to grouping information which comes as an output from `rmdup` via parameter `-D`. But I can see that that `rmdup` (also simply by its name) is made for another purpose and that you don't want to include the singletons, since this would be not the task of removing duplicates any more, but rather "deduplicate".

I might switch to CD-HIT and just cluster on 100% identity...

**Comment by shenwei356** [comment]
Right CD-HIT or other clustering tools could be more appropriate.
