### ISSUE TITLE
Error message if disk is full?

### ISSUE THREAD

**Issue by flashton2003** [shenwei356/seqkit#161]
Hello,

I just spent a few minutes trying to fix a problem with seqkit grep not writing to files, but it turns out that my hard disk was full.

I know this primarily falls on me to notice, but could seqkit perhaps give a warning if it can't write because the disk is full?

Thanks,

Phil

**Comment by shenwei356** [comment]
> a problem with seqkit grep not writing to files, but it turns out that my hard disk was full.

How did it exhaust disk if not writing to files?

> could seqkit perhaps give a warning if it can't write because the disk is full

It's hard to predict output size, especially for STDIN. So users have to leave enough disk space for output.

**Comment by flashton2003** [comment]
The disk had been filled up by another process.

Ok, no problem.
