### ISSUE TITLE
seqkit mutate -i runtime error: slice bounds out of range

### ISSUE THREAD

**Issue by jpgsu** [shenwei356/seqkit#162]
Hi, 
I got the following error when I try to use seqkit v0.13.2 to insert long sequence into GRCh38.
Any help would be appreciated.

command:
`
seqkit mutate -i 167735084:TCCCCCACCGACCTCCCCCACTGACCTCCGCCGCTGACTTCCCCTGCTGACCTCTGCCACTGACCTCCCCCTCTGACCTCTGCCGCTGACCTCCACCGCTGACCTCCCCGCTGACCTTCCGCCAACCTCTGCCGCTGACCTCCCCCTCTGACCTCCGCCATTGACCTTCCCTGCTGACCTCCACCGCAGACCTCCCCCGCTGACCTCTGCCGCTGACGTCCCCCACTGACCTCCCCCTCTGACCTCCGCCACTGACCTCCGCAGCTGACATCCCCGCTGACCTCCCCGCTGACCTCCGCCACTGACCTCTGCCACTGAACTCCACTGCTGACCTCCCCCACTGGCCTCTGCTGCTGACCTCTGCCGCTGGCCTCCCCCACTGACCTCCCCGCTGACCTCCCCGCTGACCTCCCCGCTGACCTCCCCACTGACCTCTGCCACTGACCTCTGCCGCTGACCTCCCCCACTGACCTCTGCTGCTGACCTCTGCTGCTGCCCTCCCCGCTGACCTCCCCCACTGACCTCTGCCACTGACCTCTGCTGCTGACCTCCCCTGCTGACCTCTGCTGCTGACTTCTGCCACTGACCTCTGCCGCTGACCTCTGCTGCTGACCTCCCCCGCTGACCTCTGCTGCTGACCTCCGCAGCTGACATCCCCCGCTGACCTCCCCCGCTGACCTCCGCCACTGACCTCCGCAGCTGACATCCCCCGCTGACCTCCCCCGCTGACCTCCGCCACTGACCTCTGCCACTGACCTCCACTGCTGACCTCCCCCACTGGCCTCTGCCGCTGCCCTCCACCGCTGGCCTCCCCGCTGACCTCCCCCGCTGACCTCCCCCGCTGACCTCCCCCACTGACCTCTGCCACTGACCTCTGCTGCTGACCTCTGCCACTGACCTCTGCCGCTGACCTCCCCCACTGACCTCTGCTGCTGACCTCTGCTGCCCTCCCCCGCTGACCTTCCCCACTGACCTCCCCCACTGACCTCTGCTGCTGACCTCTGCTGCTGACCTCTGCTGCTGCCC -s chr6 ../grch38/genome.fa > output.fasta
`

error:
```
[INFO] edit seq: chr6  AC:CM000668.2  gi:568336018  LN:170805979  rl:Chromosome  M5:5691468a67c7e7a7b5f2a3a683792c29  AS:GRCh38
panic: runtime error: slice bounds out of range [:338541063] with capacity 268453306

goroutine 1 [running]:
github.com/shenwei356/seqkit/seqkit/cmd.glob..func15(0x12d6140, 0xc00009c9b0, 0x1, 0x5)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/mutate.go:305 +0x25b8
github.com/spf13/cobra.(*Command).execute(0x12d6140, 0xc00009c960, 0x5, 0x5, 0x12d6140, 0xc00009c960)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:846 +0x29d
github.com/spf13/cobra.(*Command).ExecuteC(0x12d7100, 0xc00000d740, 0xc0002228d0, 0xc00000e020)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:950 +0x349
github.com/spf13/cobra.(*Command).Execute(...)
	/home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:887
github.com/shenwei356/seqkit/seqkit/cmd.Execute()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/root.go:53 +0x31
main.main()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/main.go:58 +0x20
```

**Comment by shenwei356** [comment]
It's fixed. This bug occurs when `insert site` is big in some rare cases.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5362374/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5362375/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/5362376/seqkit_windows_amd64.exe.tar.gz)

**Comment by jpgsu** [comment]
It works. Thanks for your help and the great tool.
