### ISSUE TITLE
seqkit replace with FASTQ does not respect quality scores

### ISSUE THREAD

**Issue by vmikk** [shenwei356/seqkit#163]
Hello!

Removal of nucleotides (`seqkit replace -r ""`) in FASTQ does not modify quality string.

Reproducible example:
```
seqkit replace -p "^n+|n+$" -r "" -is - <<EOT
@s1
NNGGCTGCNN
+
..FFFFFF..
EOT
```

It strips the sequence: `NNGGCTGCNN` -> `GGCTGC`
However, the quality string remains the same: `..FFFFFF..`
The expected behaviour is to remove the corresponding characters in the quality line (to `FFFFFF`), isn't it?

Piping the output of this replacement command to the next `seqkit` commands triggers the error
`[ERRO] fastx: bad fastq format`.

seqkit v0.13.2

With kind regards,
Vladimir

PS. Thank you for the great software!

### Prerequisites
- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue
* [x] describe the problem
* [x] provide a reproducible example

**Comment by shenwei356** [comment]
It looks indeed a bug, but why do you remove `N` in the *middle* of **FASTQ** sequences? 

Do you want extract some fragment in reads? Does `seqkit amplicon` help ?

**Comment by vmikk** [comment]
Here I just want to remove leading (^n) and trailing (n$) Ns from the reads.

**Comment by shenwei356** [comment]
Oh, I see, you may try other FASTQ preprocessing tools like fastp before I fixing this.

**Comment by shenwei356** [comment]
I decide to disable editing FASTQ sequence, it's not suitable.
