### ISSUE TITLE
amino acids sequence motif 

### ISSUE THREAD

**Issue by dbustoslab** [shenwei356/seqkit#165]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

I would like to use seqkit to search aa motif in proteomic date. For example, in a file containig 15000 fasta file of different proteins I would like to identify those containing the following motif
R[DE]{0,2}[DEPG]([ST])[P]{0,1}$
first posistion: R
2nd: D or E
3th: could be any aa (dot) or D/E/P/G
and so on
$ means that that partern is locate at the protein C-terminal
Thanks!

**Comment by shenwei356** [comment]
I just noticed that `seqkit locate/grep` does support searching with degenerated amino acid residues.

Due to existence of comma in the motif, here, you just need use `"` to quote the searching pattern. Because the command line argument parser accepts comma-separated-values (CSV) for multiple values.

    seqkit grep -i -r -p '"R[DE]{0,2}DEPG[P]{0,1}$"'

or

    seqkit grep -i -r -p "\"R[DE]{0,2}DEPG[P]{0,1}$\""

Or save the motif in FASTA file.

    cat motif.fa
    >C-terminal
    R[DE]{0,2}DEPG[P]{0,1}$

And use

    seqkit grep -i -r -f motif.fa

I update the help message of [seqkit locate](https://bioinf.shenwei.me/seqkit/usage/#locate).

```
locate subsequences/motifs, mismatch allowed

Attentions:

  1. Motifs could be EITHER plain sequence containing "ACTGN" OR regular
     expression like "A[TU]G(?:.{3})+?[TU](?:AG|AA|GA)" for ORFs.     
  2. Degenerate bases/residues like "RYMM.." are also supported by flag -d.
     But do not use degenerate bases/residues in regular expression, you need
     convert them to regular expression, e.g., change "N" or "X"  to ".".
  3. When providing search patterns (motifs) via flag '-p',
     please use double quotation marks for patterns containing comma, 
     e.g., -p '"A{2,}"' or -p "\"A{2,}\"". Because the command line argument
     parser accepts comma-separated-values (CSV) for multiple values (motifs).
     Patterns in file do not follow this rule.     
  4. Mismatch is allowed using flag "-m/--max-mismatch",
     but it's not fast enough for large genome like human genome.
     Though, it's fast enough for microbial genomes.
  5. When using flag --circular, end position of matched subsequence that 
     crossing genome sequence end would be greater than sequence length.
```

**Comment by dbustoslab** [comment]
It's working perfectly. Thanks
