### ISSUE TITLE
seqkit amplicon --max-mismatch problem

### ISSUE THREAD

**Issue by ong8181** [shenwei356/seqkit#166]
Dear seqkit developers,

I am currently analyzing amplicon sequence data, and am trying to extract sequences between two primers. As I want to allow some mismatches, I specified `--max-mismatch` argument as below:

```
seqkit amplicon -F GTGYCAGC -R GTWTCTAAT --max-mismatch 0 sample_001.fastq > out_m0.fastq
seqkit amplicon -F GTGYCAGC -R GTWTCTAAT --max-mismatch 1 sample_001.fastq > out_m1.fastq
seqkit stats *.fastq
```

where `GTGYCAGC` is the first 8 bases of 515F universal primer for prokaryotes, `GTWTCTAAT` is the first 9 bases of 806R reverse primer (I did not include whole primer sequences because some bases in the primer regions have low Q score, but this is not important for my problem).

`sample_001.fastq` is a small, example fastq file generated by Illumina iSeq (can be downloaded from [here](https://github.com/ong8181/random-scripts/blob/master/random_files/sample_001.fastq)), and outputs of the two lines of commands are `out_m0.fastq` and `out_m1.fastq` which I expect contain the sequence regions between the primers.

Based on my understanding, `out_m1.fastq` should contain more sequences than `out_m0.fastq` because the second line allows 1 mismatch. However, inspections by `seqkit stats *.fastq` returns following results:

```
file              format  type  num_seqs    sum_len  min_len  avg_len  max_len
out_m0.fastq      FASTQ   DNA      4,653  1,307,183      217    280.9      288
out_m1.fastq                           0          0        0        0        0
sample_001.fastq  FASTQ   DNA      9,819  2,866,165      134    291.9      292
```

I am wondering whether I misspecified some arguments or this is a bug of `seqkit amplicon`. My seqkit version is latest (`Version: 0.14.0`) and I am running this script on macOS 10.14.6.

Thank you so much for your help in advance.

Best ragerds,
Ushio

**Comment by shenwei356** [comment]
Oh, I see, my bad, the document does not speak it clearly:

Degenerate bases are allowed, but option `-m/--max-mismatch` is ignored when they are given. It's not supported for now.

To solve your problem with current version, we can create all combinations of the primer pairs, and allow mismatch.

```
$ cat primers.tsv 
p13     GTGCCAGC        GTATCTAAT
p23     GTGTCAGC        GTATCTAAT
p14     GTGCCAGC        GTTTCTAAT
p24     GTGTCAGC        GTTTCTAAT


$ seqkit amplicon -p primers.tsv  --max-mismatch 1 sample_001.fastq | seqkit rmdup | seqkit stats 
[INFO] 4 primer pair loaded
[INFO] 16973 duplicated records removed
file  format  type  num_seqs    sum_len  min_len  avg_len  max_len
-     FASTQ   DNA      7,622  2,120,349        0    278.2      288

$ seqkit amplicon -F GTGYCAGC -R GTWTCTAAT --max-mismatch 0 sample_001.fastq | seqkit stats 
[INFO] 1 primer pair loaded
file  format  type  num_seqs    sum_len  min_len  avg_len  max_len
-     FASTQ   DNA      4,653  1,307,183      217    280.9      288


```

**Comment by ong8181** [comment]
Thank you so much @shenwei356 !
This solved my problem.
