### ISSUE TITLE
How to extract reads which contain specific sequence from fastq file ?

### ISSUE THREAD

**Issue by vagabond12** [shenwei356/seqkit#167]
How to extract reads which contain specific sequence from fastq file ?

And I have the cell barcode. But the cell barcode should be still be in extracted fastq files.

**Comment by shenwei356** [comment]
Yes, it supports. But only for positive strand.

    seqkit grep -s

**Comment by shenwei356** [comment]
https://github.com/shenwei356/seqkit/releases/tag/v0.15.0rc1
