### ISSUE TITLE
Request to include IUPAC code in pattern search (motif) in sequences (new feature request)

### ISSUE THREAD

**Issue by ssvbio** [shenwei356/seqkit#169]
### Seqkit version

 seqkit v0.12.0

### Request for feature

Currently, seqkit grep function works on alphabets (A,T,C, G and other letters). Will it be possible for pattern search (in sequences) to include IUPAC base code (https://www.bioinformatics.org/sms/iupac.html)?

Use case:

input fasta:

```
$ cat test.fa                   
>seq1
CCC
>seq2
G
```

Seqkit code to extract sequences with A or C in first position, T or C in second position, and G or C in third position
```
$ seqkit grep -srp '[AC][TC][GC]' test.fa
>seq1
CCC
```
Feature request:
```
$ seqkit grep -srp 'MYS' test.fa 
```
As per IUPAC
```
M - A or C
Y - T or C
S - G or C
```
Related biostars post: https://www.biostars.org/p/473003/

pattern: **.[GC][AT]T[GC]AAA[GA]**
This can be collapsed to: **.SWTSA{2}R** (using IUPAC standard bases)

**Comment by shenwei356** [comment]
-d

**Comment by ssvbio** [comment]
I misunderstood 'degenerate' option and thought it was for codon table. Thank you for pointing out.
