### ISSUE TITLE
Seqkit Rmdup details

### ISSUE THREAD

**Issue by MichWeb75** [shenwei356/seqkit#170]
Dear developers,

I really like the function seqkit rmdup -D details.txt. However, to process the details further and identify the most redundant reads, I need to transform it into a long format. 
```
head -n 5 duplicated.detail.txt
18      dre-mir-430c-1, dre-mir-430c-2, dre-mir-430c-3
```

into 
```
18      dre-mir-430c-1
18      dre-mir-430c-2
18      dre-mir-430c-3

```

What is the easiest way to do this transformation in Linux ?

Best, Michael

**Comment by MichWeb75** [comment]
The second column is apparently a comma-separated list of duplicated read names.

**Comment by shenwei356** [comment]
I'd like to leave it to csvtk, a [similar feature request](https://github.com/shenwei356/csvtk/issues/103) is still there.

For now, if you just want list the duplicated IDs:

```
seqkit fx2tab -n -i reads_1.fq.gz  | csvtk -H -t freq -n -r | awk '$2>1'
```
