### ISSUE TITLE
seqkit grep will not receive an input (-f) file and pull out headers and sequences from a .fasta file 

### ISSUE THREAD

**Issue by erikamag** [shenwei356/seqkit#174]
Here is the .fa file I would like to parse with seqkit `mu_W22_100bp_flanking.fa`

```
cat mu_W22_100bp_flanking.fa
>chr10_149189635::CM004357.2:149189535-149189743(+)
CAGTAGCCCGACCCCATTCACAGTGAGACAGATTGATCACCAGAGCCCCCTTTGACGGCTAACAGACGGGCCCGCATTGGCAGCAGGCGTGCGTGGAGTGGGATGGGCGGTCCGAGCTGGCTTTCGACCCAACAGCCGAGAGGAGCTTTCTCTTTTAtttttttttcctcattttctgttttatatttttatttctagtttgagttca
```

I created a file with a partial header line for all the sequences I need to pull out
`less id.txt`

```
chr4_21913358
chr8_171722481
```

When I run this code 

```
seqkit grep -n -f id.txt mu_W22_100bp_flanking.fa > results.fa
```

The results.fa file is empty.

Then, I tried to identify lines with a specific sequence to see if seqkit can read mu .fa file. 

```
cat mu_W22_100bp_flanking.fa | seqkit grep -s -i -p aggcg
```

This worked and pulled out the header lines and sequence. 

```
>chr10_149189635::CM004357.2:149189535-149189743(+)
CAGTAGCCCGACCCCATTCACAGTGAGACAGATTGATCACCAGAGCCCCCTTTGACGGCT
AACAGACGGGCCCGCATTGGCAGCAGGCG TGCGTGGAGTGGGATGGGCGGTCCGAGCTGG
CTTTCGACCCAACAGCCGAGAGGAGCTTTCTCTTTTAtttttttttcctcattttctgtt
ttatatttttatttctagtttgagttca
```

In addition grep -r finds the line, but I can't get the sequence

```
grep -r 'chr5_19883718' mu_W22_100bp_flanking.fa`
mu_W22_100bp_flanking.fa:>chr5_19883718::CM004352.2:19883618-19883826(+)
```

and `grep -F -A 1 -f 'id.txt' 'mu_W22_100bp_flanking.fa'` this does what I want. 

```
>chr4_21913358::CM004351.2:21913258-21913466(+)
TATCCACGCGGCCCATTATTTCCTAGAAGCTACGGACATCATTTCTCCTTCATCCCCATCTCTTCCTCAAGCTCTAGCCGAACTCCCTCACGCCATCCTCTTTCCTGGTGTTCATCCCTGCGGCAACCACCACTTGGGCGCTCCTCTCCCTGCCCCTCCCATGGCGGCTCCCCCTGGATCCCTCCCTGCGCGGCCCCTCTCCCGTGGA
--
>chr8_171722481::CM004355.2:171722381-171722589(+)
TGCCGGCGTCGGCGGAGGCCATGGCCGCGGATGGAGATGGGGAGGGGTGGATCTGGGATTCCGTTTTCTCTCTGCTGTTTGCGGTACACAACGAAAtgtggggaggggaggggaggggaggggccgGTGAACGCTGAACAGGAATAGGGAGAAAAGAGAAGCGAACACGGATGTGATCATGGGAATAGGGAAGGGTGATGCCACTGGG
```

Any ideas why `seqkit grep` will not recognize the partial string of the header (eg. chr10_149189635) and pull out the sequence? Is it the format of the header lines? Is there someway I need to transform this .fasta file?

**Comment by shenwei356** [comment]
> I created a file with a partial header line for all the sequences I need to pull out

For "partial header", you need switch on `-r`:

    -r, --use-regexp             patterns are regular expression

But it would be very slow if you have lots of IDs to match. 
Since the sequence headers are in uniform format, we can use `--id-regexp` to specify the IDs to match.

    cat mu_W22_100bp_flanking.fa \
        | seqkit grep --id-regexp '^(.+)::' -f id.txt
