### ISSUE TITLE
building for arm platform .

### ISSUE THREAD

**Issue by X-WJ** [shenwei356/seqkit#175]
### Prerequisites

- [ ]make sure you're are using the latest version by `seqkit version`
- yes
- [ ] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)
-yes
### Describe your issue

* [ ] describe the problem

i found it difficult to build on arm platform

* [ ] provide a reproducible example

i try to build it via golang.But my network is so slow.
Can i build it from source ?Ihave no privilige to install a docker .

Thanks

**Comment by shenwei356** [comment]
sure.

**Comment by shenwei356** [comment]
I tried to cross-compile on my linux, but failed too, for both `seqkit` and othersimple projects.

```
$ GOOS=darwin GOARCH=arm64 go build
# github.com/shenwei356/seqkit/seqkit
/usr/local/go/pkg/tool/linux_amd64/link: running gcc failed: exit status 1
/tmp/go-link-904872546/go.o: file not recognized: file format not recognized
collect2: error: ld returned 1 exit status
```

**Comment by shenwei356** [comment]
Using go1.16 fixed this. https://blog.golang.org/ports

- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/5740727/seqkit_darwin_arm64.tar.gz)
- [seqkit_linux_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/5740728/seqkit_linux_arm64.tar.gz)

**Comment by X-WJ** [comment]
Thank you very much
