### ISSUE TITLE
fatal error: runtime: out of memory

### ISSUE THREAD

**Issue by Enhancer01** [shenwei356/seqkit#176]
###I am using Linux on VM and i recently installed seqkit v0.14.0
I have large multiple fasta files (more than 10, 000 files of aligned coding seq) that i want to concatenate using the concat subcommand . however, I got the following error command 

fatal error: runtime: out of memory

runtime stack:
runtime.throw(0xb4ea6c, 0x16)
        /usr/local/go/src/runtime/panic.go:1116 +0x72
runtime.sysMap(0xc118000000, 0x4000000, 0x11eedf8)
        /usr/local/go/src/runtime/mem_linux.go:169 +0xc6
runtime.(*mheap).sysAlloc(0x11d1fa0, 0x400000, 0x42be57, 0x11d1fa8)
        /usr/local/go/src/runtime/malloc.go:727 +0x1e5
runtime.(*mheap).grow(0x11d1fa0, 0x80, 0x0)
        /usr/local/go/src/runtime/mheap.go:1344 +0x85
runtime.(*mheap).allocSpan(0x11d1fa0, 0x80, 0x100, 0x11eee08, 0x41667b)
        /usr/local/go/src/runtime/mheap.go:1160 +0x6b6
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:907 +0x65
runtime.(*mheap).alloc(0x11d1fa0, 0x80, 0xc000080101, 0x42990a)
        /usr/local/go/src/runtime/mheap.go:901 +0x85
runtime.largeAlloc(0x100000, 0x460101, 0xc117f00000)
        /usr/local/go/src/runtime/malloc.go:1177 +0x92
runtime.mallocgc.func1()
        /usr/local/go/src/runtime/malloc.go:1071 +0x46
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:370 +0x66
runtime.mstart()
        /usr/local/go/src/runtime/proc.go:1116

goroutine 1 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:330 fp=0xc0000ad928 sp=0xc0000ad920 pc=0x4693c0
runtime.mallocgc(0x100000, 0xa71e60, 0xc10bda7301, 0xc117b8a390)
        /usr/local/go/src/runtime/malloc.go:1070 +0x938 fp=0xc0000ad9c8 sp=0xc0000ad928 pc=0x40dcf8
runtime.makeslice(0xa71e60, 0x0, 0x100000, 0xc117f00000)
        /usr/local/go/src/runtime/slice.go:98 +0x6c fp=0xc0000ad9f8 sp=0xc0000ad9c8 pc=0x44cb2c
github.com/shenwei356/bio/seqio/fastx.NewReader(0x0, 0x7fffe7417cb5, 0x1e, 0xb463a7, 0x9, 0x1, 0x0, 0x0)
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seqio/fastx/reader.go:123 +0x385 fp=0xc0000adaf0 sp=0xc0000ad9f8 pc=0x7377e5
github.com/shenwei356/seqkit/seqkit/cmd.glob..func4(0x11adc40, 0xc0005ec000, 0x389f, 0x389f)
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/concat.go:95 +0xaff fp=0xc0000b1d68 sp=0xc0000adaf0 pc=0x9d4fff
github.com/spf13/cobra.(*Command).execute(0x11adc40, 0xc0003a6000, 0x389f, 0x3a00, 0x11adc40, 0xc0003a6000)
        /home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:846 +0x2c2 fp=0xc0000b1e40 sp=0xc0000b1d68 pc=0x7a1e82
github.com/spf13/cobra.(*Command).ExecuteC(0x11b0640, 0xc00012d760, 0xc000354360, 0xc00011a010)
        /home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:950 +0x375 fp=0xc0000b1f18 sp=0xc0000b1e40 pc=0x7a2bb5
github.com/spf13/cobra.(*Command).Execute(...)
        /home/shenwei/shenwei/scripts/go/src/github.com/spf13/cobra/command.go:887
github.com/shenwei356/seqkit/seqkit/cmd.Execute()
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/root.go:53 +0x31 fp=0xc0000b1f78 sp=0xc0000b1f18 pc=0x9ba271
main.main()
        /home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/main.go:58 +0x25 fp=0xc0000b1f88 sp=0xc0000b1f78 pc=0xa207c5
runtime.main()
        /usr/local/go/src/runtime/proc.go:204 +0x209 fp=0xc0000b1fe0 sp=0xc0000b1f88 pc=0x438589
runtime.goexit()
        /usr/local/go/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc0000b1fe8 sp=0xc0000b1fe0 pc=0x46b001

Although i am suggesting it could be a memory problem, I don't know how to increase the mem requirement for seqkit or if it's capable of such task. any help or suggestion please?

**Comment by shenwei356** [comment]
So what's the memory of the VM? And what the sizes of all files? 

What's the size of the genome and how many samples are there?

seqkit reads whole data of input files and may exhaust the memory. 10K files is a huge number for this command.

BTW, does this tool help? https://github.com/fenghen360/HomBlocks

**Comment by Enhancer01** [comment]
the Basal memory of my VM is 4024 MB
the size of the files should be ~1G
the number of files is ~14, 000
each file is a multiple seq alignment of  a protein coding gene, which means I have 14, 000  separate genes that i want to analyse.  
I checked this link https://github.com/fenghen360/HomBlocks; my work flow is similar only from sequence trimming using Gblocks.  i main aim is to build a phylogeny tree from the concatenated files

**Comment by shenwei356** [comment]
Try shell command `paste`. [rush](https://github.com/shenwei356/rush/) is used to parallelization.


1.  Sort all sequences in files *in same order (sorting by ID, i.e., sample names, please make sure they are unique)* and retrieve the sequences.

        ls *.fasta | rush 'seqkit sort {} | seqkit fx2tab | awk "{print \$2}" > {}.tab'

2.  `paste`
 
        paste *.tab -d "" > seqs.txt

3. Add sample names to sequences and convert back to fasta.
        
        seqkit sort  gene1.fasta | seqkit seq -n -i > names.txt

        paste names.txt seqs.txt | seqkit tab2fx > result.fa

**Comment by Enhancer01** [comment]
Thank you very much, let me try it.

**Comment by shenwei356** [comment]
Solved?

**Comment by Enhancer01** [comment]
Yes, Thank you very much, your suggestions were very helpful sir.
