### ISSUE TITLE
seqkit grep command bug

### ISSUE THREAD

**Issue by xyz1396** [shenwei356/seqkit#178]
I am using the grep to search a large 70 GB fasta file of ammonia acid on Ubuntu 20.04. It raised panic: runtime error: slice bounds out of range [:-1] error. After I split the large file into a small file of 10000 sequences, many files still raise that error. The detail of the error is as follows.

goroutine 1 [running]:
github.com/shenwei356/bwt/fmi.(*FMIndex).Locate(0xc000801c08, 0xc0004fd330, 0x0, 0x10, 0x2, 0x10, 0x3c, 0x0, 0x0, 0x0)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/shenwei356/bwt@v0.0.0-20200418151221-ae79c9858c90/fmi/fmi.go:137 +0xd8a
github.com/shenwei356/seqkit/seqkit/cmd.glob..func12(0x1107420, 0xc0001dde60, 0x1, 0x9)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/grep.go:370 +0xff3
github.com/spf13/cobra.(*Command).execute(0x1107420, 0xc0001dddd0, 0x9, 0x9, 0x1107420, 0xc0001dddd0)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:854 +0x2c2
github.com/spf13/cobra.(*Command).ExecuteC(0x1109100, 0x11146e0, 0x0, 0xc0000ba778)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:958 +0x375
github.com/spf13/cobra.(*Command).Execute(...)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.1.1/command.go:895
github.com/shenwei356/seqkit/seqkit/cmd.Execute()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/root.go:53 +0x31

**Comment by shenwei356** [comment]
Command? what's the search pattern?

Searching proteins? Have you tried blastp?

**Comment by xyz1396** [comment]
Blast works good with this data. I uploaded the fasta can raise the error, follow code can reproduce the error.
`seqkit grep protienRaiseBug.fasta -s -i -m 2 -p TYLKTNLFL`
[protienRaiseBug.zip](https://github.com/shenwei356/seqkit/files/5862398/protienRaiseBug.zip)

**Comment by shenwei356** [comment]
I think I've fixed it.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5863580/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/5863581/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/5863582/seqkit_windows_amd64.exe.tar.gz)
