### ISSUE TITLE
Feature Request: automatic quality score conversion

### ISSUE THREAD

**Issue by cviner** [shenwei356/seqkit#18]
A common issue encountered by many involves [determining](https://www.biostars.org/p/6656/) and then [converting](https://www.biostars.org/p/225923/) quality scores from various older sequencing datasets to modern Phread+33 (Sanger / Illumina 1.8+) encoding. There does not yet appear to be a single unified system to perform both of these functions, as part of a larger pipeline on the Linux command line. `seqtk` itself [provides](https://github.com/lh3/seqtk/issues/77) the ability to convert from Illumina1.5 to Illumina 1.8+ formats, for instance, but [does not convert](https://github.com/lh3/seqtk/issues/48) from formats prior to Illumina 1.3. A useful Python [script exists](https://github.com/brentp/bio-playground/blob/master/reads-utils/guess-encoding.py) to guess the correct encoding. Conversion is further complicated by the fact that valid conversion between Sanger and Solexa [involves a non-linear transformation](https://en.wikipedia.org/wiki/FASTQ_format#Quality) and may require some precautions to ensure numerical stability.

SeqKit seems like an ideal toolkit to include this functionality, which many would likely find highly useful.

**Comment by shenwei356** [comment]
Thanks for suggestion and detailed description. I'll implement it when I'm free (2-3 month later, sorry).

**Comment by cviner** [comment]
@shenwei356 Glad to hear that—thanks so much!

**Comment by shenwei356** [comment]
[BioPython QualityIO](http://biopython.org/DIST/docs/api/Bio.SeqIO.QualityIO-module.html)

Quality score convertion:
- [solexa_quality_from_phred](http://biopython.org/DIST/docs/api/Bio.SeqIO.QualityIO-pysrc.html#solexa_quality_from_phred)
- [phred_quality_from_solexa](http://biopython.org/DIST/docs/api/Bio.SeqIO.QualityIO-pysrc.html#phred_quality_from_solexa)

**Comment by shenwei356** [comment]
Hi @cviner , I've added a command (alpha version below) `seqkit convert` for your request.
Please help to test it.

- [taxonkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/1170364/taxonkit_darwin_amd64.tar.gz)
- [taxonkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/1170363/taxonkit_linux_amd64.tar.gz)


By default, it guesses the quality encoding according to the leading 1000 (`-n`) records, 
you can also specify the input (`--from`) and output (`--to`) encoding.

Example:

```
seqkit convert read_1.fq.gz          --to 5 # auto detect input quality encoding
seqkit convert read_1.fq.gz --from 3 --to 5
```
Where `5` is the code for quality encoding.  available value: 0 for Unknown, 1 for Sanger, 2 for Solexa, 3 for Illumina-1.3+, 4 for Illumina-1.5+, 5 for Illumina-1.8+.

**Comment by cviner** [comment]
@shenwei356 This is great—I will test it soon! Thanks for adding this!

For the auto-detection, is it able to detect Illumina 1.5 as going up to ASCII 105 (`i`) (I mentioned this issue [elsewhere](https://github.com/brentp/bio-playground/pull/17))? Would it be possible to include a heuristic, to uniquely identify 1.5 format if many `B`s are present (similar to something I recently [added](https://github.com/cviner/bio-playground/commit/01c1af2211295a92be749bd539259f7ed99ed321) to the script I am currently using to guess the encoding)? For conversion of Illumina 1.5 to 1.8+, could the special code `B` be re-assigned to 0 (ASCII 33, `!`) in the new scale (as opposed to purely converted to 2)?

**Comment by cviner** [comment]
@shenwei356 I am not sure how to test this, using the provided binary.

`./taxonkit convert`

returns: 

```#!text
Error: unknown command "convert" for "taxonkit"
Run 'taxonkit --help' for usage.
unknown command "convert" for "taxonkit"
````

**Comment by shenwei356** [comment]
Oh no, I uploaded the wrong binaries. fixed.

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/1171544/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/1171545/seqkit_darwin_amd64.tar.gz)

The special cases of Illumina 1.5 and 1.8 will be taken into consideration soon.

**Comment by zhaoxia413** [comment]
哈哈哈




发自网易邮箱大师
On 07/25/2017 08:02, Wei Shen wrote:

Oh no, I uploaded the wrong binaries. fixed.

seqkit_linux_amd64.tar.gz
seqkit_darwin_amd64.tar.gz

The special cases of Illumina 1.5 and 1.8 will be taken into consideration soon.

**Comment by shenwei356** [comment]
As you mentioned, 1.5 format can be uniquely identified if many `B`s are present. But will this bring false-positive? And is the ["within 4th common qualities"](https://github.com/cviner/bio-playground/commit/01c1af2211295a92be749bd539259f7ed99ed321#diff-1e8bf6cb1f2874b478ad60bcfc60d0b9R34) criteria robust?

**Comment by cviner** [comment]
@shenwei356 That is a good point. It may indeed do so, which is why I think it is best to output a warning when the heuristic is used and have an option to disable it.

I think that overall, using it is better than not including it. I do not think that my criteria is particularly robust and would welcome a better heuristic!

**Comment by shenwei356** [comment]
How about this, using the criteria. Possible quality encodings of the leading N (default: 1000) records are computed firstly. And if the proportion of guessed Illumina 1.5 format is greater than some threshold, we can call them Illumina 1.5. If not, follow the regular workflow, i.e., computing the intersection of the N guesses.

**Comment by cviner** [comment]
Yes—I think that is a very good idea.

**Comment by cviner** [comment]
Although that should still somehow account for an enrichment of `B`s. Perhaps integrating that idea with the previous one?

**Comment by shenwei356** [comment]
Alright, I'll implement it tomorrow. Good morning for you and good night for me.

**Comment by shenwei356** [comment]
I set the default faction of guessed Illumina 1.5 in the leanding N as 0.1 (`--thresh-illumina1.5-frac`).

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/1175282/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/1175283/seqkit_linux_amd64.tar.gz)

**Comment by cviner** [comment]
@shenwei356 Thanks! I have tested the latest binary on a few Illumina 1.5 datasets and one Sanger. Everything appears to work well! Thanks for implementing this!

It would be nice to accept actual format names like `solexa` or `sanger`.

One issue is that the Sanger dataset is converted from Illumina 1.8, when it correctly guesses both options. I would suggest that if those two options are present, Sanger should be the default. Finally, if the source and target formats match, conversion should be aborted with a message.

**Comment by shenwei356** [comment]
Why should sanger be default if it may be sanger and illumina 1.8.

Most commands of seqkit follow the UNIX philosophy and read from stdin or file and write to stdout or file. So it still output when output and input format match, anyway it's very fast and log is written to stderr.

**Comment by cviner** [comment]
Currently it defaults to Illumina 1.8. The default should be Sanger because Illumina is now using that encoding, it is the default in many tools (e.g. Cutadapt), and all NCBI SRA / EBI ENA FASTQs are re-processed to the Sanger format. It can therefore be regarded as the current *de facto* standard.

As for always processing it, that is fair enough, but an option to not process it and return an informative message if the source and target encodings are the same would be nice.

Thanks again for all your work on this!

**Comment by shenwei356** [comment]
OK, I'll work on it ASAP.

**Comment by shenwei356** [comment]
sorry I can't have access to computer for 2 months.

**Comment by cviner** [comment]
@shenwei356 No problem! My current approach is sufficient for now. Thanks again for all your work on this and I look forward to using it after it is done.

**Comment by shenwei356** [comment]
Updated as you requested.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/1202327/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/1202326/seqkit_linux_amd64.tar.gz)

Examples:

```
$ seqkit convert t.fq 
[INFO] possible quality encodings: [Illumina-1.8+]
[INFO] guessed quality encoding: Illumina-1.8+
[INFO] converting Illumina-1.8+ -> Sanger
[WARN] source and target quality encoding match. aborted.
```

```
$ seqkit convert t.fq --to solexa --dry-run
[INFO] possible quality encodings: [Illumina-1.8+]
[INFO] guessed quality encoding: Illumina-1.8+
[INFO] converting Illumina-1.8+ -> Solexa
```

**Comment by cviner** [comment]
@shenwei356 Thanks so much!

There does appear to be a small bug with the first example, since Illumina-1.8+ -> Sanger should still be converted, since while similar, they are not the same.

**Comment by shenwei356** [comment]
what's the differences? range?

**Comment by cviner** [comment]
@shenwei356 Yes, exactly. Illumina-1.8+ currently [typically](https://en.wikipedia.org/wiki/FASTQ_format#Encoding) goes to one value higher (`I`, ASCII 41) than the initial Sanger format. More importantly, it is expected to permit higher quality scores for newer sequencing chemistries. The latest [HiSeq X Ten](https://www.illumina.com/science/education/sequencing-quality-scores.html) system, for instance, uses a binning system that introduces additional complications.

I think that for this purpose, the formats should be considered different, with conversion from Sanger -> 1.8+ resulting in no change, but with the converse resulting in all scores > 40, being set to 40.

**Comment by cviner** [comment]
I guess in this case, however, it might be best to simply leave it as is and consider the two formats the same by default (since otherwise, defaulting to Sanger, could discard higher quality scores that should usually be preserved).

Perhaps you could simply keep it this way but add a `-f` option to force conversion, even between formats regarded as identical? Then when forced, for Illumina 1.8 -> Sanger only, all scores above 40 would be truncated to 40, with a warning output to mention this to the user?

**Comment by shenwei356** [comment]
@cviner  updated as you suggested, thank you for making it better.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/1218123/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/1218124/seqkit_linux_amd64.tar.gz)

Note that `seqkit convert` always output sequences.

The test dataset contains score 41 (`J`):

```
$ seqkit head -n 1 tests/Illimina1.8.fq.gz 
@ST-E00493:56:H33MFALXX:4:1101:23439:1379 1:N:0:NACAACCA                                                   
NCGTGGAAAGACGCTAAGATTGTGATGTGCTTCCCTGACGATTACAACTGGCGTAAGGACGTTTTGCCTACCTATAAGGCTAACCGTAAGGGTTCTCGCAAGCCTGTAGGTTACAAGAGGTTCGTAGCCGAAGTGATGGCTGACTCACGG                                                                
+
#AAAFAAJFFFJJJ<JJJJJFFFJFJJJJJFJJAJJJFJJFJFJJJJFAFJ<JA<FFJ7FJJFJJAAJJJJ<JJJJJJJFJJJAJJJJJFJJ77<JJJJ-F7A-FJFFJJJJJJ<FFJ-<7FJJJFJJ)A7)7AA<7--)<-7F-A7FA<
```

By default, nothing change when converting Illumina 1.8 to Sanger. A warning message show that source and target quality encoding match.

```
$ seqkit convert tests/Illimina1.8.fq.gz  | seqkit head -n 1 
[INFO] possible quality encodings: [Illumina-1.8+]
[INFO] guessed quality encoding: Illumina-1.8+
[INFO] converting Illumina-1.8+ -> Sanger
[WARN] source and target quality encoding match.
@ST-E00493:56:H33MFALXX:4:1101:23439:1379 1:N:0:NACAACCA
NCGTGGAAAGACGCTAAGATTGTGATGTGCTTCCCTGACGATTACAACTGGCGTAAGGACGTTTTGCCTACCTATAAGGCTAACCGTAAGGGTTCTCGCAAGCCTGTAGGTTACAAGAGGTTCGTAGCCGAAGTGATGGCTGACTCACGG
+
#AAAFAAJFFFJJJ<JJJJJFFFJFJJJJJFJJAJJJFJJFJFJJJJFAFJ<JA<FFJ7FJJFJJAAJJJJ<JJJJJJJFJJJAJJJJJFJJ77<JJJJ-F7A-FJFFJJJJJJ<FFJ-<7FJJJFJJ)A7)7AA<7--)<-7F-A7FA<
```

When switching flag `--force` on,  `J` was converted to `I` (40).

```
$ seqkit convert tests/Illimina1.8.fq.gz -f | seqkit head -n 1 
[INFO] possible quality encodings: [Illumina-1.8+]
[INFO] guessed quality encoding: Illumina-1.8+
[INFO] converting Illumina-1.8+ -> Sanger
@ST-E00493:56:H33MFALXX:4:1101:23439:1379 1:N:0:NACAACCA
NCGTGGAAAGACGCTAAGATTGTGATGTGCTTCCCTGACGATTACAACTGGCGTAAGGACGTTTTGCCTACCTATAAGGCTAACCGTAAGGGTTCTCGCAAGCCTGTAGGTTACAAGAGGTTCGTAGCCGAAGTGATGGCTGACTCACGG
+
#AAAFAAIFFFIII<IIIIIFFFIFIIIIIFIIAIIIFIIFIFIIIIFAFI<IA<FFI7FIIFIIAAIIII<IIIIIIIFIIIAIIIIIFII77<IIII-F7A-FIFFIIIIII<FFI-<7FIIIFII)A7)7AA<7--)<-7F-A7FA<
```

Other cases:

To Illumina-1.5.

```
$ seqkit convert tests/Illimina1.8.fq.gz --to Illumina-1.5+ | seqkit head -n 1 
[INFO] possible quality encodings: [Illumina-1.8+]
[INFO] guessed quality encoding: Illumina-1.8+
[INFO] converting Illumina-1.8+ -> Illumina-1.5+
@ST-E00493:56:H33MFALXX:4:1101:23439:1379 1:N:0:NACAACCA
NCGTGGAAAGACGCTAAGATTGTGATGTGCTTCCCTGACGATTACAACTGGCGTAAGGACGTTTTGCCTACCTATAAGGCTAACCGTAAGGGTTCTCGCAAGCCTGTAGGTTACAAGAGGTTCGTAGCCGAAGTGATGGCTGACTCACGG
+
B```e``ieeeiii[iiiiieeeieiiiiieii`iiieiieieiiiie`ei[i`[eeiVeiieii``iiii[iiiiiiieiii`iiiiieiiVV[iiiiLeV`Leieeiiiiii[eeiL[VeiiieiiH`VHV``[VLLH[LVeL`Ve`[
```

To Illumina-1.5 and back to Sanger.

```
$ seqkit convert tests/Illimina1.8.fq.gz --to Illumina-1.5+ | seqkit convert | seqkit head -n 1       
[INFO] possible quality encodings: [Illumina-1.8+]
[INFO] guessed quality encoding: Illumina-1.8+
[INFO] converting Illumina-1.8+ -> Illumina-1.5+
[INFO] possible quality encodings: [Illumina-1.5+]
[INFO] guessed quality encoding: Illumina-1.5+
[INFO] converting Illumina-1.5+ -> Sanger
@ST-E00493:56:H33MFALXX:4:1101:23439:1379 1:N:0:NACAACCA
NCGTGGAAAGACGCTAAGATTGTGATGTGCTTCCCTGACGATTACAACTGGCGTAAGGACGTTTTGCCTACCTATAAGGCTAACCGTAAGGGTTCTCGCAAGCCTGTAGGTTACAAGAGGTTCGTAGCCGAAGTGATGGCTGACTCACGG
+
#AAAFAAJFFFJJJ<JJJJJFFFJFJJJJJFJJAJJJFJJFJFJJJJFAFJ<JA<FFJ7FJJFJJAAJJJJ<JJJJJJJFJJJAJJJJJFJJ77<JJJJ-F7A-FJFFJJJJJJ<FFJ-<7FJJJFJJ)A7)7AA<7--)<-7F-A7FA<

# check the results, they are right.

$ seqkit convert tests/Illimina1.8.fq.gz --to Illumina-1.5+ | seqkit convert | md5sum 
[INFO] possible quality encodings: [Illumina-1.8+]
[INFO] guessed quality encoding: Illumina-1.8+
[INFO] converting Illumina-1.8+ -> Illumina-1.5+
[INFO] possible quality encodings: [Illumina-1.5+]
[INFO] guessed quality encoding: Illumina-1.5+
[INFO] converting Illumina-1.5+ -> Sanger
0f1eeee73fe21ccd4f00db654fb272c2  -
$ seqkit seq tests/Illimina1.8.fq.gz | md5sum 
0f1eeee73fe21ccd4f00db654fb272c2  -
```

Checking encoding

```
$ seqkit convert tests/Illimina1.8.fq.gz --from Solexa 
[INFO] converting Solexa -> Sanger
[ERRO] seq: invalid Solexa quality
```

**Comment by cviner** [comment]
This is great! Thanks so much for implementing all of this, @shenwei356!

It would be great if you could release a new version of SeqKit, integrating all of these enhancements.

I look forward to using it in my pipeline.

**Comment by shenwei356** [comment]
@cviner Please try the new version: [v0.7.0](https://github.com/shenwei356/seqkit/releases/tag/v0.7.0)

**Comment by cviner** [comment]
@shenwei356 Great—thanks!
