### ISSUE TITLE
Anaconda Package for Windows and other OS

### ISSUE THREAD

**Issue by DerKevinRiehl** [shenwei356/seqkit#181]
I like your tool very much, when I wanted to use it in conda I found that it does not exist for all operating systems,
even though you provide ready compiled EXE for Windows on your Github.

Do you have any plans to package it for Windows as well?
If you want I can help you to package your software into a conda package for windows as well, interested?
You basically just need to copy "seqkit.exe" into the bin Folder of Windows in your build.sh, you can even use
conda convert to convert your package to Windows...

**Comment by shenwei356** [comment]
> I like your tool very much, when I wanted to use it in conda I found that it does not exist for all operating systems,
even though you provide ready compiled EXE for Windows on your Github.

Thank you. Yes, people helped to write bioconda-recipes a long time ago, and only Linux/macOS were supported.
https://github.com/bioconda/bioconda-recipes/blob/master/recipes/seqkit/meta.yaml

> Do you have any plans to package it for Windows as well?
If you want I can help you to package your software into a conda package for windows as well, interested?
You basically just need to copy "seqkit.exe" into the bin Folder of Windows in your build.sh, you can even use
conda convert to convert your package to Windows...

Yes, please. You can directly contribute to bioconda with a PR.

**Comment by DerKevinRiehl** [comment]
https://github.com/DerKevinRiehl/seqkit-conda-windows/

Here you go. Please tell me if I need to do anything else or I  did not clearly enough state out that the software is written by you :).
How to label this conda package as "bioconda"?

**Comment by shenwei356** [comment]
Great, I've never tried to build a new Conda channel. I searched across recipes of the Bioconda but found no direct solutions. Let me ask for help.

I'm not sure whether it's the best solution to directly submit the binaries to a Conda channel, cause the sizes are big and regular updates are to submit.

**Comment by shenwei356** [comment]
> ... currently Bioconda only supports Linux and OSX. ...
But someone using ubuntu in windows could also install tools from Bioconda.

Does this help? 

https://github.com/kapsakcj/win10-linux-conda-how-to/blob/master/README.md
