### ISSUE TITLE
help: printing file name

### ISSUE THREAD

**Issue by ssvbio** [shenwei356/seqkit#182]
Is there a function to print filename in seqkit? (like FILENAME in awk)

Use case:
1. User wants to print the GC content of each sequence across multiple files
2. Seqkit prints GC content of the each sequence (from all the files with multiple fasta sequences within each file) with header and sequence (depending on input params)
3. User doesn't know the source file of each sequence

Expected:
 1. An option to print FILENAME along with other functions

Thank you in advance.

**Comment by shenwei356** [comment]
$ seqkit fx2tab -n -i  -g hairpin.fa | awk -v f=hairpin.fa '{print f"\t"$0}'  | head -n 3
    hairpin.fa      cel-let-7       43.43
    hairpin.fa      cel-lin-4       54.26
    hairpin.fa      cel-mir-1       40.62

**Comment by ssvbio** [comment]
works with single file, but not with *.fa. For eg.

$ seqkit fx2tab -n -i  -g test.fa | awk -v f=test.fa '{print f"\t"$0}'  
test.fa	seq1	50.00
test.fa	seq2	25.00

with multiple files:
$ seqkit fx2tab -n -i  -g *.fa 
seq10	50.00
seq20	25.00
seq1	50.00
seq2	25.00

$ seqkit fx2tab -n -i  -g *.fa | awk -v f=*.fa '{print f"\t"$0}'  | head -n 3
*.fa	seq10	50.00
*.fa	seq20	25.00
*.fa	seq1	50.00

**Comment by shenwei356** [comment]
Just use a loop:

  for f in *.fa; do
      seqkit fx2tab -n -i  -g  $f | awk -v f=$f '{print f"\t"$0}' 
  done
