### ISSUE TITLE
Help: Allow users to print base count instead of base percentage

### ISSUE THREAD

**Issue by ssvbio** [shenwei356/seqkit#183]
Referring to this issue: https://www.biostars.org/p/488618/

User wants to print the occurrences of each base in a sequence. Seqkit prints the occurrence as % instead of counts. For one or two bases, user can calculate the number of occurrences using % and length (-l). However, if the number of bases are high in number, user has to do some home work.

Expected:

1. Allow the user to print number of occurrences of a base (number of base occurrences) instead of percentage (100*number of occurrences /length). 

(For eg```seqkit fx2tab N``` would print number instead of percentage, without ```-N```, seqkit defaults to preset format (%))

2.  If possible, please furnish a generic function to report overall occurrences or per base occurrence. For eg 
```seqkit fx2tab -B [SWR] *.fa ``` currently provides overall counts summary if a sequence has SWR. Additional function is to print occurrences S, W and R individually. Currently user has to do this to get it: ```seqkit fx2tab -B S -B W -B R *.fa ```. 

(for eg A generic function would be ```seqkit fx2tab -C``` would print the per base occurrences, without ```-C```, seqkit would revert to default occurrence (overall))

**Comment by shenwei356** [comment]
> Allow the user to print number of occurrences of a base (number of base occurrences) instead of percentage (100*number of occurrences /length).

TODO

>    -B, --base-content strings   print base content. (case ignored, multiple values supported) e.g. -B AT -B N

`-B` support multiple values. "-B [SWR]" is equal to `-B SWR`. But it seems degenerate bases not supported now.

> Additional function is to print occurrences S, W and R individually.

unnecessary.

> (for eg A generic function would be seqkit fx2tab -C would print the per base occurrences, without -C, seqkit would revert to default occurrence (overall))

This could results in unequal number of columns for different sequences.

**Comment by shenwei356** [comment]
added a new flag

      -C, --base-count strings     print base count. (case ignored, multiple values supported) e.g. -C AT -C N

Examples:

```
$ echo -ne ">s\nactgnaccts\n" | seqkit fx2tab -n -H -a -C a,c,t,g,n
#name   a       c       t       g       n       alphabet
s       2       3       2       1       1       acgnst
```
