### ISSUE TITLE
Huge memory consumption for rmdup

### ISSUE THREAD

**Issue by Z-Zen** [shenwei356/seqkit#184]
### Prerequisites

- [X] make sure you're are using the latest version by `seqkit version`
- [X] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [X] Describe the problem
Using `seqkit rmdup --by-seq file.fastq`  on huge FastQ files (400 Gb) are problematic in term of memory consumption. Is there any possible way to store the sequences in files instead of memory? Otherwise, what approaches would you suggest me for this issue ?

* [X] provide a reproducible example
Use the command `seqkit rmdup --by-seq file.fastq` on a huge FastQ file.

Thank you in advance.

**Comment by shenwei356** [comment]
Wow,  It's huge. Although `seqkit seq` [stores the hash values the sequences in memory](https://github.com/shenwei356/seqkit/blob/master/seqkit/cmd/rmdup.go#L103).

Does [khmer](
khmer) help?

[A memory efficient way to remove low-abundance k-mers from large (metagenomic?) DNA data sets](http://ivory.idyll.org/blog/kmer-filtering.html)
https://github.com/dib-lab/khmer

**Comment by Z-Zen** [comment]
> Wow, It's huge. Although `seqkit seq` [stores the hash values the sequences in memory](https://github.com/shenwei356/seqkit/blob/master/seqkit/cmd/rmdup.go#L103).
> 
> Does [khmer](khmer) help?
> 
> [A memory efficient way to remove low-abundance k-mers from large (metagenomic?) DNA data sets](http://ivory.idyll.org/blog/kmer-filtering.html)
> https://github.com/dib-lab/khmer

Thanks for the fast reply @shenwei356. 

I was reading a bit about `khmer`. It does look interesting, I will give it a try as soon as possible. However, I noticed in the following [paragraph](https://khmer.readthedocs.io/en/stable/user/choosing-table-sizes.html#rules-of-thumb), I quote:

> For metagenomic samples that are more complex, such as soil or marine, start as high as possible. For example, we are using -M 256G for ~300 Gbp of soil reads.

This means that in my case, I would require more RAM to be able to count the duplicate reads in my FastQ.

**Comment by shenwei356** [comment]
Hmm, `seqkit rmdup` counts precisely to remove all duplicates, rather than showing parts of them as FastQC does.
