### ISSUE TITLE
seqkit fx2tab -l prints out names and sequences as well

### ISSUE THREAD

**Issue by mptrsen** [shenwei356/seqkit#185]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Description

`seqkit fx2tab -l` prints names, sequences, and lengths.

### Expected

Print only the length. If the user wants names as well, they should provide `-n` (perhaps add another option to explicitly print the sequence.)

### Example

    $ seqkit version
    seqkit v0.15.0
    $ cat test.fa
    >test
    ATTTCGCATC
    $ seqkit fx2tab -l test.fa
    test   ATTTCGCATC   10

**Comment by shenwei356** [comment]
There's an option:

     -n, --name                   only print names (no sequences and qualities)

    $ seqkit fx2tab -l -n test.fa
    test    10

**Comment by mptrsen** [comment]
I know that, but it seems to me that seqkit shouldn't print names and sequences if they were not requested (since the user only used `-l`).

Essentially I wanted to output only the lengths. Of course I can pipe to `cut`; it just seems weird that seqkit prints something that wasn't requested.

**Comment by shenwei356** [comment]
The original design of `fx2tab` is converting FASTA/FASTQ to a tabular format, so users can filter or edit with shell commands or other tools. And `tab2fx` can convert the tabular format back.  Therefore `fx2tab` keeps all essential information including header, sequence, and quality by default.
