### ISSUE TITLE
Suggestion: command to make circular sequences linear via duplication

### ISSUE THREAD

**Issue by Benjamin-Lee** [shenwei356/seqkit#186]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem

From looking at the source code, your tool concatenates two copies of circular sequences to make algorithms work on them. This is great, but not every tool downstream can handle circular sequences. For example, I'm looking for ORFs in circular sequences. An ORF could span from the end of the sequence to the beginning but be missed! A tool built into seqkiit for doing this would be great.

**Comment by shenwei356** [comment]
try this?

    seqkit concat a.fasta a.fasta

**Comment by Benjamin-Lee** [comment]
That’s so obvious I can’t believe I didn’t think to do that! Thanks for the help!
