### ISSUE TITLE
seqkit fish running out of memory

### ISSUE THREAD

**Issue by vkkodali** [shenwei356/seqkit#187]
I have a small FASTA file with 10 sequences that I expect to have perfect matches in human chromosome 1. But I get a `fatal error: runtime: out of memory` every time I run it. I am running this on a laptop with 32Gb memory. 
```
$ seqkit version 
seqkit v0.15.0

$ seqkit stats temp.fa 
file     format  type  num_seqs  sum_len  min_len  avg_len  max_len
temp.fa  FASTA   DNA         10      230       23       23       23

$ seqkit stats chr1.fa 
file     format  type  num_seqs      sum_len      min_len      avg_len      max_len
chr1.fa  FASTA   DNA          1  248,956,422  248,956,422  248,956,422  248,956,422

$ seqkit fish -f temp.fa -a chr1.fa    
fatal error: runtime: out of memory
```
There are additional error messages... I can add them here if you like. 

On the other hand, `seqkit locate -f temp.fa -P chr1.fa` works instantly. However, `locate` does not return the number of mismatches when I use the `--max-mismatch 3` option.. I cannot tell if the query sequence has been located in the subject sequence with 0, 1, 2 or 3 mismatches?

**Comment by shenwei356** [comment]
Sorry for the late reply. Both `fish` and `locate` are suitable for small sequences, I recommend using mapping tools like `bwa` or `bowtie2` for this case.
