### ISSUE TITLE
Unable to get seqkit subseq to produce output from documentation for gtf file

### ISSUE THREAD

**Issue by tijeco** [shenwei356/seqkit#188]
I am currently using seqkit 0.15.0, and attempting to reproduce what is in the documentation for ```seqkit subseq``` 

This is what is in the documentation (https://bioinf.shenwei.me/seqkit/usage/#subseq):
```
$ cat t.fa
>seq
actgACTGactgn

$ cat t.gtf
seq     test    CDS     5       8       .       .       .       gene_id "A"; transcript_id "";
seq     test    CDS     5       8       .       -       .       gene_id "B"; transcript_id "";

$ seqkit subseq --gtf t.gtf t.fa
>seq_5:8:. A
ACTG
>seq_5:8:- B
CAGT
```

I run the following command with the attached files ```t.fa``` and ```t.gtf``` 

```
seqkit subseq --gtf t.gtf t.fa
```

I get the following output

```
[INFO] read GTF file ...
[INFO] 0 GTF features loaded
```

Did I mess up the input files somehow?
[Archive.zip](https://github.com/shenwei356/seqkit/files/5983474/Archive.zip)

**Comment by shenwei356** [comment]
GTF is tab-delimited file. If you just copy the example, it won't work because the tab is displayed in blanks.

```
$ seqkit subseq --gtf t.gtf t.fa
[INFO] read GTF file ...
[INFO] 0 GTF features loaded
[INFO] create FASTA index for t.fa

$ seqkit subseq --gtf <(sed -r 's/  +/\t/g' t.gtf) t.fa
[INFO] read GTF file ...
[INFO] 2 GTF features loaded
>seq_5-8:. A
ACTG
>seq_5-8:- B
CAGT
```
