### ISSUE TITLE
Bug - incorrect average quality with `seqkit fx2tab`

### ISSUE THREAD

**Issue by vmikk** [shenwei356/seqkit#189]
Hello!

In some cases `seqkit fx2tab` reports incorrect average sequence quality for PacBio data.
Reproducible example - [tst.fq.gz](https://github.com/shenwei356/seqkit/files/5995488/tst.fq.gz):
```
seqkit fx2tab --name --length --avg-qual tst.fq.gz
zcat tst.fq.gz | bioawk -c fastx '{ print $name "\t" meanqual($qual) }'
```

Output Phred scores:
| Sequence ID                        | seqkit | bioawk      | errors |
|------------------------------------|--------|-------------|--------|
| m64019_200118_024728/24/ccs        | 39.77  | 92.1688     | *      |
| m64019_200118_024728/2855/ccs      | 93.00  | 93          |        |
| m64019_200118_024728/66160/ccs     | 93.00  | 93          |        |
| m64019_200118_024728/132898/ccs    | 36.67  | 87.1113     | *      |
| **m64019_200118_024728/198025/ccs**    | **21.75**  | **53.7192**	    | *      |
| m64019_200118_024728/263024/ccs    | 93.00  | 93          |        |
| m64019_200118_024728/327750/ccs    | 65.83  | 92.1908     | *      |
| m64019_200118_024728/327959/ccs    | 93.0   | 93          |        |

I've manually checked one sequence (`m64019_200118_024728/198025/ccs`).
Its quality line is represented with the following ASCII characters:
```
DBS`;Yh3J[>Wg=_:FOO%Riia&9i<K>D,/;8e?RQMU_pJ_>cCPUoT_a)UKk<9p@Wr<*Gjkk=\WMI-0H7Z9D,Ki>QIMEJB:30OPuv:`QUGlZRa[lIZ~~Ar6SUnch.UfIj~^Gc+Ldw1Wt\:^wW]~T]~MO`[m[gAr3r7[`Z5Kfk_^b.Vs][~_\^YP[^^nZAfL]]UXyL\`s@Q9MBXSn\W_U5t[qPEZ*NQcYm^ll]]j4XALuJKoP[`P'LYX?W^^~~D^YeT[kjsS\^}M^j|D\^H=x6k^sRRKcZK\kCdx~W[~LyFPc[~L[y6lKZ%OjEP4PNIh~}@zz0fL]~N\QXwQ]LQzN{xh._bkr86Zk]SiHClOFKiR_YQWm^kfTlLDmT]VYO7IJIV_P.<XaZ\N_^jnS7O@Ym+\~M\zs9N^x1gGz6Q+Hw~>XU[h>b^l~O`|O
```
which translates to the Phred scores:
```
 35  33  50  63  26  56  71  18  41  58  29  54  70  28  62  25  37  46  46   4 
 49  72  72  64   5  24  72  27  42  29  35  11  14  26  23  68  30  49  48  44 
 52  62  79  41  62  29  66  34  47  52  78  51  62  64   8  52  42  74  27  24 
 79  31  54  81  27   9  38  73  74  74  28  59  54  44  40  12  15  39  22  57 
 24  35  11  42  72  29  48  40  44  36  41  33  25  18  15  46  47  84  85  25 
 63  48  52  38  75  57  49  64  58  75  40  57  93  93  32  81  21  50  52  77 
 66  71  13  52  69  40  73  93  61  38  66  10  43  67  86  16  54  83  59  25 
 61  86  54  60  93  51  60  93  44  46  63  58  76  58  70  32  81  18  81  22 
 58  63  57  20  42  69  74  62  61  65  13  53  82  60  58  93  62  59  61  56 
 47  58  61  61  77  57  32  69  43  60  60  52  55  88  43  59  63  82  31  48 
 24  44  33  55  50  77  59  54  62  52  20  83  58  80  47  36  57   9  45  48 
 66  56  76  61  75  75  60  60  73  19  55  32  43  84  41  42  78  47  58  63 
 47   6  43  56  55  30  54  61  61  93  93  35  61  56  68  51  58  74  73  82 
 50  59  61  92  44  61  73  91  35  59  61  39  28  87  21  74  61  82  49  49 
 42  66  57  42  59  74  34  67  87  93  54  58  93  43  88  37  47  66  58  93 
 43  58  88  21  75  42  57   4  46  73  36  47  19  47  45  40  71  93  92  31 
 89  89  15  69  43  60  93  45  59  48  55  86  48  60  43  48  89  45  90  87 
 71  13  62  65  74  81  23  21  57  74  60  50  72  39  34  75  46  37  42  72 
 49  62  56  48  54  76  61  74  69  51  75  43  35  76  51  60  53  56  46  22 
 40  41  40  53  62  47  13  27  55  64  57  59  45  62  61  73  77  50  22  46 
 31  56  76  10  59  93  44  59  89  82  24  45  61  87  16  70  38  89  21  48 
 10  39  86  93  29  55  52  58  71  29  65  61  75  93  46  63  91  46
```
 with an average of 53.71918 (the same as `bioawk`), and not 21.75 (as in `seqkit`).

- [x] `seqkit version` = v0.15.0

With kind regards,
Vladimir

**Comment by shenwei356** [comment]
> you can’t just do simple arithmetic mean of all the qscores, because it won’t be a representation of the mean error rate then.

https://gigabaseorgigabyte.wordpress.com/2017/06/26/averaging-basecall-quality-scores-the-right-way/

**Comment by vmikk** [comment]
Thank you for the clarification! I was not aware that `seqkit` estimates average sequence quality this way. But indeed, this estimate should be a better representation of the mean error rate.
