### ISSUE TITLE
Enhancement request

### ISSUE THREAD

**Issue by ssvbio** [shenwei356/seqkit#19]
Thank you for a wonderful parsing tool. After much usage, I would like to request following features.
Please add

- extract sequence by number (for fasta file). Use case: I would like to extract n th file
- Tail function. Head function is already implemented. Tail function is missing
- inverse selection for bases in a sequence. Current version allows user to select bases at the start, in the middle and at the end. It would be difficult for user to choose first few bases and last few bases. This would help user in removing sequences in the start and end of a read or a  long sequence
- Allow user to search by stop codon *. Stop codon * is present in few of predicted sequences. Currently user cannot search by * in the sequences.

**Comment by shenwei356** [comment]
- extract sequence by number (for fasta file). Use case: I would like to extract n th file

    not clear

- Tail function. Head function is already implemented. Tail function is missing

        seqkit fx2tab | tail | seqkit tab2fx

- inverse selection for bases in a sequence. Current version allows user to select bases at the start, in the middle and at the end. It would be difficult for user to choose first few bases and last few bases. This would help user in removing sequences in the start and end of a read or a long sequence

    i understand this, but it not so useful in practice.

- Allow user to search by stop codon *. Stop codon * is present in few of predicted sequences. Currently user cannot search by * in the sequences.

        seqkit grep -r -p '\*' # it should work

**Comment by ssvbio** [comment]
1) Use case: I would like to extract every 4th sequence from fasta file or every 4th and 6th file either from the top or bottom of fasta file.

2) There is a head function like this: seqkit head -n 1 hairpin.fa.gz. I would like similar tail function.  
3) use case: https://www.biostars.org/p/263861/
4) I tried it on following fasta file and didn't work.  seqkit grep -r -p '\*' test.fa gives me blank lines

$ cat test.fa 
>p1
ACDLA
>p2
ADCGLAGCTYLAKQ*
>P3
GTCTY*ATCG
>P4
*GAP
>P5
AGATE

**Comment by shenwei356** [comment]
1.  seqkit fx2tab | sed / awk | seqkit tab2fx
2.  seqkit fx2tab | tail | seqkit tab2fx
3.  easy for region without overlap, but will be out of control for completed cases.
4.  seqkit grep -s -r -p '\*'

**Comment by shenwei356** [comment]
@ssvbio  check new version: [v0.7.0](https://github.com/shenwei356/seqkit/releases/tag/v0.7.0)

1. `seqkit range -r 4:4` for retrieving 4th records
1. `seqkit range -r -10:-1` for retrieving last 10 records (tail)
