### ISSUE TITLE
Feature request: locate returning unmatched sequence

### ISSUE THREAD

**Issue by waemm** [shenwei356/seqkit#190]
Hi,

Thanks for a great tool! I was wondering if its possible for locate to return unmatched fasta/fastq reads as well? Or at least having the grep "-v" for collecting the inverse matches. 

I was wondering if  its possible to collect unmatched reads by using a  "NNNNNN" pattern? I have not managed to get this to work though.

Thanks again!
Warren

**Comment by shenwei356** [comment]
use `seqkit grep`
