### ISSUE TITLE
seqkit amplicon & multithreading

### ISSUE THREAD

**Issue by mlosilla** [shenwei356/seqkit#192]
hi,

I am running seqkit amplicon version 0.15.0 on CentOS 7. I set the number of threads I want to use with the -j flag, but according to the output of top, seqkit is only using one CPU (%CPU displays ~110). 

Does this mean that seqkit is not using the CPUs I request? If so, what am I doing wrong?

the input for seqkit amplicon is one fastq file with ~7000 sequences. My command is:
seqkit amplicon $input_fastq --bed -m $mismatches -p $primer_file -t dna -j $threads -w 0 -o $bed_file

Thanks!

**Comment by shenwei356** [comment]
> Does this mean that seqkit is not using the CPUs I request?

No, most subcommands only utilize a single CPU. Using multi-threads does not always bring performance improvement, cause file read/write is the bottleneck most of the time. Here's a [note](https://bioinf.shenwei.me/seqkit/note/#sequence-parsing-strategies) I wrote.

**Comment by shenwei356** [comment]
Hi @mlosilla  , I've optimized the FM-indexing, `seqkit amplicon -m` is *20X faster* ! Please try this:

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6228636/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6228637/seqkit_linux_amd64.tar.gz)

Using multithreading could further accelerating searching, but I may implement it later.

**Comment by mlosilla** [comment]
hi @shenwei356 

Thank you so much for these improvements! I have finished this part of my current project, but I will certainly be using seqkit in the future, it is a fantastic tool and you keep making it better! I am sure this will be useful to many.

Many thanks!
