### ISSUE TITLE
grep sub command with -m is very slow

### ISSUE THREAD

**Issue by niuniudevp** [shenwei356/seqkit#193]
hi,

I am running seqkit grep version 0.15.0 on MacOS. I want to filter out fastq sequences start with a certain sequence and allow some mismatch, I used this command:
"cat L1_1.fq.gz|seqkit grep -j 12 -s -i -p 'TCTTGTGGAAAGGACGA' -m 1 -P -R 1:35 -o 1_5-m1.fq.gz"
but this command performing very slow, after 12h the out put file is only 20B size.
after remove -m the command output result in 2min

what am I doing wrong? 
Thanks!

**Comment by shenwei356** [comment]
Yes, it's slow, especially for FASTQ.  You may use demultiplex tools designed for this job, e.g., https://demultiplex.readthedocs.io/en/latest/usage.html

Searching with mismatches in SeqKit performs real-time Burrows-Wheeler Transforming and FM-indexing, which is slow for a larger number of sequences. Besides only a single thread is used for `seqkit grep/locate`, I may parallelize it when I'm free.

**Comment by niuniudevp** [comment]
> Yes, it's slow, especially for FASTQ. You may use demultiplex tools designed for this job, e.g., https://demultiplex.readthedocs.io/en/latest/usage.html
> 
> Searching with mismatches in SeqKit performs real-time Burrows-Wheeler Transforming and FM-indexing, which is slow for a larger number of sequences. Besides only a single thread is used for `seqkit grep/locate`, I may parallelize it when I'm free.

Thansk a lot!

**Comment by shenwei356** [comment]
> after 12h the out put file is only 20B size

But It should not be that slow.

Try the new version? 0.15.1

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6046964/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/6046963/seqkit_darwin_arm64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6046962/seqkit_darwin_amd64.tar.gz)

**Comment by shenwei356** [comment]
Hi @niuniudevp , I've optimized the FM-indexing, `seqkit grep -m` is *400X faster* ! Please try this:

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6228636/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6228637/seqkit_linux_amd64.tar.gz)

**Comment by shenwei356** [comment]
The FM-indexing is further optimized

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6235640/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6235643/seqkit_linux_amd64.tar.gz)

**Comment by shenwei356** [comment]
I'm closing this.
