### ISSUE TITLE
unexpected output for `subseq` on bed files with blank column 5 

### ISSUE THREAD

**Issue by timedreamer** [shenwei356/seqkit#195]
Hi Wei!

Maybe this is an enhancement. I notice some unexpected output when working with bed files using `seqkit subseq`. An example is at the end.

I sometimes got bed files with a blank column 5, but still has strand in column 6. Basically, if column 5 of the bed file is blank (still hold the column), then the column six strand information will not be used by `seqkit subseq`.  

Although it can be easily adjusted by adding some text in column 5, the trick is not in the document (I think?).

Maybe worth mentioning this in the doc or allow the column 5 be blank.

Please correct me if I missed something! 

Thanks for this awesome tool.
Ji 

---
An example:

```
[V4] cat -A t1.bed
seq^I5^I8^IA^I^I+$
seq^I5^I8^IB^I^I-$
[V4] cat t.fa
>seq
actgACTGactgn
[V4] seqkit subseq --bed t1.bed t.fa
[INFO] read BED file ...
[INFO] 2 BED features loaded
>seq_6-8:. A
CTG
>seq_6-8:. B
CTG

```

**Comment by shenwei356** [comment]
Thanks for reporting. It's an old bug :(

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6066290/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/6066291/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6066289/seqkit_darwin_amd64.tar.gz)
