### ISSUE TITLE
non-greedy grep?

### ISSUE THREAD

**Issue by dlnp2** [shenwei356/seqkit#196]
When applying `seqkit grep` for a very large FASTA file (~120GB), it usually takes a prohibitively long time before it returns a result. I guess this stems from the greedy behavior of `seqkit grep`. Could you add "the first N hits" option?

**Comment by shenwei356** [comment]
Are the sequences long? Can you paste the result of the commands below?

    seqkit head -n 100 seqs.fasta | seqkit stats

What do you mean the "greedy behavior"? Can you paste your commands?

**Comment by dlnp2** [comment]
@shenwei356
Thank you very much for your quick reply.
```shell
$ seqkit head -n 100 seqs.fasta | seqkit stats
file  format  type     num_seqs  sum_len  min_len  avg_len  max_len
-     FASTA   Protein       100   25,147       50    251.5    1,165
```
and the command was
```shell
seqkit grep -rp <ID> seqs.fasta
```
Here `<ID>` was the id of the first entry in the FASTA file. Am I doing something wrong?

**Comment by shenwei356** [comment]
You need [seqkit faidx](http://bioinf.shenwei.me/seqkit/usage/#faidx), which is for retrieving records with IDs supports regular expression too.

```
$ seqkit faidx seqs.fasta <ID> -f 
```

**Comment by dlnp2** [comment]
Thank you for the suggestion. `seqkit faidx seqs.fasta <ID>` created a `.fasta.fai` file (~10GB). But even with this file, `seqkit faidx seqs.fasta <ID>`is still slow...

**Comment by shenwei356** [comment]
OK, the input sequence file is just too big. 10GB is also too big for a `.fai` file.

We can add an option for stop search right after one or more records are found,  but if the wanted records are at the tail of the file, it still needs to read the whole file.

**Comment by shenwei356** [comment]
Try use `seqkit head -n 1 ` followed the `seqkit grep` command,` seqkit head` should stop the two commands when one record is returned.

    seqkit grep -p <ID> seqs.fasta | seqkit head -n 1

**Comment by dlnp2** [comment]
I am sorry for the late reply. I tried your suggestion but got a slow response. I am afraid that my database is too large, thus will try other method. Thank you again for your kind responses.

**Comment by shenwei356** [comment]
I add a new flag `-I/--immediate-output`, which stops using writing buffer and returns a sequence immediately. This should be the right answer.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6204438/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6204439/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/6204441/seqkit_windows_amd64.exe.tar.gz)

**Comment by dlnp2** [comment]
@shenwei356 Thanks a lot!!!!! This saved me.
