### ISSUE TITLE
log-scale calculation of quality

### ISSUE THREAD

**Issue by osilander** [shenwei356/seqkit#198]
As I understand, currently seqkit calculates read quality based on an average (median or mean?) of phred-based q-scores along a read, and from there calculates %Q20, %Q30, etc.

This is problematic for low quality (ONT, PacBio) reads. For example, the phred-based mean of a 4 bp read with qualities 40, 40, 2, 2 would be 21 - so 99% sure the sequence is correct. However, this should be closer to 68%. This is clear if we first translate to accuracy  - the average of 99.99, 99.99, 36.9, and 36.9 is 68.

Could you add this option to this amazing tool?

**Comment by shenwei356** [comment]
We have used power and log transform. check here: 

https://github.com/shenwei356/bio/blob/master/seq/seq.go#L701

https://github.com/shenwei356/bio/blob/master/seq/seq.go#L20

similar issue #189

**Comment by osilander** [comment]
Thanks!

I actually didn't realise the `seqkit stats` %Q20 was for all bases - I thought it was average for a read (like, % reads with average q-scores of Q20 or above). I now understand I need the fx2tab.
