### ISSUE TITLE
seqkit bam

### ISSUE THREAD

**Issue by hugs314** [shenwei356/seqkit#200]
I saw this cmd in the nanopore tutorial, and I hope you can help me answer it. Thank you!!!
seqkit bam -j 20 -x -T 'AlnContext: { Ref: "hg38.fa", LeftShift: -24, RightShift: 24, RegexEnd: "[Aa]{8,}", Stranded: True, Invert: True, Tsv: "alignments/internal_priming_fail.tsv"} ' -

**Comment by shenwei356** [comment]
But, what's happening?

**Comment by hugs314** [comment]
> But, what's happening?

I'm not sure what this command does. It should filter the record in BAM, So I looked up the seqkit tutorial, but I still don't know what exactly this command does

**Comment by shenwei356** [comment]
> monitoring and online histograms of BAM record features 

Actually, I have never try it 😅  
@bsipos maintains it, maybe he can help to explain.

**Comment by hugs314** [comment]
> > monitoring and online histograms of BAM record features
> 
> Actually, I have never try it 😅
> @bsipos maintains it, maybe he can help to explain.

ok，thank you very much.

**Comment by diysmr** [comment]
@hugs314 Based on having a glance at the somewhat shoddily written code in `bam_toolbox.go` the mystery command line 🤣 invokes a function that looks at the rightmost mapping coordinate of the read and filters out the records that match the regular expression `[Aa]{8,}` (more than 8 consecutive As). Some info about the records which are filtered out are logged in `alignments/internal_priming_fail.tsv`.

**Comment by hugs314** [comment]
@diysmr thank you for your answer.  By your answer, I have already understood what this command is intended to do

**Comment by botond-sipos** [comment]
Thanks @camillaugolini-iit for reporting this bug! I have submitted a pull request with the fix: https://github.com/shenwei356/seqkit/pull/567
