### ISSUE TITLE
reverse translate

### ISSUE THREAD

**Issue by nick-youngblut** [shenwei356/seqkit#201]
Feature request: It would be great if seqkit included a reverse translate feature. 

Regardless, the software is great!

**Comment by shenwei356** [comment]
Reversing codon to DNA is ambiguous due to different codons can be translated to some amino acids.

**Comment by nick-youngblut** [comment]
I meant as in revTrans, but one can always just use revTrans. Adding the revTrans code to seqkit just helps to centralize general sequence manipulation tools

**Comment by shenwei356** [comment]
sorry, it's out of consideration
