### ISSUE TITLE
How to drop sequences with degenerate nucleotides with `seq` command

### ISSUE THREAD

**Issue by VorontsovIE** [shenwei356/seqkit#202]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

Dear @shenwei356 ,
First of all, thank you for your fantastical tool, it helps me a lot!
I wanted to ask you if there is a way to drop any sequences which has N-nucleotides (or other IUPAC-nucleotides) in `seq` command? For downstream analysis I want to leave only sequences without degenerate nucleotides, is it possible?
Smth like 
`echo -e ">seq1\nACGT\n>seq2\nACNT" | ./seqkit seq --non-redundant`
would be very useful.

**Comment by shenwei356** [comment]
Using [grep](http://bioinf.shenwei.me/seqkit/usage/#grep)

```
$ echo -e ">seq1\nACGT\n>seq2\nACNT" \
    | seqkit grep -s -i -r -p '[^ACGT]' -v 
>seq1
ACGT
```
Where `[^ACGT]` is a regular expression representING any charactor except A, C, G, and T.

The relevant options:

```
  -s, --by-seq                 search subseq on seq, both positive and negative strand are searched, and mismatch allowed using flag -m/--max-mismatch
  -i, --ignore-case            ignore case
  -r, --use-regexp             patterns are regular expression
  -p, --pattern strings        search pattern (multiple values supported. Attention: use double quotation marks for patterns containing comma, e.g., -p '"A{2,}"'))
  -v, --invert-match           invert the sense of matching, to select non-matching records

```

**Comment by VorontsovIE** [comment]
Great! Thank you a lot, I didn't know about seqkit's grep.
