### ISSUE TITLE
[Suggestion] Mention homebrew installation method in README

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/seqkit#204]
[Another one in Homebrew](https://github.com/Homebrew/homebrew-core/pull/75950). :)

```
brew install seqkit
```

**Comment by shenwei356** [comment]
Thanks, though it's already in brewsci https://github.com/brewsci/homebrew-bio/blob/develop/Formula/seqkit.rb

    brew install brewsci/bio/seqkit
