### ISSUE TITLE
Is it be possible to delete specific sequence from multi-FASTA file by ID?

### ISSUE THREAD

**Issue by kopelol** [shenwei356/seqkit#205]
Is it be possible to delete specific sequence from multi-FASTA file by ID?

I would like to delete some sequences from multi-FASTA file by specifying ID, then output new multi-FASTA file.

For example, in case of following file, 
>ABC
atgcatacggctagcatcgatcgatcgactg
>DEF
actgatcgatacgtcgatgatcgtcactgcat
>GHI
cgatcgatgatcgacatcgatcatcgaaacgatg

I would like to following create new file after deleting DFE sequence.
>ABC
atgcatacggctagcatcgatcgatcgactg
>GHI
cgatcgatgatcgacatcgatcatcgaaacgatg

Thanks,

**Comment by kopelol** [comment]
**>ABC**
atgcatacggctagcatcgatcgatcgactg
**>DEF**
actgatcgatacgtcgatgatcgtcactgcat
**>GHI**
cgatcgatgatcgacatcgatcatcgaaacgatg

**Comment by shenwei356** [comment]
[seqkit grep  -v](https://bioinf.shenwei.me/seqkit/usage/#grep)

    seqkit grep -p DFE -v input.fasta -o output.fasta

Where

      -v, --invert-match           invert the sense of matching, to select non-matching records

**Comment by kopelol** [comment]
Thank you very much.
