### ISSUE TITLE
fx2tab complaining about headers

### ISSUE THREAD

**Issue by Axze-rgb** [shenwei356/seqkit#206]
Hello,

what are the requirements of seqkit as for the formatting of fasta headers? For example, I am trying to convert fasta to tab 

```
seqkit tab2fx organism.fa.transdecoder.pep  
[ERRO] at least two columns needed: >GIQZ01000001.1.p1_GENE.GIQZ01000001.1~~GIQZ01000001.1.p1__ORF_type:5prime_partial_len:425_(-),score=43.40,UniRef90_A0A087SZN6|46.4|3.40e-104_GIQZ01000001.1:681-1955(-)

```

I obviously need to parse the header, but I don't know which character seqkit doesn't like. 

Thank you

**Comment by shenwei356** [comment]
>  I am trying to convert fasta to tab

You need

    seqkit fx2tab organism.fa.transdecoder.pep

**Comment by Axze-rgb** [comment]
Ohhh right, thanks a lot
