### ISSUE TITLE
subsetting fasta file with pipe in header

### ISSUE THREAD

**Issue by lms272727** [shenwei356/seqkit#207]
I'm trying to subset sequences from a fasta file of approx 1.2 million viral sequences based on collection date.
The problem is that the fasta header has three dates (year, collection date, submission date) separated by |, for example:

>hCoV-19/USA/ME-HETL-J0102/2020|2020-08-25|2021-01-01

I know that the file has (for example) 18217 sequences which were collected during July 2020, but the following command:

seqkit grep -r -p "2020-07" sequences.fasta -o resultX.fa.gz

returns 44324 sequences, presumably due to sequences which were either collected or submitted in July 2020.

I tried concatenating two search terms together (year plus collection date, so that submission date would not match) using:

seqkit grep -r -p "2020|2020-07" sequences.fasta -o resultY.fa.gz

but this returned 492271 matches - not sure why, is the pipes symbol interpreted strangely in regex searches?

Any suggestions?

**Comment by shenwei356** [comment]
Yes, you need to use backslash `\` to escape special characters in regular expression, including `-`, `|` and so on.

    seqkit grep -r -p "2020\-07" sequences.fasta -o resultX.fa.gz

    seqkit grep -r -p "2020\|2020\-07" sequences.fasta -o resultY.fa.gz

**Comment by lms272727** [comment]
Thanks! Works wonderfully
