### ISSUE TITLE
Can seqkit replace the gap length to the same size (different N to 100N) in the fasta?

### ISSUE THREAD

**Issue by hungweichen0327** [shenwei356/seqkit#208]
Dear community,

I am not sure whether seqkit can replace the N of different length in each sequence to 100 Ns from the fasta file according to the seqkit manual. Currently I have the assembly.fasta file in which the scaffolds have different gap length (i.e. different N number). And I want to change the different gap length to the same gap length (100 Ns).

Thank you for the help.

**Comment by shenwei356** [comment]
```
$ echo -ne ">s\nACNNNNNNGT\n" | seqkit replace -s -p "[Nn]+" -r "NNN"
>s
ACNNNGT
```

**Comment by hungweichen0327** [comment]
Dear @shenwei356,

Thank you for the quick reply and help. I am very appreciated!
