### ISSUE TITLE
Here are instructions on installing via homebrew

### ISSUE THREAD

**Issue by tseemann** [shenwei356/seqkit#21]
```
brew tap homebrew/science
brew tap tseemann/bioinformatics-linux
brew install seqkit
```

(it works for OSX and Linux despite the -linux tap name)
(eventually we will build from source and add to homebrew/science directly)

**Comment by shenwei356** [comment]
That's cool, I was really confused how to add app to homebrew.

**Comment by ctava** [comment]
brew install wget --with-libressl

**Comment by tseemann** [comment]
The above information is out of date.

It is now `brew install brewsci/bio/seqkit`

**Comment by shenwei356** [comment]
Thank you @tseemann , tha's simple enough, I'll maintain the formula.

**Comment by shenwei356** [comment]
submitted a PR, hope it merged soon.

**Comment by shenwei356** [comment]
merged, you can brew update it 👻
