### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by Timmywang1** [shenwei356/seqkit#211]
I got the following error when I tried to count the number of read in FASTQ form. command 'seqkit stat 1111.fq ' or 'seqkit stat *.fq'

panic: runtime error: index out of range [-1]

goroutine 13 [running]:
github.com/shenwei356/bio/seqio/fastx.(*Reader).read(0xc00010e000)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seqio/fastx/reader.go:229 +0x7ae
github.com/shenwei356/bio/seqio/fastx.(*Reader).Read(...)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seqio/fastx/reader.go:141
github.com/shenwei356/seqkit/seqkit/cmd.glob..func29.3(0xc000455740, 0xc000030210, 0x1, 0x0, 0xaf69c8, 0x9, 0xc00002a2a0, 0xc0000e3860, 0x0, 0xc000455730, ...)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/stat.go:320 +0x30a
created by github.com/shenwei356/seqkit/seqkit/cmd.glob..func29
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/stat.go:283 +0x8d4

What is wrong?
Thanks!

**Comment by shenwei356** [comment]
Please tell me the version of seqkit.

    seqkit version

**Comment by Timmywang1** [comment]
version 0.15.0

**Comment by shenwei356** [comment]
please update to the lastest version, and attach a small compressed file that could reproduce the error.

**Comment by shenwei356** [comment]
I'll close this issue cause there's no response.
