### ISSUE TITLE
how to restrict range of sequence from 100bp from start to 100bp before end

### ISSUE THREAD

**Issue by yipukangda** [shenwei356/seqkit#213]
Hi, 

When calling `fish` modue I want to restrict the search range to `from 100bp from start to 100bp before end`, how to set the `-r` argument, I tried `-r 100:-100` then be feedback with an error: `panic: invalid range: 100:-100`

**Comment by shenwei356** [comment]
I check the [code](https://github.com/shenwei356/seqkit/blob/master/seqkit/cmd/seq_detect.go#L114), it is supposed to support this. But [the parameter checking](https://github.com/shenwei356/seqkit/blob/master/seqkit/cmd/fish.go#L105) stopped this.

Try the patch

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6573929/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/6573931/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6573928/seqkit_darwin_amd64.tar.gz)

**Comment by yipukangda** [comment]
@shenwei356 Thank, adding the patch dose work.
