### ISSUE TITLE
Does rmdup ignore reverse complement?

### ISSUE THREAD

**Issue by ythuang0522** [shenwei356/seqkit#215]
Hi, I pulled the latest version and tried rmdup for removing duplicated reads
When creating artificial reads of one forward duplicate and one of reverse complement.
```
more test.fa 
>1
ATCGATATGGCCGTATATATGGGTTTTAATTC
>2
ATCGATATGGCCGTATATATGGGTTTTAATTC
>3
GAATTAAAACCCATATATACGGCCATATCGAT
```

```
./seqkit rmdup -s test.fa 
[INFO] 1 duplicated records removed
>1
ATCGATATGGCCGTATATATGGGTTTTAATTC
>3
GAATTAAAACCCATATATACGGCCATATCGAT
```
It looks the reverse complement is not considered.
Just wanna double confirm.
Would be nice to have this feature for removing duplicated reads.

Thanks,
Yao-Ting

**Comment by shenwei356** [comment]
Thank you for the suggestion, I've added a flag to make it optional.

>   -r, --consider-revcom        considering the reverse compelment sequence

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6660871/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6660872/seqkit_linux_amd64.tar.gz)

**Comment by shenwei356** [comment]
Closing this.
