### ISSUE TITLE
[Suggestion] Add an option to ignore gaps in 'seqkit sort --by-length'

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/seqkit#216]
Let's say you have a MSA and you want to sort the sequences by length. Because every entry, by definition, will have the same length it could be useful to have a option to ignore `-` characters in `seqkit sort --by-length`.

For example, this file:
```
>seq1
TACGTT---TACATGG-TC---
>seq2
GGCGTT---TTCATGG-TCA--
>seq3
GACGTA-ACTACATCG-TCA--
```
Would be sorted like this:
```
>seq3
GACGTA-ACTACATCG-TCA--
>seq2
GGCGTT---TTCATGG-TCA--
>seq1
TACGTT---TACATGG-TC---
```

**Comment by jmonroynieto** [comment]
This can already be achieved using `seqkit seq -g text.fasta | seqkit sort -l`.

**Comment by shenwei356** [comment]
>  3. if you have large number of IDs, you can use:
>        seqkit faidx seqs.fasta --infile-list IDs.txt

Thank you @jmonroynieto , long list is also supported.

    seqkit faidx example.fasta --infile-list <(seqkit seq -g example.fasta | seqkit sort -l | seqkit seq -n -i).

> Add an option to ignore gaps in 'seqkit sort --by-length' 

I'll add this.

**Comment by apcamargo** [comment]
Thank you!

**Comment by shenwei356** [comment]
#223

**Comment by shenwei356** [comment]
> Add an option to ignore gaps in 'seqkit sort --by-length'

done.

```
  -b, --by-bases                by non-gap bases
  -G, --gap-letters string      gap letters (default "- \t.")

```


```

$ cat t.fa
>a
a-c-t-g
>b
aacct-g
>c
--c-t-g

$ seqkit sort --by-bases t.fa
[INFO] read sequences ...
[INFO] 3 sequences loaded
[INFO] sorting ...
[INFO] output ...
>c
--c-t-g
>a
a-c-t-g
>b
aacct-g

```

**Comment by apcamargo** [comment]
Thank you!
