### ISSUE TITLE
Question/Suggestion

### ISSUE THREAD

**Issue by itaxlab** [shenwei356/seqkit#218]
Hi Wei Shen

Amazing tool! I really appreciate seqkit, it helps a lot!

Is it possible to also wrap .fasta sequences with "seqkit sana" or just .fastq files?

Would be great feature! I am generating an artificial genome out of many fasta sequences in a single multi .fasta file.
Maybe that could also be of interest for a new seqkit function. So the tasks would be:
1. .fasta file containing many sequences
2. removing all headers
3. removing all line breaks
4. adding new header for the whole sequence
5. wrapping the now single sequence into standard 60 lines
maybe:
6. split the new huge sequence into smaller pieces (like contigs of an assembly)

Thanks and cheers Lucas

**Comment by shenwei356** [comment]
example:

```
$ cat seqs.fa 
>a
aaaa
>c
cccccc
cccccc
>g
ggggggggggg
gggggg

```

1-5:

```
$ (echo ">new header"; seqkit seq -s seqs.fa) | seqkit seq -w 10
>new header
aaaacccccc
ccccccgggg
gggggggggg
ggg

```

6.

```
$ (echo ">new header"; seqkit seq -s seqs.fa) \
      | seqkit seq -w 10 \
      | seqkit sliding -s 20 -W 20 -g
>new_sliding:1-20
aaaaccccccccccccgggg
>new_sliding:21-33
ggggggggggggg

$ (echo ">new header"; seqkit seq -s seqs.fa) \
      | seqkit seq -w 10 \
      | seqkit sliding -s 20 -W 20 -g \
      | seqkit replace -p '.+' -r 'piece{nr}'
>piece1
aaaaccccccccccccgggg
>piece2
ggggggggggggg
```

**Comment by itaxlab** [comment]
Many thanks for your fast reply! Cool!

Just one additional question.

Would it be possible to split a .fasta file with multiple sequences into several smaller fasta files, each with a defined total length of sequences?

e.g. 1 huge fasta —> X fastas containing sequences not longer than a total length of e.g. 10Mb

Thanks and best
Lucas

Lucas Blattner | MSc Biogeography/Applied Ecology
Integrative Taxonomy Lab GmbH
Hollenweg 1 | 4153 Reinach | Switzerland
Tel. +41 79 587 01 32 | Email ***@***.*** ***@***.***>
https://itaxlab.ch <https://itaxlab.ch/>

**Comment by shenwei356** [comment]
<= 10Mb is no supported, only supporting >= 10Mb:

    seqkit split2 -l

>   -l, --by-length string   split sequences into chunks of >=N bases, supports K/M/G suffix

**Comment by itaxlab** [comment]
Cool amazing!

Many thanks!

Lucas Blattner | MSc Biogeography/Applied Ecology
Integrative Taxonomy Lab GmbH
Hollenweg 1 | 4153 Reinach | Switzerland
Tel. +41 79 587 01 32 | Email ***@***.*** ***@***.***>
https://itaxlab.ch <https://itaxlab.ch/>
