### ISSUE TITLE
seqkit fx2tab - MD5/SHA1 column output option?

### ISSUE THREAD

**Issue by tseemann** [shenwei356/seqkit#219]
I am making good use of `seqkit seq` but could not find a way to generate a hash of the sequence, eg md5, sha1 or sha256.

I know `rmdup` etc use hashes internally but is it would be amazing to be able to print a hash in `fx2tab` along with other TSV columns that it suports (eg. length, ID, no-sequence etc)

Thanks for considering this option
Or telling me another (efficient) way I can do it

(I have 2 million viral genomes)

**Comment by shenwei356** [comment]
`seqkit fx2tab` provides an option:

>   -s, --seq-hash               print hash of sequence (case sensitive)

````
$ echo -ne ">s\nactg\n>S\nACTG\n" \
    | seqkit fx2tab -s
s       actg            93303730909596952
S       ACTG            8091619150997941746
````

**Comment by tseemann** [comment]
I don't know how I missed this!

**Comment by shenwei356** [comment]
It uses xxhash (github.com/cespare/xxhash)

> Would you consider printing a fixed-width hexadecimal version instead?

sure

> Would you consider making it case-IN-sensitive?
> You have -I option already, but it only applies to -B ____ mode.

sure, working on it

**Comment by shenwei356** [comment]
Now, I'm computing MD5, which is shorter than SHA1.

```
[shenwei@BioS ~]$ echo -ne ">s\nactg\n>S\nACTG\n" \
    | seqkit fx2tab -s
s       actg            d9df8ea5717fa20b355691e9f80bccb5
S       ACTG            d9df8ea5717fa20b355691e9f80bccb5
[shenwei@BioS ~]$ echo -ne ">s\nactg\n>S\nACTG\n" \
    | seqkit fx2tab -s -I
s       actg            d9df8ea5717fa20b355691e9f80bccb5
S       ACTG            86bfb9f78dd8b6cd35962bb7324fdbf8
```
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6686092/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6686094/seqkit_linux_amd64.tar.gz)
