### ISSUE TITLE
[Request] csvtk sort -R    /or/ csvtk shuf

### ISSUE THREAD

**Issue by tseemann** [shenwei356/seqkit#220]
I want to randomly re-order the rows in my CSV file.

Basically unix `shuf` or `sort -R` but for xSV data.

The actual use case is to shuffle the data before using `csvtk uniq -n 40` say.
Is this possible?

**Comment by shenwei356** [comment]
Here is seqkit repo :sweat_smile:

**Comment by tseemann** [comment]
Whoops!
Stop writing so many good tools @shenwei356 ! :-)
