### ISSUE TITLE
seqkit fxtab - just ID & SEQ without QUAL?

### ISSUE THREAD

**Issue by tseemann** [shenwei356/seqkit#221]
I would like a TSV file of `ID \t SEQ` only.
This is for when it's a  FASTA file.
I do not not want the empty 3rd column.

I know I can pipe it to `cut -f 1,2` to remove it.
But that is inefficient on my 60 GB FASTA files.

Is there a `--no-qual` option for `fx2tab` ?

**Comment by shenwei356** [comment]
updated binaries are available at #219
