### ISSUE TITLE
Grep from FASTA file

### ISSUE THREAD

**Issue by MichWeb75** [shenwei356/seqkit#222]
Dear developers,

I am using `seqkit grep` to extract some sequences from a FASTA file. However, I dont get any matches with the following calls

```
seqkit grep -p "filter.2" fasta_file.fna
seqkit grep -n -p "filter.2" fasta_file.fna
```

The fasta file contains the following entries:
```
>IDABC_filter.1
>IDABC_filter.2
>IDABC_filter.3
```

How to extract some specific IDs ?

**Comment by shenwei356** [comment]
add `-r`

**Comment by MichWeb75** [comment]
Works! Thanks a lot!
