### ISSUE TITLE
Request: seqkit faidx -f  <file_of_regions>

### ISSUE THREAD

**Issue by tseemann** [shenwei356/seqkit#223]
I have a file of 2 million  viral genomes.
I need extract groups of sequences, usuaally ~1 to ~10,000.
I was using `seqkit frep -f IDS.txt` but it can be slow.

I indexed my FASTA with `seqkit faidx`
`seqkit faidx seqs.fasta $(cat IDS.txt)` is clumsy.

Could we have ` -f IDS.txt` (could be regions, not just IDs) ?

THis should be faster than `seqkit grep` ?

**Comment by shenwei356** [comment]
>   3. if you have large number of IDs, you can use:
>                seqkit faidx seqs.fasta --infile-list IDs.txt


```
$ cat test.txt 
ame-mir-9894:1-10

$ seqkit faidx --infile-list test.txt hairpin.fa 
[INFO] create FASTA index for hairpin.fa
>ame-mir-9894:1-10
UAUUAACUAU
```

**Comment by tseemann** [comment]
Sorry I did not see it the jhelp at the top!
COuld it appear int he tool options?
Instead of Global optioons?

**Comment by shenwei356** [comment]
added:

      -l, --region-file string   file containing a list of regions

    seqkit faidx -l test.txt hairpin.fa 

also supports `begin` > `start`, i.e., returning reverse complement sequence, not supported by `samtools faidx`

        $ seqkit faidx tests/hairpin.fa hsa-let-7a-1:10-1
        >hsa-let-7a-1:10-1
        CCUCAUCCCA

**Comment by shenwei356** [comment]
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6692994/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6692996/seqkit_linux_amd64.tar.gz)
