### ISSUE TITLE
seqkit shuffle --two-pass | seqkit split

### ISSUE THREAD

**Issue by nick-youngblut** [shenwei356/seqkit#225]
If I used `seqkit shuffle` with `--two-pass` and pipe that into `seqkit split`, not all sequences are parsed into the split files:

```
$ seqkit shuffle -j 1 --two-pass clusters_reps.faa.gz | seqkit split --by-part 5 --out-dir test_split
[INFO] read and write sequences to tempory file: clusters_reps.faa.gz.fastx ...
[WARN] outdir not empty: test_split, you can use --force to overwrite
[INFO] split into 5 parts
[INFO] read sequences ...
[INFO] 31800 sequences saved
[INFO] create and read FASTA index ...
[INFO] create FASTA index for clusters_reps.faa.gz.fastx
[INFO] read sequence IDs from FASTA index ...
[INFO] 31800 sequences loaded
[INFO] shuffle ...
[INFO] output ...
[INFO] read 1244 sequences
[INFO] write 249 sequences to file: test_split/stdin.part_001.fasta
[INFO] write 249 sequences to file: test_split/stdin.part_002.fasta
[INFO] write 249 sequences to file: test_split/stdin.part_003.fasta
[INFO] write 249 sequences to file: test_split/stdin.part_004.fasta
[INFO] write 248 sequences to file: test_split/stdin.part_005.fasta
```

If I remove `--two-pass`, then I get the correct number of sequences per split:

```
$ seqkit shuffle -j 1 clusters_reps.faa.gz | seqkit split --by-part 5 --out-dir test_split
[INFO] read sequences ...
[WARN] outdir not empty: test_split, you can use --force to overwrite
[INFO] split into 5 parts
[INFO] read sequences ...
[INFO] 31800 sequences loaded
[INFO] shuffle ...
[INFO] output ...
[INFO] read 31800 sequences
[INFO] write 6360 sequences to file: test_split/stdin.part_001.fasta
[INFO] write 6360 sequences to file: test_split/stdin.part_002.fasta
[INFO] write 6360 sequences to file: test_split/stdin.part_003.fasta
[INFO] write 6360 sequences to file: test_split/stdin.part_004.fasta
[INFO] write 6360 sequences to file: test_split/stdin.part_005.fasta
```

It would be good to at least have a warning about using `--two-pass`

I'm using seqkit 0.16.1.

**Comment by shenwei356** [comment]
I see, but I can't reproduce this, could you please provide a demo file?

You can also use `seqkit shuffle -k` to save the tmp file, and check several records in it.

You can also replace `seqkit split` with `seqkit split2`.

**Comment by nick-youngblut** [comment]
hmmm... now I can't reproduce the issue. 

In regards to `seqkit shuffle`, it would be great if one could select the temp file path for `--two-pass`

**Comment by shenwei356** [comment]
The temp file is only needed for the gzipped input file, nothing to do with `--two-pass`.

**Comment by nick-youngblut** [comment]
It appears that the message `[INFO] read and write sequences to tempory file: clusters_reps.faa.gz.fastx ...` is only displayed with `--two-pass` (see above). Is that temp file also written without `--two-pass`?

**Comment by shenwei356** [comment]
Oh, sorry, my memory is wrong ... 

It happens for gzipped input files in two-pass mode.

The tmp file could be "$inputfile.fastx", being in the same directory of the input file. 
The disk space would not be a problem. You may also uncompress it to anywhere and use the plain file as the input.
