### ISSUE TITLE
Help with renaming sequences

### ISSUE THREAD

**Issue by Ahmed-Shibl** [shenwei356/seqkit#229]
First, thanks for this extremely useful tool!

I have a fasta file of around ~3000 sequences with long headers. I wanted to rename the headers so that they show the organism's name only. I tried using the `rename` flag and the `seq --id-regexp` flag but couldn't get it right.
For clarification, I attached here a subset of my original FASTA file (Test.txt) and another file displaying the output I am seeking (Output_seeked.txt). n.b. attached as *.txt due to required format here.

Thanks a lot for your help and looking forward to learning how to do this!

[Output_seeked.txt](https://github.com/shenwei356/seqkit/files/6915566/Output_seeked.txt)
[Test.txt](https://github.com/shenwei356/seqkit/files/6915568/Test.txt)

**Comment by shenwei356** [comment]
seqkit replace -p ".+OS=(.+?) OX=.+" -r "\$1" Test.txt

or 

    seqkit seq --id-regexp "OS=(.+?) OX=" -i  Test.txt
