### ISSUE TITLE
seqkit grep is slow

### ISSUE THREAD

**Issue by zhoudreames** [shenwei356/seqkit#231]
it is a little slow when i using code :"seqkit grep -f file.txt all.fasta -j 100 >file.fa"
the size of all.fasta is so big,approch 1Tb,though my threads set to 100,but it no  use so many threads,instead of using 1~2 threads.i dont how to accelerate the time of extract reads ，could you help me ？

**Comment by zhoudreames** [comment]
@shenwei356 i am so sorry disturb you,could you help me? thanks~

**Comment by shenwei356** [comment]
Using 100 threads does not help for `seqkit grep`, cause the bottle-neck is file I/O.

But you can split the `all.fasta` into small pieces using `seqkit split2 `:

    seqkit split2 -p 10 all.fasta

And parallelize the `seqkit grep` using `parallel` or [rush](https://github.com/shenwei356/rush)

    ls all.fasta.split/*.fasta | rush -j 10 'seqkit grep -f file.txt {} > {}.tmp'

At last, merge the result

    cat all.fasta.split/*.tmp > result.txt

**Comment by zhoudreames** [comment]
thanks~
