### ISSUE TITLE
seqkit grep to select entries by fasta header

### ISSUE THREAD

**Issue by lborcard** [shenwei356/seqkit#232]
### Prerequisites

- [ OK] make sure you're are using the latest version by `seqkit version`
- [OK ] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

I need to select entries from a fasta header by EPI ids from GISAID  e.g EPI_ISL_926748
`echo EPI_ISL_926748 > test_epi.txt`
* my fasta header
```
grep ">" msa_0730_raw.fasta

>hCoV-19/Denmark/DCGC-35607/2021|EPI_ISL_926748|2021-01-18|Europe
>hCoV-19/USA/VT-MASPHL-02609/2021|EPI_ISL_1503779|2021-03-09|NorthAmerica
>hCoV-19/USA/CA-CDC-QDX23761630/2021|EPI_ISL_1753647|2021-04-05|NorthAmerica
>hCoV-19/USA/NY-Wadsworth-21021262-01/2021|EPI_ISL_1228278|2021-02-09|NorthAmerica
>hCoV-19/England/TFCI-2701DED/2021|EPI_ISL_924781|2021-01-06|Europe
>hCoV-19/England/MILK-B8C6E1/2020|EPI_ISL_675834|2020-11-12|Europe

`seqkit grep -n -f test_epi.txt msa_0730_raw.fasta`
```
expected output:
`>hCoV-19/Denmark/DCGC-35607/2021|EPI_ISL_926748|2021-01-18|Europe`

Actual output 
` nothing`

thank you for your help

**Comment by shenwei356** [comment]
The EPI ids are just part of the headers, and not sure whether sequence headers have a uniform format. So switch on `-r/--use-regexp` (slower)

    seqkit grep -n -r -f test_epi.txt msa_0730_raw.fasta

Suppose they are well-formatted, let's specify where the ID is (faster):

    seqkit grep --id-regexp "^[^|]+\|([^|]+)" -f test_epi.txt msa_0730_raw.fasta

**Comment by lborcard** [comment]
Thanks a lot for your answer the command is running, we'll see about the output.  Although it is already very helpful, Perhaps it would help new users to specify such things in the manual page. I am also struggling with seqkit locate to reproduce your example 
```
$ seqkit grep --pattern-file id2.txt viral.1.1.genomic.fna.gz \
    | seqkit locate --ignore-case --only-positive-strand --pattern K+ --pattern N+
seqID   patternName     pattern strand  start   end     matched
gi|564292828|ref|NC_023009.1|   N+      N+      +       87972   87972   N
gi|564292828|ref|NC_023009.1|   N+      N+      +       100983  100983  N
gi|557307918|ref|NC_022755.1|   K+      K+      +       1788    1788    K
gi|557307918|ref|NC_022755.1|   K+      K+      +       4044    4044    K
gi|589287065|ref|NC_023585.1|   K+      K+      +       28296   28296   K
gi|590911929|ref|NC_023639.1|   N+      N+      +       741654  741753  NNNNNNNNNNNNNNNNNNNNNNNNNNN
```
I am trying to get the location and the length of regions of N in a multiple alignment file but it's returning something else
```
 seqkit locate -d --ignore-case --only-positive-strand --pattern N+ msa_0730_raw.fasta
hCoV-19/Wuhan/WIV04/2019|EPI_ISL_402124|2019-12-30|China        N+      N+      +       126     174     ATTAAAGGTTTATACCTTCCCAGGTAACAAACCAACCAACTTTCGATCT
hCoV-19/Wuhan/WIV04/2019|EPI_ISL_402124|2019-12-30|China        N+      N+      +       176     185     CTTGTAGATC
hCoV-19/Wuhan/WIV04/2019|EPI_ISL_402124|2019-12-30|China        N+      N+      +       189     203     TGTTCTCTAAACGAA
hCoV-19/Wuhan/WIV04/2019|EPI_ISL_402124|2019-12-30|China        N+      N+      +       216     216     C
hCoV-19/Wuhan/WIV04/2019|EPI_ISL_402124|2019-12-30|China        N+      N+      +       228     228     T

````

**Comment by shenwei356** [comment]
Please use `-r/--use-regexp` instead of `-d/--degenerate`. Here, `N+` is a regular expression.

```
$ echo -ne ">seq\nACTGNACNNNNNC\n" \
    | seqkit locate --ignore-case --only-positive-strand --pattern N+ --use-regexp 
seqID   patternName     pattern strand  start   end     matched
seq     N+      N+      +       5       5       N
seq     N+      N+      +       8       12      NNNNN
```

Use `-d/--degenerate` when searching some fragment like `ACTGNACT`, where `N` is a degenerate base.
