### ISSUE TITLE
怎样取消-w 60的默认值

### ISSUE THREAD

**Issue by zhoudreames** [shenwei356/seqkit#233]
您好~，我想利用您开发的seqkit的工具快速检索序列的信息，但是我的序列不是fa的格式，而是有一个reads的id，如:“>reads_1”，以及这条reads包含的信息，如下图所示：
![image](https://user-images.githubusercontent.com/54714639/129338475-1156da8a-2c03-4de5-ba5a-924b98902bff.png)
当我使用seqkit grep -p reads_1 readInform.fa ,检索的结果如下：但是它会把默认的行以60个字符进行拆分，但我想保留原来行进行输出，可以实现这个吗？
![image](https://user-images.githubusercontent.com/54714639/129338842-d061960e-bd7d-40e6-8744-57075765ba33.png)

**Comment by zhoudreames** [comment]
@shenwei356 非常抱歉打扰您，您是否可以帮助我解答一下呢，谢谢~

**Comment by shenwei356** [comment]
seqkit faidx -f file.fa read_1

**Comment by shenwei356** [comment]
不支持。不过我看你那数据挺有规律，可以用其他工具重新调整格式：


    seqkit grep -p reads_1 t.txt  | sed -E 's/([a-z]+):/\n\1:\n/g' | awk '$0 != ""'
    >reads_1
    overlap:
    ###
    bam:
    ###
    indentity:
    ###

**Comment by zhoudreames** [comment]
> 不支持。不过我看你那数据挺有规律，可以用其他工具重新调整格式：
> 
> ```
> seqkit grep -p reads_1 t.txt  | sed -E 's/([a-z]+):/\n\1:\n/g' | awk '$0 != ""'
> >reads_1
> overlap:
> ###
> bam:
> ###
> indentity:
> ###
> ```

谢谢您~
