### ISSUE TITLE
Correlation between fasta sequences with p-value

### ISSUE THREAD

**Issue by gk7279** [shenwei356/seqkit#234]
### Prerequisites

- [ x] make sure you're are using the latest version by `seqkit version`
- [ x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [ x] describe the problem
* [ ] provide a reproducible example

If I have two fasta files, how do I compute the correlation with a p-value metric?
I plan to use this - https://mash.readthedocs.io/en/latest/tutorials.html#simple-distance-estimation
And was wondering if seqkit could do anything similar.
Thanks

**Comment by shenwei356** [comment]
not supported.

try sourmash (https://github.com/sourmash-bio/sourmash), another tool for comparing genome distance/similarity using minhash sketch, but it does not output p value.
