### ISSUE TITLE
seqkit sample

### ISSUE THREAD

**Issue by Gotumbtai** [shenwei356/seqkit#235]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

I used `seqkit sample` to do dwonsampling from my FASTQ files and following message was shown for some samples: 
`line 2:  3582 Done                    gzcat XXX_R1.fastq.gz
      3583 Killed: 9               | seqkit sample -s 100 -n 49000000 -o XXX_down_R1.fastq.gz`
And I found some output files were truncated. Does the message mean that the process ended up using too much memory? Thank you for your suggestion.

Best regards

**Comment by shenwei356** [comment]
```
$ seqkit sample -h
sample sequences by number or proportion.

Attention:
1. Do not use '-n' on large FASTQ files, it loads all seqs into memory!
   use 'seqkit sample -p 0.1 seqs.fq.gz | seqkit head -n N' instead!

Usage:
  seqkit sample [flags]

Flags:
  -h, --help               help for sample
  -n, --number int         sample by number (result may not exactly match), DO NOT use on large FASTQ files.
  -p, --proportion float   sample by proportion
  -s, --rand-seed int      rand seed (default 11)
  -2, --two-pass           2-pass mode read files twice to lower memory usage. Not allowed when reading from stdin
```

**Comment by Gotumbtai** [comment]
Thank you. I understand. I saw some of the files seemed to be successfully output even though they were also large. Should I re-run those files again with `seqkit sample -p` to unify the way of downsamling or do you think it is ok that some files were done with `-n` and others will be done with `-p` in one experiment? Or, is it probable that the output files by `-n` are also broken when they are large if the outputs seemed to show success?

**Comment by shenwei356** [comment]
> Should I re-run those files again with seqkit sample -p to unify the way of downsamling

There's no need.

> o you think it is ok that some files were done with -n and others will be done with -p in one experiment

Should be OK.

> Or, is it probable that the output files by -n are also broken when they are large if the outputs seemed to show success?

They should be OK unless you saw error message.

**Comment by Gotumbtai** [comment]
Thanks a lot!
