### ISSUE TITLE
seqkit rename feature request:  do not return original ID

### ISSUE THREAD

**Issue by dougwyu** [shenwei356/seqkit#236]
### Prerequisites

- [ ] make sure you're are using the latest version by `seqkit version`
- [ x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x ] describe the problem
* [ x] provide a reproducible example

I am using 0.16.0

seqkit rename's current behaviour returns the original ID like this from your example:
```
>a comment
aaaa
```
to

```
>a_2 a comment
aaaa
```

I have a feature request for a toggle so that seqkit rename does not return the original ID. 

I would like this output:
```
>a_2 comment
aaaa
```

**Comment by shenwei356** [comment]
Added a new flag

```
  -i, --inplace             rename ID in-place
```

Use these

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6999232/seqkit_darwin_amd64.tar.gz)
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/6999234/seqkit_darwin_arm64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/6999235/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_386.exe.tar.gz](https://github.com/shenwei356/seqkit/files/6999236/seqkit_windows_386.exe.tar.gz)


Example

```
$ cat seqs.fasta 
>a comment
aaaa
>a comment A
cccc
>b
ttt
>b
ggg


$ seqkit rename seqs.fasta 
>a comment
aaaa
>a_2 a comment A
cccc
>b
ttt
>b_2 b
ggg

$ seqkit rename seqs.fasta  -i
>a comment
aaaa
>a_2 comment A
cccc
>b
ttt
>b_2 
ggg

```

**Comment by dougwyu** [comment]
thank you!
