### ISSUE TITLE
missing -m or --md5 option from rmdup

### ISSUE THREAD

**Issue by MariusGheorghe** [shenwei356/seqkit#237]
Hi,

Reading the documentation present at: https://bioinf.shenwei.me/seqkit/usage/#seqkit it seems that there should be the possibility to use the MD5 checksum instead the actual read ID when using the `rmdup` subcommand:
```
Some subcommands need to store sequences or heads in memory, but there are strategy to reduce memory occupation, including rmdup and common. When comparing with sequences, MD5 digest could be used to replace sequence by flag -m (--md5).
```
but when I try it, it tells me there is no such option:
```
$ seqkit rmdup -m my_fastq_R1.fastq.gz my_fastq_R2.fastq.gz 
Error: unknown shorthand flag: 'm' in -m

$seqkit rmdup --md5 my_fastq_R1.fastq.gz my_fastq_R2.fastq.gz  
Error: unknown flag: --md5
```

I tried both `seqkit v0.15.0` (which is marked in the documentation) and latest `seqkit v0.16.1` with no success. Can you please let me know if that flag is still valid or if I am not constructing the command line correctly?

Thank you very much in advance!

Marius

**Comment by shenwei356** [comment]
Oh sorry, the homepage document was not kept updated, while the [usage page](https://bioinf.shenwei.me/seqkit/usage/#rmdup) is.

Flag `--md5` was removed since [v0.10.2](https://github.com/shenwei356/seqkit/releases/tag/v0.10.2), we recorded this change in the [download page](https://bioinf.shenwei.me/seqkit/download/):

> `seqkit common/rmdup/split`: use xxhash to replace MD5 when comparing with sequence, discard flag -m/--md5.

**Comment by MariusGheorghe** [comment]
Oh OK. Thanks for your prompt reply. So then I guess there is not much to do to reduce RAM consumption when dealing with deeply sequenced data (i.e., a very large number of reads). Tried also to use multi threading, but the RAM consumption plateaus when using `-j` >8 

Would you have other suggestion to reduce the memory footprint? Thank you very much in advance

**Comment by shenwei356** [comment]
I did not try very big FASTQ files. Check if this issue helps: #184

And using more threads does not help for speed, cause the bottle-neck is file I/O and hashing computation.

**Comment by MariusGheorghe** [comment]
Thanks for the link. Will check it out.

I was trying multiple threads to reduce the memory footprint, not necessarily for speed, thinking that the input files would get chopped in smaller chunks and the lookup tables with the read identifiers would become smaller, hence more manageable. But I am not familiar with all the implementation details.

I think one alternative would be to actually split the input files in a loop in chunks of let's say 1 million reads and call `seqkit rmdup` on each pair of chunks and append the results to the same output file. That should do the trick in principle.

Thanks again for your help. Closing this issue.

**Comment by shenwei356** [comment]
> I think one alternative would be to actually split the input files in a loop in chunks of let's say 1 million reads and call seqkit rmdup on each pair of chunks and append the results to the same output file. 

Yes, try `seqkit split2 -s 1000000`. Though few reads appear in multiple chunks will not be deduplicated.

**Comment by MariusGheorghe** [comment]
and this assumes that the FASTQs are sorted, right?

**Comment by shenwei356** [comment]
> and this assumes that the FASTQs are sorted, right?

No
