### ISSUE TITLE
seqkit convert: quality encoding not consistent

### ISSUE THREAD

**Issue by nick-youngblut** [shenwei356/seqkit#239]
I'm using `seqkit v0.16.1`. 

`seqkit convert` seems a bit too strict, which is forcing me to use `fqtools` instead. I'm processing a lot of 16S rRNA amplicon datasets, and I often get `[ERRO] quality encoding not consistent`, while `fqtools` can correctly identify the quality encoding. I'm forcing all fastq file to Sanger format, regardless of the input file quality encodings.

**Comment by shenwei356** [comment]
I think I know why it's too strict. https://github.com/shenwei356/seqkit/issues/254#issuecomment-955998124
