### ISSUE TITLE
Sort FASTQ by sequence

### ISSUE THREAD

**Issue by tseemann** [shenwei356/seqkit#24]
I noticed `seqkit sort`   => `FASTQ not supported.`

Sorting can be very useful to improve  gzip compression:
See https://www.biostars.org/p/225338/

**Comment by shenwei356** [comment]
Sorry, I have not yet found a good way to sort FASTQ without filling all data into memory.

**Comment by tseemann** [comment]
External merge sort .. i believe the Unix `sort` command uses it.

https://en.wikipedia.org/wiki/External_sorting

**Comment by shenwei356** [comment]
Yes, I'll try

**Comment by greatfireball** [comment]
Any update on this issue?

**Comment by shenwei356** [comment]
Nope, but you can utilize shell command `sort`.

    seqkit fx2tab xxx.fq.gz  | sort -t$'\t' -k 2,2 | seqkit tab2fx -o xxx.sorted.fq.gz

**Comment by greatfireball** [comment]
Thx... I will give it a try...
