### ISSUE TITLE
select/subset subcommand

### ISSUE THREAD

**Issue by nick-youngblut** [shenwei356/seqkit#241]
As far as I can tell, there is no command to subset a sequence dataset based on a file that lists the sequences to keep/remove. This would be a convenient addition to seqkit. I was thinking of an implementation like:

```
# fasta
>seq1
ATAGAGA
>seq2
TATTTAAT
>seq3
GGTAGAT
```

```
# *.txt file listing sequences to keep (or remove)
seq1
seq3
```

```
# command to subseq seqs
seqkit select seqs_to_keep.txt seqs.fasta > seqs_selected.fasta
```

**Comment by thackl** [comment]
Try this 
```
seqkit grep -f seqs_to_keep.txt seqs.fasta > seqs_keep.fasta
seqkit grep -vf seqs_to_remove.txt seqs.fasta > seqs_keep.fasta
```

**Comment by nick-youngblut** [comment]
Thanks @thackl! I didn't see that `seqkit grep` to use a file of queries as input.

Also, the unintuitive thing about `seqkit grep` is that it defaults to exact matches UNLESS `--use-regexp` is used, which is not how `grep` works, and I never remember that it defaults to exact matches.

**Comment by thackl** [comment]
Yeah, bin there ;). Might make sense to put a note in the `subseq` help that points at `grep` for said purpose.

**Comment by shenwei356** [comment]
updated
