### ISSUE TITLE
seqkit split writes an extra empty file when using --two-pass

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/seqkit#244]
I got an FASTA file with 847 sequences and I tried to split it into individual files with:

```
seqkit split -w 0 -2 -p 847 foo.fasta
```

848 files were created, the last one of which is empty. Omitting `-2` solves the issue.

**Comment by shenwei356** [comment]
I see, I can reproduce this.

`seqkit split2` is recommended, which doe not have this issue.

    seqkit split2 -w 0 -s 1 foo.fasta

BTW, use `-s 1` where you do not have to know the number of sequences before using `-p 847`, for splitting into individual files.

**Comment by apcamargo** [comment]
Thanks for the help!
