### ISSUE TITLE
2.0.0 isn't picked up by Google's Go index server

### ISSUE THREAD

**Issue by yurivict** [shenwei356/seqkit#245]
go.mod should contain github.com/shenwei356/seqkit/v2 for versions 2.x

**Comment by shenwei356** [comment]
This project is supposed to be a standalone command line-tools, instead of a Golang package. 
So I think it should be OK.

**Comment by yurivict** [comment]
> This project is supposed to be a standalone command line-tools, instead of a Golang package.
> So I think it should be OK.

The port can't build and create a package because it takes info from Go index server.

**Comment by shenwei356** [comment]
[updated](https://github.com/shenwei356/seqkit/commit/0b608f051524d7a38c00850817bb1afa735d004d)

**Comment by yurivict** [comment]
Thank you!

**Comment by yurivict** [comment]
```go get``` doesn't work, though:
```
$ go get github.com/shenwei356/seqkit/v2
go get: module github.com/shenwei356/seqkit@upgrade found (v0.16.1), but does not contain package github.com/shenwei356/seqkit/v2
```

**Comment by shenwei356** [comment]
may need tagging a new version.

**Comment by shenwei356** [comment]
Please try again.

**Comment by yurivict** [comment]
It works now. Thanks!
