### ISSUE TITLE
Wrong version?

### ISSUE THREAD

**Issue by nileshpatra** [shenwei356/seqkit#248]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

Hi @shenwei356 

Seqkit version 2.0.1 has been tagged, however the version string still seems to lag behind at 2.0.0

```
$ seqkit version
seqkit v2.0.0
```
It would be great if you could apply:

```
--- a/seqkit/cmd/version.go
+++ b/seqkit/cmd/version.go
@@ -29,7 +29,7 @@
 )
 
 // VERSION of seqkit
-const VERSION = "2.0.0"
+const VERSION = "2.0.1"
 
 // versionCmd represents the version command
 var versionCmd = &cobra.Command{

```

**Comment by nileshpatra** [comment]
Or is leaving version to 2.0.0 somehow intentional?

**Comment by shenwei356** [comment]
Tag `2.0.1` was a patch that [fixed the installation via source code](https://github.com/shenwei356/seqkit/issues/245), while there were no functionalities or bug-fixes to the binaries which are the main distribution way.  So I leave it unchanged until next minor version.
