### ISSUE TITLE
[Question] Is there a way to prepend and append to fasta headers?

### ISSUE THREAD

**Issue by jolespin** [shenwei356/seqkit#249]
### Prerequisites

- [X] make sure you're are using the latest version by `seqkit version`
- [X] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue
Is it possible to prepend or append to fasta headers like with bbrename.sh? 

`bbrename.sh in=file.fasta out=renamed.fasta prefix=phosphate addprefix=t`

**Comment by jmonroynieto** [comment]
You are looking for the [replace command](https://bioinf.shenwei.me/seqkit/usage/#replace).
prepending:
`echo -e ">seq1 abc-123\nACGT-ACGT" | seqkit replace -p "^" -r "x"`
appending: 
`echo -e ">seq1 abc-123\nACGT-ACGT" | seqkit replace -p "$" -r "x"`

**Comment by shenwei356** [comment]
Thank you @jmonroynieto

**Comment by jolespin** [comment]
@shenwei356 Would this be useful as an item in the usage documentation?  I was doing some searches and it took a deep dive to find this thread and I could imagine this being pretty useful to others.

**Comment by shenwei356** [comment]
I see. For users who are not familiar with regular expressions, it would not be straightforward to find this solution.

I can add some examples.


But still, I'd like to recommend users learn regular expressions cause it's really useful. This tutorial looks good: [The 30 Minute Regex Tutorial](https://www.codeproject.com/Articles/9099/The-30-Minute-Regex-Tutorial).

**Comment by jmonroynieto** [comment]
My favourite resource for understanding and studying regexes is regex101.com.

Give it a try.

**Comment by shenwei356** [comment]
I've added some examples.


1. Prepend or append to the header

        $ echo -e ">seq1 abc-123\nACGT-ACGT"
        >seq1 abc-123
        ACGT-ACGT
        
        # prefix
        $ echo -e ">seq1 abc-123\nACGT-ACGT" \
            | seqkit replace -p ^ -r _prefix_
        >_prefix_seq1 abc-123
        ACGT-ACGT
        
        # suffix
        $ echo -e ">seq1 abc-123\nACGT-ACGT" \
            | seqkit replace -p $ -r _suffix_
        >seq1 abc-123_suffix_
        ACGT-ACGT
        $ echo -e ">seq1 abc-123\nACGT-ACGT" \
            | seqkit seq -i \
            | seqkit replace -p $ -r _suffix_
        >seq1_suffix_
        ACGT-ACGT
