### ISSUE TITLE
fx2tab slower than shell commands

### ISSUE THREAD

**Issue by tseemann** [shenwei356/seqkit#25]
fx2tab seems to be about 4 times slower than shell commands. Is that expected?

```
$ time (zcat R1_001.fastq.gz | paste - - - - | cut -f 1,2,4 > /dev/null)

real    0m3.000s
user    0m4.673s
sys     0m0.324s

$ time seqkit fx2tab R1_001.fastq.gz  > /dev/null

real    0m12.991s
user    0m13.025s
sys     0m0.202s

$ time seqkit -j 2 fx2tab R1_001.fastq.gz  > /dev/null

real    0m12.672s
user    0m12.693s
sys     0m0.233s
```

**Comment by shenwei356** [comment]
seqkit calls `pigz` (faster than `gzip`) or `gzip` to decompress .gz file, if they are available.

On my labtop with SSD, if I make the `pigz` unavailable, the speed is similar:

```
$ seqkit stats M1_1.fq.gz                                                   
file        format  type   num_seqs        sum_len  min_len  avg_len  max_len
M1_1.fq.gz  FASTQ   DNA   7,554,106  1,400,819,555      100    185.4      230

$ time (zcat M1_1.fq.gz | paste - - - - | cut -f 1,2,4 > /dev/null)

real    0m23.274s                                                                                 
user    0m49.392s                                                                                 
sys     0m3.490s   
                                                                               
$ time seqkit fx2tab M1_1.fq.gz > /dev/null               
                                                                                                  
real    0m22.618s                                                                                 
user    0m9.250s                                                                                  
sys     0m2.190s
```
When `pigz` is available, it's much faster:

```
$ time seqkit fx2tab M1_1.fq.gz > /dev/null 

real    0m14.584s                                                                                 
user    0m10.142s                                                                                 
sys     0m2.245s
```

**Comment by tseemann** [comment]
I do have `pigz` available in PATH.  
Most people won't be using SSD either - they have all their data on clusters.

```
% seqkit stats R1_001.fastq.gz
file                            format  type   num_seqs      sum_len  min_len  avg_len  max_len
R1_001.fastq.gz  FASTQ   DNA   1,091,110  162,522,654       35      149      151

% time (gzip -c -d R1_001.fastq.gz | paste - - - - | cut -f 1,2,4 > /dev/null)

real    0m3.454s
user    0m5.175s
sys     0m0.359s

% time (pigz -c -d R1_001.fastq.gz | paste - - - - | cut -f 1,2,4 > /dev/null)

real    0m2.434s
user    0m3.952s
sys     0m0.935s

% which pigz
~/.linuxbrew/bin/pigz
% time seqkit fx2tab R1_001.fastq.gz > /dev/null

real    0m15.344s
user    0m14.220s
sys     0m0.327s

% time seqkit fx2tab -j 8 R1_001.fastq.gz > /dev/null

real    0m14.082s
user    0m14.138s
sys     0m0.235s
```

**Comment by shenwei356** [comment]
Well, I don't have access to server now.

SeqKit, as well as seqtk, does not just read every 4-lines and reformat them as gzip/pigz+paste+cut does. They both support FASTQ format with sequences and quality in multi-line, so it will be slower than gzip/pigz+paste+cut.

But your results really make me surprised. I need more tests.

The parsing module is indeed optimized, but NOT FOR SDD. I'll find the cause.

A tool [seqk_tab](https://github.com/jameslz/seqtk_utils/blob/master/seqtk_tab), which uses klib, can be used in the benchmark.

A benchmark script is available for anyone to test: [bench-fx2tab.sh](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce)

**Comment by shenwei356** [comment]
A tool [seqk_tab](https://github.com/jameslz/seqtk_utils/blob/master/seqtk_tab), which uses klib, can be used in the benchmark.

A benchmark script is available for anyone to test: [bench-fx2tab.sh](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-bench-fx2tab-sh). 

Here are some results on different platforms from my friend:

- [Laptop-With-SDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-laptop-with-ssd)
- [Laptop-With-7.2KRPM-HDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-laptop-with-7-2krpm-hdd)
- [Server-With-10KRPM-HDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-server-with-10krpm-hdd)
- [Server-With-HDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-server-with-hdd)
- [Server-With-7.2KRPM-HDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-server-with-7-2krpm-hdd) (data not available now)
- [VPS-With-SDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-vps-with-ssd)

![](http://sm.uploads.im/d/n1Nr6.png)

Note: The test data on different platform may be different. But the reads amount are all 1M.

**Comment by jameslz** [comment]
I hava tested a dataset on my DELL R730 server with HDD.
Here is the test result.
    
    $seqkit stats EAOA2.fq.gz
    file         format  type    num_seqs        sum_len  min_len  avg_len  max_len
    EAOA2.fq.gz  FASTQ   DNA   16,017,817  2,402,672,550      150      150      150
    
    $ time (gzip -c -d EAOA2.fq.gz | paste - - - - | cut -f 1,2,4 > /dev/null)

    real    0m38.195s
    user    1m7.577s
    sys     0m5.141s
    
    time (pigz -c -d EAOA2.fq.gz | paste - - - - | cut -f 1,2,4 > /dev/null)

    real    0m20.407s
    user    1m2.547s
    sys     0m8.182s
    
    #with pigz
    time seqkit fx2tab EAOA2.fq.gz > /dev/null

    real    0m21.934s
    user    0m17.370s
    sys     0m3.735s
    
    #with pigz
    time seqkit fx2tab -j 8  EAOA2.fq.gz > /dev/null

    real    0m23.544s
    user    0m21.857s
    sys     0m5.047s
    
    #without pigz
    time seqkit fx2tab EAOA2.fq.gz > /dev/null

    real 0m40.135s
    user 0m19.697s
    sys  0m4.412s

    #without pigz
    time seqkit fx2tab -j 8  EAOA2.fq.gz > /dev/null

    real 0m40.259s
    user 0m22.970s
    sys  0m5.013s
    

    time  seqtk_tab EAOA2.fq.gz  >/dev/null
    
    real    0m29.091s
    user    0m28.610s
    sys     0m0.453s

    time  pigz -c -d  EAOA2.fq.gz | seqtk_tab -  >/dev/null

    real    0m19.603s
    user    0m36.531s
    sys     0m4.786s

**Comment by shenwei356** [comment]
@tseemann can you please provide your machine infomation and seqkit version? How about rebooting the server?

**Comment by shenwei356** [comment]
Two more results added:

- [Laptop-With-7.2KRPM-HDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-laptop-with-7-2krpm-hdd)
- [Laptop-With-SDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-laptop-with-ssd)
- [Server-With-10KRPM-HDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-server-with-10krpm-hdd)
- [Server-With-HDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-server-with-hdd)
- [Server-With-7.2KRPM-HDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-server-with-7-2krpm-hdd) 
- [Server2-With-HDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-server2-with-hdd)
- [VPS-With-SDD](https://gist.github.com/shenwei356/70d016694e5ebffe833289ccaad0bdce#file-result-vps-with-ssd)

![](http://sk.uploads.im/d/xlATP.png)
