### ISSUE TITLE
Number of sequences at different length thresholds

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/seqkit#253]
Would be very useful if `seqkit stats` provided the number of sequences longer than a given threshold (alternatively, the number of sequences within different length bins). This a function that is provided by BBmap via the [`stats.sh`](https://www.biostars.org/p/403175/) script.

**Comment by shenwei356** [comment]
try

    seqkit fx2tab -l test.fasta  | csvtk plot hist -f 4 -o len.hist.png
