### ISSUE TITLE
[QUESTION]  Guessing FASTQ quality system using seqkit convert

### ISSUE THREAD

**Issue by alienzj** [shenwei356/seqkit#254]
seqkit version
```bash
➤ seqkit version
seqkit v0.16.1
```

Problem I meet:
```
➤ seqkit convert V300109217_L03-506_1.fq.gz | head
[INFO] possible quality encodings: []
[ERRO] quality encoding not consistent
```

Dear Shenwei,

I used seqkit to guess the FASTQ quality system, but the quality system does not seem to be identified. 
Any good suggestions ? 

Thank you for developing seqkit and excellent documentation.

**Comment by alienzj** [comment]
Hi, Shenwei, thanks for your help.

I downloaded the latest compiled version of seqkit you provided: `seqkit_linux_amd64.tar.gz`,
but the quality system still does not seem to be identified.

```
➤ ./seqkit version
seqkit v2.0.0
jiezhu@hpc2021:/l/g/s/j/p/c/R/a/rna-seq-star-deseq2-v2
➤ ./seqkit convert V300109217_L03-506_1.fq.gz | head
[INFO] possible quality encodings: []
[ERRO] quality encoding not consistent
```

**Comment by shenwei356** [comment]
paste some sequences please.

**Comment by alienzj** [comment]
[test_100K.fq.gz](https://github.com/shenwei356/seqkit/files/7451093/test_100K.fq.gz)

Dear Shenwei, thanks,
please see the attachments for 100K reads which were randomly generated from a bigger data sets.

**Comment by shenwei356** [comment]
Some reads are treated as Illumina 1.5. It can be solved by using a small value of `-N/--thresh-B-in-n-most-common`, like `2`.

I also changed the default value from `4` to `2`, [related discussion](https://github.com/shenwei356/seqkit/issues/18#issuecomment-317773063).

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/7451339/seqkit_linux_amd64.tar.gz)

**Comment by alienzj** [comment]
```
➤ ./seqkit convert test_100K.fq.gz | head
[INFO] possible quality encodings: [Sanger Illumina-1.8+]
[INFO] guessed quality encoding: Sanger
[INFO] converting Sanger -> Sanger
[WARN] source and target quality encoding match.
```

Great, Shenwei, thank you sou much !
