### ISSUE TITLE
Reverse Complimented Dups not always found

### ISSUE THREAD

**Issue by Thernn88** [shenwei356/seqkit#255]
### Prerequisites

- Seqkit  Version 2.0.0

Command run - for i in *.fasta; do seqkit rmdup -d Dups/$i -s < $i > Clean/$i; done
### Describe your issue
rmdup does not always find reverse complimented duplicates.

### Provide a reproducible example

NODE_5130_length_508_cov_14.228346_R

Is a reverse complement duplicate of 

NODE_1971_length_508_cov_18.929134_S

I believe there are 16 additional RC dups in the attached file but I only tracked down the above one to have it serve as an example.

[AB33593873_S12_SPM_prepared.zip](https://github.com/shenwei356/seqkit/files/7449635/AB33593873_S12_SPM_prepared.zip)

**Comment by shenwei356** [comment]
add `-s`

**Comment by Thernn88** [comment]
-s is part of the command.

I can move it before the -d if that would make a difference?

BBTools is also blind to these duplicates.

Orthograph however finds them. It does this by hashing the sequences and
comparing the hashes.

Cheers

**Comment by shenwei356** [comment]
Remove potential gaps and convert to upper case.

    seqkit seq -u -g AB33593873_S12_SPM_prepared.fasta -o t.fasta

`NODE_5130_length_508_cov_14.228346_R`:

    seqkit faidx t.fasta NODE_5130_length_508_cov_14.228346_R -o 1.fa

Reverse complement sequence of `NODE_1971_length_508_cov_18.929134_S`:

    seqkit faidx t.fasta NODE_1971_length_508_cov_18.929134_S | seqkit seq -r -p -o 2.fa

Diff:

    diff 1.fa 2.fa 
    1c1
    < >NODE_5130_length_508_cov_14.228346_R
    ---
    > >NODE_1971_length_508_cov_18.929134_S
    8,9c8,9
    < CCATAGCGAGTTTCTGATAGTAGTTGGCCATTGTTTTAGCAGCGGGACTTTTTTTAGAAA
    < GTGACATCAAACCATATATATCCTCAATAGCCTTATATGCCTCCAACCATAGTTCCATTT
    ---
    > CCATAGCGAGTTTCTGATAGTAGTTGGCCATTGTTTTAGCAGCGGGGCTTTTTTTAGAAA
    > GTGACATCAAACCATATATATCCTCAATGGCCTTATATGCCTCCAACCATAGTTCCATTT

There are two differences.


                                                  407
                                                  |
    CCATAGCGAGTTTCTGATAGTAGTTGGCCATTGTTTTAGCAGCGGGACTTTTTTTAGAAA    1.fa
    |||||||||||||||||||||||||||||||||||||||||||||| |||||||||||||
    CCATAGCGAGTTTCTGATAGTAGTTGGCCATTGTTTTAGCAGCGGGGCTTTTTTTAGAAA    2.fa

                                 
                                449
                                |
    GTGACATCAAACCATATATATCCTCAATAGCCTTATATGCCTCCAACCATAGTTCCATTT    1.fa
    |||||||||||||||||||||||||||| |||||||||||||||||||||||||||||||
    GTGACATCAAACCATATATATCCTCAATGGCCTTATATGCCTCCAACCATAGTTCCATTT    2.fa

**Comment by Thernn88** [comment]
Hmm. I see. I ran it through diff checker before I posted. Must've missed it somehow.

Thanks for the explanation.

Must be the same only on the AA level.
