### ISSUE TITLE
seqkit seq -Q and -R are not working

### ISSUE THREAD

**Issue by cgjosephlee** [shenwei356/seqkit#257]
seqkit v2.0.0

`seqkit seq -Q 7 < zymo.fq` makes no change, and
`seqkit seq -R 7 < zymo.fq` produces nothing.

Test data: top 100000 reads in "https://nanopore.s3.climb.ac.uk/Zymo-GridION-EVEN-BB-SN.fq.gz"

**Comment by shenwei356** [comment]
Sorry, it's a bug. I've fixed it.

- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/7482694/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/7482691/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/7482686/seqkit_darwin_amd64.tar.gz)
