### ISSUE TITLE
[Question] 

### ISSUE THREAD

**Issue by lborcard** [shenwei356/seqkit#258]
Hi,

- [x] make sure you're are using the latest version by `seqkit version`
- [X] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue 

* [x] describe the problem
I am trying to export the ids of the reads which map to the position 4000 max in my ref genome :
 ` seqkit bam  -f Pos -M 4000 barcode22_Ref_Seq/barcode22.sorted.mapped.bam  > pos_4000.tsv` 

the problem is that I only get a graph which is not what I want, is there a way to access the ids  of the reads using the `-f  Pos` flag. 
*

thanks for your  help

**Comment by shenwei356** [comment]
samtool view + cut 

[Extract Reads From A Bam File That Fall Within A Given Region](https://www.biostars.org/p/48719/)

**Comment by lborcard** [comment]
Dear Shenwei, 

Thank you for your answer, I am experimenting with `samtools view -L bedfile.bed` to obtain the read that overlap my region of interest but I need to obtain the reads that completely cover the ROI not only overlap it. It seemed that your tool was able to do that in a simple way.

**Comment by shenwei356** [comment]
@botond-sipos wrote this command, I'm not familiar with it. 

You may need this:

      -x, --pass                 passthrough mode (forward filtered BAM to output)

**Comment by botond-sipos** [comment]
@lborcard You need to specify more than one field to get the tabular output. So what you need to run is:

seqkit bam -x -f Pos -M 4000 pcs109_5k_prim.bam | seqkit bam -f Ref,Pos -

Here the first command performs the filtering and the second prints the tabular output.

**Comment by lborcard** [comment]
Thank you @botond-sipos , I managed to output a bam file that spans of my ROI. 
` seqkit bam -x -f Pos -M 4000  barcode.sorted.mapped.bam | seqkit bam -x -f EndPos -m 6000 > roi.bam`
again I really love your tools, thanks for being so quick to respond.

Best regards,

Loïc
