### ISSUE TITLE
The order  of the splited fastq file ? 

### ISSUE THREAD

**Issue by hmyh1202** [shenwei356/seqkit#259]
Hi, WeiShen :
 
  I have had split my big fastq file into 5 parts small fastq files. And the order of the small fastq file is randomed, I need the chunked flle keep the original order of the original big fastq file. DO you have any suggestions or tool for that ?

Thank you!
The best.

**Comment by shenwei356** [comment]
> And the order of the small fastq file is randomed

I don't get it. Please classify which command is used, `split` or `split2`? 

Seems like `split2`? Then use `split`.

```
seq 10 | csvtk mutate -H -t  | seqkit tab2fx > t.fa

# --------------------------------------------------
# split
seqkit split -p 3 t.fa -O split

seqkit seq -n split/t.part_001.fa 
1
2
3
4

# --------------------------------------------------
# split2
seqkit split2 -p 3 t.fa -O split2

seqkit seq -n split2/t.part_001.fa 
1
4
7
10

```

**Comment by hmyh1202** [comment]
Yes , I used seqkit split2 for big fastq file. And the order of the chunked fastq( file1, file2, ... filen)  file is not the original order of the big fastq.  Now, I need the small part of the fastq files(merge 1 to n file) have the same order as the big fastq.

**Comment by shenwei356** [comment]
As I said, please switch to `split` and apply to read 1 and read 2 files separately.
