### ISSUE TITLE
Feature request for `seqkit stats -a`

### ISSUE THREAD

**Issue by vmikk** [shenwei356/seqkit#26]
Dear @shenwei356,
First of all I would like to thank you for the SeqKit toolkit, it's really gorgeous!

It would be great if you could add some additional statistics of FASTA/Q files to the output of `seqkit stats -a`. In particular, the first (Q1) and the third (Q3) quartiles of the sequence length distribution will be very useful. Given this quartiles one will have a sense of sequence length variability and can easily estimate where the central 50% of lengths are dispersed within the dataset.

Thank you,
Vladimir

**Comment by shenwei356** [comment]
Yes, It's easily added in [v0.7.2-dev](https://github.com/shenwei356/seqkit/releases/tag/v0.7.2-dev):

```
$ seqkit stats tests/*.f{a,q}.gz -a
file                     format  type  num_seqs    sum_len  min_len  avg_len  max_len   Q1   Q2   Q3  sum_gap  N50
tests/hairpin.fa.gz      FASTA   RNA     28,645  2,949,871       39      103    2,354   76   91  111        0  101
tests/mature.fa.gz       FASTA   RNA     35,828    781,222       15     21.8       34   21   22   22        0   22
tests/Illimina1.8.fq.gz  FASTQ   DNA     10,000  1,500,000      150      150      150  150  150  150        0  150
tests/reads_1.fq.gz      FASTQ   DNA      2,500    567,516      226      227      229  227  227  227        0  227
tests/reads_2.fq.gz      FASTQ   DNA      2,500    560,002      223      224      225  224  224  224        0  224
```
cut some columns using csvtk:

```
$ seqkit stats tests/*.f{a,q}.gz -a -T | csvtk cut -t -f 1,6-11 | csvtk pretty -t
file                      min_len   avg_len   max_len   Q1    Q2    Q3
tests/hairpin.fa.gz       39        103.0     2354      76    91    111
tests/mature.fa.gz        15        21.8      34        21    22    22
tests/Illimina1.8.fq.gz   150       150.0     150       150   150   150
tests/reads_1.fq.gz       226       227.0     229       227   227   227
tests/reads_2.fq.gz       223       224.0     225       224   224   224
```

```
$ seqkit stats tests/*.f{a,q}.gz -a -T | csvtk cut -t -f 1,6-11 | csvtk csv2md -t
```

file                   |min_len|avg_len|max_len|Q1 |Q2 |Q3
:----------------------|:------|:------|:------|:--|:--|:--
tests/hairpin.fa.gz    |39     |103.0  |2354   |76 |91 |111
tests/mature.fa.gz     |15     |21.8   |34     |21 |22 |22
tests/Illimina1.8.fq.gz|150    |150.0  |150    |150|150|150
tests/reads_1.fq.gz    |226    |227.0  |229    |227|227|227
tests/reads_2.fq.gz    |223    |224.0  |225    |224|224|224

**Comment by vmikk** [comment]
Thanks a lot for the ultrafast response and inplementation of this feature!
I think we can close this issue now.
