### ISSUE TITLE
`seqkit version` does not show if there is an update

### ISSUE THREAD

**Issue by vkkodali** [shenwei356/seqkit#260]
When I run `seqkit version` it does not show that an update is available. Is there some setting that needs to be checked for that? I am running `seqkit` on a linux machine. 
```
$ seqkit version 
seqkit v2.0.0
$ uname -a
Linux cistron 5.13.0-21-generic #21-Ubuntu SMP Tue Oct 19 08:59:28 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```

**Comment by shenwei356** [comment]
From v0.12.0, checking new version is optional:

>   -u, --check-update   check update

```
$ seqkit version -u
seqkit v2.1.0

Checking new version...
You are using the latest version of seqkit


```

**Comment by vkkodali** [comment]
Thanks, that did it!
