### ISSUE TITLE
Help: Is it possible to extract  bases (using subseq) with multiple ranges from a sequence?

### ISSUE THREAD

**Issue by ssvbio** [shenwei356/seqkit#261]
Is it possible to use multiple `-r` or multiple ranges from a single sequence? For eg.

$seqkit subseq -r 1:10,25-45,55-100 input.fasta

or 

$seqkit subseq -r 1:10 -r 25-45 -r 55-100 input.fasta

This command would extract bases 1 to 10, 25-45 and 55-100 and stitches as one single fasta keeping the original header

**Comment by shenwei356** [comment]
Nope, but there's a workaround solution:

```
seqkit concat -o result.fa \
    <(seqkit subseq -r 1:10   input.fasta) \
    <(seqkit subseq -r 25:45  input.fasta) \
    <(seqkit subseq -r 55:100 input.fasta)
```
