### ISSUE TITLE
Idea: Robust FASTA/Q checksum

### ISSUE THREAD

**Issue by photocyte** [shenwei356/seqkit#262]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

Hi there, thanks for writing Seqkit. I've found it really useful for my research.

Maybe you're like me, where you have tons of very similar FASTA/Q files, and it can be a challenge to determine which files are the same in terms of sequence content, and which ones are different. 

For example, file-based checksums like md5sum, are insufficient., as the FASTA/FASTQ record IDs/descriptions can vary in a trivial way (e.g. `scaffold000001 vs scf1`). Or, just the order of the record/scaffolds within the FASTA/Q file can be changed, which is inconsequential for most analyses (e.g. mapping or assemlbly). Similarly, `seqkit stat` only provides high level summary statistics & can't detect subtle changes to the file.

As a solution, I've made a FASTA/Q record & sequence based checksum using Seqkit. See below for a Bash function implementing this:

```
function faschk() {
MD5CHK=$(cat $1 | openssl md5 | cut -f 2 -d " " | cut -c1-4)
SEQNUM=$(seqkit stat -T $1 | tail -n 1 | cut -f 4)
IDCHK=$(seqkit seq --quiet -n -i $1 | sort | openssl md5 | cut -f 2 -d " " | cut -c1-8)
SEQCHK=$(seqkit seq --quiet -u $1 | seqkit sort --quiet -s | seqkit seq --quiet -s | openssl md5 | cut -f 2 -d " " | cut -c1-8)
ESEQCHK=$(seqkit sort --quiet -s $1 | seqkit seq --quiet -s | openssl md5 | cut -f 2 -d " " | cut -c1-4)
echo $1 faschk:${SEQNUM}-${MD5CHK}-${IDCHK}-${SEQCHK}-${ESEQCHK}
}
```

Hopefully what it does is self explanatory from the code. Let me know if any parts need more explanation, but in short, it sorts the sequence or record IDs, and pipes them into an md5sum, making a final summary string which is a concatenation of these smaller checksums.

Here is a real life example: I uploaded some raw read sets to SRA multiple times accidentally, here I can confirm that the sequence content of `SRR15608978_1.fastq` & `SRR15608979.fastq` is the same, even if the md5sum & record IDs are different.
```
SRR15608978_1.fastq faschk:26394840-a5f8-552576a8-b7ebb9f8-b7eb
SRR15608978_2.fastq faschk:26394840-3592-552576a8-e0dfc296-e0df
SRR15608979.fastq faschk:26394840-d80c-198f7632-b7ebb9f8-b7eb
```

But, this approach is pretty slow, since it is a dumb algorithm that sorts the dataset multiple times. It would be great to have an internal seqkit command which did something similar but ran with better time & memory efficiency. What do you think? I don't know Go, but maybe with some guidance could learn Go & help implement this.

P.S. I looked briefly but didn't see implementation of a similar idea in `fasta_utilities`, `fastx_toolkit`, `pyfaidx` , `seqmagick`, or `seqtk`.

**Comment by shenwei356** [comment]
This is interesting! I'll add a new command in the next version. 

Just checking the sequence and quality right? Here's my plan:

1. computing the digest for every sequence (in lower/upper case), optional with quality .
2. sorting all digests in alphabet order.
3. computing a new digest from 2).

Step 2) ensures the digest is not being affected by the sequence order, and sorting fixed-length digests (e.g., 8-bytes `uint64` hash values) is much cheaper than sorting sequences.

**Comment by photocyte** [comment]
Yes, I think optional with quality is the right approach. In most cases, quality is not that informative & probably isn't different if the # of reads is the same & the sequence content is the same (exception: if people are converting the Phred scale FASTQ encoding, but I personally don't often do that). Looks like you already considered the lower/uppercase situation: Yes, that matters for things like softmasking where the sequence content is identical but the case varies between two files.

**Comment by photocyte** [comment]
Another idea on this: Perhaps for circular DNA sequences (e.g. plasmids), could have a switch to "canonicalize" the sequence by rotating it to a deterministic location (e.g. `seqkit rotate` to a location that is uniquely defined based on sequence content - let's say, the longest stretch of AT-rich DNA), and, then either print the forward or reverse complement strand based on another deterministic heuristic. This would allow for plasmid sequences that differ in terms of representation, but not in terms of content (`seqkit seq --reverse --complement` or `seqkit rotate`) to give the same `FASCHK` string, which would be helpful.

**Comment by shenwei356** [comment]
I have another tool which computes kmers or kmer sketches (minimizer et al) with support of circular genomesI think I can borrow the idea, computing the digest for all sorted canonical kmers.

**Comment by shenwei356** [comment]
If computing kmers, there's no need to rotate the genome, just copy the leading k-1 bases to the end, that could make sure all kmers are counted.
When k is big enought (31 or 51 or 127,) and taking kmers number in consideration, it should minimalize the collision possibility.

**Comment by shenwei356** [comment]
It seems what sourmash does!

**Comment by shenwei356** [comment]
I also find it very useful for comparing newly assembled phage/virus!

**Comment by shenwei356** [comment]
Here's a prototype. Circular genomes are not supported yet.

[Uploading seqkit_darwin_amd64.tar.gz…]()

```
$ time md5sum dataset_C.fq.gz
421365088fa04da8df512fe3c543fb45  dataset_C.fq.gz

real    0m0.737s
user    0m0.683s
sys     0m0.053s

$ time ./seqkit sum dataset_C.fq.gz 
0f41cf55aaf38f38f78d39f3edd1521c        dataset_C.fq.gz

real    0m10.325s
user    0m19.654s
sys     0m0.323s

```


Usage 

```
$ ./seqkit sum -h
compute message digest for FASTA/Q files

Methods:
  1. computing the hash (xxhash) for every sequence (in lower case, gap removed).
  2. sorting all hash values.
  3. computing MD5 digest from the hash values from 2),
     along with sequences length and number.

Usage:
  seqkit sum [flags]

Flags:
  -b, --basename             only output basename of files
  -c, --circular             the file contains a single cicular genome sequence
  -G, --gap-letters string   gap letters (default "- \t.")
  -h, --help                 help for sum

```

**Comment by shenwei356** [comment]
Circular genomes supported:

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/7832730/seqkit_darwin_amd64.tar.gz)
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/7832731/seqkit_darwin_arm64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/7832732/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/7832733/seqkit_windows_amd64.exe.tar.gz)

### Usage

```text
compute message digest for all sequences in FASTA/Q files

Attentions:
  1. Sequence headers and qualities are skipped, only sequences matter.
  2. The order of sequences records does not matter.
  3. Circular complete genomes are supported with the flag -c/--circular.
     - The same genomes with different start positions or in reverse
       complement strand will not affect the result.
     - The message digest would change with different values of k-mer size.
  4. Multiple files are processed in parallel (-j/--threads).

Method:
  1. Converting the sequences to low cases, optionally removing gaps (-g).
  2. Computing the hash (xxhash) for all sequences or k-mers of a circular
     complete genome (-c/--circular).
  3. Sorting all hash values, for ignoring the order of sequences.
  4. Computing MD5 digest from the hash values, sequences length, and
     the number of sequences.

Usage:
  seqkit sum [flags]

Flags:
  -b, --basename             only output basename of files
  -c, --circular             the file contains a single cicular genome sequence
  -G, --gap-letters string   gap letters (default "- \t.")
  -h, --help                 help for sum
  -k, --kmer-size int        k-mer size for processing circular genomes (default 1000)
  -g, --remove-gaps          remove gaps

```

### Examples

 A, B, C, D are the same vircular genomes with different starting positions or strands:

    $ cat virus-{A,B,C,D}.fasta
    >seq
    TGGTAGGGAGTTGAGTAGCATGGGTATAGTATAGTGTCATGATGCCAGATTTTAAAAAAA
    >seq.revcom
    TTTTTTTAAAATCTGGCATCATGACACTATACTATACCCATGCTACTCAACTCCCTACCA
    >seq.new-start
    GGTAGGGAGTTGAGTAGCATGGGTATAGTATAGTGTCATGATGCCAGATTTTAAAAAAAT
    >seq.revcom.new-start
    TTTTTTAAAATCTGGCATCATGACACTATACTATACCCATGCTACTCAACTCCCTACCAT
    
    # cat to one file
    $ cat virus-{A,B,C,D}.fasta > virues.fasta
    
    # shuffle and rename
    $ cat virus-{A,B,C,D}.fasta \
        | seqkit shuffle \
        | seqkit replace -p '.*' -r '{nr}' \
        | tee virues.shuffled.fasta
    >1
    TTTTTTAAAATCTGGCATCATGACACTATACTATACCCATGCTACTCAACTCCCTACCAT
    >2
    TGGTAGGGAGTTGAGTAGCATGGGTATAGTATAGTGTCATGATGCCAGATTTTAAAAAAA
    >3
    GGTAGGGAGTTGAGTAGCATGGGTATAGTATAGTGTCATGATGCCAGATTTTAAAAAAAT
    >4
    TTTTTTTAAAATCTGGCATCATGACACTATACTATACCCATGCTACTCAACTCCCTACCA

Sum of all files (the sequences order does not matter):

    $ seqkit sum viru*.fasta
    9bbe0abefc26013dffdde952a6725b17        virues.fasta
    9bbe0abefc26013dffdde952a6725b17        virues.shuffled.fasta
    176250c8d1cde6c385397df525aa1a94        virus-A.fasta
    7a813339f9ae686b376b1df55cd596ca        virus-B.fasta
    0fd51028bfbfa85ddbdd2b86ef7bd1c1        virus-C.fasta
    88b1d20dd0fe0dbf41c00b075fee4e4e        virus-D.fasta

Circular genomes (The same genomes with different start positions or in reverse
complement strand will not affect the result):

    $ seqkit sum -c -k 21  virus-*.fasta
    a7bc5eca47c14bb9db5568f7c5446b92        virus-A.fasta
    a7bc5eca47c14bb9db5568f7c5446b92        virus-B.fasta
    a7bc5eca47c14bb9db5568f7c5446b92        virus-C.fasta
    a7bc5eca47c14bb9db5568f7c5446b92        virus-D.fasta
    
    $ seqkit sum -c -k 51  virus-*.fasta
    90cf26400dc1853e178582dfe8204a3a        virus-A.fasta
    90cf26400dc1853e178582dfe8204a3a        virus-B.fasta
    90cf26400dc1853e178582dfe8204a3a        virus-C.fasta
    90cf26400dc1853e178582dfe8204a3a        virus-D.fasta

**Comment by shenwei356** [comment]
Sorry, there's a bug using nthash with big k (1000),  I've fixed it and updated the download links.

**Comment by shenwei356** [comment]
I use this tool on the Genbank viral collection and find 279 genomes are duplicated.

[sum.summary2.tar.gz](https://github.com/shenwei356/seqkit/files/7833251/sum.summary2.tar.gz)



Here are the top 10:

|species                                 |genome-size|#genomes|files                                                                                                                                                                                                                                                                                                                                                                                                                                                                    |
|:---------------------------------------|:----------|:-------|:------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|
|Flavobacterium phage vB_FspP_elemoA_9-1A|60073      |27      |GCA_014071075.1; GCA_014071015.1; GCA_014071005.1; GCA_014070725.1; GCA_014070655.1; GCA_014071055.1; GCA_014071025.1; GCA_014070765.1; GCA_014070985.1; GCA_014070855.1; GCA_014070615.1; GCA_014070595.1; GCA_014071035.1; GCA_014070565.1; GCA_014070535.1; GCA_014070775.1; GCA_014070715.1; GCA_014070675.1; GCA_014070665.1; GCA_014070625.1; GCA_014070895.1; GCA_014070835.1; GCA_014070825.1; GCA_014070735.1; GCA_014070875.1; GCA_014070785.1; GCA_014070695.1|
|Vibrio phage 1.136.O._10N.261.45.E11    |31617      |8       |GCA_003928295.1; GCA_003928415.1; GCA_003926555.1; GCA_003928615.1; GCA_003929835.1; GCA_003931415.1; GCA_003929815.1; GCA_003931395.1                                                                                                                                                                                                                                                                                                                                   |
|Vibrio phage 36E38.1                    |36824      |6       |GCA_020477115.1; GCA_020483865.1; GCA_020477065.1; GCA_020477405.1; GCA_020477205.1; GCA_020477415.1                                                                                                                                                                                                                                                                                                                                                                     |
|Rheinheimera phage vB_RspM_barba_10-9E  |80556      |5       |GCA_014515185.1; GCA_014517155.1; GCA_014517095.1; GCA_014517035.1; GCA_014517265.1                                                                                                                                                                                                                                                                                                                                                                                      |
|Rheinheimera phage vB_RspM_barba_12-6H  |80348      |5       |GCA_014517085.1; GCA_014517065.1; GCA_014517275.1; GCA_014517025.1; GCA_014517305.1                                                                                                                                                                                                                                                                                                                                                                                      |
|Stx2a-converting phage Stx2_PV03-14     |65397      |5       |GCA_019334045.1; GCA_019334055.1; GCA_019333895.1; GCA_019334035.1; GCA_019334025.1                                                                                                                                                                                                                                                                                                                                                                                      |
|Escherichia phage PA44                  |62708      |5       |GCA_002594945.1; GCA_002594885.1; GCA_002594765.1; GCA_002594685.1; GCA_002594845.1                                                                                                                                                                                                                                                                                                                                                                                      |
|Corynebacterium phage LGCM-V7           |36671      |5       |GCA_002622225.1; GCA_002622245.1; GCA_002622185.1; GCA_002622205.1; GCA_002622265.1                                                                                                                                                                                                                                                                                                                                                                                      |
|Streptococcus satellite phage Javan282  |14560      |5       |GCA_004773155.1; GCA_004773135.1; GCA_004773175.1; GCA_004773115.1; GCA_004773075.1                                                                                                                                                                                                                                                                                                                                                                                      |



Steps

    time seqkit sum -c -a -b --infile-list <(fd gz$ files.renamed/) -j 160 > sum.tsv 2>sum.tsv.log

    p=sum
    
    sed 's/.fna.gz//' -i $p.tsv
    
    # add species name
    csvtk join -Ht -f '2;1' $p.tsv name.map > $p.tsv.t
    mv $p.tsv.t $p.tsv
    
    csvtk fold -Ht -f 1 -v 2 $p.tsv \
        | csvtk join -Ht - $p.tsv <(csvtk freq -Ht $p.tsv) \
        | csvtk uniq -Ht -f 1 \
        | csvtk cut -Ht -f 6,5,7,2 \
        | csvtk sort -Ht -k 3:nr -k 2:nr \
        | csvtk add-header -t -n "species,genome-size,#genomes,files" \
        > $p.summary.tsv
        
    csvtk filter2 -t -f '$3 > 1' $p.summary.tsv > $p.summary2.tsv

**Comment by shenwei356** [comment]
Updated binaries:

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/7833255/seqkit_darwin_amd64.tar.gz)
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/7833256/seqkit_darwin_arm64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/7833257/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/7833258/seqkit_windows_amd64.exe.tar.gz)

**Comment by shenwei356** [comment]
Similar project: https://pkg.go.dev/github.com/TimothyStiles/poly/seqhash

**Comment by shenwei356** [comment]
Updated again:

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/7837449/seqkit_darwin_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/7837455/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/7837454/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/7837450/seqkit_darwin_arm64.tar.gz)

```
Following the seqhash in Poly (https://github.com/TimothyStiles/poly/),
We add meta information to the message digest, with format of:

    <version>_<seq type><seq structure><strand>_<kmer size>_<seq digest>

    <version>:       digest version
    <seq type>:      'D' for DNA, 'R' for RNA, 'P' for protein
    <seq structure>: 'L' for linear sequence, 'C' for circular genome
    <strand>:        'D' for double-stranded, 'S' for single-stranded
    <kmer size>:     0 for linear sequence, other values for circular genome

Examples:

    v0.1_DLS_k0_176250c8d1cde6c385397df525aa1a94    DNA.fq.gz
    v0.1_PLS_k0_c244954e4960dd2a1409cd8ee53d92b9    Protein.fasta
    v0.1_RLS_k0_0f1fb263f0c05a259ae179a61a80578d    single-stranded RNA.fasta

    v0.1_DCD_k31_e59dad6d561f1f1f28ebf185c6f4c183   double-stranded circular DNA.fasta
    v0.1_DCS_k31_dd050490cd62ea5f94d73d4d636b7d60   single-stranded circular DNA.fasta
```

**Comment by photocyte** [comment]
For the meta information, what about multi FASTA files that combine DNA & protein sequences (probably not common, but not impossible). It seems the seqhash is more intended for single FASTA records, rather than multi FASTA files?

**Comment by shenwei356** [comment]
Seqkit assumes a consistent sequence type in a file and detects the sequence type according to the leading 10K bases of the first sequence.

    -t, --seq-type string                 sequence type (dna|rna|protein|unlimit|auto) (for auto, it automatically detect by the first sequence) (default "auto")

> It seems the seqhash is more intended for single FASTA records, rather than multi FASTA files?

Right, it applies to single sequences, and it uses a different strategy to deal with circular sequences.

**Comment by apcamargo** [comment]
Would it make sense to support multi-FASTA files to allow, for instance, the identification of circular sequences in a metagenomic assembly?

**Comment by shenwei356** [comment]
I would leave it to `seqkit fx2tab` which already support output md5 sum of every sequence, we can make it support circular sequence.

**Comment by apcamargo** [comment]
Seems good! Identifying circular sequences in metagenomes data is pretty common and I think it would be a great feature

**Comment by shenwei356** [comment]
Hmm, let me make it clear. It's not "identifying circular sequences". But it can find (circular) sequences with the same content from genome assemblies.

**Comment by apcamargo** [comment]
You mean identifying sequences that, when rotated, are the same as a given sequence?

If that's the case, I could use it to identify sequences that generate the same hash value when "rotated".

**Comment by shenwei356** [comment]
Right

**Comment by photocyte** [comment]
Hi there, I finally got around to testing the `seqkit sum` command. It worked well for my original use case of a single hash for a multi-FASTA file, and it is very fast. Thank you!

I think the relationship to https://pkg.go.dev/github.com/TimothyStiles/poly/seqhash is a little bit unclear. It uses a very similar naming scheme, but would the poly `seqhash` produce the same hash for a single-record FASTA file as `seqkit sum`? 

If yes, it seems reasonable to have the very similar naming scheme, although it is unclear if `seqhash` will produce a single combined-hash for a multi-FASTA, like `seqkit sum` does. 

If no (I think this is the case, `seqkit` uses `xxhash`, `poly` uses `Blake3`), I think a different naming scheme should be considered, to prevent confusion between the two hashing techniques. Maybe `v1s_DLS_k0_176250c8d1cde6c385397df525aa1a94` , `v1s` meaning version 1, seqkit? `v0.1` for seqkit and `v1` for `poly` seems too similar, IMO.

**Comment by shenwei356** [comment]
Actually, we have a `k` before the md5sum which `seqhash` does not have.

How about adding a `seqkit_sum` prefix:

    seqkit_sum_v0.1_DLS_k0_176250c8d1cde6c385397df525aa1a94

**Comment by photocyte** [comment]
Hmm, true. I forgot about that `k0` . `seqkit_sum` is explicit at least! Seems like a lot of characters, but worthwhile tradeoff? maybe `seqkit.v1_DLS ...` ? It being a checksum of some sort can be inferred from the structure of it.

**Comment by shenwei356** [comment]
will release this tool.
