### ISSUE TITLE
Documentation link broken for fx2tab

### ISSUE THREAD

**Issue by corneliusroemer** [shenwei356/seqkit#263]
The link on https://bioinf.shenwei.me/seqkit/ for fx2tab does not actually go to the right part of the usage docs, because the URL parameter should be `#fx2tab-tab2fx` not `#fx2tab`:

https://bioinf.shenwei.me/seqkit/usage/#fx2tab-tab2fx

![image](https://user-images.githubusercontent.com/25161793/144344831-3c2f55a7-e884-4af5-aabc-83e68b558060.png)

![image](https://user-images.githubusercontent.com/25161793/144344838-ea22add4-7e8f-40f9-9258-2a1af1a05798.png)

**Comment by shenwei356** [comment]
Thank you very much for reporting this. It's fixed.

**Comment by corneliusroemer** [comment]
That was fast :)

Great toolset, just discovered and love it already.
