### ISSUE TITLE
Does rmdup always keep the first sequence when identifying duplicates by ID or name?

### ISSUE THREAD

**Issue by matthuska** [shenwei356/seqkit#265]
When using seqkit rmdup, in my case removing dups by ID, does seqkit always keep the first sequence that belongs to each duplicate or is the behavior undefined? If it is guaranteed to always return the first instance, could this be noted in the usage documentation?

**Comment by shenwei356** [comment]
Yes, it keeps the first one. I'll add some notes. Thank you!
