### ISSUE TITLE
Add seqkit grep --count for counting matches

### ISSUE THREAD

**Issue by peterjc** [shenwei356/seqkit#267]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

Classical ``grep`` supports ``-c`` or ``--count`` meaning return an integer count on stdout, not the matching lines.

I expected ``seqkit grep`` to do the same (although I see you're already using ``-c``  as the short form for ``--circular``, so perhaps just adding ``--count`` would be best).

**Comment by peterjc** [comment]
Example with workaround:

```
$ echo -e ">seq\nacgtryswkmbdhvACGTRYSWKMBDHV" | seqkit grep -s -p ACG | grep -c "^>"
1
```

**Comment by shenwei356** [comment]
Usually, I pipe the result to `seqkit stats`. 

```
$ echo -e ">seq\nacgtryswkmbdhvACGTRYSWKMBDHV" | seqkit grep -s -p ACG | seqkit stats 
file  format  type  num_seqs  sum_len  min_len  avg_len  max_len
-     FASTA   DNA          1       28       28       28       28

```

Only outputting the count should speed up for large sequence files.

**Comment by shenwei356** [comment]
Implemented, but I have to use `-C`, the upper case. Cause many subcommand use `-c`, the lower case for "circular genome".

```
  -c, --circular               circular genome
  -C, --count                  just print a count of matching records. with the -v/--invert-match flag, count non-matching records
```
