### ISSUE TITLE
Is multi-threading not working?

### ISSUE THREAD

**Issue by elcortegano** [shenwei356/seqkit#268]
Hi, I am using `seqkit 2.1.0`, and I am not sure whether the option `-j` to set the number of threads is working.

The exact command I am running is:

    cat file.fa | seqkit locate -j 64 -r -p "[AG]G|C[CT]"

While multi-threading is set with `-j 64`, I cannot see that number of processes working with seqkit using standard commands like `htop` or `ps -e`. Is this a bug or there is something I am missing? Thanks

**Comment by shenwei356** [comment]
It only works for -m

> Mismatch is allowed using flag "-m/--max-mismatch",
>     you can increase the value of "-j/--threads" to accelerate processing.

Is the file very big? or the sequence is very long?

**Comment by shenwei356** [comment]
The home page lists the command/option than can benefit multiple threads. https://github.com/shenwei356/seqkit#subcommands

> Multiple-threads: Using the default 4 threads is fast enough for most commands, some commands can benefit from extra threads.

**Comment by shenwei356** [comment]
That's short. It search the complement sequence, so just use "[AG]G", or do not use regular expression, cause it's slow. 

Expand the motif:

    seqkit locate -p AG -p CG

**Comment by elcortegano** [comment]
Thank you for the feedback, it is much appreciated!
