### ISSUE TITLE
seqkit concat incorrectly treats duplicates

### ISSUE THREAD

**Issue by stas-malavin** [shenwei356/seqkit#269]
All sequences with the same ID from all files are concatenated (is this a wanted behavior?).
In case one of the files contains duplicates, this causes the concatenation of all sequences into one, which is generally not what one wants.
`seqkit concat <(echo -e '>A1 a\nAGCT--\n>A1 b\nACTG--\n>B1 a\nGTCA--') <(echo -e '>A1\nCCCT--\n>C1\nTTTC--')`
```
[INFO] read file: /dev/fd/63
[INFO] 3 records loaded
[INFO] read file: /dev/fd/62
[INFO] 2 records loaded
>A1
AGCT--ACTG--CCCT--
>A1
AGCT--ACTG--CCCT--
>B1
GTCA--
```
I'd prefer if the result of the command above was
```
>A1
AGCT--CCCT--
>A1
ACTG--CCCT--
>B1
GTCA--
```
```
$ seqkit version
seqkit v2.1.0
```

**Comment by shenwei356** [comment]
Yes, it looks reasonable. I'll fix it.

**Comment by shenwei356** [comment]
But it would become complicated, e.g., the second file has 3 `A1`. Should I compute the combination? It has 2 x 3 = 6 combinations.

**Comment by stas-malavin** [comment]
> But it would become complicated, e.g., the second file has 3 `A1`. Should I compute the combination? It has 2 x 3 = 6 combinations.

Yes, I think so. Or you might implement a flag influencing this behavior (see my another issue about joining).

**Comment by sklages** [comment]
Interesting .. I never used this option before, but from `--help` I would have expected the result to be:
```
>A1
AGCT--ACTG--CCCT--
>B1
GTCA--
>C1
TTTC--
```
.. leaving single records untouxhed :-)

**Comment by stas-malavin** [comment]
I agree, silent dropping of sequences is also an issue

**Comment by shenwei356** [comment]
Sorry, it's late.

```
$ seqkit concat <(echo -e '>A1 a\nAGCT--\n>A1 b\nACTG--\n>B1 a\nGTCA--') \
    <(echo -e '>A1\nCCCT--\n>C1\nTTTC--')

[INFO] read file: /dev/fd/63
[INFO] 3 records loaded from file: /dev/fd/63
[INFO] read file: /dev/fd/62
[INFO] 2 records loaded from file: /dev/fd/62
>A1 a|
AGCT--CCCT--
>A1 b|
ACTG--CCCT--

$ seqkit concat <(echo -e '>A1 a\nAGCT--\n>A1 b\nACTG--\n>B1 a\nGTCA--') \
     <(echo -e '>A1\nCCCT--\n>C1\nTTTC--') -f
[INFO] read file: /dev/fd/63
[INFO] 3 records loaded from file: /dev/fd/63
[INFO] read file: /dev/fd/62
[INFO] 2 records loaded from file: /dev/fd/62
>A1 a|
AGCT--CCCT--
>A1 b|
ACTG--CCCT--
>B1 a
GTCA--
>C1
TTTC--
```

**Comment by shenwei356** [comment]
Usage

``` text
concatenate sequences with same ID from multiple files

Attentions:
   1. By default, only sequences with IDs that appear in all files are outputted.
      use -f/--full to output all sequences.
   2. If there are more than one sequences of the same ID, we output the Cartesian
      product of sequences.
   3. Description are also concatenated with a separator (-s/--separator).
   4. Order of sequences with different IDs are random.

Usage:
  seqkit concat [flags]

Aliases:
  concat, concate

Flags:
  -f, --full               keep all sequences, like full/outter join
  -h, --help               help for concat
  -s, --separator string   separator for descriptions of records with the same ID (default "|")

```

Examples

```
$ cat a.fa 
>A 1
a1-
>A 2
a2-
>B 1
b1-

$ cat b.fa 
>A x
ax-
>C 1
c1-

$ seqkit concat a.fa b.fa 
>A 1|x
a1-ax-
>A 2|x
a2-ax-

$ seqkit concat a.fa b.fa --full
>C 1
c1-
>A 1|x
a1-ax-
>A 2|x
a2-ax-
>B 1
b1-

```

**Comment by stas-malavin** [comment]
Thanks, @shenwei356, looks great!

**Comment by shenwei356** [comment]
Oh, forgot the binaries, please have a try. If there's no bug, I'll tag a new release/

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/8242419/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/8242418/seqkit_darwin_amd64.tar.gz)

**Comment by stas-malavin** [comment]
Hi, works all right, thanks!
Two small things— (1) I would by default drop the comments with a warning and output concatenated with a flag (I assume this is a more frequent scenario), (2) "outter join" (a typo).

**Comment by shenwei356** [comment]
Thanks for the feedback.

(1) I thought about this when writing the code, but finally made outputting comments a default manner. Because it's simple to remove it using `seqkit seq -i`.
