### ISSUE TITLE
split error

### ISSUE THREAD

**Issue by kmatsuno** [shenwei356/seqkit#27]
I am using seqkit version 0.7.1. Attempting to split a FASTA file of protein causes the following error.
$ seqkit split -2 -p 2 test.faa
[ERRO] different line length in sequence

Apparently, it seems that an error occurs if the number of amino residues per line is different. In the base sequence, no error occurs even if the number of bases per line is different. Is there a solution to this problem?

**Comment by shenwei356** [comment]
seqkit seq test.faa > test.formated.faa
    seqkit split -2 -p 2 test.formated.faa

or

    seqkit seq test.faa | seqkit split -2 -p 2

**Comment by kmatsuno** [comment]
It was done correctly. Thank you very much.
