### ISSUE TITLE
seqkit concat: preserve the comments (full name)

### ISSUE THREAD

**Issue by stas-malavin** [shenwei356/seqkit#271]
```
$ seqkit concat <(echo -e '>A1 commentA\nAGCT--\n>B1 commentB\nGTCA--') <(echo -e '>A1\nCCCT--\n>B1\nTTTC--')
[INFO] read file: /dev/fd/63
[INFO] 2 records loaded
[INFO] read file: /dev/fd/62
[INFO] 2 records loaded
>A1
AGCT--CCCT--
>B1
GTCA--TTTC--
```
May preserve comments from the first set or from both (concatenating them too) — see also my other issue of joining.

**Comment by shenwei356** [comment]
Things become too complex, can you tell the real scenario?

**Comment by stas-malavin** [comment]
Ok, I have two sets of genes, and want to concatenate them. In the first set, some specimens were heterozygotes, so guys who sequenced them included both alleles with the same ID and different comments, e.g. `>Sp.A a` and `>Sp.A b`. Another gene has no duplicates (just `>Sp.A'). I want to concatenate them, preserving both alleles from set 1 and adding the same sequence from set 2 to both. And I'd also like to preserve comments.

Of course, I can do this in other way. But I thought this might be a separate useful improvement.

**Comment by stas-malavin** [comment]
But I really think these three issues might be solved separately, that's why I opened them one by one

**Comment by shenwei356** [comment]
see https://github.com/shenwei356/seqkit/issues/269
