### ISSUE TITLE
Feature: Implement `seqkit tail` analogously to `seqkit head` and unix `tail`

### ISSUE THREAD

**Issue by corneliusroemer** [shenwei356/seqkit#272]
Feature: Implement `seqkit tail` analogously to `seqkit head` and unix `tail`

**Comment by shenwei356** [comment]
Try [seqkit range](https://bioinf.shenwei.me/seqkit/usage/#range):

The last 100 records:

```
seqkit range -r -100:-1
```

**Comment by corneliusroemer** [comment]
Fab that's perfect, thanks so much.

I guess throwing in a `tail` somewhere in the doc string would help people like me find it better. And mention in `head` that instead of `tail` there is `range`.

**Comment by shenwei356** [comment]
Right, I'll update the docs.

**Comment by corneliusroemer** [comment]
The commands added missed the `-r` 🙃 

Fixed via #423

**Comment by shenwei356** [comment]
Thank you!
