### ISSUE TITLE
[Docs] Link to pgzip broken

### ISSUE THREAD

**Issue by corneliusroemer** [shenwei356/seqkit#273]
The link to pgzip here is broken https://bioinf.shenwei.me/seqkit/#acknowledgements

![image](https://user-images.githubusercontent.com/25161793/147186669-1e383715-32d0-42bb-8772-56150d501a30.png)

It leads to https://bioinf.shenwei.me/seqkit/github.com/klauspost/pgzip which is not the right address

![image](https://user-images.githubusercontent.com/25161793/147186697-6114d635-b760-451f-9b74-6a5533972b7d.png)

**Comment by shenwei356** [comment]
Thank you, It's fixed.

**Comment by corneliusroemer** [comment]
You're fast 🚀 😄

**Comment by corneliusroemer** [comment]
Fixed by https://github.com/shenwei356/seqkit/commit/528a3f627f0c8d0308f834bcf0d8d7b660e1ad33
