### ISSUE TITLE
[Enhancement] Support xz and/or zstd in addition to gzip

### ISSUE THREAD

**Issue by corneliusroemer** [shenwei356/seqkit#274]
For SARS-CoV-2 sequences gzip isn't really a good compression method. Everyone uses `xz` but `zstd` also works well.

It'd be great if `seqkit` supported one or both of these compression formats for input/output compression as well.

**Comment by shenwei356** [comment]
We use the  [xopen](https://github.com/brentp/xopen) for I/O, which recognize gzip data according to the magic number,
the golang packages for [zstd](https://github.com/klauspost/compress/tree/master/zstd) and [xz](https://github.com/ulikunitz/xz) might be easy to be integrated.

**Comment by corneliusroemer** [comment]
That would be amazing! I can imagine this being useful for many people.

**Comment by shenwei356** [comment]
Sorry, it's late, but I've made it. :fireworks: 

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/8237332/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/8237329/seqkit_darwin_amd64.tar.gz)



```
$ seqkit stats ../tests/hairpin.* -e
file                     format  type  num_seqs    sum_len  min_len  avg_len  max_len
../tests/hairpin.fa      FASTA   RNA     28,645  2,949,871       39      103    2,354
../tests/hairpin.fa.gz   FASTA   RNA     28,645  2,949,871       39      103    2,354
../tests/hairpin.fa.xz   FASTA   RNA     28,645  2,949,871       39      103    2,354
../tests/hairpin.fa.zst  FASTA   RNA     28,645  2,949,871       39      103    2,354
```
