### ISSUE TITLE
[Enhancement] Allow output file name to be specified in `split2`

### ISSUE THREAD

**Issue by corneliusroemer** [shenwei356/seqkit#275]
I want to be able to tell `split2` what my output file name should be.

Right now, it always seems to be the name of the input file. Causing weird names when one uses `stdin` for example.

This should be simple by adding a flag for this purpose.

**Comment by shenwei356** [comment]
done. see https://github.com/shenwei356/seqkit/issues/276#issuecomment-1066115170
