### ISSUE TITLE
Sequence extraction

### ISSUE THREAD

**Issue by zhichusun** [shenwei356/seqkit#278]
Hello, I have a fasta file that contains sequences of different lengths. I want to extract the base sequences greater than 500 and less than 10000bp and regenerate a fasta file. What should I do? Thanks a lot if anyone can help.

**Comment by zhichusun** [comment]
i found a way：seqkit seq -g -M 10000 -m 500 file.fas > new_file.fas

**Comment by shenwei356** [comment]
Glad you did it!
