### ISSUE TITLE
seqkit range enhancement

### ISSUE THREAD

**Issue by alxsimon** [shenwei356/seqkit#279]
Hi,
It would be great if `seqkit range` was accepting the following type of range syntax:
`seqkit range -r 15:-1` (or `seqkit range -r +15:-1`)
which would be equivalent to a `tail -n +15`

This is useful when working with several fasta and you don't know the number of sequences present (so you can't know easily the first range number starting from the end as the syntax is currently requiring or you can't know the last record number either if you wanted to do `-r 15:last`).

Let me know if this is not clear.
Thanks!

**Comment by shenwei356** [comment]
https://bioinf.shenwei.me/seqkit/usage/#range

example 2

**Comment by alxsimon** [comment]
Thanks, but in example 2 I don't have a priori knowledge of the first number (i.e. -100 here). It could be variable depending on the fasta file, while I would know the fixed position from the top of the file (15 in my example above).
Does that make sense?

**Comment by alxsimon** [comment]
I've used a workaround seen in the issues `seqkit fx2tab {input} | tail -n +15 | seqkit tab2fx`. But I feel like this can be a frequent use case that is missing in the syntax.

**Comment by shenwei356** [comment]
Oh I see. It should be easier to implement.

**Comment by shenwei356** [comment]
done.

```
Examples:
  1. leading 100 records (head -n 100)
      seqkit range -r 1:100
  2. last 100 records (tail -n 100)
      seqkit range -r -100:-1
  3. remove leading 100 records (tail -n +101)
      seqkit range -r 101:-1
  4. other ranges:
      seqkit range -r 10:100
      seqkit range -r -100:-10
```
