### ISSUE TITLE
add subcommand `translate`

### ISSUE THREAD

**Issue by shenwei356** [shenwei356/seqkit#28]

**Comment by ctava** [comment]
@shenwei356 could you kindly provide more requirements for the feature? are you talking about translation of mrna into amino acid sequences? why would / wouldn't this fit into the seq command?

**Comment by shenwei356** [comment]
Yes, it's RNA/DNA to Protein translation.  Many other tools provides this function, so I did not implement this yet. 

Options:

- codon table

Since `seqkit seq` has 10+ options now, I don't want make it more complicated. `stranslate` can be a separated command focusing on its function.
