### ISSUE TITLE
seqkit sort -s strange behavior

### ISSUE THREAD

**Issue by stas-malavin** [shenwei356/seqkit#281]
With gapped sequences (alignment), it sorts (reversely!) by the number of trailing gaps:
```
[~]: echo -e ">A\n-C---\n>B\n--TCG\n>C\n---CG" | seqkit sort -s
>C
---CG
>B
--TCG
>A
-C---
```
This seems to work properly if the gaps are removed beforehand:
```
[~]: echo -e ">A\n-C---\n>B\n--TCG\n>C\n---CG" | seqkit seq -g | seqkit sort -s
>A
C
>C
CG
>B
TCG
```
But then, I don't understand this:
```
[~]: echo -e ">A\n--AACGT\n>B\n---ACGT\n>C\n--AAC--" | seqkit seq -g | seqkit sort -s
>C
AAC
>A
AACGT
>B
ACGT
```
This seems to follow the previously described reverse sorting by trailing gaps number:
```
[~]: echo -e ">A\n--AACGT\n>B\n---ACGT\n>C\n--AAC--" | seqkit sort -s
>B
---ACGT
>C
--AAC--
>A
--AACGT
```
And by the way, I'd be happy to have a one-step way to sort gapped _alignments_ by the number of _non-gap characters_ in each sequence, i.e.:
```
>A
-C---
>C
---CG
>B
--TCG
```

**Comment by stas-malavin** [comment]
Ok, I haven't noticed the -b flag.
Yet, would be nice if the output was still aligned.

**Comment by shenwei356** [comment]
Just because the ASCII code of `-` is smaller than others.

```python
# python
>>> ord('-')
45
>>> [ord(x) for x in 'ACGTacgt']
[65, 67, 71, 84, 97, 99, 103, 116]
```
