### ISSUE TITLE
subseq returning hits from GTF/GFF or BED file in non-deterministic order

### ISSUE THREAD

**Issue by pmagwene** [shenwei356/seqkit#282]
### Prerequisites

- seqkit v2.1.0 (via bioconda)
- OS: Ubuntu 20.04

### Describe your issue

I'm using `seqkit subseq --gtf` to extract sequences of interest, specified in a GFF file, from a whole genome FASTA file.

 I expected the order of output to match the order of the feature input as specified in the GFF file, but the generated FASTA sequences seem to be returned in a non-deterministic order.   

I thought this might related to multithreading, so I tried setting `-j 1` but the order of output FASTA records still appears to be random.

Is this expected behavior? Is there any way to constrain output order to match input order of GTF/GFF file?

## Example files

* [target-genes.gff](https://raw.githubusercontent.com/pmagwene/seqkit-issues/main/target-genes.gff) -- GFF file with 
* [yeast.fna](https://raw.githubusercontent.com/pmagwene/seqkit-issues/main/yeast.fna) -- FASTA file

## Example call

```
seqkit subseq -j1 --gtf targets.gff yeast.fna > target-seq.fna
```
Call repeatedly to see different output.

**Comment by pmagwene** [comment]
In case this might have to do with the slight differences between GTF and GFF format, I converted the targets.gff file (linked above) to a BED file, and I can confirm that `--bed` as input still returns in non-determinstic order.

**Comment by shenwei356** [comment]
All features are stored *randomly* in a `map` structure, so the order is random.

Try `bedops` or `bedtools`?
