### ISSUE TITLE
Seqkit fish in parallel leads to broken output format

### ISSUE THREAD

**Issue by lborcard** [shenwei356/seqkit#283]
Hi,

### Prerequisites

- [x ] make sure you're are using the latest version by `seqkit version`
- [X ] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

 [ ] describe the problem
* I am try to parallelize a *seqkit fish * call using GNU parallel but the output format is completely broken where some line are not complete e.g 
`line 1 c53ddc5a-1468-4481-90c2-cb785a924cd5	676	732	flank_right	0	56	-	60.00	224	100.00	100.00	100.00`
`line 2 463	flank_left	0	77	+	9.83	276	0.00	0.00	100.00 `
* 
* [ ] provide a reproducible example
`time cat id_split.txt | parallel -j 15 'seqkit fish {} -f $Workdir/flanking_region.fasta  2>&1 >> results_fish_trim.txt '`

id_split.txt is a list of paths of a split fasta file.

I am also confused about `fish`, is the output written to stdout or stderr ?

thanks for the help

**Comment by shenwei356** [comment]
GNU parallel needs `--line-buffer` to avoid mixed lines, You may need `-k` to output the results of all commands in order.

**Comment by lborcard** [comment]
Thank you so much for your help,
 I resorted to outputting each to a separate file and concatenated them but thanks for the answer! 
I love your software btw!
