### ISSUE TITLE
seqkit grep reads patterns but does not return sequences on full sized file

### ISSUE THREAD

**Issue by EddoGilding** [shenwei356/seqkit#284]
Hello,

I am using seqkit v2.1.0. I have been trying to take a file of ID patterns to match in a nucleotide fasta file and extract those sequences to a new file. When I take a subset IDs and a subset of the fasta file, I get a result. When I attempt it on the full data set, it reports it is reading the patterns then the program ends with no result or error message. I have attempted flags and various combinations of flags but nothing works. 

In the attached files I have a part of the fasta and a short list of examples to extract. This example works, but the question is when this is done on the >18000 sequences in the fasta, seqkit does not give a result? When I try the full fasta with the shorter cdna_test.list.txt file it fails in the same way. I have also made sure there is the right encoding for LF in editpad.

Any idea what may be causing the program to return no result on the full set?

[cdna_test.txt](https://github.com/shenwei356/seqkit/files/8046061/cdna_test.txt)
[cdna_test.list.txt](https://github.com/shenwei356/seqkit/files/8046062/cdna_test.list.txt)

**Comment by shenwei356** [comment]
LF CR  should not be the reason, cause we recognize them.

More details of the big fasta file are needed, please run

```
# base information
seqkit stats big.fasta

# extract some headers
seqkit head -n 10 big.fasta | seqkit seq -n -o t.txt

# open the t.txt, and set edipad to show all symbols.

```
