### ISSUE TITLE
grep not matching any reads

### ISSUE THREAD

**Issue by rhysnewell** [shenwei356/seqkit#285]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

I have a set of reads whose headers are formatted like this:
`@NS500333:202:HTWLCBGX5:1:11101:18499:1035 1:N:0:TAGGCATG+NCTTACGC`

I can't seem to get seqkit grep to recognise and return any reads from these fastq files. I've attempted a number of different ID patterns but to no avail. I've also tried matching on the entire name `-n` but that did not work either. My guess is the colons in the name are messing with what seqkit grep determines to be the actual ID or header of the read. Is there an easy work around for something like this?

Reproducible example:
FASTQ:
```
@NS500333:202:HTWLCBGX5:1:11101:18499:1035 1:N:0:TAGGCATG+NCTTACGC
CTCGCNGGGCGGGAGGTTCCAGGCGACCACTGCGTGGTCATCGGCGGCGGGCTGGTCGGAGTCGAGGTCGCCGACTATCTCGCCGAGCGCGGCAAGCAGGTCGTCGTCGTCGCGCGCTCGGAGCTGCTCAAGAAGGCCGTGCACGCGGAC
+
AAAAA#EEEEEEEEEEEEEEEEEAEEEA/EEEEEEEEEE/EEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEEE/AEEEEEAEEEEAEEEAEEAEEEEEEEEEEA<EEAEEEE<<<EAAEEEEAAAEAE/EEA/EAEEAAEE</EAAE/AE
```

ID list:
```
@NS500333:202:HTWLCBGX5:1:11101:18499:1035 1:N:0:TAGGCATG+NCTTACGC
@NS500333:202:HTWLCBGX5:1:11101:18499:1035
@NS500333:202:HTWLCBGX5
@NS500333
```

Commands used:

`seqkit grep --pattern-file test_id.txt test_read.fastq`
`seqkit grep -n --pattern-file test_id.txt test_read.fastq`
`seqkit grep -r --pattern-file test_id.txt test_read.fastq`

Thank you,
Rhys

**Comment by shenwei356** [comment]
try grep to see if the record is there

    grep ns500333:202:HTWLCBGX5:1:11101:18499:1035 xxx.fastq

**Comment by shenwei356** [comment]
```

NS500333:202:HTWLCBGX5:1:11101:18499:1035 1:N:0:TAGGCATG+NCTTACGC            seqkit grep -n -f test_id.txt
NS500333:202:HTWLCBGX5:1:11101:18499:1035                                    seqkit grep    -f test_id.txt

```

**Comment by rhysnewell** [comment]
Yep, you're right. Sorry this was a mistake on my end. The script I was using to get the read id list files was written by someone else, and I didn't realise that it trims the last two characters off of the read id as it assumes the read id ends with '/1' or '/2' to indicate paired end reads. I've removed this assumption, and all should be well. Sorry for the concern!

Thank you
