### ISSUE TITLE
[Enhancement] [seqkit amplicon] filter by lowest mismatch or output mismatch count

### ISSUE THREAD

**Issue by Mandalaaron** [shenwei356/seqkit#286]
Hello there,

I'm currently using SeqKit v2.1.0 and need to filter my fastq/a by primer sets. Therefore I'm using `seqkit amplicon` with a tolerance of mismatches. I provide a huge primer list where primer pairs can be very identical. So after filtering, the tool outputs me multiple sequence IDs in case there are multiple matches with different primer pairs. But I'm only interested in the match with the lowest mismatch count. Currently I output the result as a bed file, since only here the primer ID appears (Correct me if I'm wrong here?)

So there would be different solutions:

1. automatically filter by lowest mismatch before output the final results (by flag)
2. provide the mismatch score in the final output, so I can filter by hand afterwards (additional column)
3. ...

I hope I could make my problem understandable. I would be very happy if you could add this feature (I think that it is not so complicated), but I am also open for alternative suggestions.

Thanks in advance,
Aaron

**Comment by shenwei356** [comment]
Added a new flag 

      -M, --output-mismatches      append the total mismatches and mismatches of 5' end and 3' end

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/8057720/seqkit_darwin_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/8057724/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/8057721/seqkit_linux_amd64.tar.gz)


Example:

    $ echo -ne ">seq\nacgcccactgaaatga\n" \
        | seqkit amplicon -F ccc -R ttt -m 1 -M
    >seq mismatches=2(1+1)
    cgcccactgaaat
    
    $ echo -ne ">seq\nacgcccactgaaatga\n" \
        | seqkit amplicon -F ccc -R ttt -m 1 -M --bed
    seq     1       14      .       0       +       cgcccactgaaat   2       1       1

**Comment by Mandalaaron** [comment]
Perfect! Thanks a lot!
