### ISSUE TITLE
[Suggestion] Allow filtering reads based on the expected number of errors

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/seqkit#287]
In amplicon-based analysis it is customary to filter reads based on the expected number of errors (sum of the error probabilities of the bases in the read, see [section 2.2](https://academic.oup.com/bioinformatics/article/31/21/3476/194979)). `seqkit seq` already handles filtering based on average quality, so it would be useful to have use it to filter reads based on the expected number of errors.

**Comment by shenwei356** [comment]
Oh, sorry, I've missed this issue.

I'm thinking we can hand over this kind of job to quality control tools.
