### ISSUE TITLE
seqkit split consumes lots of memory

### ISSUE THREAD

**Issue by lituan** [shenwei356/seqkit#29]
seqkit version v0.7.2

### Describe your issue
I try to use seqkit to split a fastq.gz  into small parts
the command is as follows:

seqkit split -j 4 -p 10 $fq -O split

$fq is about 2G, and it use about 10 minutes to finish the job, which is quite fast

the problem is that it consumes a lot of memory, about 60G

can you help reduce the memory it consumes.

**Comment by shenwei356** [comment]
`seqkit split` is originally designed to splitting FASTA files of which the size are not that much big.

You can manually use `seqkit range` to get subset of FASTQ files, which does not read the whole files in memory.

1. Firstly, get the total number of records: 11,721,965

        $ seqkit stats read_1.fq.gz 
        file          format  type    num_seqs        sum_len  min_len  avg_len  max_len
        read_1.fq.gz  FASTQ   DNA   11,721,965  1,758,294,750      150      150      150

        # file size: 343M
        $ du -h TLR6-kd_1.fq.gz
        343M    TLR6-kd_1.fq.gz

    `seqkit split` uses >10 G memory ::cry::
        
1. Prepairing the ranges to split

        $ cat ranges.tsv | csvtk -t pretty 
        1    1          1172196
        2    1172197    2344392
        3    2344393    3516588
        4    3516589    4688784
        5    4688785    5860980
        6    5860981    7033176
        7    7033177    8205372
        8    8205373    9377568
        9    9377569    10549764
        10   10549765   11721965

1. Splitting

        # dry run
        
        $ rush -j 1 -i ranges.tsv 'seqkit range -r {2}:{3} {file} | pigz -c > read_1.part{1}.fq.gz' --dry-run
        seqkit range -r 1:1172196 {file} | pigz -c > read_1.part1.fq.gz
        seqkit range -r 1172197:2344392 {file} | pigz -c > read_1.part2.fq.gz
        seqkit range -r 2344393:3516588 {file} | pigz -c > read_1.part3.fq.gz
        seqkit range -r 3516589:4688784 {file} | pigz -c > read_1.part4.fq.gz
        seqkit range -r 4688785:5860980 {file} | pigz -c > read_1.part5.fq.gz
        seqkit range -r 5860981:7033176 {file} | pigz -c > read_1.part6.fq.gz
        seqkit range -r 7033177:8205372 {file} | pigz -c > read_1.part7.fq.gz
        seqkit range -r 8205373:9377568 {file} | pigz -c > read_1.part8.fq.gz
        seqkit range -r 9377569:10549764 {file} | pigz -c > read_1.part9.fq.gz
        seqkit range -r 10549765:11721965 {file} | pigz -c > read_1.part10.fq.gz
        
        # time and memory usage
        
        $ memusg -t rush -j 1 -i ranges.tsv 'seqkit range -r {2}:{3} read_1.fq.gz | pigz -c > read_1.part{1}.fq.gz'
        elapsed time: 1m:56s
        peak rss: 31.29 MB
        
        # accuracy: 100%
        
        $ seqkit seq read_1.part?.fq.gz read_1.part10.fq.gz | md5sum 
        810ca35af6566e0f1af1f81c602ad90b  -
        
        $ seqkit seq read_1.fq.gz | md5sum 
        810ca35af6566e0f1af1f81c602ad90b  -

Wow, the peak memory is only 32MB! Although It has to read the file 10 times.

I'll optimize `seqkit split` when I'm free.

**Comment by lituan** [comment]
I will try this, Thank you
