### ISSUE TITLE
Minor typo in 2.2.0 release notes

### ISSUE THREAD

**Issue by heuermh** [shenwei356/seqkit#292]
In release notes for https://github.com/shenwei356/seqkit/releases/tag/v2.2.0

> add support of `zx` and `zstd` input/output formats. https://github.com/shenwei356/seqkit/issues/274

should be

> add support of `xz` and `zstd` input/output formats. https://github.com/shenwei356/seqkit/issues/274

**Comment by shenwei356** [comment]
oh, right, thank you

**Comment by heuermh** [comment]
No problem, thank you!
