### ISSUE TITLE
An empty file when split size equals the number of sequences in the fasta

### ISSUE THREAD

**Issue by robertbio** [shenwei356/seqkit#293]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
```
seqkit version                  
 seqkit v2.2.0
```
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
Creating a split of a fasta file when the number of sequences is equal to the number specified in the split command will create two files, one with all the sequences and another one empty. The expected behavior would be to not create the second file.

* [x] provide a reproducible example

file.fasta
```
>seq1
KYRTWEEFTRAAEKLYQADPMKVRVVLKYRHCDGNLCIKVTDDVVCLLYRTDQAQDVKKIEKFHSQLMRLME
>seq2
EEYQTWEEFARAAEKLYLTDPMKVRVVLKYRHCDGNLCMKVTDDAVCLQYKTDQAQDVKKVEKLHGK
```

Command:
```
seqkit split file.fasta -2 -s 2
[INFO] create and read FASTA index ...
[INFO] create FASTA index for file.fasta
[INFO] read sequence IDs from FASTA index ...
[INFO] 2 sequences loaded
[INFO] write 2 sequences to file: file.fasta.split/file.part_001.fasta
```

The result is a folder `file.fasta.split` with two files, the second one empty.
```
tree .
.
├── file.fasta
├── file.fasta.seqkit.fai
└── file.fasta.split
    ├── file.part_001.fasta
    └── file.part_002.fasta

1 directory, 4 files

ls -lh file.fasta.split
total 8
-rw-r--r--  1 x  x   190B Mar 15 18:00 file.part_001.fasta
-rw-r--r--  1 x  x     0B Mar 15 18:00 file.part_002.fasta

```

**Comment by shenwei356** [comment]
Thanks for reporting this, it's fixed now.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/8258282/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/8258284/seqkit_linux_amd64.tar.gz)

But I'd like to recommend using the `seqkit split2` instead, as the help message said,

> If you just want to split by parts or sizes, please use "seqkit split2",
> which also applies for paired- and single-end FASTQ.
