### ISSUE TITLE
seqkit -seq -Q 30 filter potential bug

### ISSUE THREAD

**Issue by slowsmile** [shenwei356/seqkit#297]
Dear seqkit author and other users
I am using seqkit to filter my fastq files based on minimum average quality of the reads, in the beginning I checked the stats of my fastq file ( this is a test fastq file I sub-sampled from my original fastq file)

`seqkit stats mytest.fastq -a`

and I got the following:
```

file          format  type  num_seqs     sum_len  min_len  avg_len  max_len   Q1   Q2   Q3  sum_gap  N50  Q20(%)  Q30(%)
mytest.fastq  FASTQ   DNA     76,907  23,072,100      300      300      300  150  300  150        0  300   79.99   68.37
```

Then I filtered my fastq file at minimum average reads quality score of 30
```
seqkit seq -Q 30 mytest.fastq | seqkit stats
file  format  type  num_seqs  sum_len  min_len  avg_len  max_len
-     FASTQ   DNA        613  183,900      300      300      300
```

this looks weird as my original file has 76,907 sequences and at least 68.37% bases has a score higher than 30, how come after filtering the qualified reads drastically reduced to 613? Almost 99%+ reads were filtered out.

so I used another tool "fastq" to benchmark, https://github.com/OpenGene/fastp , I tried
`fastp -e 30 -i mytest.fastq -o fastq_out.fastq`

and I got the following output

```
Detecting adapter sequence for read1...
No adapter detected for read1

Read1 before filtering:
total reads: 76907
total bases: 23072100
Q20 bases: 18455339(79.9899%)
Q30 bases: 15774388(68.37%)

Read1 after filtering:
total reads: 48299
total bases: 14489700
Q20 bases: 12791535(88.2802%)
Q30 bases: 11348213(78.3192%)
```
I think the fastq filter actually gave reasonable output since 48,299 out of 76,907 reads passed the Q30 filter (62.8%), which is very similar to the number of bases above Q30 in the original fastq file.

Based on my observation there appears to be some issue with **seqkit seq -Q 30** use when you want to filter low quality reads by minimum average read quality scores. Would you please look into the issue and see if there is a bug involved? Or I used the function in the wrong way?
Thanks a lot

I've attached my test fastq file for you to investigate

[mytest.fastq.gz](https://github.com/shenwei356/seqkit/files/8382097/mytest.fastq.gz)

Xiao

**Comment by shenwei356** [comment]
To my knowledge, `Q30(%)` refers to the percent of **bases** with quality >= 30, while the `-Q 30` filters **reads** with average quality >= 30.

**Comment by shenwei356** [comment]
related issues:

#198
#189

**Comment by shenwei356** [comment]
You may need a QC tools, like [fastp](https://github.com/OpenGene/fastp), to triming 3' low-quality subsequences, rather than according to the average quality of a read (`-e 30`).

**Comment by slowsmile** [comment]
I understand Q30(%) refers to percent of bases with quality >=30.
However, based on what I read from the seqkit manual **seqkit seq -Q 30** removes reads with average quality less than 30, isn't it? And that's the problem since it removed way more reads than it is supposed to do. You can check the sample fa file I attached, there are about 62% reads with average quality >=30 however, seqkit seq -Q 30 removed almost 99% of the reads.

**Comment by shenwei356** [comment]
Fastp has a different way to compute the average quality, by [simply computing the mean of the qualities](https://github.com/OpenGene/fastp/blob/ceedcc74f9d7b74c0a54ff7ec5938fcd01c99b3b/src/filter.cpp#L22-L50). While in seqkit, [it's different](https://github.com/shenwei356/bio/blob/64c4ab65d82a7de0fdb2b7dea17652f1eedd8771/seq/seq.go#L727-L739):

> take the qscore for each base, convert it back to an error probability, take the mean of those, and then convert that mean error back into a qscore

References:

- https://gigabaseorgigabyte.wordpress.com/2017/06/26/averaging-basecall-quality-scores-the-right-way/
- #189
