### ISSUE TITLE
regular expression syntax

### ISSUE THREAD

**Issue by ccshao** [shenwei356/seqkit#30]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

Could you kindly provide more details on syntax of regular expressed used by seqkit? Does it use the 
perl syntax or python, or other languages? I find the examples are useful, however,  limited. 

Thanks!

**Comment by shenwei356** [comment]
It's RE2 ([detai](https://github.com/google/re2/wiki/Syntax)l) not Perl nor Python, some features offered by Perl not supported.

Ref:

- [WhyRE2](https://github.com/google/re2/wiki/WhyRE2)
- https://github.com/google/re2/wiki/Syntax

**Comment by ccshao** [comment]
Thanks for the quick help!
