### ISSUE TITLE
Grep with -f ID.txt and -m 0 returns all the sequences in FASTQ instead of the ones matching with ID.txt

### ISSUE THREAD

**Issue by yangyxt** [shenwei356/seqkit#300]
### Prerequisites

using seqkit 2.2.0, installed with conda

### Describe your issue

Command is :
`seqkit grep -m 0 -f ID.txt -v input.fq.gz -o output.fq.gz`

Issue:
Returning all the sequences in FASTQ instead of the ones with ID matching patterns in ID.txt

A typical ID in ID.txt:
`A01225:404:H5NYTDSX3:2:1468:23032:22686`

A typical header line in FASTQ.gz file:
`@A01225:404:H5NYTDSX3:2:1101:3902:1016 1:N:0:CGTACAGA+TAAGATTA`

**Comment by yangyxt** [comment]
To supplement:

I also tried adding double quotes on IDs in ID.txt file, like this:
`"A01225:404:H5NYTDSX3:2:1468:23032:22686"`
And still every sequence is matched.

I also tried adding ^ and $ for regex pattern and added -r flag in seqkit grep:
`^A01225:404:H5NYTDSX3:2:1468:23032:22686$`
And still every sequence is matched.

Also the final matched number is determined by -C flag

**Comment by shenwei356** [comment]
should not use -v

      -v, --invert-match           invert the sense of matching, to select non-matching records

**Comment by yangyxt** [comment]
> should not use -v
> 
> ```
>   -v, --invert-match           invert the sense of matching, to select non-matching records
> ```

Thanks for the response. My bad on missing the help message of -v flag.
