### ISSUE TITLE
output files interleaved?

### ISSUE THREAD

**Issue by lauramason326** [shenwei356/seqkit#301]
Hello
 I am trying to split a large fastq.gz file into smaller files with 50M reads/ file  using seqkit split2, and I am giving it a forward and a reverse read, as below. The output, however, does not appear to be split into forward and reverse reads. Is this correct? Do I need to split my reads again using bbmap etc?
Thanks
Laura

```
(seqtk_env) bash-4.2$ seqkit split2 -1 COA1R.trimmed_R1.fastq.gz -2 COA1R.trimmed_R2.fastq.gz -o COA1R_50M -s 50000000 --force
[INFO] flag -1/--read1 and -2/--read2 given, ignore: -
[INFO] split seqs from COA1R.trimmed_R1.fastq.gz and COA1R.trimmed_R2.fastq.gz
[INFO] split into 50000000 seqs per file
[INFO] write 50000000 sequences to file: COA1R.trimmed_R1.fastq.gz.split/COA1R_50M.part_001.fastq.gz
[INFO] write 50000000 sequences to file: COA1R.trimmed_R1.fastq.gz.split/COA1R_50M.part_001.fastq.gz
[INFO] write 28697186 sequences to file: COA1R.trimmed_R1.fastq.gz.split/COA1R_50M.part_002.fastq.gz
[INFO] write 28697186 sequences to file: COA1R.trimmed_R1.fastq.gz.split/COA1R_50M.part_002.fastq.gz
```

**Comment by jmonroynieto** [comment]
You are using lowercase "o" which overrides the filenames. Could you change that to upper case "O" instead to see if your the sequences in the output directory match your expectations? If this does not work, it might be possible that the second file was emptied during a previous transformation, please check that you have sequences.
