### ISSUE TITLE
SeqKit for Galaxy?

### ISSUE THREAD

**Issue by ajkarloss** [shenwei356/seqkit#302]
Does SeqKit available for Galaxy platform? I couldn't find it in the toolshedd

**Comment by jmonroynieto** [comment]
The main tool shed has this [ community seqkit version available](https://toolshed.g2.bx.psu.edu/view/alyssa/seqkit_seq/871ff25d128c).

This is not an official distribution channel and it is therefore not provided in this repo or supported by the developer. Please contact your system administrator and ask them to make it available in your instance. If you are administering your own, please follow [this instructions](https://galaxyproject.org/admin/tools/add-tool-tutorial/).

**Comment by shenwei356** [comment]
@jmonroynieto Thanks for your kind reply.
