### ISSUE TITLE
seqkit fa2fq: [ERRO] fastx: stdin not detected

### ISSUE THREAD

**Issue by luoxungh** [shenwei356/seqkit#303]
When I use fa2fq for transforming fa to fq, there is an error, just like this:

```bash
$ seqkit fa2fq -f test.fa.gz -o test.fq.gz
[INFO] 25 sequences loaded
[ERRO] fastx: stdin not detected
```

The version of seqkit I use is 2.2.0. Maybe fa2fq is seldom used, and I just want to test it.

Please check it, thank you!

**Comment by shenwei356** [comment]
seqkit fa2fq -f small.fa.gz big.fq.gz -o small.fq.gz

**Comment by luoxungh** [comment]
Ok, thank you!

I did not understand the usage scenario of `seqkit fa2fq`, and there was an error.

BTW, I fulfill the tasks using `seqtk seq`.
