### ISSUE TITLE
split2: runtime: out of memory when split paired FASTQ files. 

### ISSUE THREAD

**Issue by wkang0** [shenwei356/seqkit#304]
### Prerequisites

- [x ] make sure you're are using the latest version by `seqkit version`
```bash
Singularity> seqkit version
seqkit v2.2.0
```
- [ x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [ x] describe the problem
runtime: out of memory: cannot allocate 4194304-byte block (3987767296 in use)
fatal error: out of memory

goroutine 66 [running]:
runtime.throw({0x865eb54, 0xd})
	/usr/local/go/src/runtime/panic.go:1198 +0x6a fp=0xb05dc8c sp=0xb05dc78 pc=0x807a84a
runtime.(*mcache).allocLarge(0xf77862e0, 0x10000, 0x0, 0x1)
	/usr/local/go/src/runtime/mcache.go:229 +0x250 fp=0xb05dcc0 sp=0xb05dc8c pc=0x805c490
runtime.mallocgc(0x10000, 0x85de520, 0x1)
	/usr/local/go/src/runtime/malloc.go:1088 +0x49d fp=0xb05dd10 sp=0xb05dcc0 pc=0x805342d
runtime.makeslice(0x85de520, 0x10000, 0x10000)
	/usr/local/go/src/runtime/slice.go:98 +0x4f fp=0xb05dd24 sp=0xb05dd10 pc=0x8090def
bufio.NewWriterSize(...)
	/usr/local/go/src/bufio/bufio.go:578

* [x ] provide a reproducible example
```bash
#!/bin/bash -euo pipefail
seqkit \
    split2 \
    --by-size 10 \
    --read1 r_H_5849_1.fq.gz \
    --read2 r_H_5849_2.fq.gz \
    --out-dir sample1_T1
```
read1 and read2 are about 40G each.

**Comment by shenwei356** [comment]
4194304-byte equals to 4MB, which is very small. Please check the Singularity configurations.

**Comment by wkang0** [comment]
No, the problem has nothing to do with Singularity. I installed seqkit on our HPC and got exactly the same errors. 

```text
[INFO] write 10 sequences to file: sample1/r_H_5849_1.part_2766.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_2.part_2794.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_1.part_2767.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_1.part_2768.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_1.part_2769.fq.gz
runtime: out of memory: cannot allocate 4194304-byte block (3987734528 in use)
fatal error: out of memory

goroutine 17689 [running]:
runtime.throw({0x865eb54, 0xd})
	/usr/local/go/src/runtime/panic.go:1198 +0x6a fp=0xaec4ea0 sp=0xaec4e8c pc=0x807a84a
runtime.(*mcache).allocLarge(0xf7735790, 0x110000, 0x0, 0x1)
```

**Comment by shenwei356** [comment]
Please paste more traceback logs, so I can know which line of code causes the panic.

**Comment by wkang0** [comment]
[INFO] write 10 sequences to file: sample1/r_H_5849_2.part_2793.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_1.part_2766.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_2.part_2794.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_1.part_2767.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_1.part_2768.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_1.part_2769.fq.gz
runtime: out of memory: cannot allocate 4194304-byte block (3987734528 in use)
fatal error: out of memory

goroutine 17689 [running]:
runtime.throw({0x865eb54, 0xd})
	/usr/local/go/src/runtime/panic.go:1198 +0x6a fp=0xaec4ea0 sp=0xaec4e8c pc=0x807a84a
runtime.(*mcache).allocLarge(0xf7735790, 0x110000, 0x0, 0x1)
	/usr/local/go/src/runtime/mcache.go:229 +0x250 fp=0xaec4ed4 sp=0xaec4ea0 pc=0x805c490
runtime.mallocgc(0x110000, 0x85de520, 0x1)
	/usr/local/go/src/runtime/malloc.go:1088 +0x49d fp=0xaec4f24 sp=0xaec4ed4 pc=0x805342d
runtime.makeslice(0x85de520, 0x0, 0x110000)
	/usr/local/go/src/runtime/slice.go:98 +0x4f fp=0xaec4f38 sp=0xaec4f24 pc=0x8090def
github.com/klauspost/pgzip.(*Writer).SetConcurrency.func1()
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:88 +0x3d fp=0xaec4f50 sp=0xaec4f38 pc=0x830532d
sync.(*Pool).Get(0x315d2278)
	/usr/local/go/src/sync/pool.go:148 +0xc4 fp=0xaec4f70 sp=0xaec4f50 pc=0x80af524
github.com/klauspost/pgzip.(*Writer).compressBlock(0x315d21c0, {0xff4ee000, 0xe60, 0x110000}, {0x0, 0x0, 0x0}, {0x334fe900, 0x315d04c0}, 0x0)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:425 +0x6e fp=0xaec4fc8 sp=0xaec4f70 pc=0x830690e
runtime.goexit()
	/usr/local/go/src/runtime/asm_386.s:1319 +0x1 fp=0xaec4fcc sp=0xaec4fc8 pc=0x80a8101
created by github.com/klauspost/pgzip.(*Writer).compressCurrent
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:270 +0x2d1

goroutine 1 [semacquire]:
sync.runtime_Semacquire(0xb033b28)
	/usr/local/go/src/runtime/sema.go:56 +0x36
sync.(*WaitGroup).Wait(0xb033b20)
	/usr/local/go/src/sync/waitgroup.go:130 +0x87
github.com/shenwei356/seqkit/v2/seqkit/cmd.glob..func32(0x8cb7a60, {0xb20d380, 0x0, 0x8})
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/split2.go:390 +0x16a4
github.com/spf13/cobra.(*Command).execute(0x8cb7a60, {0xb20d340, 0x8, 0x8})
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:860 +0x61c
github.com/spf13/cobra.(*Command).ExecuteC(0x8cb69e0)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:974 +0x403
github.com/spf13/cobra.(*Command).Execute(...)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/spf13/cobra@v1.4.0/command.go:902
github.com/shenwei356/seqkit/v2/seqkit/cmd.Execute()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/root.go:63 +0x27
main.main()
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/main.go:58 +0x17

goroutine 65 [chan receive]:
github.com/klauspost/pgzip.(*Writer).compressCurrent(0x315d21c0, 0x1)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:277 +0x345
github.com/klauspost/pgzip.(*Writer).Flush(0x315d21c0)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:478 +0x8e
github.com/shenwei356/xopen.(*Writer).Flush(0xb1a56c8)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/shenwei356/xopen@v0.2.1/xopen.go:148 +0x36
github.com/shenwei356/xopen.(*Writer).Close(0xb1a56c8)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/shenwei356/xopen@v0.2.1/xopen.go:130 +0x21
github.com/shenwei356/seqkit/v2/seqkit/cmd.glob..func32.1(0xb033b20, 0x1, 0x0, 0x0, 0x0, 0x0, {0x865bf85, 0x9}, 0xb20d3c0, 0x0, ...)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/split2.go:267 +0x483
created by github.com/shenwei356/seqkit/v2/seqkit/cmd.glob..func32
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/split2.go:209 +0x10c8

goroutine 66 [chan receive]:
github.com/klauspost/pgzip.(*Writer).compressCurrent(0x14e5dce0, 0x1)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:277 +0x345
github.com/klauspost/pgzip.(*Writer).Flush(0x14e5dce0)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:478 +0x8e
github.com/shenwei356/xopen.(*Writer).Flush(0xf931350)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/shenwei356/xopen@v0.2.1/xopen.go:148 +0x36
github.com/shenwei356/xopen.(*Writer).Close(0xf931350)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/shenwei356/xopen@v0.2.1/xopen.go:130 +0x21
github.com/shenwei356/seqkit/v2/seqkit/cmd.glob..func32.1(0xb033b20, 0x1, 0x0, 0x0, 0x0, 0x0, {0x865bf85, 0x9}, 0xb20d3c0, 0x0, ...)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/split2.go:267 +0x483
created by github.com/shenwei356/seqkit/v2/seqkit/cmd.glob..func32
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/split2.go:209 +0x10c8

goroutine 17688 [runnable]:
github.com/klauspost/pgzip.(*Writer).Write.func1(0x315d21c0)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:360
created by github.com/klauspost/pgzip.(*Writer).Write
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:360 +0x1ec

goroutine 17645 [chan receive]:
github.com/klauspost/pgzip.(*Writer).Write.func1(0x14e5dce0)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:373 +0xae
created by github.com/klauspost/pgzip.(*Writer).Write
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:360 +0x1ec

goroutine 17646 [runnable]:
github.com/klauspost/compress/flate.(*fastGen).Reset(0xfed04000)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/compress@v1.15.1/flate/fast_encoder.go:203 +0x40
github.com/klauspost/compress/flate.(*compressor).reset(0xfebb2000, {0x87521fc, 0x9bfbe30})
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/compress@v1.15.1/flate/deflate.go:772 +0x18b
github.com/klauspost/compress/flate.(*Writer).ResetDict(0xfebb2000, {0x87521fc, 0x9bfbe30}, {0x0, 0x0, 0x0})
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/compress@v1.15.1/flate/deflate.go:909 +0x70
github.com/klauspost/pgzip.(*Writer).compressBlock(0x14e5dce0, {0xfe872000, 0xe60, 0x110000}, {0x0, 0x0, 0x0}, {0x426efd80, 0x462dc280}, 0x0)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:429 +0x162
created by github.com/klauspost/pgzip.(*Writer).compressCurrent
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:270 +0x2d1

goroutine 17685 [runnable]:
github.com/klauspost/pgzip.(*Writer).Write.func1(0x315d20e0)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:364 +0x55
created by github.com/klauspost/pgzip.(*Writer).Write
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/klauspost/pgzip@v1.2.5/gzip.go:360 +0x1ec

**Comment by shenwei356** [comment]
It seems caused by the github.com/klauspost/pgzip package.  But I also reduce the memory consumption of `--by-size` and `--by-length'. 

Please try the new binaries, if the error remains, please paste again.

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/8797101/seqkit_linux_amd64.tar.gz)

**Comment by wkang0** [comment]
It looks OK now. But what exactly the split2 is doing now? It writes 10 sequences to each file? I have 700 million sequences. Does this mean I will get 70 million lines in my log file and 70 millions files for just spliting the fastq file? 

[INFO] write 10 sequences to file: sample1/r_H_5849_2.part_190389.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_1.part_190525.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_2.part_190390.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_1.part_190526.fq.gz
and continue

**Comment by wkang0** [comment]
Is it possible to increase the number of sequences write to files? 10 sequences for each file are too small. 

```bash
[INFO] write 10 sequences to file: sample1/r_H_5849_2.part_1051030.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_1.part_1051853.fq.gz
[INFO] write 10 sequences to file: sample1/r_H_5849_2.part_1051031.fq.gz
^C
$ ^C
$ ls
$ cd sample1/
ls | wc -l
2102886
 zcat r_H_5849_2.part_1051031.fq.gz | wc -l
40
```
