### ISSUE TITLE
How can I match up huge fastq sequences by seqkit pair?

### ISSUE THREAD

**Issue by TaskeHAMANO** [shenwei356/seqkit#305]
Thank you for continuing to develop this useful tools.

### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem

I am currently working on a deep sequenced FASTQ from a single cells, with 49GB of post-QC gz data on the F side and 62GB on the R side. As these data were QC'd using fastp with different criteria, I am trying to extract sequences that are only present in both using `seqkit pair`.

Following Usage's attention [1](https://bioinf.shenwei.me/seqkit/usage/#pair), I sorted the Sequence IDs of the data after QC and ran seqkit pair.  **However, the process is interrupted because it uses up about 380 GB of RAM (memory allocation error).** 
I monitored the output and the amount of memory with `htop` and found that the memory consumption is about 40 GB at the time of the output file size is 400 MB. Also, the amount of memory just keeps increasing.

How can I complete this procedure? Thank you for your help.

Note1: `seqkit sort` ran out of memory, so I used BBTools' sortbyname.sh for sequence sorting. The result itself was same with those by `seqkit sort`.  
Note2: The data used in this case had duplicated sequence IDs, so I used `seqkit rename` to make these unique, but it did not change the amount of memory used in `seqkit pair`.

* [x] provide a reproducible example

```bash
 seqkit pair -1 FORWARD.fastq.gz -2 REVERSE.fastq.gz -O OUTPUT_DIR -j 20
 ```

**Comment by shenwei356** [comment]
> As these data were QC'd using fastp with different criteria

I think the original order of sequence IDs was retained.

> I sorted the Sequence IDs of the data after QC and ran seqkit pair

So, there's no need to sort.

> The data used in this case had duplicated sequence IDs

How did it happen?

**Comment by TaskeHAMANO** [comment]
> How did it happen?

This data was created by additional re-sequencing due to insufficient number of reads.
This resulted in DataA.fq and DataB.fq, with duplicate Sequence IDs. To ensure that the amount of data was sufficient, I concatenated A and B to create C.fq. I use this C.fq.

**Comment by shenwei356** [comment]
Try use `seqkit rename` before merging and QC with fastp, this should works.

**Comment by TaskeHAMANO** [comment]
Thank you for your advice! 

As I mentioned in Note 2, the current order is
`Raw sequence -> QC by fastp -> sequence sort by bbtools -> make unique by seqkit rename -> match up by seqkit pair`
I will change it to the following order 😀
`Raw sequence -> make unique by seqkit rename -> QC by fastp -> match up by seqkit pair`

**Comment by TaskeHAMANO** [comment]
I tried the above steps but could not match up because the `seqkit pair` increased memory usage significantly. Below are the calculated costs for each procedure measured using GNU time.
Any advice would be appreciated!

---

|Nsteps|Steps|Memory|time|Notes|
|---| ------------- | ------------- |----|---|
|1|seqkit rename R1|147 GB|1:56:34||
|2|seqkit rename R2|143 GB|3:11:28||
|3|fastp R1|455 MB|1:30:31|Reads passed filters = 1.7 G reads|
|4|fastp R2|455 MB|1:44:37|Reads passed filters = 910 M reads|
|5|seqkit pair|392 GB|4:26:17|This task was terminated because of memory consumption; 392 GB is upper bounds of the machine|

**Comment by shenwei356** [comment]
Sorry for the late reply.

1. `sekqit rename` consumes too much memory. I've improved it ([seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/8866237/seqkit_linux_amd64.tar.gz)).
2. A lot of R2 reads failed to pass the fastp, 1.7G-910M, it's a big number so `seqkit pair` need a lot of memory to buffer these SE R1 reads.

Another low-memory method:

1. Still call `seqkit rename` before merging and QC with fastp.
1. Compute the intersection of R1 and R2 sequence IDs, which are the IDs of the paired reads.

        # sort a huge number of data is slow, and it may need use temporary files.
        sort -T ./ <(seqkit seq -ni R1.fq.gz) <(seqkit seq -ni R2.fq.gz) | uniq -d | gzip -c > id.gz

2. Extract paired reads with `seqkit greq` (use the new binary, which uses less memory and is faster)

        seqkit grep -f id.gz R1.fq.gz -o R1.pe.fq.gz
        seqkit grep -f id.gz R2.fq.gz -o R2.pe.fq.gz

**Comment by TaskeHAMANO** [comment]
Thank you very much for the hard work 🙇‍♂️

As for pairing, I had also considered [`fastq-pair`](https://github.com/linsalrob/fastq-pair), but the method you described clearly appears to be the best way! The test results for extracting 10,000,000 sequences from the original sequences were as follows:

- seqkit
	- Vanilla (sorted): Memory:12,872,084 KB time:0:56.02
	- After `seqkit shuffle` (randomized): Memory:16,096,980 KB time:1:01.72
- seqkit (decompressed)
	- Vanilla: Memory:14,623,444 KB time:0:55.89
- fastq_pair (decompressed)
	- Vanilla: Memory:1,805,020 KB time:2:52.41
- fastq_pair (decompressed; hashtable size=50021)
	- Vanilla: Memory:1,804,420 KB time:5:14.04
- fastq_pair (decompressed; hashtable size=10000000)
	- Vanilla: Memory:1,882,388 KB time:0:40.20
- sort for intersection and grep method
	- Vanilla: sort=Memory:24740 KB time:2:28.91,  grep=Memory: **749,412 KB** time:0:07.63

I will try it for whole data as soon as possible😁

**Comment by TaskeHAMANO** [comment]
Hi!
I have tried for the whole data and the calculation was completed successfully. Here is the required resource.

|Nsteps|Steps|Memory|time|Notes|
|---| ------------- | ------------- |----|---|
|1|seqkit rename R1|147 GB|1:56:34||
|2|seqkit rename R2|143 GB|3:11:28||
|3|fastp R1|455 MB|1:30:31|Reads passed filters = 1.7 G reads|
|4|fastp R2|455 MB|1:44:37|Reads passed filters = 910 M reads|
|5|Extract common sequence ID|55MB|7:30:24||
|6|seqkit grep R1|80GB|22:34:87||
|7|seqkit grep R2|80GB|28:37:03||

Thanks a lot!

**Comment by shenwei356** [comment]
Great!  Though the huge data takes such a long time.

Splitting the initial files (before renaming and merging) into chunks (seqkit split2 -p ) may reduce memory usage and may be faster by parallelization.

**Comment by jolespin** [comment]
Is this similar to bbmerge.sh from bbmap suite? 

Also, do you have any alternatives to repair.sh from that suite available in seqkit? 

I'm slowly realizing that I can significantly decrease dependencies for most of my environments by just using seqkit.  It's amazing!

**Comment by shenwei356** [comment]
> For paired reads in a single interleaved file, the second read is the mate of the first read, and the 4th read is the mate of the 3rd read, etc

Sorry, there's no such function.

**Comment by mbhall88** [comment]
I've just stumbled across this issue when using `seqkit pair` and running out of 750GB RAM!!

I wonder if this might be easily fixed with a `--two-pass` option? I would make a PR but I don't know go sorry.

**Comment by shenwei356** [comment]
It's probably because the reads are totally unordered.

```
Attentions:
1. Orders of headers in the two files better be the same (not shuffled),
   otherwise, it consumes a huge number of memory for buffering reads in memory.
```

Random access to FASTQ files is not supported by seqkit. Otherwise,  millions of passes are needed, not just two.

You can try the low-memory workaround: https://github.com/shenwei356/seqkit/issues/305#issuecomment-1150603307

**Comment by mbhall88** [comment]
The reads are in the exact same order 🤷

**Comment by shenwei356** [comment]
Can you show some lines of the ids?

    seqkit seq -n -i R1.fq.gz | head -n 5
    seqkit seq -n -i R2.fq.gz | head -n 5

**Comment by shenwei356** [comment]
@mbhall88  Well, it works well with me.

```
$ memusg -t -s "seqkit pair -1 ERR3243073_1.fastq.gz -2 ERR3243073_2.fastq.gz -O result"
[INFO] 791405007 paired-end reads saved to result/ERR3243073_1.fastq.gz and result/ERR3243073_2.fastq.gz

elapsed time: 17m:32s
peak rss: 126.62 MB

$ tree -lh
.
├── [  27G]  ERR3243073_1.fastq.gz
├── [  28G]  ERR3243073_2.fastq.gz
└── [ 4.0K]  result
    ├── [  29G]  ERR3243073_1.fastq.gz
    └── [  30G]  ERR3243073_2.fastq.gz

$ seqkit version 
seqkit v2.6.1
```

The files are bigger because that the default compress level is 5 instead of 6 in gzip.

**Comment by mbhall88** [comment]
Weird... I'll have to dig into this further and see why I'm having memory issues.

**Comment by mbhall88** [comment]
Hmm I used `/us/bin/time` and also found similar results. No idea why I was getting memory issues previously. Sorry about the false alarm. Might have been something weird going on on my HPC at the time

**Comment by shenwei356** [comment]
No worries.
