### ISSUE TITLE
Individual Contig Lengths

### ISSUE THREAD

**Issue by cassondranewman** [shenwei356/seqkit#309]
Beautiful tool! 

I am interested in indexing the contigs rather than the chromosomes. In seqkit stats, the contig statistics are provided so I am hoping a contig index is possible! I am looking to get the raw data for each contig length specifically. 

Thank you!!

**Comment by shenwei356** [comment]
seqkit seq -l contigs.fasta | cut -f 1,4

**Comment by cassondranewman** [comment]
Thank you for your quick response. The command seqkit `fx2tab -n -i -l XXX.fasta` pulls  out each sequence (with '>header') and corresponding length well. For me, my sequences are chromosomes ('>chr1', '>chr2', etc) however I was looking to assess the contigs within those chromosomes. 

No worries if this is not possible - just thought I would ask!

**Comment by cassondranewman** [comment]
Creating an AGP file from my genome.fasta did the trick! I was able to get lengths for the components [contigs] of the larger sequences [chromosomes]! Thanks for your time - closing the issue.
