### ISSUE TITLE
seqkit common and grep alternative do not return the same results

### ISSUE THREAD

**Issue by alcooj** [shenwei356/seqkit#31]
Good day, Wei.

Thanks for providing and continuously improving seqkit.

My question is regarding the documentation on seqkit common (I'm using the latest version 0.8.0): https://bioinf.shenwei.me/seqkit/usage/#common

Maybe I'm missing something but I get different results when I run the following:

`seqkit common -s sample.txt sample.txt | seqkit stats`
![image](https://user-images.githubusercontent.com/12235998/40761726-7bdf018e-6462-11e8-84b4-5b417683397f.png)

`seqkit grep -s -f <(seqkit seq -s sample.txt) sample.txt | seqkit stats`
![image](https://user-images.githubusercontent.com/12235998/40761489-6589b4f2-6461-11e8-9d40-ac2498021485.png)

The alternative syntax using grep is not returning all the sequences in sample.txt.

I've placed here [sample.txt](https://github.com/shenwei356/seqkit/files/2056615/sample.txt) for your reference.

**Comment by shenwei356** [comment]
Hi, result of `rmdup` shows that it's not the case of `common`:

```
$ seqkit rmdup -s sample.txt  | seqkit stats 
[INFO] 0 duplicated records removed
file  format  type     num_seqs  sum_len  min_len  avg_len  max_len
-     FASTA   Protein     1,000  320,266       27    320.3    2,820
```
And I try `seq -s`:

```
$ seqkit seq -s sample.txt | head -n 10
MICDFTYYSPTKVVFGKGRERETGVLVKERGAQKVLILYGGKSAQKSGLLFRVTDSLEQA
GIAYAALGGVTPNPRLSFVRMGTQKAREEGIDLILAVGGGSVIDAAKAISYALCYEGDVW
DFYAGKAQAQKALPVGVVLTLAASGSELSNSSVITNDRTHEKRGYNSDLARPVFAVMNPE
LTMTLPAYQTACGCCDIIMHTLERYFVQGPSMELTDALAEGLLRTVMAQSLILRDHPDDY
DARAEIMWAGSLSHNDLTGLGHYARDFATHRLEHEVSGLYDVAHGAGLTALWGSWARYVY
KDCLPRFCRFALHVMNVPEIGSDEAIALKGIEALEAFFASISMPISLKELGLILSDEDLR
TLARMCSHTAKDALGSAKVLHEKDMYTIYKAAYERT
MPRNDFDDFEDSADFPMNDGEEFKPITFGELGVPGLLVRVLAADGKKTAFPIQADTLPDS
LAGRDVLGRGRTGSGKTLAFSIPLVTRLGSYDSLGQTAMKEFRDEIKRRKKASLEERRSD
DFLPHPRGLVLAPTRELANQINDVLMPLARTFGMNTTTIYGGVKYIHQVRDLKAGADIVV
```
Here's the problem: `seqkit` wraps FASTA sequences into 60 base/aa per line by default, while `seqkit grep -f` reads every line as a query.  Therefore, you need to switch off the sequence wrapping by `-w 0`:

```
$ seqkit grep -s -f <(seqkit seq -s -w 0 sample.txt) sample.txt | seqkit stats
file  format  type     num_seqs  sum_len  min_len  avg_len  max_len
-     FASTA   Protein     1,000  320,266       27    320.3    2,820
```

Thanks for using and reporting.
