### ISSUE TITLE
Feature request: New switches for amplicon & stat?

### ISSUE THREAD

**Issue by photocyte** [shenwei356/seqkit#310]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

Hi there, thanks again for creating seqkit, I always find it really useful.

I have two feature requests:

(1) `seqkit amplicon` having a new switch, where it puts the string of `-F` and `-R` into the output FASTA record description

`seqkit amplicon -NEWSWITCH -s -F GGCTTGCGCAACATGAAGAA -R GCACGTGAGAAGTGAGGACA example.fasta`
outputs:
```
>record_id GGCTTGCGCAACATGAAGAA_and_GCACGTGAGAAGTGAGGACA_amplicon
GGCTTGCGCA...
```

(2) `seqkit stat`  having a setting, where it puts the seqkit stat results into the output FASTA record description. 

`seqkit stat -NEWSWITCH example.fasta`
outputs:
```
>record_id sum_len=460
GGCTTGCGCA...
```

**Comment by shenwei356** [comment]
> (1) `seqkit amplicon` puts the string of -F and -R into the output FASTA record description

It's simple.

> (2) `seqkit stats` puts the seqkit stat results into the output FASTA record description

It's not what `stats` should do. And it's simple to to:

```
$ echo -ne ">s\nactg\n"
>s
actg

$ echo -ne ">s\nactg\n" \
    | seqkit fx2tab -l -Q \
    | awk '{print $1" len="$3"\t"$2;}' \
    | seqkit tab2fx 
>s len=4
actg
```

**Comment by photocyte** [comment]
For (1), I found that `isPcr` (https://bioconda.github.io/recipes/ispcr/README.html) could do it. `isPcr` also reports all the amplicons, rather than just the longest like `seqkit amplicon`. For my application, I needed an in-silico PCR program that reports all the amplicons, so the (1) feature request is no longer needed.

For (2), I agree, it does seem to be a big change in the output style of `seqkit stat` . So, I think (2) is no longer needed either. Please close this issue if you agree.
