### ISSUE TITLE
A question about grep

### ISSUE THREAD

**Issue by DinizFerreira** [shenwei356/seqkit#311]
I've only been recently introduced to seqkit. I have a general doubt (maybe it's even too simple) about grep.

I'm working with a large fasta file and I want to filter out all of the sequences that are not from a specific gene (names of genes are always in the header). 

I know that grep is able to find certain patterns and that there is also a flag --delete-matched that deletes these occurrences. But I am wondering now if there is a way to find sequences by their gene name and delete them as a whole (not only the pattern matched).

Thanks in advance!

**Comment by shenwei356** [comment]
Try this:

    seqkit grep -r -v -i -p GENE seqs.fasta.gz -o gene.fasta.gz

Where `-r` is for partially matching, `-p` is the search pattern, `-v` is for outputting records that do not match the pattern. Details:

    -r, --use-regexp             patterns are regular expression
    -v, --invert-match           invert the sense of matching, to select non-matching records
    -i, --ignore-case            ignore case
    -p, --pattern strings        search pattern (multiple values supported. Attention: use double quotation marks for patterns containing comma, e.g., -p '"A{2,}"'))

[detailed usage and more examples](https://bioinf.shenwei.me/seqkit/usage/#grep)

Sorry, the flag `--delete-matched` is kind of misleading. It's not needed here.

**Comment by DinizFerreira** [comment]
Hi! 

Sorry for the delay. I tried to use this command in my fasta (seqkit grep -r -v -i -p ITS2 bold_chrysomya_coi.fasta -o teste.fasta) but when I use it I still get these "ITS2" records in my output. My intent is to find them and delete their whole record (headers and sequences). Is there a way to do it?

Thanks in advance

**Comment by shenwei356** [comment]
oh, missing the:
      -n, --by-name                match by full name instead of just ID

**Comment by DinizFerreira** [comment]
It works now! Thanks a lot!
