### ISSUE TITLE
How to subset sequences of certain length range

### ISSUE THREAD

**Issue by nsgarcia27** [shenwei356/seqkit#312]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem 
* [x] provide a reproducible example

Not really a bug, but can you use seqkit to subset sequences in a fasta file of certain length range? For example, I want to subset all sequences between 500-1000 bp long. Thanks!

**Comment by thallinger** [comment]
>Not really a bug, but can you use seqkit to subset sequences in a fasta file of certain length range? For example, I want to subset all sequences between 500-1000 bp long. 

You can achieve that with ``seqkit`` as follows:
```
  seqkit seq --min-len 500 <your input file> | seqkit seq --max-len 1000 -o <your output file>  
```
You may savely ignore the warning. Check output with:
```
  seqkit stats <your output file>  
```

**Comment by nsgarcia27** [comment]
> > Not really a bug, but can you use seqkit to subset sequences in a fasta file of certain length range? For example, I want to subset all sequences between 500-1000 bp long.
> 
> You can achieve that with `seqkit` as follows:
> 
> ```
>   seqkit seq --min-len 500 <your input file> | seqkit seq --max-len 1000 -o <your output file>  
> ```
> 
> You may savely ignore the warning. Check output with:
> 
> ```
>   seqkit stats <your output file>  
> ```

Thank you Gerhard. It worked!

**Comment by thallinger** [comment]
> Thank you Gerhard. It worked!

Glad to hear that. Filtering can be done even more elegantly:
```
   seqkit seq --min-len 500 --max-len 1000 <your input file> -o <your output file>  
```
