### ISSUE TITLE
Issue extracting subsequences from BED file

### ISSUE THREAD

**Issue by snakesch** [shenwei356/seqkit#315]
Dear Wei,

I would like to report an issue related to the usage of seqkit subseq. I tried to extract several subsequences, with coordinates in a BED file, from the UCSC reference genome of hg19 build. 
```{bash}
seqkit subseq --bed BED REF_GENOME 
```
The BED file is formatted as follows.
```
chr11   86806425        86806736        311
chr11   86806840        86807090        250
chr11   86807090        86807340        250
chr11   86807340        86807351        11
```

FASTA of reference genome is formatted as:
```
>chr11
xxxxxxxxxxxxxxxxxxxxxxx
>chr12
xxxxxxxxxxxxxxxxxxxxxxx
```
Output message:
![image](https://user-images.githubusercontent.com/70497658/177988575-dc54a2a4-82eb-48a2-8811-fdd5b789c36d.png)

However, as I tried to run line by line from the BED file using `seqkit subseq -r<start>:<end> REF_GENOME`, I can see the desired sequences in fact exist.

In another attempt, we resorted to `seqtk subseq REF_GENOME BED` and got the expected output. 
![image](https://user-images.githubusercontent.com/70497658/177990639-b4eaa507-28d7-45a8-a746-cd809d15798f.png)

Spec:
go version 1.13.6
seqkit version 2.2.0
linux/amd64

Please let me know if there is anything else I can provide (eg. sample BED file/reference genome FASTA).
Highly appreciated if you could advise on this issue and may I wish you a nice weekend!

Louis

**Comment by shenwei356** [comment]
Please check whether  IDs in  `ucsc.hg19.fasta.seqkit.fai` and `xxx.bed` files match.

**Comment by snakesch** [comment]
Thanks for the advice. I checked `ucsc.hg19.fasta.seqkit.fai` and noted that it only contains chrM, chr1, chr2 and chr3. Problem resolved after deleting `ucsc.hg19.fasta.seqkit.fai`.
