### ISSUE TITLE
seqkit seq never uses more than ~3 threads even though -j is higher (I/O bound?)

### ISSUE THREAD

**Issue by hermidalc** [shenwei356/seqkit#319]
I have a very fast NVMe drive, so wondering if `seqkit seq` is typically so I/O bound? When looking at my driver stats, it's not getting much utilization or read/writing that much. I passing in a long list of FASTA files, so isn’t due to file contention.

**Comment by shenwei356** [comment]
yes, it is.

**Comment by hermidalc** [comment]
Side question, is there a `seqkit seq` hidden option to control the `pgzip` compression level (like gzip -1 to -9)?

**Comment by shenwei356** [comment]
Yes, we did not provide this option, we use the default compression level 5.

If you want a smaller output size, you can change the output file extension to `.xz` or `.zst`, which are usually smaller than `.gz` files.

**Comment by hermidalc** [comment]
> Yes, we did not provide this option, we use the default compression level 5.
> 
> If you want a smaller output size, you can change the output file extension to `.xz` or `.zst`, which are usually smaller than `.gz` files.

I'll add it as an enhancement issue.
