### ISSUE TITLE
Prefix

### ISSUE THREAD

**Issue by mlcossette9224** [shenwei356/seqkit#322]
Hi ,
I have downloaded the most recent version. 
I am trying to split my scaffold based on a specific position using the following command:

seqkit-2.3.0/seqkit/seqkit split tarseq_10763.fa -r 1:2882375 --by-region-prefix Part_1

But the prefix flag is not working, my output still outputs all of the bp and won't actually give me an output because "file name too long"

Am I doing something wrong?
Thanks.
Marie

**Comment by shenwei356** [comment]
> split my scaffold based on a specific position

Why?

I don't think splitting your scaffolds based on a so large region (1:2882375) is a good idea. 2.8M bytes is of cause too long for a file name.

[The right example](https://bioinf.shenwei.me/seqkit/usage/#split):

```
## Split sequences by sequence region (for example, sequence barcode)

$ seqkit split hairpin.fa.gz -r 1:3 -2
[INFO] split by region: 1:3
[INFO] read and write sequences to tempory file: hairpin.fa.gz.fa ...
[INFO] read sequence IDs and sequence region from FASTA file ...
[INFO] create and read FASTA index ...
[INFO] write 463 sequences to file: hairpin.region_1:3_AUG.fa.gz
[INFO] write 349 sequences to file: hairpin.region_1:3_ACU.fa.gz
[INFO] write 311 sequences to file: hairpin.region_1:3_CGG.fa.gz
```

**Comment by mlcossette9224** [comment]
Because I am trying to submit my genome to GenBank and they asked me to split a scaffold at that specific location because there seems to be contamination based on their screening method. 

Marie

**Comment by shenwei356** [comment]
Hi Marie, I think they meant to `cut` the contigs and abandon some `fragments`. While `seqkit split` is used to `divide` multiple sequences into `chunks`/`partitions`.

Could you please tell how they exactly describe the specific location? For `1:2882375`, if you want to discard this region, you can use `seqkit subseq` or `seqkit faidx`.

For example, remove the leading 5bp of "s1".

```
$ cat scaffold.fasta 
>s1
NNNNNACTG
>s2
ACTGactg
```

First, remove the leading 5bp of "s1". There are two ways.

```
# 1) extract region [6, ] with seqkit faidx.
$ seqkit faidx scaffold.fasta s1:6--1
[INFO] create FASTA index for scaffold.fasta
>s1
ACTG

# 2) with seqkit subseq
$ seqkit grep -p s1 scaffold.fasta | seqkit subseq -r 6:-1
>s1
ACT
```

Then append other sequences to the cleaned "S1".

```
$ seqkit grep -p s1 -v scaffold.fasta
>s2
ACTGactg
```
<hr>

Steps:

```
seqkit faidx scaffold.fasta scalfoldname1:2882375--1 -o clean.fasta
seqkit grep -p  scalfoldname1 -v scaffold.fasta >> clean.fasta
```

**Comment by shenwei356** [comment]
If the region is in the middle of the sequence, then extract up- and down-stream subsequence using [seqkit subseq](https://bioinf.shenwei.me/seqkit/usage/#subseq), and join them with [seqkit concat](http://bioinf.shenwei.me/seqkit/usage/#concat).

```
$ cat scaffold.fasta
>s1
AAAAANNNNNCCCCC
>s2
ACTGactg

$ seqkit grep scaffold.fasta -p s1 | seqkit subseq -r 1:5 > left.fasta
$ seqkit grep scaffold.fasta -p s1 | seqkit subseq -r 11:-1 > right.fasta
$ seqkit concat left.fasta right.fasta 
>s1
AAAAACCCCC

```

**Comment by mlcossette9224** [comment]
Awesome, that should work thanks!!
