### ISSUE TITLE
Help: Specific SeqKit Use Case

### ISSUE THREAD

**Issue by CharlesARoy** [shenwei356/seqkit#324]
Hello,

I'm interested in using SeqKit for a specific set of Fastq manipulations but from what I can tell, it isn't capable of doing what I want. On the off chance that I missed something in the documentation, I'll describe what I'd like to do and if SeqKit can do any of it, please let me know how.

For some background, I'm working with demultiplexed paired-end reads that start with Unique Molecular Identifiers (UMIs). I'd like to:

1. Split the fastq files into high-quality and low-quality full-length reads.  
With `seqkit seq` I see that there are the `--max-qual` and `--min-qual` flags but I'd like to do this in one operation and write the high/low quality reads to separate files. 
3. For the high-quality reads, remove duplicates using a portion of the full sequence from both R1 and R2 of the paired-end reads, potentially with up to N mismatches. 
- The rationalle for combining sequence from both reads when removing duplicates is that the UMI sequences on each read are different, and by combining them, one can increase the certainty that a given pair of reads were PCR-amplified from the same molecule.
- The rationalle for using only a portion of the reads (say the first 20 bases of each) is to avoid inadvertently retaining duplicates that were seen as unique due to sequencing errors later in the read. 
- The rationalle for allowing up to N mismatches when removing duplicates is to avoid the aforementioned issue due to occasional sequencing errors.  
With `seqkit rmdup`, I see that there is the `--by-seq` flag which removes duplicates by sequence and the `--dup-seqs-file` flag which allows you to write the duplicates to a specific file. However, I don't see any options to consider R1 and R2, sub-regions of the sequences, or allow mismatches.
3. For the unique reads, trim the UMI sequences from each of the paired-end reads.  
I know that you could trim the reads with a command like e.g.:  
`awk '(FNR%2==0 || FNR%4==0){print substr($0,<start_coordinate>,<end_coordinate>);next} 1'`  
but I'm wondering whether SeqKit can do trimming itself (and whether it's faster than awk).

**Comment by shenwei356** [comment]
Tried [UMI-tools](https://umi-tools.readthedocs.io/en/latest/)? Its commands: 

- [whitelist](https://umi-tools.readthedocs.io/en/latest/reference/whitelist.html)
- [extract](https://umi-tools.readthedocs.io/en/latest/reference/extract.html)
- [group](https://umi-tools.readthedocs.io/en/latest/reference/group.html)
- [dedup](https://umi-tools.readthedocs.io/en/latest/reference/dedup.html)
- [count](https://umi-tools.readthedocs.io/en/latest/reference/count.html)
- [count_tab](https://umi-tools.readthedocs.io/en/latest/reference/count_tab.html)

<hr>

> 1. Split the fastq files into high-quality and low-quality full-length reads.
With seqkit seq I see that there are the --max-qual and --min-qual flags but I'd like to do this in one operation and write the high/low quality reads to separate files.

Not directly supported. But most people would discard low-quality reads. If you do need them, use `seqkit grep -f <ID file of high-quality reads> <original reads file> -v -o <low-quality reads>` to filter out HQ reads.

> 2. For the high-quality reads, remove duplicates using a portion of the full sequence from both R1 and R2 of the paired-end reads, potentially with up to N mimatches.

Not supported.

> 2.1 The rationalle for combining sequence from both reads when removing duplicates is that the UMI sequences on each read are different, and by combining them, one can increase the certainty that a given pair of reads were PCR-amplified from the same molecule.

I get it, by seqkit are not able to archive this. You may write a script.

> 2.2 The rationalle for using only a portion of the reads (say the first 20 bases of each) is to avoid inadvertently retaining duplicates that were seen as unique due to sequencing errors later in the read.

Reasonable.

> 2.3 The rationalle for allowing up to N mismatches when removing duplicates is to avoid the aforementioned issue due to occasional sequencing errors.

> With seqkit rmdup, I see that there is the --by-seq flag which removes duplicates by sequence and the --dup-seqs-file flag which allows you to write the duplicates to a specific file. However, I don't see any options to consider R1 and R2, sub-regions of the sequences, or allow mismatches.

`seqkit rmdup` compares the whole sequences, and does not consider R1 and R2.


> 3. For the unique reads, trim the UMI sequences from each of the paired-end reads.
I know that you could trim the reads with a command like e.g.:
awk '(FNR%2==0 || FNR%4==0){print substr($0,<start_coordinate>,<end_coordinate>);next} 1'
but I'm wondering whether SeqKit can do trimming itself (and whether it's faster than awk).

`seqkit subseq -r start:end` is faster than `awk`. [usage](https://bioinf.shenwei.me/seqkit/usage/#subseq). Removing first 16 bp:
    
    seqkit subseq -r 17:-1 read.fq.gz -o out.fq.gz

**Comment by CharlesARoy** [comment]
Thank you for your rapid response, this is all very helpful!
