### ISSUE TITLE
seqkit split2 ERROR: panic: runtime error: slice bounds out of range [122:60]

### ISSUE THREAD

**Issue by WJT0925** [shenwei356/seqkit#325]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

seqkit v2.3.0

seqkit split2  -p 2 -1 2016_1.fa.gz -2 2016_2.fa.gz --force
[INFO] flag -1/--read1 and -2/--read2 given, ignore: -
[INFO] split seqs from 2016_1.fa.gz and 2016_2.fa.gz
[INFO] split into 2 parts
panic: runtime error: slice bounds out of range [122:60]

goroutine 93 [running]:
bytes.(*Buffer).Write(0x565335?, {0xc001814078?, 0xc0001b0000?, 0x10000?})
	/usr/local/go/src/bytes/buffer.go:172 +0xd6
github.com/shenwei356/bio/seqio/fastx.wrapByteSlice({0xc001814000?, 0x96, 0xa00000}, 0x3c, 0xc0003300d0?)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/shenwei356/bio@v0.7.0/seqio/fastx/records.go:182 +0x1a6
github.com/shenwei356/bio/seqio/fastx.(*Record).FormatToWriter(0xc00013c0a0, 0xc0003d60c0, 0x3c)
	/home/shenwei/shenwei/scripts/go/pkg/mod/github.com/shenwei356/bio@v0.7.0/seqio/fastx/records.go:138 +0x1eb
github.com/shenwei356/seqkit/v2/seqkit/cmd.glob..func32.1({0x7ffcd946da92?, 0xc?})
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/split2.go:394 +0x1518
created by github.com/shenwei356/seqkit/v2/seqkit/cmd.glob..func32
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/seqkit/seqkit/cmd/split2.go:217 +0x186a

**Comment by shenwei356** [comment]
I've checked the code, but it's hard to find out what's the cause. Please paste the result of the command below:

    seqkit stats -a 2016_1.fa.gz 2016_2.fa.gz

**Comment by WJT0925** [comment]
file          format  type    num_seqs        sum_len  min_len  avg_len  max_len   Q1   Q2   Q3  sum_gap  N50  Q20(%)  Q30(%)  GC(%)
2016_1.fa.gz  FASTA   DNA   47,351,078  7,042,670,329       75    148.7      150  149  150  150        0  150       0       0   46.4
2016_2.fa.gz  FASTA   DNA   47,351,078  6,992,890,423       75    147.7      150  148  149  150        0  149       0       0  46.46

**Comment by shenwei356** [comment]
Fixed it. This bug only occurs when splitting two FASTA files.

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/9492542/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/9492543/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/9492540/seqkit_darwin_amd64.tar.gz)

**Comment by WJT0925** [comment]
Thanks！
