### ISSUE TITLE
Question regarding the split 2 function

### ISSUE THREAD

**Issue by Hywel-W** [shenwei356/seqkit#327]
This is not so much a problem but a question regarding how the split2 function works. I am using v2.2.0 and have run the following to split my fastq files into two separate files: $ seqkit split2 -1 reads_1.fq.gz -2 reads_2.fq.gz -p 2 -O out -f

I wondered how the split works, is it random or does it take the first half of the data and put it in one file and then the second half into the second file?

I want the data split randomly but I also need the read-pairs to be in the same output file (ie file 1 or 2) for downstream processing so I'd be grateful if you could explain a little more how the process works.

Many thanks - Hywel

**Comment by shenwei356** [comment]
> I wondered how the split works, is it random or does it take the first half of the data and put it in one file and then the second half into the second file?

It's `seqkit split` does, but it may consume a lot of memory for FASTQ files.

```
$ seqkit seq -n seqs.fa
1
2
3
4
```

`seqkit split`:

```
$ seqkit split -p 2 -O split seqs.fa

$ seqkit seq -n  split/seqs.part_001.fa 
1
2

$ seqkit seq -n  split/seqs.part_002.fa 
3
4
```

`seqkit split2`:

```
$ seqkit split2 -p 2 -O split2 seqs.fa

$ seqkit seq -n  split2/seqs.part_001.fa 
1
3

$ seqkit seq -n  split2/seqs.part_002.fa 
2
4
```

> I want the data split randomly but I also need the read-pairs to be in the same output file (ie file 1 or 2)

So you have interleaved PE reads. It's kind of not easy to reach the two goals.
The order of reads is not important in most cases, so you need simply split the files into two parts.

Firstly, get the number of reads in the file:

```
$ seqkit stats dataset_Ca.fq.gz
file              format  type   num_seqs      sum_len  min_len  avg_len  max_len
dataset_Ca.fq.gz  FASTQ   DNA   9,186,045  918,604,500      100      100      100
```

So, each part should has 9186040/2= 4593020 reads. Let's use`seqkit range` to extract reads, which has a small memory footprint.

```
$ memusg -t -s "seqkit range -r 1:4593020 dataset_Ca.fq.gz -o p1.fq.gz"

elapsed time: 4.667s
peak rss: 37.6 MB

$ memusg -t -s "seqkit range -r 4593021:-1 dataset_Ca.fq.gz -o p2.fq.gz"
elapsed time: 9.020s
peak rss: 36.94 MB

$  seqkit stats p1.fq.gz p2.fq.gz 
file      format  type   num_seqs      sum_len  min_len  avg_len  max_len
p1.fq.gz  FASTQ   DNA   4,593,020  459,302,000      100      100      100
p2.fq.gz  FASTQ   DNA   4,593,025  459,302,500      100      100      100
```

I'll add some doc and examples for this special case.

**Comment by Hywel-W** [comment]
Many thanks for this explanation, it's very helpful.

Best wishes

Hywel
