### ISSUE TITLE
grep `--invert-match` per `--pattern` (not global)

### ISSUE THREAD

**Issue by hermidalc** [shenwei356/seqkit#333]
It's very nice that `grep` provides the `--invert-match` flag, since Golang doesn't provide negative lookahead regex assertions. Would be a useful feature to be able to specify that `--invert-match` only applies to some of the `--pattern` strings. I currently have a use-case where running `seqkit grep` multiple times to get the filtering I need is expensive, and would like to be able to `grep` multiple patterns at once and `--invert-match` only apply to some of them.

**Comment by shenwei356** [comment]
> grep multiple patterns at once and --invert-match only apply to some of them

That's complicated. Currently, when multiple search patterns and the flag -v are igiven, only sequences that match none of the patterns are returned.

**Comment by hermidalc** [comment]
I'll pipe multiple `seqkit grep` for now, but just wanted to see if in future would be possible, since this would be possible patterns that include negative lookahead assertions but these aren't supported (not seqkit's fault but underlying Golang)
