### ISSUE TITLE
seqkit usage enhancement

### ISSUE THREAD

**Issue by Yijun-Tian** [shenwei356/seqkit#334]
Hello Shenwei,
I found seqkit extremly powerful in sequence parsing in for NGS data. Here I would like to ask you whether it will be difficult to implement another usage with seqkit mutate command, or it could be a new subcommand (e.g. seqkit emulate) that can help parsing nanopore sequencing data.
The situation I met is to emulate the nanopore sequencing reads in a bisulfite conversion like format. Attached is a sample sam file, with the sequences being raw ATCG bases, and two addtional base modification tags in MM:Z: and ML:B:, which tells modified base locations and probabilities in a sequences. The detail description of the two tags can be found here:
chrome-extension://efaidnbmnnnibpcajpcglclefindmkaj/https://samtools.github.io/hts-specs/SAMtags.pdf 

For example, in read 1, MM:Z:c+m,2,1,6,10,8,94; ML:B:c,126,186,211,190,107,232,
`ACTGTACTT**CG**TTCAGTTA**CG**TATTGCTCACCTCAGTCAAGA**CG**GAAGTAAAGGCTCAGGAAACAGCCCACCACAGAGGC**CG**TCAAACCAAAGACAGATTGCTTAACCAACAGATGGG**CG**CTGACCTAACC...
`
is there a easier way that I can change the modified C according to MM:Z: and ML:B info to T, like below
`ACTGTACTT**TG**TTCAGTTA**TG**TATTGCTCACCTCAGTCAAGA**TG**GAAGTAAAGGCTCAGGAAACAGCCCACCACAGAGGC**TG**TCAAACCAAAGACAGATTGCTTAACCAACAGATGGG**TG**CTGACCTAACC...`

Is it possible that we can use seqkit mutate with an option of -p 3,6,8,9:T after parsing the MM and ML tags to get a comma separated locations (absolute), or it will be easy for seqkit to do it from the scratch to realize such emulations? Since the MM and ML are reported based on the read sequences and do not consider alignment status (CIGAR, MAPQ doesn't influence the base modification call process), I feel this new usage will be suitable for seqkit to add and will attract a lot of users working on base modification analysis. 

I attached a sample sam file for your reference, hope it will be easy to make it happen.
Thanks for your help in advance!
[test.zip](https://github.com/shenwei356/seqkit/files/9780445/test.zip)

**Comment by shenwei356** [comment]
Thanks for your interest, but I'm afraid it's out of the scope of seqkit, you may try tools like [NanoSim](https://github.com/bcgsc/NanoSim).

**Comment by Yijun-Tian** [comment]
> Thanks for your interest, but I'm afraid it's out of the scope of seqkit, you may try tools like [NanoSim](https://github.com/bcgsc/NanoSim).

Great to know. I'll check the tool usage and see how it works.
