### ISSUE TITLE
Option for seqkit amplicon to search primer pairs in specific range/window/region

### ISSUE THREAD

**Issue by Subject-13** [shenwei356/seqkit#335]
Hi @shenwei356,

I would like to search for primer pairs in a specific range/window/region with `seqkit amplicon`. If I know the context of my sequences (like expecting the forward primer to be found at a base-position of 200-250) I would like to speed up the searching procedure by restricting the searching area of my sequences for both primers. Otherwise it would be cool to set a window where the reserve primer has to be found if the forward primer has been found somewhere in the sequence. For example, I don't know where to find the forward primer, but I know that the reserve primer always has to follow within the next 100 bases. Shouldn't this shorten the searching time? Please tell me if this feature is already implemented, I haven't found it in the manual.

Thanks!

**Comment by shenwei356** [comment]
Not supported.

> Shouldn't this shorten the search time? 

- No mismatch allowed: it could be a little bit faster. Linearly string indexing is used.
- Mismatch allowed: no big difference, may be faster. Burrows-Wheeler Transform and FM-index are used for searching.

**Comment by Mandalaaron** [comment]
Thanks for the advice.

Would this still be a useful feature to implement in the future? Or can this issue be closed?
