### ISSUE TITLE
locate issue

### ISSUE THREAD

**Issue by wonaya** [shenwei356/seqkit#336]
### Prerequisites

- [ seqkit v2.3.0] make sure you're are using the latest version by `seqkit version`
- [ yes] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [ I am running seqkit locate to find sequences (~300bp) to see if they are in my long reads (~1000bp), and somehow it is reporting sequences that are not in the reads ] describe the problem
* [seqkit locate -f sequence.fa pacbio.fastq --max-mismatch 0 > seqkit_mismatch_0.tsv ] provide a reproducible example

**Comment by shenwei356** [comment]
How do you know they are not in the reads? Using shell `grep` command? 

Did you check the strand in the result? Are they on the negative strand?
