### ISSUE TITLE
subseq  by gtf -tag only can be used by the frist tag

### ISSUE THREAD

**Issue by saltyduckegg** [shenwei356/seqkit#337]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
subseq  by gtf -tag only can be used by the frist tag
* [x] provide a reproducible example

- like 
```
$ cat t.gtf
seq     test    CDS     5       8       .       .       .       gene_id "A"; transcript_id "a";
seq     test    CDS     5       8       .       -       .       gene_id "B"; transcript_id "b";
```
they are useful:
```
seqkit subseq --gtf t.gtf t.fa 
seqkit subseq --gtf t.gtf t.fa --gtf-tag "gene_id" 
```

they are unuseful:
```
seqkit subseq --gtf t.gtf t.fa --gtf-tag "transcript_id" 
```

**Comment by shenwei356** [comment]
also check: https://github.com/arq5x/bedtools2 and https://github.com/bedops/bedops
