### ISSUE TITLE
Version 2.3.1?

### ISSUE THREAD

**Issue by pooranis** [shenwei356/seqkit#338]
### Prerequisites

- [?] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

Hello.  We downloaded the newest version of seqkit here: https://github.com/shenwei356/seqkit/releases/tag/v2.3.1
for both darwin and linux amd64 and when I run
```bash
$ seqkit version
seqkit v2.3.0
```

for both.  Is this the correct version we are downloading?  Is the version number just not changed?  
Thanks so much.

**Comment by shenwei356** [comment]
I forgot to update the version number …

https://github.com/shenwei356/seqkit/blob/v2.3.1/seqkit/cmd/version.go#L32
