### ISSUE TITLE
[Feature suggestion] seqkit rmdup output the number and sequences of duplicated sequences ? not number and  name

### ISSUE THREAD

**Issue by Winjor** [shenwei356/seqkit#339]
Hi, I want to count the number of duplicated reads of fastq(SE, or fasta ) file, I found seqkit rmdup has similar functions, -s "remove by seq", and -D "save number and list of duplicated seqs".  However the file output by -D only save the number and seqs's name, not save the seq itself. 

For example:
raw.fasta file like this:
>seq1
AAAAAAA
>seq2
AAAAAAA
>seq3
GGGGGGG

cmd:  seqkit rmdup -s -D out.number -o out.rmdup.fasta raw.fasta

the out.number file is:
2    seq1, seq2
1    seq3 
noly has the seqs name.

what I want like ths:
2  AAAAAAA  
1  GGGGGGG 

Is seqkit has this function now? or will add the  function in the future?

thanks!

**Comment by shenwei356** [comment]
https://bioinf.shenwei.me/seqkit/usage/#rmdup
```
  -d, --dup-seqs-file string   file to save duplicated seqs
```

**Comment by shenwei356** [comment]
seqkit rmdup -s -i hairpin.fa.gz -o clean.fa.gz -d duplicated.fa.gz -D duplicated.detail.txt
    
    
    
    # id -> count   for duplicated sequences
    # and only keep one id for a group of sequence
    sed -r 's/, .+//' duplicated.detail.txt \
        | csvtk cut -Ht -f 2,1 \
        > id2count.dup1.tsv

    # id -> count   for unique sequences
    seqkit seq -ni hairpin.fa.gz \
        | csvtk grep -Ht -v -P <(cut -f 1 id2count.dup1.tsv) \
        | awk '{print $1"\t"1}' \
        > id2count.uniq.tsv
        
    # extact these sequences with the IDs
    # ony keep ID
    # replace ID with count
    # convert to tabular format
    seqkit grep -f <(cat id2count.dup1.tsv id2count.uniq.tsv | cut -f 1) hairpin.fa.gz \
        | seqkit seq -i \
        | seqkit replace -k <(cat id2count.dup1.tsv id2count.uniq.tsv) -p '(.+)' -r '{kv}' \
        | seqkit fx2tab -o count2seq.tsv.gz
        
    $ zcat count2seq.tsv.gz | csvtk uniq -Ht -f 1  | head -n 3
    1       UACACUGUGGAUCCGGUGAGGUAGUAGGUUGUAUAGUUUGGAAUAUUACCACCGGUGAACUAUGCAAUUUUCUACCUUACCGGAGACAGAACUCUUCGA
    4       UGGGAUGAGGUAGUAGGUUGUAUAGUUUUAGGGUCACACCCACCACUGGGAGAUAACUAUACAAUCUACUGUCUUUCCUA
    6       GCAUCCGGGUUGAGGUAGUAGGUUGUAUGGUUUAGAGUUACACCCUGGGAGUUAACUGUACAACCUUCUAGCUUUCCUUGGAGC

**Comment by Winjor** [comment]
thanks a lot，it is useful way！
