### ISSUE TITLE
Split an interleaved paired-end FASTQ into R1 and R2 files

### ISSUE THREAD

**Issue by hermidalc** [shenwei356/seqkit#340]
I know other tools can do it, like BBMap `reformat.sh`, it's just a simple useful feature to add to seqkit

**Comment by shenwei356** [comment]
seqkit split2 -p 2 interleaved.fastq.gz -O paired

**Comment by hermidalc** [comment]
Oh sorry @shenwei356, I missed that in the docs, I searched the Usage for interleaved and didn't see the string so assumed feature wasn't there. Thank you!

**Comment by shenwei356** [comment]
It's a hidden feature, I'll add some doc. 

But I can't remember what the way of distributing reads is called. It's like the process of giving cards to players one by one in a card game.
