### ISSUE TITLE
Explanation of `seqkit bam` read count columns when running `--count` or `--idx-count`

### ISSUE THREAD

**Issue by hermidalc** [shenwei356/seqkit#342]
Could you explain output columns when running `seqkit bam` with `--count` or `--idx-count`?

**Comment by hermidalc** [comment]
Sorry I see now that `SecCount` == from secondary alignments and `SupCount` == from supplementary alignments

One follow-up question, does `Count` include the counts from these other columns? I.e. is it a total count

**Comment by hermidalc** [comment]
@shenwei356 just wondering, does `Count` include the counts from `SecCount` and `SupCount` columns? i.e. is it a total count

**Comment by shenwei356** [comment]
Sorry, the `bam` command was contributed by @botond-sipos , I'm not familiar with the detail.

**Comment by hermidalc** [comment]
I see on 

https://github.com/shenwei356/seqkit/blob/master/seqkit/cmd/bam.go#L219-L225

that it appears to be a total count, thank you.
