### ISSUE TITLE
`seqkit bam` with `--count` or  `--idx-count` doesn't keep count rows with IDs from `--grep-ids`

### ISSUE THREAD

**Issue by hermidalc** [shenwei356/seqkit#343]
Unless I'm doing something wrong (which is totally possible!), `seqkit bam` with `--count` or `--idx-count` doesn't keep count rows with IDs from `--grep-ids`, it gives you the same output as if you didn't specify the option.

**Comment by botond-sipos** [comment]
The `--idx-count` mode cannot use the list provided by `--grep-ids` as it reports the pre-calculated counts directly from the BAM index.
The `--count` option should take into account the specified IDs (unless there is a bug). Also, keep in mind that `--grep-ids` does not accept regular expressions and the IDs need to match perfectly with the ones from the BAM file.
