### ISSUE TITLE
reading GISAIDs .fasta.tar.xz file format errors with "fastx: invalid FASTA/Q format"

### ISSUE THREAD

**Issue by Mike-Honey** [shenwei356/seqkit#345]
### Prerequisites

- [X] make sure you're are using the latest version by `seqkit version`
- [X] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### reading GISAIDs .fasta.tar.xz file format errors with "fastx: invalid FASTA/Q format"

I'm guessing this is because of their nested file format; they wrap a ".fasta" format file first in a .tar archive, then in a .xz. Perhaps seqkit decompresses just the .xz layer and expects a .fasta file, but instead there is a .tar archive of a .fasta file?

Any shortcuts to overcome this, or do I have to unpack it all before seqkit?

**Comment by shenwei356** [comment]
Yes, you need to unpack it. It may contain many files in it.

**Comment by Mike-Honey** [comment]
Thanks for the speedy reply!
