### ISSUE TITLE
Fish interpretation/comparison to blast

### ISSUE THREAD

**Issue by lborcard** [shenwei356/seqkit#351]
I am trying to compare the results from fish the results of blast but I do not understand the all the outputs from the fish function. Where could I find this information?

best,

Loïc

**Comment by shenwei356** [comment]
Usage and examples: https://bioinf.shenwei.me/seqkit/usage/#fish

@botond-sipos contributes this command, he might help.

**Comment by lborcard** [comment]
> Usage and examples: https://bioinf.shenwei.me/seqkit/usage/#fish

Thank you for your answer,

Well I have read it several times but not every output is explained

**Comment by botond-sipos** [comment]
The `seqkit fish` tool does not provide rigorous statistics. If you need those you should use BLAST.
