### ISSUE TITLE
[Question] - Is it possible to use rmdup on fastq_1 and fastq_2 simultaneously

### ISSUE THREAD

**Issue by tamuanand** [shenwei356/seqkit#352]
Hi

Is it possible to run rmdup on both fastq_1 and fastq_2 simultaneously

https://bioinf.shenwei.me/seqkit/usage/#rmdup

Something like how clumpify can - https://www.biostars.org/p/225338/

clumpify.sh in1=r1.fq.gz in2=r2.fq.gz out1=clumped1.fq.gz out2=clumped2.fq.gz reorder

Thanks,

**Comment by shenwei356** [comment]
Oh sorry to miss this issue. It's not supported.
