### ISSUE TITLE
seqkit command not found when using seqkit grep in file.sh

### ISSUE THREAD

**Issue by jiaow1018** [shenwei356/seqkit#355]
* When running a bash script with the command below inside, the error " seqkit: command not found " was raised. But it would be totally fine if seqkit combined with other commands.

```
seqkit=/path/to/seqkit 
$seqkit grep -r -p "pattern" fasta.fa
```

**Comment by shenwei356** [comment]
Make sure the path seqkit located is added to the environment veriable PATH.

**Comment by jiaow1018** [comment]
Already gave the path of seqkit

> Make sure the path seqkit located is added to the environment veriable PATH.

**Comment by shenwei356** [comment]
> Already gave the path of seqkit

Please recheck it with `echo $PATH`.

<hr/>

It would be simple with

    mkdir -p $HOME/bin/; cp seqkit $HOME/bin/

cause `$HOME/bin` is in `$PATH` by dfault.

**Comment by jiaow1018** [comment]
> > Already gave the path of seqkit
> 
> Please recheck it with `echo $PATH`.
> 
> It would be simple with
> 
> ```
> mkdir -p $HOME/bin/; cp seqkit $HOME/bin/
> ```
> 
> cause `$HOME/bin` is in `$PATH` by dfault.

But why the realpath of seqkit didn't work?

**Comment by jiaow1018** [comment]
> > Already gave the path of seqkit
> 
> Please recheck it with `echo $PATH`.
> 
> It would be simple with
> 
> ```
> mkdir -p $HOME/bin/; cp seqkit $HOME/bin/
> ```
> 
> cause `$HOME/bin` is in `$PATH` by dfault.

That's not because of the path of seqkit. It seems there's a conflict between `seqkit grep` and bash `grep`. When I use seqkit grep in .sh file, it calls the bash `grep`. Because seqkit fx2tab works fine.

**Comment by shenwei356** [comment]
> It seems there's a conflict between seqkit grep and bash grep

Never met this. It should not happen. Please paste some code snippets of the .sh file.

**Comment by jiaow1018** [comment]
> > It seems there's a conflict between seqkit grep and bash grep
> 
> Never met this. It should not happen. Please paste some code snippets of the .sh file.

That's the code snippets of the file.
```
#!/bin/bash
seqkit=/home/bq_jwang/.conda/envs/Py36/bin/seqkit
$seqkit grep -r -p "P01116" uniprot_sprot.fasta
```
By the way, is your Gmail works fine? Maybe we can talk by mandarin

**Comment by shenwei356** [comment]
Replace `$seqkit` with `seqkit` please, the former is a veriable named "seqkit".
