### ISSUE TITLE
seqkit split --two-pass does not work in conjunction with `stdin` input

### ISSUE THREAD

**Issue by davemcg** [shenwei356/seqkit#356]
### Prerequisites

- [x ] make sure you're are using the latest version by `seqkit version`
- [ x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x ] describe the problem

`seqkit split --by-id --two-pass` does not appear to use the index (but it does make it) when the fasta is given as `stdin`. It runs out of memory with a large fastq set and thus perhaps is still using the in-memory approach? Perhaps because the index is saved as `stdin.fastx` ? This bug persists even when using `--by-id-prefix` and `--out-dir` (and `stdin.fastx` continues to be in the index name even with these flags used).
* [ x] provide a reproducible example (seqtk seq -A turn a fastq into a fasta)
`seqtk seq input.fq.gz -A | seqkit split - --by-id --id-regexp "([ATGCN]{16})"  --extension .gz --two-pass`

**Comment by davemcg** [comment]
I am using `2.3.0`

**Comment by shenwei356** [comment]
-2, --two-pass                  two-pass mode read files twice to lower memory usage. (only for FASTA format)

Just because the two-pass mode only applies to FASTA format. When FASTQ is given, it loads all data into RAM.

**Comment by shenwei356** [comment]
You might need other UMI tools.

For me, I use [`seqkit grep`](https://bioinf.shenwei.me/seqkit/usage/#grep) to extract reads for each barcode if the positions of the barcodes are certain.

    seqkit grep -s -r 1:16 -m 2 -p ACTGACTGACTGACTG

Also I use [`seqkit amplicon`](https://bioinf.shenwei.me/seqkit/usage/#amplicon) to extract sequences next to a barcode/primer. 

    seqkit amplicon -F ACTGACTGACTGACTG -r 17:-1


These two commands search on both strands.
