### ISSUE TITLE
Non-recursive scat

### ISSUE THREAD

**Issue by mbhall88** [shenwei356/seqkit#358]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

It would be great if there was a flag in `scat` for non-recursive concatenation of files - i.e., just the fastq files under the directory given. Is this feasible?

**Comment by shenwei356** [comment]
seqkit seq *.fastq ?

**Comment by mbhall88** [comment]
Ah nice. Although, is there a way to this without running into "argument list too long" issues?

**Comment by shenwei356** [comment]
Sure

    seqkit seq --infile-list <(find -name "*.fastq.gz") -o out.fastq.gz

Next version, the --infile-list flag will supoort stdin.

    find -name "*.fastq.gz" | seqkit seq --infile-list - -o out.fastq.gz

**Comment by mbhall88** [comment]
Very neat!! Thank you
