### ISSUE TITLE
Recommended usage for `seqkit amplicon` when extracting amplicons from genomes

### ISSUE THREAD

**Issue by jolespin** [shenwei356/seqkit#359]
### Prerequisites

- [ ] make sure you're are using the latest version by `seqkit version`
- [ ] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [ ] describe the problem

I'm trying to run the universal primers from this study: https://pubmed.ncbi.nlm.nih.gov/30824940/ with a basic yeast strain (https://www.ncbi.nlm.nih.gov/assembly/GCF_000146045.2) using `seqkit amplicon` and I can't figure out how to properly tune the parameters to pull out the region of interest. 

```
We designed a primer pair of each 27 bases to amplify a ∼4000 bp fragment of the ribosomal DNA, including partial 18S and 28S as well as full ITS1, 5.8S, and ITS2 sequences (18S_F4 GGCTACCACATCYAARGAAGGCAGCAG and 28S_R8 TCGGCAGGTGAGTYGTTRCACAYTCCT).
```
https://pubmed.ncbi.nlm.nih.gov/30824940/ 

It could be that their study focuses on animals instead of fungi but I just wanted to double check if there were any parameters that I should tweak before finding different primers. 

* [ ] provide a reproducible example

```
(base) seqkit amplicon -F GGCTACCACATCYAARGAAGGCAGCAG -R TCGGCAGGTGAGTYGTTRCACAYTCCT GCA_000146045.2_R64_genomic.fna
[INFO] 1 primer pair loaded
```

More resources: 
https://www.biostars.org/p/9549078/#9549154

[GCF_000146045.2_R64_genomic.fna.zip](https://github.com/shenwei356/seqkit/files/10299117/GCF_000146045.2_R64_genomic.fna.zip)

**Comment by shenwei356** [comment]
Sorry, I missed this post for so long.

 `seqkit amplicon` is not a specialized tool for amplicon analysis.  I wrote it mainly for extracting amplicon in short-read data.

- It allows mismatches, but the position can't be specialized. However, in PCR reactions, mismatches at 5p are less tolerate than at 3p.
- Only the longest product is returned.

**Comment by jolespin** [comment]
I actually developed some primers based on the 18S and 28S databases on NCBI.  Seqkit amplicon worked great once I actually got a good primer set.
