### ISSUE TITLE
seqkit handles empty files inconsitently

### ISSUE THREAD

**Issue by and3k** [shenwei356/seqkit#36]
Hi!

seqkit exits with 1 when getting an empty file. I use seqkit in scripts and makefiles, and sometimes the fasta files processed are empty and imho they should be treated like any file containing sequences.

seqkit also handles empty files and files just contain one newline differently:

```
$ touch file.fasta; seqkit seq file.fasta; echo $?
2018/08/01 11:34:36 EOF
1
$ echo > file.fasta; seqkit seq file.fasta; echo $?
0
```

Would be nice if the first command would exit with 0 without any messages? or to have a flag to enable this behaviour?

Thanks :)
Bela

**Comment by shenwei356** [comment]
Hi Bela,

Thanks for reporting this. It's fixed now, you can try the dev version:  [v0.8.2-dev](https://github.com/shenwei356/seqkit/releases/tag/v0.8.2-dev).

Tell me if you have more questions.

Wei

**Comment by and3k** [comment]
Works! Thanks! :)

**Comment by jwasmuth** [comment]
Sorry to reopen this, but I'm getting a segmentation fault when running seqkit (v0.9.2) stats on an empty file.

> panic: runtime error: invalid memory address or nil pointer dereference
> [signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x767eee]
> 
> goroutine 7 [running]:
> github.com/shenwei356/bio/seq.(*Alphabet).String(...)
>         /home/shenwei/shenwei/script/Go/project/src/github.com/shenwei356/bio/seq/alphabet.go:213
> github.com/shenwei356/seqkit/seqkit/cmd.glob..func24.3(0xc0001647e0, 0xc0000121c0, 0x1, 0x0, 0x839d04, 0xc, 0xc0000be780, 0xc0000a1860, 0x0, 0xc0001647d0, ...)
>         /home/shenwei/shenwei/script/Go/project/src/github.com/shenwei356/seqkit/seqkit/cmd/stat.go:375 +0xa9e
> created by github.com/shenwei356/seqkit/seqkit/cmd.glob..func24
>         /home/shenwei/shenwei/script/Go/project/src/github.com/shenwei356/seqkit/seqkit/cmd/stat.go:281 +0x8d2

Thanks
James
