### ISSUE TITLE
[Suggestion] New parameters for `seqkit rename`

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/seqkit#360]
Right now, `seqkit rename` doesn't provide users with parameters to tune how the renaming is performed. I recently had to rename duplicated headers using `|` as a field separator and needed to use `awk` for that.

Some suggestions:
- Allow custom separators (instead of just `_`).
- Allow the counter to start from an arbitrary integer (eg. `0`).
- Allow to add a suffix to all the headers, regardless if they have duplicates or not.

Those are just suggestions, so feel free to ignore them if you don't think they fit SeqKit's design.

**Comment by shenwei356** [comment]
> Allow custom separators (instead of just _)

Sure, it's easy.

> Allow the counter to start from an arbitrary integer (eg. 0).

OK

> Allow to add a suffix to all the headers, regardless if they have duplicates or not.

    seqkit replace -p '$' -r '_suffix'

**Comment by shenwei356** [comment]
Added.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/10317342/seqkit_darwin_amd64.tar.gz)
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/10317343/seqkit_darwin_arm64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/10317344/seqkit_linux_amd64.tar.gz)

There are only IDs.

    $ echo -ne ">s\na\n>s\nc\n"
    >s
    a
    >s
    c

    $ echo -ne ">s\na\n>s\nc\n" \
        | seqkit rename  -s '|' -N 0  \
        | seqkit replace -p '$' -r _suffix
    >s_suffix
    a
    >s|0_suffix
    c
    
There are IDs and descriptions.

    
    $ echo -ne ">s a\na\n>s b\nc\n"
    >s a
    a
    >s b
    c
    
    $ echo -ne ">s a\na\n>s b\nc\n" \
        | seqkit rename  -s '|' -N 0 \
        | seqkit seq -i \
        | seqkit replace -p '$' -r _suffix
    >s_suffix
    a
    >s|0_suffix
    c

**Comment by apcamargo** [comment]
Thank you! That was really quick!

> Allow to add a suffix to all the headers, regardless if they have duplicates or not.

By that I meant the suffix with the counter. So, in your example, it would be something like this:

```
>s|0
a
>s|1
c
```

**Comment by shenwei356** [comment]
I see, we can add another flag to add a count to the first record.

**Comment by shenwei356** [comment]
Three flags added:

```
  -1, --rename-1st-rec      rename the first record as well
  -s, --separator string    separator between original ID/name and the counter (default "_")
  -N, --start-num int       starting count number for *duplicated* IDs/names, should be greater than zero (default 2)
```

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/10317566/seqkit_darwin_amd64.tar.gz)
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/10317567/seqkit_darwin_arm64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/10317568/seqkit_linux_amd64.tar.gz)


```
$ echo -ne ">s a\na\n>s b\nc\n>s2\ng\n"
>s a
a
>s b
c
>s2
g

# default
$ echo -ne ">s a\na\n>s b\nc\n>s2\ng\n"    \
    | seqkit rename  
>s a
a
>s_2 b
c
>s2
g

$ echo -ne ">s a\na\n>s b\nc\n>s2\ng\n"   \
    | seqkit rename  -s '|' -N 1 -1
>s|0 a
a
>s|1 b
c
>s2|0
g
```

**Comment by apcamargo** [comment]
Thanks!!
