### ISSUE TITLE
support bzip2 compression

### ISSUE THREAD

**Issue by nick-youngblut** [shenwei356/seqkit#361]
As stated in the README:

> Supporting (gzip/xz/zstd compressed) STDIN/STDOUT and input/output file, easily integrated in pipe

Given that bzip2 is so common for bioinformatics, it would be helpful if bzip2 was also supported.

**Comment by shenwei356** [comment]
Yes, you're right.

**Comment by shenwei356** [comment]
The only Golang package support both bzip2 compression and decompression: https://github.com/dsnet/compress/tree/master/bzip2

**Comment by nick-youngblut** [comment]
Time to switch to Rust (https://docs.rs/bzip2/latest/bzip2/)?? 😜 

Users can always just pipe the data in. For instance, I'm using `bzip2 -d -c read.fq.bz2 | seqkit sample -n 50000 -`

**Comment by shenwei356** [comment]
It's supported now. And also added a flag `--compress-level` to set the compression level , see https://github.com/shenwei356/seqkit/issues/320#issuecomment-1468002060
