### ISSUE TITLE
Convert multiple fastq.gz files to fasta.gz 

### ISSUE THREAD

**Issue by nsgarcia27** [shenwei356/seqkit#362]
Hello, 

This is not really a bug or a problem, but I wonder if it is possible to convert about 100 fastq.gz files to fasta.gz files in just one command instead of converting them one by one.

Thanks!

Nelson

### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [ ] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [ ] provide a reproducible example

**Comment by shenwei356** [comment]
seqkit fq2fa --infile-list <(find dir/ -name "*.fastq.gz") -o out.fasta.gz

**Comment by nsgarcia27** [comment]
Thank you!
