### ISSUE TITLE
seqkit sort and seqkit grep take > 70 GB of working memory

### ISSUE THREAD

**Issue by MelinaKlostermann** [shenwei356/seqkit#363]
Hi, seqkit grep and seqkit sort seem to use a lot of working memory on large files. 
Would there be a possibility to write results in between to temporay files like samtools sort or star do?

 seqkit grep -n --quiet -f names.list  file.fastq.gz

[INFO] 38015 pairs of key-value loaded
[INFO] read sequences ...
[INFO] 38015 sequences loaded
[INFO] sorting ...
[INFO] output ...

Takes around 70GB of working memory

**Comment by shenwei356** [comment]
Please run the commands below and paste the results.

Which version is used? 

    seqkit version

`seqkit grep` should not consume such a large memory. How many lines are in the names.list? 

    wc -l names.list

How long of the read length? Loading 38k short reads would not occupy 70GB of memory. 

    seqkit grep -n --quiet -f names.list file.fastq.gz | seqkit stats 

Besides, why would you like to sort FASTQ records? It's unnecessary.

**Comment by MelinaKlostermann** [comment]
Hi,
 so the list is 55.659.792 reads long ( which is around half of the complete fastq file). Maybe that many is not what the command was designed for? I am splitting up the whole fastq file in two parts based on a previous step. 

The reads are 150nt long.

The version is seqkit v2.3.0
 
 I afterwards do sort on the 55.659.792 reads from the grep. I think this is necessary before I do alignment (I use STAR for the alignment). Is it not?

Thanks a lot for you help (I am sorry I did not see you answer previously)

**Comment by shenwei356** [comment]
> I think this is necessary before I do alignment (I use STAR for the alignment). Is it not?

There's no need to sort. The order of FASTQ records is meaningless.

**Comment by MelinaKlostermann** [comment]
the complete command is
```
seqkit grep -n --quiet -f {input.non_chimeric_list} {input.fastq} > {output.fastq} && \
seqkit sort -n {output.fastq} | gzip > {output.fastq_sort}
```

**Comment by MelinaKlostermann** [comment]
Ok thanks, I will try without the sort. That should already save a lot of time and memory!

**Comment by shenwei356** [comment]
> seqkit sort -n {output.fastq} | gzip > {output.fastq_sort}

Just  for this command, there's no need to pipe data to `gzip` for compression, `seqkit xxx -o yyy.gz` is faster. Besides, it should be `xxxxxx | gzip -c > xxx.gz`.

**Comment by MelinaKlostermann** [comment]
Nice I will also leave the gzip then

**Comment by MelinaKlostermann** [comment]
The memory just for the grep is fine now! Thanks a lot!

/usr/bin/time -v seqkit grep -n --quiet -f /media/storage/home/mklostermann/projects/06_AgoCLIP_miR181/03_pipe_chimeric/results_mm10_3/results/tmp/non_chimeric/IP6_WT3_R1_001.alignMir.non_chimeric.list /media/storage/home/mklostermann/projects/06_AgoCLIP_miR181/03_pipe_chimeric/results_mm10_3/results/demultiplex/trimmed_IP6_WT3_R1_001.fastq.gz  > test.fastq
	Command being timed: "seqkit grep -n --quiet -f /media/storage/home/mklostermann/projects/06_AgoCLIP_miR181/03_pipe_chimeric/results_mm10_3/results/tmp/non_chimeric/IP6_WT3_R1_001.alignMir.non_chimeric.list /media/storage/home/mklostermann/projects/06_AgoCLIP_miR181/03_pipe_chimeric/results_mm10_3/results/demultiplex/trimmed_IP6_WT3_R1_001.fastq.gz"
	User time (seconds): 122.48
	System time (seconds): 20.97
	Percent of CPU this job got: 145%
	Elapsed (wall clock) time (h:mm:ss or m:ss): 1:38.84
	Average shared text size (kbytes): 0
	Average unshared data size (kbytes): 0
	Average stack size (kbytes): 0
	Average total size (kbytes): 0
	Maximum resident set size (kbytes): 7754552
	Average resident set size (kbytes): 0
	Major (requiring I/O) page faults: 0
	Minor (reclaiming a frame) page faults: 3788014
	Voluntary context switches: 610189
	Involuntary context switches: 425
	Swaps: 0
	File system inputs: 64056
	File system outputs: 36824104
	Socket messages sent: 0
	Socket messages received: 0
	Signals delivered: 0
	Page size (bytes): 4096
	Exit status: 0
