### ISSUE TITLE
What situations contribute to "unexpected EOF" error?

### ISSUE THREAD

**Issue by xbx-xbx-1208** [shenwei356/seqkit#366]
### Prerequisites

- [Yes] make sure you're are using the latest version by `seqkit version`
- [Yes] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [ ] describe the problem
I found the seqkit progrem report the error "unexpected EOF" when I use one HiFi sequencing data as input. However,  seqkit is normal when handling other HiFi data. So I wonder what situation can lead to this error? If there are some problems, for example in data format, in my data? 
* [ ] provide a reproducible example
* [ ] 
![image](https://user-images.githubusercontent.com/72716707/219945961-565afe31-74c6-427a-9a3e-511e69ea3699.png)

**Comment by shenwei356** [comment]
A truncated file, for example, the file downloading process corrupted unexpectedly.

**Comment by shenwei356** [comment]
Here's a way to list truncated gzip-compressed files.

```
# check sequence file integrity using seqkit, gzip -t would fail sometimes.
# rush    https://github.com/shenwei356/rush
# rush can be replaced with GNU parallel.
find ./ -name "*.gz" \
    | rush 'seqkit seq -w 0 {} > /dev/null; if [ $? -ne 0 ]; then echo {}; fi' \
    > failed.txt
```

**Comment by xbx-xbx-1208** [comment]
Thanks a lot!
