### ISSUE TITLE
seqkit amplicon minus strand co-ordinates count from end

### ISSUE THREAD

**Issue by ZacharyArdern** [shenwei356/seqkit#367]
### Describe your issue

when using seqkit amplicon, if the primers extract a negative strand feature, the co-ordinates given (with BED format) are counted from the end of the chromosome/contig. I think this is not the expected/intended behaviour, and is not the behaviour of seqkit locate. e.g.:

#
seqkit amplicon --bed -t dna -F ATGGAGATGTTGTCTGGAGCCG -R VTAYASRCRYYTAAGYTTCGCW test.txt ;

seqkit locate -d -p ATGGAGATGTTGTCTGGAGCCG test.txt ;
# 

Thank you!

[test.txt](https://github.com/shenwei356/seqkit/files/10785018/test.txt)

**Comment by shenwei356** [comment]
Yes, you're right.  It's a bug, and I've just fixed it, please help to test it. Thanks for reporting.

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/10785522/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/10785519/seqkit_darwin_arm64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/10785515/seqkit_darwin_amd64.tar.gz)




```
echo -ne ">s\nATGGAGATGTTGTCTGGAGCCG\n"  \
    | seqkit stats 
file  format  type  num_seqs  sum_len  min_len  avg_len  max_len
-     FASTA   DNA          1       22       22       22       22

echo -ne ">s\nATGGAGATGTTGTCTGGAGCCG\n"  \
    | seqkit amplicon -F TGGAG -R GGCTCC -I --bed
s       1       21      .       0       +       TGGAGATGTTGTCTGGAGCC

echo -ne ">s\nATGGAGATGTTGTCTGGAGCCG\n"  \
    | seqkit amplicon -F GGCTCC -R TGGAG -I --bed
s       1       21      .       0       -       GGCTCCAGACAACATCTCCA

```

**Comment by ZacharyArdern** [comment]
Thanks for the quick fix! I've tested it and it appears to have the correct behaviour now
