### ISSUE TITLE
how to split interleaved sequences using the seqkit

### ISSUE THREAD

**Issue by chaoyanggu** [shenwei356/seqkit#369]
I want to split interleaved sequences using the seqkit, but I do not know which module can I use. please give me some advices, thank you.

the interleaved sequence as follows:
@V300045699BL3C001R0220315937/0001_0001_0066 BX:Z:0001_0001_0066-1
AAATCATCTGCAAACTTAAGATACTTTTCTTCCTTGGTTAAGTCATACATCTGAAGAACTGCTTTAATCATACAGCCATCAATATAGTTCCACTTTGACT
+
ED*DD5?7DCF4E8C;F3EECE<;<EF0EBDEED><BEE3)>8>BDFEAEFEE0=E:BE=DFEFEDAFDFBFE?BFE4BF8+<F:@FEAFF4AF2F?EE;
@V300045699BL3C001R0220315937/0001_0001_0066 BX:Z:0001_0001_0066-1
ATATATATGTTTCCCCATATAAGTTGATAAGGAGACAGAAATAATGGACGCAGTAGTAAAGTATATTGACGGGCTTCTGGAAAAAAGCACACCAGATGCT
+
F=FFFFFFFDF=EEFFFFF<FFFEEFAGFFED2FEFFFFFFFFFFFEEFFFFFEFFFFFBFF?FFFFF2FFFEFFFFFFEF?FFCFDEFFFFFGFEFFFF
@V300045699BL4C002R0700292222/0001_0001_0066 BX:Z:0001_0001_0066-1
AACCCCATAGCTTGGCTCTACATTAGCTGCAATATATGCAAGAAGCAGCAGTATCCATATTATTCCCTGTGAAATTAATATCTTATAAACTTCTTTACCG
+
FFFFFFFFFFFFFFFFFFGFEFFFFFFAFFFFEGFEFFFFFFFFFFFFFFFFFFFFGFGFFFFFFFFFFFG?FGFFFFFGGFFFGD)FFGFFDFF>FGBG
@V300045699BL4C002R0700292222/0001_0001_0066 BX:Z:0001_0001_0066-1
CGATAATTGTATCGGTATTTATAGGAATACTGGCTTTGTTTGCAAGTGCATATATCAGCATAAGAAAATATTTCACTGGTAAGATGAATATAGTAGAAAA
+
FFFFFFF:FEFEFFFEFFBFFFFDFCEFFFFFFFFFEGFEDFFCDFEGBFFGFFFGFFFF@GFD>FFFF?FFFBGFFE=FFEFFF?FFFFFCGFFFFGFF
@V300045699BL3C005R0710766845/0001_0001_0842 BX:Z:0001_0001_0842-1
CGGGGAGCGCCCAGCGGCAAGGGGCGGGACCACCCGTCCCGACGAGCGCCCACACCATAAACTTTTTTTCGAATAAGCACACAACCGTTTTTCGAACCCT
+
FGFFFFFFGFGGFFFFFFFFFFFFFDFF>FFFFGFFFFFFFBFGEG;GFGFFGFFGFFDFFFFFDFFFFFF@FFFEFFFFFFFFFFFECFGFBFFEFGFG
@V300045699BL3C005R0710766845/0001_0001_0842 BX:Z:0001_0001_0842-1
GACCTACTCAAGCAAATCACCAGAAGCAGAGGTTTCGGCATGGGTATGTAACCCCCCCCGCCCCCAAAGGGGGAGCGACCAAACGGCAGCTTCACTCAAT
+
FFFFFFFFFFFFFFFFFFFFFFFFDFFFFDFFFFFFFFFFFFFFFGFFEFFFDFDGFGFFBFFFF@;EEEFFF;C1B<BF;FFFFF?AF>AFFEAEFEDC

**Comment by shenwei356** [comment]
seqkit split2 -p 2 xxx.fastq.gz -O output

**Comment by chaoyanggu** [comment]
I got it, thank you very much.
