### ISSUE TITLE
Split a big MSA file into smaller ones every 5000 bp

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/seqkit#37]
Hi, 
Thanks for this great tool. 

I have a large multiple sequence alignment file for 200 bacterial strains  (3.25 Mb). 
Is that possible to split this alignment file each 5000 bp
so at the end the output will be  700 alignment files for the 200 strains. 1st file from 0 to 5000, 2nd from 5001 to 10000 and so on. 

When using  `seqkit sliding  -s 5000 -W 5000 file.fasta`, the output is gathered into a single file. Also the remaining sequences, which are less than 5000 bp are ignored. 

Thanks and best regards,

**Comment by shenwei356** [comment]
hi, this can be done by 

1. adding option --greedy to keep last fragments shorter than window size. 
https://bioinf.shenwei.me/seqkit/usage/#sliding
2. spliting the output file according to the sequence ID ("_sliding:1-5000") with global option `--id-regrep '(_sliding:\d+-\d+)'`. 
https://bioinf.shenwei.me/seqkit/usage/#split
3. optionally renaming sequence IDs with seqkit replace.

**Comment by MostafaYA** [comment]
Thanks a lot for your reply and providing the example. 
This is really helpful.

**Comment by MostafaYA** [comment]
This works perfectly
