### ISSUE TITLE
seqkit-2.3.1 claims to be 2.3.0

### ISSUE THREAD

**Issue by EricDeveaud** [shenwei356/seqkit#371]
Hello, 

FYI seqkit-2.3.1 display `seqkit v2.3.0`. 

see:
```
rpm_maker://tmp > wget -q  https://github.com/shenwei356/seqkit/releases/download/v2.3.1/seqkit_linux_amd64.tar.gz
rpm_maker://tmp > tar  xf seqkit_linux_amd64.tar.gz
rpm_maker://tmp > ./seqkit version
seqkit v2.3.0
```

maybee it will worth to update cmd/version.go

regards

Eric

**Comment by shenwei356** [comment]
Yes, Eric, it's not updated. And there are more [bugs fixed and features updated](https://github.com/shenwei356/seqkit/blob/master/CHANGELOG.md) since then, you can download the newest version here: https://github.com/shenwei356/seqkit/issues/370 .

I'll tag a new version soon.
