### ISSUE TITLE
 count non-AGCT characters

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/seqkit#372]
### Prerequisites

- [X ] make sure you're are using the latest version by `seqkit version`
- [ ] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue
Hi, perhaps I missed it in the user manual. How can I use seqkit to count the non-AGCT characters in a fasta sequence file?
Thanks
* [ ] describe the problem
* [ ] provide a reproducible example

**Comment by shenwei356** [comment]
Remove `ACTG`  and count left characters:

```
$ echo -ne ">s\nactgnx\n" | seqkit replace -i -s -p 'actg' | seqkit stats 
file  format  type     num_seqs  sum_len  min_len  avg_len  max_len
-     FASTA   Protein         1        2        2        2        2
```

For known non-ACGT characters like `N`, you can count it as "gap" with custom "gap" letters.

```
 -G, --gap-letters string   gap letters (default "- .")

# check the column: sum_gap
$ echo -ne ">s\nactgnx\n" | seqkit stats -a -G n
file  format  type     num_seqs  sum_len  min_len  avg_len  max_len  Q1  Q2  Q3  sum_gap  N50  Q20(%)  Q30(%)  GC(%)
-     FASTA   Protein         1        6        6        6        6   6   6   6        1    6       0       0  33.33
```

**Comment by MostafaYA** [comment]
It did not work with the first example. Here we are: 
```
$ echo -ne ">s\nactgAGTCnx-\n" | seqkit replace -i -s -p 'actg'
>s
AGTCnx-
```

**Comment by MostafaYA** [comment]
It worked. Thanks!!
