### ISSUE TITLE
Logic for seqkit watch bin size 

### ISSUE THREAD

**Issue by bhagesh-codebeast** [shenwei356/seqkit#373]
How is the bin size calculated when we provide `-y` or `--dump` option with `-B` set to default (-1)?
every sample outputs a different number of bins, so I was curious about the logic.

Thank you in advance.

**Comment by shenwei356** [comment]
@botond-sipos writes this command, and he might tell the details.

You can also check the code here: https://github.com/botond-sipos/thist/blob/master/hist.go#L104 and here https://github.com/shenwei356/seqkit/blob/master/seqkit/cmd/watch.go#L54 . 

So the default mode is `termfit`, so it should be dynamic.

**Comment by botond-sipos** [comment]
In the "auto" and "termfit" modes the bin size is calculated by [Scott's rule](https://en.wikipedia.org/wiki/Histogram#Scott's_normal_reference_rule) by this [piece of code](https://github.com/botond-sipos/thist/blob/fc68acd52afdaf5fb93a5eb2c61ba7e575eea154/hist.go#L168).
