### ISSUE TITLE
Please bump golang.org/x/sys dependency

### ISSUE THREAD

**Issue by clausecker** [shenwei356/seqkit#378]
The version of golang.org/x/sys you ship is outdated and doesn't support some newer platforms like riscv64-freebsd.

Please update the dependency to enable a build there.  The same applies to some of your other projects, too.

**Comment by shenwei356** [comment]
Thanks for the information.  But will the update break the compatibility for some old operating systems, especially those running on the old servers?

For example: 

```
Ports
Windows
Go 1.20 is the last release that will run on any release of Windows 7, 8, Server 2008 and Server 2012. Go 1.21 will require at least Windows 10 or Server 2016.

Darwin and iOS
Go 1.20 is the last release that will run on macOS 10.13 High Sierra or 10.14 Mojave. Go 1.21 will require macOS 10.15 Catalina or later.

FreeBSD/RISC-V
Go 1.20 adds experimental support for FreeBSD on RISC-V (GOOS=freebsd, GOARCH=riscv64).
```


```
Linux
Go 1.18 requires Linux kernel version 2.6.32 or later.
```

I don't know whether the statically-linked binaries will still be affected.

**Comment by clausecker** [comment]
Hi,

I'm asking you to bump the version of a dependency, not of the Go toolchain itself.  The most recent version of `golang.org/x/sys` requires Go 1.17 to build.  That supports quite a few older operating systems than Go 1.20.  In the end, it's your choice to make.  Support old outdated operating systems or more recent platforms.

**Comment by shenwei356** [comment]
I see. Thank you Robert!

**Comment by clausecker** [comment]
Please note that this update is also needed for other projects of yours, such as csvtk.  I additionally found a portability issue in your fork of the pospop routines, which I will address separately.

**Comment by shenwei356** [comment]
Thanks for reminding me. I appreciate your kind help.
