### ISSUE TITLE
Could we ad self-update to the project

### ISSUE THREAD

**Issue by KimBioInfoStudio** [shenwei356/seqkit#379]
could we add self-update to the binary download form github relrease?
and i find this for reference https://github.com/minio/selfupdate

**Comment by shenwei356** [comment]
It's a good point. But it's unsuitable for scenarios like some analysis workflows where specific versions of tools are required to ensure reproducibility.

Updating SeqKit is easy, downloading the latest binary from Github or running `conda update -c bioconda seqkit`.
