### ISSUE TITLE
Adding a break function?

### ISSUE THREAD

**Issue by Tonny-zhou** [shenwei356/seqkit#380]
### Prerequisites

- [ ] make sure you're are using the latest version by `seqkit version`
- [ ] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [ ] describe the problem
* [ ] provide a reproducible example

Have you considered adding a "break" function to linearize circular genomes? This would help us to manipulate these genome data more conveniently.

**Comment by shenwei356** [comment]
Circular genomes, e.g., bacterial,  are usually saved as linear sequences. You may need [seqkit restart](https://bioinf.shenwei.me/seqkit/usage/#restart) to rotate the start position; this operation is similar to choosing a  position to **break** a  circular genome.

```
$ seqkit restart  -h
reset start position for circular genome

Examples

    $ echo -e ">seq\nacgtnACGTN"
    >seq
    acgtnACGTN

    $ echo -e ">seq\nacgtnACGTN" | seqkit restart -i 2
    >seq
    cgtnACGTNa

    $ echo -e ">seq\nacgtnACGTN" | seqkit restart -i -2
    >seq
    TNacgtnACG

```
