### ISSUE TITLE
[Question]: How to use seqkit replace to change fasta ids

### ISSUE THREAD

**Issue by tamuanand** [shenwei356/seqkit#381]
Hi

I am using seqkit 2.3.0 and I need to change test.fa from 

```
>seq1 name1
CCCCAAAACCCCATGATCATGGATC
>seq2 name2
CCCCAAAACCCCATGGCATCATTCA
>seq3 name3
CCCCAAAACCCCATGTTGCTACTAG
```

to  renamed_test.fa as below

```
>new_1 name1
CCCCAAAACCCCATGATCATGGATC
>new_2 name2
CCCCAAAACCCCATGGCATCATTCA
>new_3 name3
CCCCAAAACCCCATGTTGCTACTAG
```

I have a 2 column tab delimited text file called `alias.txt` as below
```
seq1    new_1
seq2    new_2
seq3    new_3
```

I am trying this below but it does not seem to work 

```
seqkit replace -p '>(.*)' -r '{kv}' -k alias.txt test.fa

seqkit replace -p '>(\S+)' -r '{kv}' -k alias.txt test.fa
```

Thanks in advance.

**Comment by shenwei356** [comment]
seqkit replace -p '^(\S+)\s+(.+)$' -r '{kv} $2' -k alias.txt test.fa

**Comment by tamuanand** [comment]
Thanks. 

A suggestion: You could add the above as example to https://bioinf.shenwei.me/seqkit/usage/#replace within Example 8 snippets

Thanks once again

**Comment by shenwei356** [comment]
Yes, I'll add it.

**Comment by shenwei356** [comment]
A more robust way (in case some headers have no descriptions at the end of ID):

    seqkit replace -p '^(\S+)(.+?)$' -r '{kv}$2' -k alias.txt test.fa

**Comment by shenwei356** [comment]
A more robust way (in case some headers have no descriptions at the end of ID):

    seqkit replace -p '^(\S+)(.+?)$' -r '{kv}$2' -k alias.txt test.fa

**Comment by tamuanand** [comment]
Couple of other suggestions to add to the docs if you find this below useful

Sometimes one might want to have the new_id and replacement_id as the fasta_id

`seqkit replace --quiet -p '^(\S+)(.+?)$' -r '{kv}|$1 $2' -k alias.txt test.fa` will produce 

```
>new_1|seq1  name1
CCCCAAAACCCCATGATCATGGATC
>new_2|seq2  name2
CCCCAAAACCCCATGGCATCATTCA
>new_3|seq3  name3
CCCCAAAACCCCATGTTGCTACTAG
```

and

`seqkit replace --quiet -p '^(\S+)(.+?)$' -r '$1|{kv}$2' -k alias.txt test.fa` will get you

```
>seq1|new_1 name1
CCCCAAAACCCCATGATCATGGATC
>seq2|new_2 name2
CCCCAAAACCCCATGGCATCATTCA
>seq3|new_3 name3
CCCCAAAACCCCATGTTGCTACTAG
```
