### ISSUE TITLE
"seqkit pair" command  for MGI sequences

### ISSUE THREAD

**Issue by kabilov** [shenwei356/seqkit#382]
If I am not confusing anything, then there is a problem when analyze  MGI/BGI data by using the "seqkit pair" command. Possibly because the read names for Ilumina and MGI are different: "1:N" vs "/1".

**Comment by shenwei356** [comment]
https://github.com/shenwei356/seqkit/issues/350#issuecomment-1325933220

**Comment by kabilov** [comment]
Thanks!
