### ISSUE TITLE
grep extract less count of sequences than ID counts provided

### ISSUE THREAD

**Issue by Shairah** [shenwei356/seqkit#383]
### Prerequisites

- [ ] make sure you're are using the latest version by `seqkit version`
- [ ] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [ ] describe the problem
* [ ] provide a reproducible example

Hi, I am using the latest seqkit version v2.4.0

When I extract Fasta sequences that match the unique ID using the ID.txt file (I have 406 lists of IDs) from my proteome.fa, grep only give me 405 files instead of 406 fa files. I am not sure why the count is less than it should be. Is this because of a bug? I have attached both ID.txt and proteome.fa files. I'd really appreciate your help.

seqkit grep -f ID.txt /path/to/directory/proteome.fa -C                              #this is to check the count of matched number
seqkit grep -p -f ID.txt /path/to/directory/proteome.fa -o Baikal_hit.faa  #this is to extract the files
[seqkit_files.zip](https://github.com/shenwei356/seqkit/files/11273634/seqkit_files.zip)

**Comment by shenwei356** [comment]
@Shairah solve it?
