### ISSUE TITLE
Feature request: Output bgzip format

### ISSUE THREAD

**Issue by maximilianmordig** [shenwei356/seqkit#385]
Can you support the bgzip format (http://www.htslib.org/doc/bgzip.html)? Currently, when I run
```
seqkit head -n 80 -o output.fasta.gz input.fasta.gz
```
and then try to open it in Python with
```
pysam.FastaFile(fasta_file)
```
it fails with
```
[E::fai_build3_core] Cannot index files compressed with gzip, please use bgzip
```

**Comment by jmonroynieto** [comment]
Already implemented by a different request #361.

**Comment by shenwei356** [comment]
@maximilianmordig Just install [htslib](https://github.com/samtools/htslib) and use `bgzip` :

    seqkit head -n 80 input.fasta.gz | bgzip -c > output.fasta.gz

@jmonroynieto  bgzip and bzip2 shall be different according to Google results.

**Comment by jmonroynieto** [comment]
Sorry about the confusion.

**Comment by fgvieira** [comment]
I would actually argue that it would make more sense to support `bgzip` natively rather `gzip`. Compression is almost the same, they are inter-compatible, and `bgzip` is turning into the standard for FASTA/Q files since it allows for indexing.
