### ISSUE TITLE
Way to "natural sort"  Fasta  with seqkit sort ?

### ISSUE THREAD

**Issue by BenoitFiset** [shenwei356/seqkit#39]
Hello,

 using version: seqkit v0.8.1

I havent figured out a way to Natural Sort fasta file with seqkit. Am I missing something ?

tried -s and -n flags with sort

Example:

```
seqkit sort -2 -n -j 8 -t dna -o Homo_sapiens.GRCh38.dna.primary_assembly_sorted.fa  Homo_sapiens.GRCh38.dna.primary_assembly.fa 
```

Gives: 

```
>1 dna:chromosome chromosome:GRCh38:1:1:248956422:1 REF
>10 dna:chromosome chromosome:GRCh38:10:1:133797422:1 REF
>11 dna:chromosome chromosome:GRCh38:11:1:135086622:1 REF
>12 dna:chromosome chromosome:GRCh38:12:1:133275309:1 REF
>13 dna:chromosome chromosome:GRCh38:13:1:114364328:1 REF
>14 dna:chromosome chromosome:GRCh38:14:1:107043718:1 REF
>15 dna:chromosome chromosome:GRCh38:15:1:101991189:1 REF
>16 dna:chromosome chromosome:GRCh38:16:1:90338345:1 REF
>17 dna:chromosome chromosome:GRCh38:17:1:83257441:1 REF
>18 dna:chromosome chromosome:GRCh38:18:1:80373285:1 REF
>19 dna:chromosome chromosome:GRCh38:19:1:58617616:1 REF
>2 dna:chromosome chromosome:GRCh38:2:1:242193529:1 REF
>20 dna:chromosome chromosome:GRCh38:20:1:64444167:1 REF
>21 dna:chromosome chromosome:GRCh38:21:1:46709983:1 REF
>22 dna:chromosome chromosome:GRCh38:22:1:50818468:1 REF
>3 dna:chromosome chromosome:GRCh38:3:1:198295559:1 REF
>4 dna:chromosome chromosome:GRCh38:4:1:190214555:1 REF
>5 dna:chromosome chromosome:GRCh38:5:1:181538259:1 REF
>6 dna:chromosome chromosome:GRCh38:6:1:170805979:1 REF
>7 dna:chromosome chromosome:GRCh38:7:1:159345973:1 REF
>8 dna:chromosome chromosome:GRCh38:8:1:145138636:1 REF
>9 dna:chromosome chromosome:GRCh38:9:1:138394717:1 REF
```

When I want:

```
>1 dna:chromosome chromosome:GRCh38:1:1:248956422:1 REF
>2 dna:chromosome chromosome:GRCh38:2:1:242193529:1 REF
>3 dna:chromosome chromosome:GRCh38:3:1:198295559:1 REF
>4 dna:chromosome chromosome:GRCh38:4:1:190214555:1 REF
>5 dna:chromosome chromosome:GRCh38:5:1:181538259:1 REF
>6 dna:chromosome chromosome:GRCh38:6:1:170805979:1 REF
>7 dna:chromosome chromosome:GRCh38:7:1:159345973:1 REF
>8 dna:chromosome chromosome:GRCh38:8:1:145138636:1 REF
>9 dna:chromosome chromosome:GRCh38:9:1:138394717:1 REF
>10 dna:chromosome chromosome:GRCh38:10:1:133797422:1 REF
>11 dna:chromosome chromosome:GRCh38:11:1:135086622:1 REF
>12 dna:chromosome chromosome:GRCh38:12:1:133275309:1 REF
>13 dna:chromosome chromosome:GRCh38:13:1:114364328:1 REF
>14 dna:chromosome chromosome:GRCh38:14:1:107043718:1 REF
>15 dna:chromosome chromosome:GRCh38:15:1:101991189:1 REF
>16 dna:chromosome chromosome:GRCh38:16:1:90338345:1 REF
>17 dna:chromosome chromosome:GRCh38:17:1:83257441:1 REF
>18 dna:chromosome chromosome:GRCh38:18:1:80373285:1 REF
>19 dna:chromosome chromosome:GRCh38:19:1:58617616:1 REF
>20 dna:chromosome chromosome:GRCh38:20:1:64444167:1 REF
>21 dna:chromosome chromosome:GRCh38:21:1:46709983:1 REF
>22 dna:chromosome chromosome:GRCh38:22:1:50818468:1 REF
```

What am I missing ?

Thanks,

B.

**Comment by shenwei356** [comment]
It's not directly supported, but you can ultilize the `seqkit faidx`:

    $ cat t.fasta 
    >1 dna:chromosome chromosome:GRCh38:1:1:248956422:1 REF
    a
    >10 dna:chromosome chromosome:GRCh38:10:1:133797422:1 REF
    a
    >11 dna:chromosome chromosome:GRCh38:11:1:135086622:1 REF
    a
    >2 dna:chromosome chromosome:GRCh38:2:1:242193529:1 REF
    a
    >20 dna:chromosome chromosome:GRCh38:20:1:64444167:1 REF
    a
    >21 dna:chromosome chromosome:GRCh38:21:1:46709983:1 REF
    a
    >3 dna:chromosome chromosome:GRCh38:3:1:198295559:1 REF
    a
    >X dna:chromosome chromosome:GRCh38:9:1:138394717:1 REF 
    a
    >4 dna:chromosome chromosome:GRCh38:9:1:138394717:1 REF 
    a

Retrieve the IDs and sort.

    $ seqkit seq -n -i t.fasta | sort -k1,1n | tee ids.txt
    X
    1
    2
    3
    4
    10
    11
    20
    21

    $ seqkit faidx --full-head t.fasta $(paste -s -d ' ' ids.txt)  
    >X dna:chromosome chromosome:GRCh38:9:1:138394717:1 REF 
    a
    >1 dna:chromosome chromosome:GRCh38:1:1:248956422:1 REF
    a
    >2 dna:chromosome chromosome:GRCh38:2:1:242193529:1 REF
    a
    >3 dna:chromosome chromosome:GRCh38:3:1:198295559:1 REF
    a
    >4 dna:chromosome chromosome:GRCh38:9:1:138394717:1 REF 
    a
    >10 dna:chromosome chromosome:GRCh38:10:1:133797422:1 REF
    a
    >11 dna:chromosome chromosome:GRCh38:11:1:135086622:1 REF
    a
    >20 dna:chromosome chromosome:GRCh38:20:1:64444167:1 REF
    a
    >21 dna:chromosome chromosome:GRCh38:21:1:46709983:1 REF
    a

If you want the X at the end, you can manually change the order.

    $ seqkit faidx --full-head t.fasta $(seq 1 22) X Y
    [WARN] sequence not found: 5
    [WARN] sequence not found: 6
    [WARN] sequence not found: 7
    [WARN] sequence not found: 8
    [WARN] sequence not found: 9
    [WARN] sequence not found: 12
    [WARN] sequence not found: 13
    [WARN] sequence not found: 14
    [WARN] sequence not found: 15
    [WARN] sequence not found: 16
    [WARN] sequence not found: 17
    [WARN] sequence not found: 18
    [WARN] sequence not found: 19
    [WARN] sequence not found: 22
    [WARN] sequence not found: Y
    >1 dna:chromosome chromosome:GRCh38:1:1:248956422:1 REF
    a
    >2 dna:chromosome chromosome:GRCh38:2:1:242193529:1 REF
    a
    >3 dna:chromosome chromosome:GRCh38:3:1:198295559:1 REF
    a
    >4 dna:chromosome chromosome:GRCh38:9:1:138394717:1 REF 
    a
    >10 dna:chromosome chromosome:GRCh38:10:1:133797422:1 REF
    a
    >11 dna:chromosome chromosome:GRCh38:11:1:135086622:1 REF
    a
    >20 dna:chromosome chromosome:GRCh38:20:1:64444167:1 REF
    a
    >21 dna:chromosome chromosome:GRCh38:21:1:46709983:1 REF
    a
    >X dna:chromosome chromosome:GRCh38:9:1:138394717:1 REF 
    a

**Comment by BenoitFiset** [comment]
Hi,

 what you are saying, before you implement natural sort in seqkit, is that I create an ID file and use this ID file to extract via faidx ?

**Comment by BenoitFiset** [comment]
Hi,

This doesn't sort natural way.... Letters arrive before numbers
```
seqkit seq -n -i t.fasta | sort -k1,1n | tee ids.txt
```
using awk and adding the sort -V does the trick
```
seqkit seq -n -i Homo_sapiens.GRCh38.dna.primary_assembly.fa | awk -F" " '{print $1}' | sort -V  > ids.txt
```

**Comment by shenwei356** [comment]
Hi Benoit , you can do this with option `-N/--natural-order` now ([v0.9.0-dev2](https://github.com/shenwei356/seqkit/releases/tag/v0.9.0-dev2))

```
seqkit sort -N -i -2   seqs.fa -o seqs.sorted.fa.gz
```

Example:

```
$ echo -e ">3\n>1\n>Y\n>x\n>Mt\n>11\n>2\n"
>3
>1
>Y
>x
>Mt
>11
>2

$ echo -e ">3\n>1\n>Y\n>x\n>Mt\n>11\n>2\n" | seqkit sort -N -i
>1

>2

>3

>11

>Mt

>x

>Y

```

**Comment by BenoitFiset** [comment]
Hello,

  Nice.... works well. Thanks for the new version.

B.
