### ISSUE TITLE
seqkit subseq ­- accept reverse coordinates in gtf

### ISSUE THREAD

**Issue by stas-malavin** [shenwei356/seqkit#392]
Hello,
It makes sense to me if ```seqkit subseq``` would accept reverse coordinates (```530 2```) in ```gtf``` (and also probably ```bed```, though I haven't tried that option).
In my scenario, I build ```gtf``` from ```hmmscan``` results, and some seqs in the initial DB are on the strand 2, hence reversed coordinates. I'm replacing them, but anyway, why not accepting as it is?
Thank you

**Comment by shenwei356** [comment]
I'll implement this later  (>1-2 week(s)).

**Comment by shenwei356** [comment]
Oh, I forgot to tell you that it was implemented last week.

**Comment by stas-malavin** [comment]
Perfect, thanks so much! :)
