### ISSUE TITLE
[stats] N90, N95, N99, NXX

### ISSUE THREAD

**Issue by fgvieira** [shenwei356/seqkit#393]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

Similar to issue #34 , it would be nice to also be able to calculate (apart from `N50`) `N90`/`N95`/`N99`/`N99.9`/...
Would it be possible to add an option to specify the `NXX` number (default to 50)? Ideally, it would take a CSV string of values (e.g.) `50,75,95,99,99.9` and give:
```
$ seqkit stats *.f{a,q}.gz -a
file               format  type  num_seqs    sum_len  min_len  avg_len  max_len   Q1   Q2   Q3  sum_gap  N50  N75  N95  N99  N99.9   Q20(%)  Q30(%)  GC(%)
```

**Comment by shenwei356** [comment]
You can use the [assembly-stats](https://github.com/sanger-pathogens/assembly-stats) at this moment.

**Comment by fgvieira** [comment]
But how can you specify an arbitrary value for N? For example, `N99.9`?

**Comment by fgvieira** [comment]
In the end, what I am looking for, is a way to remove sequences that are shorter than `NXX`, so a `seqkit seq --min-len N99.9` command would be awesome!
But I understand if it is too much work... a `seqkit stats -N 99.9` followed by `seqkit seq --min-len <some_value>` would also work.

**Comment by shenwei356** [comment]
Added a new flag

```
  -N, --N strings            other N50-like stats. value range [0, 100], multiple values supported,
                             e.g., -N 50,90 or -N 50 -N 90
```

```
[shenwei@mBio tests]$ seqkit stats hairpin.fa
file        format  type  num_seqs    sum_len  min_len  avg_len  max_len
hairpin.fa  FASTA   RNA     28,645  2,949,871       39      103    2,354

[shenwei@mBio tests]$ seqkit stats hairpin.fa -N 50,90,99.999
file        format  type  num_seqs    sum_len  min_len  avg_len  max_len  N50  N90  N99.999
hairpin.fa  FASTA   RNA     28,645  2,949,871       39      103    2,354  101   69       39

[shenwei@mBio tests]$ seqkit stats hairpin.fa -N 50,90,99.999 -a 
file        format  type  num_seqs    sum_len  min_len  avg_len  max_len  Q1  Q2   Q3  sum_gap  N50  Q20(%)  Q30(%)  GC(%)  N50  N90  N99.999
hairpin.fa  FASTA   RNA     28,645  2,949,871       39      103    2,354  76  91  111        0  101       0       0  45.77  101   69       39

$ seqkit stats hairpin.fa -N 50,90,99.999 -T | csvtk pretty -t -S bold
┏━━━━━━━━━━━━┳━━━━━━━━┳━━━━━━┳━━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━━━━━┳━━━━━┳━━━━━┳━━━━━━━━━┓
┃ file       ┃ format ┃ type ┃ num_seqs ┃ sum_len ┃ min_len ┃ avg_len ┃ max_len ┃ N50 ┃ N90 ┃ N99.999 ┃
┣━━━━━━━━━━━━╋━━━━━━━━╋━━━━━━╋━━━━━━━━━━╋━━━━━━━━━╋━━━━━━━━━╋━━━━━━━━━╋━━━━━━━━━╋━━━━━╋━━━━━╋━━━━━━━━━┫
┃ hairpin.fa ┃ FASTA  ┃ RNA  ┃ 28645    ┃ 2949871 ┃ 39      ┃ 103.0   ┃ 2354    ┃ 101 ┃ 69  ┃ 39      ┃
┗━━━━━━━━━━━━┻━━━━━━━━┻━━━━━━┻━━━━━━━━━━┻━━━━━━━━━┻━━━━━━━━━┻━━━━━━━━━┻━━━━━━━━━┻━━━━━┻━━━━━┻━━━━━━━━━┛
```

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/11934457/seqkit_darwin_amd64.tar.gz)
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/11934460/seqkit_darwin_arm64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/11934461/seqkit_linux_amd64.tar.gz)
