### ISSUE TITLE
SeqKit rmdup for RefSeq

### ISSUE THREAD

**Issue by SergeyBaikal** [shenwei356/seqkit#394]
version 2.3.0

Dear Developers. Could you clarify please. How seqkit removes duplicates by default? I want to make the RefSeq database not redundant. What settings should I apply?
I ran the test and it seems to remove only those sequences that have the same id. Is that correct?

`seqkit rmdup -d duplicated.fasta -D duplicated.detail.txt Refseq_all_2023_prot_218.fasta > Refseq_all_2023_prot_218_uniq.fasta `

**Comment by shenwei356** [comment]
> it seems to remove only those sequences that have the same id.

Yes. You may add the flags `--by-seq` and `--ignore-case`.

```
  -n, --by-name                by full name instead of just id
  -s, --by-seq                 by seq

  -i, --ignore-case            ignore case

```

**Comment by SergeyBaikal** [comment]
Thank you!
