### ISSUE TITLE
Default to not removing ‘*’ for seqkit sum of peptides?

### ISSUE THREAD

**Issue by photocyte** [shenwei356/seqkit#399]
Related to: https://github.com/shenwei356/seqkit/pull/397

Currently seqkit defaults to removing the stop codon when checksumming proteins with ‘sum’. Shouldn’t the default be to *not* remove the stop codon, to prevent the unexpected behavior of distinct files (all no stop codon & all with stop codon) from having the same checksum? I agree that it is a very useful feature to remove the stop codon, but, I feel it should be a flag/switch rather than the default.

it’s also unclear how the behavior would deal with internal stop codons, and those definitely shouldn’t be removed by default.

Thanks again for making seqkit!
-Tim

**Comment by shenwei356** [comment]
You're right. I agree.

**Comment by shenwei356** [comment]
Please don't hesitate to tell me if there's any issue.
[seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/12060474/seqkit_linux_amd64.tar.gz)
