### ISSUE TITLE
using seqkit locate for k-mer counting

### ISSUE THREAD

**Issue by MortenEneberg** [shenwei356/seqkit#401]
Hi Wei,

Thanks for an excellent tool! I am computing dinucleotide frequencies for a large set of genomes (>300 gigabases in total) and have found that seqkit locate is the only tool to output the statistics for each fasta sequence in a multi fasta file doing something like this:

`cat file.fasta | seqkit locate -i -f motifs.fa | csvtk -t freq -k -f 1,2 > output.tsv`

where motifs.fa is simply a fasta file with all the 16 dinucleotides

However, it is fairly slow because it computes the exact location of the 2-mer - does seqkit have an implementation where the fasta header is tracked without the specific genomic locations (as to make it faster)? 

Sincerely, Morten

**Comment by shenwei356** [comment]
<s>You may use some dedicated k-mer counting tools like [KMC3](https://github.com/refresh-bio/KMC) or [DSK](https://github.com/GATB/dsk).</s>

> a large set of genomes
Small genomes like Bacteria, or big genomes like humans?

How about splitting the file into individual files, each with one genome, and counting k-mers for each genome with some k-mer counting tools?

Did you aim to find group-specific k-mers? Some tools are available, like [kmdiff](https://github.com/tlemane/kmdiff
), [Kevlar](https://github.com/kevlar-dev/kevlar).

Also have a look at [kmtricks](https://github.com/tlemane/kmtricks).

**Comment by MortenEneberg** [comment]
Hi Wei, thanks for getting back. I ended up solving it similarly to your suggestion by processing the files separately and using jellyfish for k-mer counting. Thanks for your suggestion!
