### ISSUE TITLE
Locate memory usage

### ISSUE THREAD

**Issue by mbhall88** [shenwei356/seqkit#402]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

I was trying to use `locate` to find exact matches for 25 7-mers in the human genome but ran out of memory (40GB). Is this expected? And if so, how come it uses so much memory when the human genome is ~3GB?

Here's an example of the command I used

```
seqkit locate -f top25.fa -V 0 -F -M ../h37rv.fa -m 0 --bed
```

**Comment by shenwei356** [comment]
I think it's due to the FM Index occupying too much memory, which is not highly optimized for big genomes. You can try removing `-F`, which should use lesser RAM.

Besides, `-V 0` is not necessary, which check the whole sequences before computing reverse complement sequences.

**Comment by mbhall88** [comment]
Wow that made a big difference - only 2.6GB now. Thanks as always for the awesome tools @shenwei356
