### ISSUE TITLE
Remove reads with certain amount of ambiguous bases

### ISSUE THREAD

**Issue by mbhall88** [shenwei356/seqkit#403]
Hey @shenwei356. For nearly all tasks I assume there is probably some way of using seqkit, so I was wondering if you could help me figure out how to use seqkit to do something. I want to remove reads with more than a certain proportion of ambiguous (non-ACGT) bases. Can seqkit be used for this?

**Comment by shenwei356** [comment]
https://bioinf.shenwei.me/seqkit/usage/#fx2tab-tab2fx

     -B, --base-content strings   print base content. (case ignored, multiple values supported) e.g. -B AT -B N

 ```
seqkit fx2tab -B ACGT input.fq.gz \
    | awk '$4 > 95' \
    | seqkit tab2fx -o out.fq.gz
```

**Comment by mbhall88** [comment]
Unreal!! You are awesome!
