### ISSUE TITLE
Possible bug in seqkit stats

### ISSUE THREAD

**Issue by hpsubramanian** [shenwei356/seqkit#405]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
```
seqkit version
seqkit v2.5.0
```

- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem

Hello! For a given "n" fastq files, seqkit stats output does not contain information for all files provided as input. The output also contains duplicate entries.

* [x] provide a reproducible example
#### Reproducible example

1. Sample FASTQ file
```
cat A_R1.fastq 
@M01234:567:000000000-L8MMM:1:1101:14508:1394 1:N:0:CAGGTTCA+TATCCTCT
ACCGGTTGATGTGATGGGAGCCCTTCTTCTTCTGCTCGGACTCAGGCCCTTCCTCCTCCAGCTTCTGCCGTTTGTACTTTGTCCTCCGGTTCTGGAACCACACCTTCACCTGGGCCAGGGAGGGAGGGGCACAGATGAGAAA
+
AAAA3>A>CDF5FADGBACFGEFFEFFGHFGFGBDAGA?E?EHFHBBEEGGBCFGCHHHEHHFGGG5GHEEEHGHHGHHFBGFHHHEECEEGHGBHHHGHGF>AFF3E?3B?0?/?/FGECFCCAECCC?@BG01F<1?1<<
```

3. Make copies of the FASTQ file
```
for i in B C D E F G H; do cp A_R1.fastq ${i}_R1.fastq; done

wc -l *fastq
   4 A_R1.fastq
   4 B_R1.fastq
   4 C_R1.fastq
   4 D_R1.fastq
   4 E_R1.fastq
   4 F_R1.fastq
   4 G_R1.fastq
   4 H_R1.fastq
  32 total
```

4. Run seqkit stats on all files
```
seqkit stats -T *R1*fastq > output.txt
processed files:  8 / 8 [======================================] ETA: 0s. done
```

5. The results table does not have an entry for B_R1.fastq. H_R1.fastq is present twice.
```
cat output.txt 
file    format  type    num_seqs        sum_len min_len avg_len max_len
A_R1.fastq      FASTQ   DNA     1       142     142     142.0   142
C_R1.fastq      FASTQ   DNA     1       142     142     142.0   142
D_R1.fastq      FASTQ   DNA     1       142     142     142.0   142
G_R1.fastq      FASTQ   DNA     1       142     142     142.0   142
E_R1.fastq      FASTQ   DNA     1       142     142     142.0   142
F_R1.fastq      FASTQ   DNA     1       142     142     142.0   142
H_R1.fastq      FASTQ   DNA     1       142     142     142.0   142
H_R1.fastq      FASTQ   DNA     1       142     142     142.0   142
```

Thank you!

**Comment by shenwei356** [comment]
Hi @hpsubramanian, thank you for reporting this, it is a bug newly introduced in v2.5.0. Please use binaries below, currently.

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/12272265/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/12272264/seqkit_darwin_arm64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/12272263/seqkit_darwin_amd64.tar.gz)

**Comment by hpsubramanian** [comment]
Thanks for your quick fix!
