### ISSUE TITLE
Allow grep to handle pair suffix in ID

### ISSUE THREAD

**Issue by mbhall88** [shenwei356/seqkit#406]
There probably is already a way to do this and I am just missing it but I would like to use `seqkit grep` to extract reads from a fastq from a file of IDs. BUT my file of IDs don't have `/1` or `/2` at the end, however the read IDs in the fastq do. It would be cool to have an option to ignore the last two character of the ID (or maybe something a little more flexible) when matching on ID.

#### Example

Read IDs

```
foo1
bar
```

fastq

```
@foo1/1
ACGT
+
!!!!
@foo11/1
ACGT
+
!!!!
```

I would only want the first read.

I don't want to use the option to treat the pattern as a regex as in my use case the IDs have regex special characters in them.

**Comment by shenwei356** [comment]
Please use the global option `--id-regexp`.

```
$ seqkit grep --id-regexp '^(\S+)/[12]' -f id.txt seqs.fastq 
[INFO] 2 patterns loaded from file
@foo1/1
ACGT
+
!!!!
```

ref:  https://bioinf.shenwei.me/seqkit/usage/#sequence-id

**Comment by mbhall88** [comment]
As always, love your work @shenwei356! Apologies for not spotting this option.
