### ISSUE TITLE
Fast way to run seqkit locate

### ISSUE THREAD

**Issue by arslan9732** [shenwei356/seqkit#407]
I am using seqkit to get the location of Ns from the hard-masked genome file (genome size 3.02Gb). The command is:
```
seqkit locate --bed -rPp "N+" Genome-hmsk.fasta > N_coords.bed
```
The problem is, it only uses 1 thread and is very slow. Is there any way to make it multithreaded, or process the file faster?

**Comment by shenwei356** [comment]
Sorry, it's not parallelized. I might optimize it in the future.

By the way, please switch the flag `-G` to avoid outputting overlap regions, which can also speed up slightly.

      -G, --non-greedy                non-greedy mode, faster but may miss motifs overlapping with others
