### ISSUE TITLE
Exit status 141 running sample and head

### ISSUE THREAD

**Issue by jervermex** [shenwei356/seqkit#410]
### Prerequisites

- [ x] make sure you're are using the latest version by `seqkit version`
- [ x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [ ] describe the problem
I'm trying to make a sample of a huge fasta file. As comented in the online documentation, u use the recomendation of a pipe command:
$ seqkit sample -j 2  -2 -p 0.5 huge-nt.fasta.gz |  ~/seqkit  head -j 4 -n 100000 -o  sample.fasta.gz

The command get me back a sample.fasta.gz file, with 100000 sequence. The problem is this piped commands generate a exit status 141. As it's running on a cluster, my script don't follow with other stuff, as i decide to stop anyt script that generate an error.

If i don this sample in 2 steps, with an intermediary file, all run well.

That's not very annoying, just strange...

Regards

**Comment by shenwei356** [comment]
It's interesting, and I've never met this. But it looks common in shell pipes.

refs:

- https://github.com/jqlang/jq/issues/1017
- https://stackoverflow.com/questions/19120263/why-exit-code-141-with-grep-q
- http://www.greenend.org.uk/rjk/tech/shellmistakes.html#pipeerrors

I guess your script sets `set -o pipefail`, you can remove it and try again. If not, try add a line `set +o pipefail`.

```
$ seq 100000 | head -n 1; echo $?". "${PIPESTATUS[@]}
1
0. 141 0


$ set -o pipefail
$ seq 100000 | head -n 1; echo $?". "${PIPESTATUS[@]}
1
141. 141 0

```
