### ISSUE TITLE
Add subseq selected coordinates to FASTA?

### ISSUE THREAD

**Issue by photocyte** [shenwei356/seqkit#413]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

Hi there,

It would be useful for `subseq` to have a flag where it would add the coordinates of the selected region to the FASTA record description.

E.g. if subseq were run with `-r 14:14` it would add `SEQID:14-14` to the end of the FASTA description. It would ideally work with GTF/GFF & BED defined regions as well, but would need to change from 0-indexing to 1-indexing in the case of BED.

I briefly looked and the analogous command to `subseq` in `seqtk` does not have this feature. `bedtools getfasta `implements this behavior by default.

All the best,
-Tim

**Comment by shenwei356** [comment]
Added one.

```
  -R, --region-coord      append coordinates to sequence ID for -r/--region
```
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/12768792/seqkit_darwin_arm64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/12768793/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/12768789/seqkit_darwin_amd64.tar.gz)


```
$ seqkit head -n 1 ../tests/hairpin.fa 
>cel-let-7 MI0000001 Caenorhabditis elegans let-7 stem-loop
UACACUGUGGAUCCGGUGAGGUAGUAGGUUGUAUAGUUUGGAAUAUUACCACCGGUGAAC
UAUGCAAUUUUCUACCUUACCGGAGACAGAACUCUUCGA

$ seqkit head -n 1 ../tests/hairpin.fa \
    | ./seqkit subseq -r 1:10 -R
>cel-let-7:1-10 MI0000001 Caenorhabditis elegans let-7 stem-loop
UACACUGUGG
```
