### ISSUE TITLE
Retrieve the nucleotide sequences initially used from the SeqIDs of the protein sequences (question)

### ISSUE THREAD

**Issue by silvia1234567890** [shenwei356/seqkit#415]
Hello,
I have a nucleotide.fasta file with lot of sequences, which I translated to amino acid sequences with all frames using "seqkit translate". Then I filter these sequences into "productive" and "non productive".

Using Seqkit, is there any way to retrieve the nucleotide sequences initially used of the "non productive" amino acid sequences? maybe using the SeqIDs? The problem is that the SeqID is not the same, as long as, in the protein.fasta file has the frame added at the end, and there are no blanks in the SeqIDs.

Example of SeqIDs in both files:

nucleotide.fasta

```
>GAACACGAAGGACGC|PRCONS=Primer_Read1_Rod_Cmu|SEQORIENT=F|CREGION=Inner_Scomax_Cmu|CONSCOUNT=19|DUPCOUNT=8
```

protein.fasta

```
>GAACACGAAGGACGC|PRCONS=Primer_Read1_Rod_Cmu|SEQORIENT=F|CREGION=Inner_Scomax_Cmu|CONSCOUNT=19|DUPCOUNT=8_frame=1
```

I used:

`seqkit seq nonprod_seq.fasta -n -o nonproductiveIDs.txt`

to extract the IDs. And then, I used:

`seqkit grep -f nonproductiveIDs.txt nucleotide.fasta -o nonprodnucl.fasta`

to extract the file with the nucleotide sequences, but I just get this message on the command line:

`[INFO] 608703 patterns loaded from file`

The number of sequences is correct, but the output file "nonprodnucl.fasta" is empty. 
Could you help me please?

Thank you in advance

**Comment by shenwei356** [comment]
You can use the option `--id-regexp` to specify the IDs for matching.

    seqkit grep -f nonproductiveIDs.txt nucleotide.fasta -o nonprodnucl.fasta  --id-regexp '^(.+)_frame='

**Comment by shenwei356** [comment]
> [INFO] 608703 patterns loaded from file

It just shows how many patterns are loaded.

The key problem is that these patterns have suffixes like `_frame=1`, which do not exist in the sequence file. So, we need to remove these suffixes before searching.

    seqkit grep -f <(perl -pne  's/_frame\=\d+$//' nonproductiveIDs.txt) nucleotide.fasta -o nonprodnucl.fasta

> Is it okay to use -o for the output files?

It is.

**Comment by silvia1234567890** [comment]
Oh, I understand.
I would like like to create the IDs.txt with the first 15 characters of the headers, because that sequences is an UMI and it's unique for every sequence. How could I do it?

**Comment by silvia1234567890** [comment]
and to create the IDs.txt with the full header except the `_frame= ` (example) part? How could I do it?

**Comment by shenwei356** [comment]
Well, you can just simply combine the methods above.

    seqkit seq nonprod_seq.fasta -n | perl -pne  's/_frame\=\d+$//' > IDs.txt

**Comment by silvia1234567890** [comment]
Hello, I ran this code:
`seqkit seq nonproductive_seqs.fasta -ni --id-regexp 's/_frame\=\d+$//' -o IDs.txt`
 and I'm getting this error:
`[ERRO] fastx: regular expression must contain "(" and ")" to capture matched ID. default: ^(\S+)\s?`

**Comment by shenwei356** [comment]
https://github.com/shenwei356/seqkit/issues/415#issuecomment-1744820386
