### ISSUE TITLE
Feature request: clustering

### ISSUE THREAD

**Issue by stas-malavin** [shenwei356/seqkit#420]
Hi Wei, have you ever thought of implementing clustering?

**Comment by shenwei356** [comment]
Not really. It's not easy, and there are some existing great tools.

What kind of clustering do you need?

**Comment by stas-malavin** [comment]
I need to reduce the volume of the sequence set; cluster at, say, 95% and take representatives of each cluster.
I usually use CD-HIT for that, but as seqkit (+taxonkit +csvtk) is gradually becoming my every-day Switzerland knife, I thought maybe there's some smart library in Go devoted to sequence clustering that makes implementing this easy.

**Comment by shenwei356** [comment]
It's a very complicated wheel to reinvent. :rofl:
