### ISSUE TITLE
Genbank to fasta?

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/seqkit#426]
### Prerequisites

- [ ] make sure you're are using the latest version by `seqkit version`
- [ ] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue
Hi, 
Would `seqkit` may be support the conversion of genbank / embl file into fasta format? 
Thanks

* [ ] describe the problem
* [ ] provide a reproducible example

**Comment by shenwei356** [comment]
You might try this: https://github.com/tseemann/any2fasta

**Comment by MostafaYA** [comment]
I am aware of it. I thought it might be easy to have this implemented in `seqkit` as a new subcommand, so that I have all what I need in this tool!
