### ISSUE TITLE
any good method to extract sequences from a MAS file?

### ISSUE THREAD

**Issue by BEAST-Community** [shenwei356/seqkit#430]
Dear @shenwei356,

Do you have any good suggestions on how to extract  sequences from a big MAS file, thanks.

**Comment by shenwei356** [comment]
Hi, I'm not sure if I understand correctly on the file type and the way you want to extract.

Is this tool what you want?
https://emboss.sourceforge.net/apps/release/6.0/emboss/apps/extractalign.html

**Comment by shenwei356** [comment]
Please provide more information.
1. Which version of SeqKit are you using?

        seqkit version

3. How big is the file? Please pate the result of

        ls -lh read_1.fq.gz

4. (optional) How many sequences are in the file

       seqkit stats read_1.fq.gz

5. Does the sequence ID in `IDs.txt` match the format in sequence files?

        head -n 5 IDs.txt

        seqkit seq -n  read_1.fq.gz | head -n 5

**Comment by shenwei356** [comment]
Well, you need to decompress the tarball file first.

    tar -xf xxx.tar.xz

**Comment by shenwei356** [comment]
Are you @BEAST-Community @liamxg the same person?

Shells kill a command mostly when the command exhausts the memory. But `seqkit stats` is memory efficient. So it's kind of strange. According to the previous comments, I guess you are a beginner. So Please always provide as much information as you can. I can't help with limited information.  Or it's just a waste of time for you and me.

1. What's the size of the msa.fa?

        ls -lh msa.fa

2. How many memory do you have?

        free -h

3. Show some lines of the file

        head -n 5 msa.fa

4. I'm even curious on what the file is

        file msa.fa

**Comment by shenwei356** [comment]
OMG, that must be millions of SARS-COV-2 sequences. Though they are aligned, seqkit should have no problem handling these small genome sequences in a small/moderate PC/server.

As asked before, how many memory (RAM) do you have? Please check with `htop` or `top` command or ask the administrator. 

Please also try this command below, it creates an index for the fasta file and then extracts sequences (regions) with random access of the sequence file. This commend is memory-efficient, unless the `IDs.txt` is very very big.

    seqkit faidx -l IDs.txt msa.fa -o result.fasta

**Comment by shenwei356** [comment]
For the `top` command, I mean check the total memory.

![image](https://github.com/shenwei356/seqkit/assets/2655946/f6e19803-f6e5-445e-a6a6-e7fc07d3cd02)

> if I have many IDs files, and one msa.fa file, how can I extract them at the same time, thanks.

Use `for` loop, or [GNU parallel](https://www.gnu.org/software/parallel/), or [rush](https://github.com/shenwei356/rush).

> Can I use unzipped files msa. tar.xz file, because the msa.fa file is 461G?

No. No tools can achieve that.

**Comment by shenwei356** [comment]
Well, you should tell the machine at the very beginning.

How did you install `seqkit`? Which binary file did you download? `seqkit_darwin_arm64.tar.gz` for M1/2/3 chips, and `seqkit_darwin_amd64.tar.gz` for Intel CPUs.

Did you try running `seqkit` with other small datasets? How about creating one simple fasta file and run `seqkit stats` with it ?  


BTW, it's not a good idea to compress JUST ONE SINGLE file with `tar`. You only need to compress it with `xz`

    xz -k msa.fa.

BTW, you might handle these big files on a server if you can get access to.

**Comment by shenwei356** [comment]
Sorry, according to [the previous reply](https://github.com/shenwei356/seqkit/releases/download/v2.6.1/seqkit_darwin_arm64.tar.gz), I think you're running with the correct binary file.

Did you try running seqkit with other small datasets? How about creating one simple fasta file and running `seqkit stats` with it? If these's no problem. It might be due to the limited free memory of your machine (looks like 8GB).
However, as I said before. `seqkit faidx -l` is memory-efficient. So I'm kind of confused. 

Could you please also share the file `msa.tar.xz` with me? Or tell me where to download it.
