### ISSUE TITLE
Invalid Index File Created for Some FASTAs

### ISSUE THREAD

**Issue by simone-says** [shenwei356/seqkit#432]
I am trying to use subseq and fx2tab to measure GC content of certain regions in many genomes, and the index file created before subsequences are generated is invalid for a few of my genome FASTAs. I'm running:
```
seqkit subseq --bed ${species}.CR1.bed -d 1000 -f ${species}.genome.fa | seqkit fx2tab --name --only-id --gc 
> ${species}.flank_CR1_1kb.bed
```
And I'm getting the error: 
```
[INFO] create FASTA index for /projects/tollis_lab/busco_phylo/squamates/ref/omes/laudakiaSacra.genome.fa
[INFO] read BED file ...
[INFO] 254250 BED features loaded
[ERRO] invalid fai records: GWHBKHB00000001	OriSeqID=Contig1	Len=77011479	77011479	47	100	101
```

Because the index files look like:
```
GWHBKHB00000001	OriSeqID=Contig1	Len=77011479	77011479	47	100	101
GWHBKHB00000002	OriSeqID=Contig2	Len=67595787	67595787	77781688	100	101
GWHBKHB00000003	OriSeqID=Contig3	Len=60031939	60031939	146053480	100	101
GWHBKHB00000004	OriSeqID=Contig4	Len=54550570	54550570	206685786	100	101

```
It looks like it's only happening for the first chromosome/contig, and only for a few files...

**Comment by shenwei356** [comment]
Could you please share one genome file and a few lines of the bed file?

**Comment by shenwei356** [comment]
I see, because there are some tabs ("\t") in the FASTA headers.

To solve this, please remove any descriptions by

    seqkit seq -i ${species}.genome.fa -o ${species}.genome.filter.fa

    seqkit subseq --bed ${species}.CR1.bed -d 1000 -f ${species}.genome.filter.fa \
        | seqkit fx2tab --name --only-id --gc > ${species}.flank_CR1_1kb.bed

As for specific FASTA index format (`.seqkit.fai` file), I can't remember why I use this for `subseq` and a few other commands, for now.

**Comment by shenwei356** [comment]
OK, please just use the new version:



- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/13823518/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_arm64.tar.gz](https://github.com/shenwei356/seqkit/files/13823516/seqkit_darwin_arm64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/13823514/seqkit_darwin_amd64.tar.gz)

Changes:

- `seqkit subseq`:
    - Use the ID regular expression from the option `--id-regexp` to create FASTA index file. This solves the panic happened for sequences containing tabs in the headers. [#432](https://github.com/shenwei356/seqkit/issues/432)
- `seqkit split/sort/shuffle`:
    - When using two-pass mode (`-2/--two-pass`), replace possible tabs in the sequence header.

**Comment by simone-says** [comment]
Thank you! I tried used the `--id-regexp` option with regex `^(\\S+)\\s?[\\s\\t]?` to include tabs as well but couldn't get that to work so I used `seqkit seq -i ${species}.genome.fa -o ${species}.genome.filter.fa` as you suggested earlier. That option worked with no issues! Thanks for your speedy response.
