### ISSUE TITLE
error when extracting sequences that didn't start with ATG

### ISSUE THREAD

**Issue by Tiramisu023** [shenwei356/seqkit#435]
Hello,

I had trouble when I tried to extract the sequences that didn't start with 'ATG'.

The sequence '9730' and 'test9730' actually start with 'GAC', the only difference between these two sequences is the addition of 'CAT' at the end of 'test9730', however, seqkit thought 'test9730' starts with 'ATG'. It appears that seqkit mistakenly reverse and complement the ending CAT as ATG, and thus assumes that the sequence begins with ATG.

`cat test.fas
\>9730
GACTTTATTCTTCCTACTCCTTTTTCATTGCAGCCAAGGAGAACACGTAACTCAGCACCC
TCACTTCCACTTCCACGGTGTTCCGTCCAGATGCAATCCTTGCATTGCTCAGAAAGGCTT
TCATCTGGGAACCGTTTGCAGAACGGCTTCTAGAGCTTTGCTGAAGATTGAACAGCCCAG
\>test9730
GACTTTATTCTTCCTACTCCTTTTTCATTGCAGCCAAGGAGAACACGTAACTCAGCACCC
TCACTTCCACTTCCACGGTGTTCCGTCCAGATGCAATCCTTGCATTGCTCAGAAAGGCTT
TCATCTGGGAACCGTTTGCAGAACGGCTTCTAGAGCTTTGCTGAAGATTGAACAGCCCAG
CAT

seqkit grep -s -i -r -p ^ATG test.fas
\>test9730
GACTTTATTCTTCCTACTCCTTTTTCATTGCAGCCAAGGAGAACACGTAACTCAGCACCC
TCACTTCCACTTCCACGGTGTTCCGTCCAGATGCAATCCTTGCATTGCTCAGAAAGGCTT
TCATCTGGGAACCGTTTGCAGAACGGCTTCTAGAGCTTTGCTGAAGATTGAACAGCCCAG
CAT`

I have tried the version '2.6.1', '2.6.0' and '2.5.1' in conda.  Could you please confirm this?
Thank you.

Best wishes.

**Comment by shenwei356** [comment]
Because `^ATG` matches the reverse complement sequence of `test9730`. 

Since v0.15.0 (2021-01-12), seqkit searches on both strands when searching by sequence.

```
$ seqkit grep -h
Attentions
  2. When searching by sequences, it's partly matching, and both positive
     and negative strands are searched.
     Mismatch is allowed using flag "-m/--max-mismatch", you can increase
     the value of "-j/--threads" to accelerate processing.

```

The solution is adding a flag:

```
  -P, --only-positive-strand        only search on positive strand
```

**Comment by shenwei356** [comment]
I'll add some notes in the help message.
