### ISSUE TITLE
Improving Random Subsampling from FASTQ file: Shuffling Before Subsampling

### ISSUE THREAD

**Issue by AnupamGautam** [shenwei356/seqkit#438]
Dear Developer,

I've concatenated the FASTQ files using the command:

```
cat paired_1.fastq paired_2.fastq unpaired_1.fastq unpaired_2.fastq > concatenated.fastq
```

However, when I attempted to use `reformat.sh` to randomly subsample 25 million reads, it seems to primarily cover reads from `paired_1.fastq` and `paired_2.fastq`, despite their random order.

I'm considering using `seqkit` with the command `seqkit shuffle -o shuffled.fastq -j 30 concatenated.fastq` to generate a randomly shuffled FASTQ file. Then, I plan to subsample 25 million reads using `seqkit sample` for a more reliable random subsampling.

Could you please confirm if this approach sounds reasonable to ensure random subsampling of reads?

Thank you,
Anupam

**Comment by shenwei356** [comment]
Sorry, I missed this issue.

> it seems to primarily cover reads from paired_1.fastq and paired_2.fastq, despite their random order.

I guess it's just because there're are much more paired reads than unpaired ones.

> seqkit shuffle -o shuffled.fastq -j 30 concatenated.fastq 

That would consume a massive RAM.

**Comment by AnupamGautam** [comment]
Sorry, I missed this issue.
>
> it seems to primarily cover reads from paired_1.fastq and paired_2.fastq,
> despite their random order.
>
>
No worries, Thank you for the response.

> I guess it's just because there're are much more paired reads than
> unpaired ones.
>
> seqkit shuffle -o shuffled.fastq -j 30 concatenated.fastq
>
> That would consume a massive RAM.
>
There was a bug in my script, "reformat," which was indeed giving reads
from unpaired data. Somehow, I missed that. Additionally, both the tools,
"reformat" and "seqkit," modified the third line of the FASTQ format,
leading to some confusion. However, now it's rectified, and we processed
the result with the "reformat" outcome.

For example:

Before processing:
```
@ERR123456.1/1
AAAAATTTTTGGGG
+ERR123456.1/1
"""""""""""???
```

After processing:
```
@ERR123456.1/1
AAAAATTTTTGGGG
+
"""""""""""???
```

Thanks,
Anupam
