### ISSUE TITLE
seqkit locate: typo in error message

### ISSUE THREAD

**Issue by stas-malavin** [shenwei356/seqkit#442]
```
$ cat contig.fa | seqkit locate -p '"aaggttaa.{0,24}cagcacct"' -r -P -m 2
[ERRO] flag -r (--use-regexp) not allowed when giving flag -m (--use-regexp)
```
Should be `-m (--max-mismatch)`

**Comment by shenwei356** [comment]
Thank you Stas!

**Comment by shenwei356** [comment]
Yes, you can just use the `amplicon`. [Example 5](https://bioinf.shenwei.me/seqkit/usage/#amplicon).

```
$ echo -ne ">s\nacggaaaaa\n" 
>s
acggaaaaa

$ echo -ne ">s\nacggaaaaa\n" \
    | seqkit amplicon -F actg -m 1 -f -r 1:99999999999
[INFO] 1 primer pair loaded
>s
aaaaa
```

> There are various combinations of sequences that I need to locate and trim.

`seqkit amplicon` support a list of primers with `-p, --primer-file`.

**Comment by stas-malavin** [comment]
Gosh, I knew it's somewhere there…
Thanks so much!

**Comment by stas-malavin** [comment]
Actually, I need a regular expression `AAGGTTAA.{0,30}CAGCACCT`, which seems not possible with `amplicon`.
But, I can put all the actual adapters instead of `.{0,30}`, put them all in a file, as you suggested, and allow some mismatches. Yeah, should work this way.
