### ISSUE TITLE
Apple preventing software load

### ISSUE THREAD

**Issue by j-p-courneya** [shenwei356/seqkit#447]
Hi I was wondering if you'd received any feedback that seqkit was being blocked by apple security as it can't be scanned for malware. I'm on a MacBook Pro with M2 chip. I was using the seqkit_darwin_arm64.tar.gz

**Comment by shenwei356** [comment]
Not yet, thanks for reporting this.

**Comment by martinghunt** [comment]
This works for me on M1 mac: in finder, right click -> Open on seqkit. You'll get a window saying:
macOS cannot verify the developer of "seqkit". Are you sure you want to open it?

Choose Open. It will run seqkit in a new terminal, showing the help message. Close the window.

You only need to do all of that once. From now on using seqkit as normal in a terminal works

**Comment by j-p-courneya** [comment]
Hi @shenwei356 and @martinghunt thanks for responding so quickly. I wanted to report that upon entering settings > privacy & security i was able to allow the application to run. this seems to have resolved the issue and the software is running. Thank you for the guidance and assistance. I will close this
