### ISSUE TITLE
The calculation of average quality score appears to be lower than it actually is

### ISSUE THREAD

**Issue by bolangshali** [shenwei356/seqkit#448]
Hi, We have used seqkit to calculate  a batch of data and found that the results of average quality score seemed to be low. As in the screenshot below, the Q30 ratio is 86%, but the average mass is only 15.45, even if these 85% bases are only calculated according to the mass value of 30, the remaining base mass is 0, and the average mass should be more than 24, please check the possible problem.
![1711707498050](https://github.com/shenwei356/seqkit/assets/58835794/42a9b2cd-6f2e-4f83-86bc-031a01b8bfce)

**Comment by shenwei356** [comment]
https://github.com/shenwei356/seqkit/issues/297#issuecomment-1085639766

> you can’t just do simple arithmetic mean of all the qscores, because it won’t be a representation of the mean error rate then.

https://gigabaseorgigabyte.wordpress.com/2017/06/26/averaging-basecall-quality-scores-the-right-way/
