### ISSUE TITLE
hi, can add Q20% Q30% to stats result?

### ISSUE THREAD

**Issue by wangzhichao1990** [shenwei356/seqkit#45]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [ ] describe the problem
* [ ] provide a reproducible example
Just like this
https://github.com/zhimenggan/FastqCount

Thanks!

**Comment by shenwei356** [comment]
added: https://github.com/shenwei356/seqkit/commit/f5a941e7ff47ad9097a517cc848c67ad2a6d5d04

**Comment by shenwei356** [comment]
available with https://github.com/shenwei356/seqkit/releases/tag/v0.9.0
