### ISSUE TITLE
sekqit fish goroutine error

### ISSUE THREAD

**Issue by lborcard** [shenwei356/seqkit#450]
Hello,

I wanted to use seqkit fish, which I have used before, but for some reason it threw an error after running for a while.

seqkit version 2.8.0 (same error with 2.2 and 2.6)

command `cat bc12.fasta | seqkit -j 10 fish -a  -f complete_viruses.fasta `

head .fasta

```
>complete genome
GTGTTATCTATTGCTGAAGATCAAATCGCTTCTGCTGGTTATAATACATGGTTCAAAGGGACTTACTTAC
ATCAAATTGATAGTAAGCGCGCAATAGTTGTTGCACAAAGTCCTTTTGTCGCTGAGTGGTTAACCAATAA
ATATCACGAGCACGTCACAAACTTTATATATGAAGTGATTGGAGACAAAGTTCAAGTTAAATTTATATCA
GAAGGCTGCTTCACTAGCAGTAGCCGAAGAACCAGCCAATGCTTATAATCCGCTTTTCATATATGGA
GGCGTCGGTTTAGGAAAGACACATTTAATGCATGCAATTGGTCATTATGTGCTTGAACAAAATCCAAATG
CTAACGTTCTATATACATCTAGCGAAAAATTCACCAATTGGTCATTATGTGCTTGAACAAAATCCAAATG
CTAACGTTCTATATACATCTAGCGAAAAATTCACAAATGAATTTATTAAGTCTATACGTATGAACGATAC
GGAAAGCTTTAGAGACAAGTATCGAAACATCGATGTGCTCTTAATAGATGACATTCAATTCATTCAAAAG
>contig_2
TCAGTGTAAAGGTAGCATAACCGATATTATACGGCGTTTACCAGTTTTTGTAAGGGGGGA
TAGTTGTAGATTTTGAATGCCAATTTATTCCTAAAATCGCCTATACTGTCACATCCTCAC
ACACATCACGAGCACGTCACAAACTTTATATATGAAGTGATTGGAGACAAAGTTCAAGTTAAATTTATATCA
GAAGAAGATTTACAAAGTGAAGATTTCACTGAACAGCCAGAAAAACCTAAAGAAACTGAAGCATATGAAG
AAGTTACAAATAGTCAGCTGAACAGTAATAACACTTTTGATACATTCGTTATCATTTACATCATTTTCCCTA
GTAACACTCGTATATTTACCTCACAACTATCACGCTATTCTCTTACTCACATTCTCCTAT
TCATATTTCTTAATCATGTCTCTTCAACTCTATTCACAGCATACTTTAACAATCACTCAT
```
error (1 out of many error messages I obtained):
```
goroutine 87 gp=0xc000498700 m=nil [GC worker (idle), 3 minutes]:
runtime.gopark(0x159584e38b9b4b?, 0x3?, 0xb1?, 0x93?, 0x0?)
        /usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc00050f750 sp=0xc00050f730 pc=0x43e7ae
runtime.gcBgMarkWorker()
        /usr/local/go/src/runtime/mgc.go:1310 +0xe5 fp=0xc00050f7e0 sp=0xc00050f750 pc=0x420865
runtime.goexit({})
        /usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc00050f7e8 sp=0xc00050f7e0 pc=0x471161
created by runtime.gcBgMarkStartWorkers in goroutine 1
        /usr/local/go/src/runtime/mgc.go:1234 +0x1c

```
thanks for the help

**Comment by shenwei356** [comment]
I had never seen this kind of error before. And I can't reproduce this with a simple test. Do you have enough memory?
@botond-sipos any idea?

**Comment by lborcard** [comment]
Frankly neither have I, we are running an old version of go (1.19) though I don't know if that could be causing this issue.

**Comment by shenwei356** [comment]
It should be compatible with all go versions. No new features like generics and new keywords like `clear` are used in seqkit.

**Comment by lborcard** [comment]
We just updated our system to version 2.2 of go and I get the same error even without the `-j 10` flag.

**Comment by lborcard** [comment]
We ran some test and indeed it overloads the memory of our system to 400gb+ but we do not know why, the genome I am looking at is 2.9MB long. Do you have any idea why this would happen?

**Comment by botond-sipos** [comment]
@lborcard I think the issue is the size of the input. Fish was designed to search for short sequences in long reads and it is not able to cope with whole genomes as input as it uses a rather simple recursive alignment strategy.
If you are searching for short sequences in a whole genomes, I would suggest using a proper aligner, such as [bwa mem](https://github.com/lh3/bwa).

**Comment by lborcard** [comment]
Thank you for your answers !
