### ISSUE TITLE
seqkit version 2.8.1 reporting version as 2.8.0

### ISSUE THREAD

**Issue by heuermh** [shenwei356/seqkit#454]
After updating seqkit to version 2.8.1 via homebrew, the version is still reported as 2.8.0
```
$ seqkit version
seqkit v2.8.0

$ which seqkit
/usr/local/bin/seqkit

$ ls -als `which seqkit`
0 lrwxr-xr-x@ 1 foo  bar  33 Apr 10 11:50 /usr/local/bin/seqkit -> ../Cellar/seqkit/2.8.1/bin/seqkit
```

Not sure if this is an issue with the 2.8.1 release or with the homebrew formula, am looking into it further.

**Comment by heuermh** [comment]
Got it, thank you!  At least where I am using seqkit (in [nf-core/modules](https://github.com/nf-core/modules/pull/5463)) it causes no obvious concern.

**Comment by shenwei356** [comment]
I'll tag a new release.

**Comment by heuermh** [comment]
Thank you, @shenwei356!

Note that in nf-core/modules we have completed updating all the seqkit modules to version 2.8.1
https://github.com/nf-core/modules/tree/master/modules/nf-core/seqkit
