### ISSUE TITLE
can seqkit handle fasta format sequence in `*.tar.xz`?

### ISSUE THREAD

**Issue by liamxg** [shenwei356/seqkit#456]
Dear @shenwei356,

When I run `seqkit seq seq.tar.xz`, it reported errr:

[ERRO] fastx: invalid FASTA/Q format

`seq.tar.xz` is compressed fasta format sequence data.

**Comment by shenwei356** [comment]
No similar tools handle that. Please decompress it first.

**Comment by shenwei356** [comment]
Decompress the tarball and compress **individual** files with gzip/xz.
