### ISSUE TITLE
"seqkit pair" command problem

### ISSUE THREAD

**Issue by kabilov** [shenwei356/seqkit#464]
Hi Shen!

It was used seqkit v2.8.0
The result of two commands is different:
1) seqkit pair -1 1.fq -2 2.fq                                                  ==> 1 pair (right)
2) seqkit pair -1 1.fq -2 2.fq --id-regexp '^(\S+?)(\/[12])?'   ==> 3 pair (wrong)

1.fq
----------
@M01026:40:000000000-J7WJ3:1:1101:22243:1697 1:N:0:28
G
+
F
@M01026:40:000000000-J7WJ3:1:1101:22247:1697 1:N:0:28
G
+
F
@M01026:40:000000000-J7WJ3:1:1101:22243:1699 1:N:0:28
G
+
F

2.fq
---------
@M01026:40:000000000-J7WJ3:1:1101:22243:1697 2:N:0:28
T
+
F
@M01026:40:000000000-J7WJ3:1:1101:22243:1698 2:N:0:28
T
+
F
@M01026:40:000000000-J7WJ3:1:1101:22243:1696 2:N:0:28
T
+
F

**Comment by shenwei356** [comment]
The regular expression is not what you expected.

```
$ seqkit seq -ni --id-regexp '^(\S+?)(/[12])?'  1.fq 
M
M
M

$ seqkit seq -ni --id-regexp '^(\S+)(/[12])?'  1.fq 
M01026:40:000000000-J7WJ3:1:1101:22243:1697
M01026:40:000000000-J7WJ3:1:1101:22247:1697
M01026:40:000000000-J7WJ3:1:1101:22243:1699
```

I guess you should use this, which supports both `xxxxxx/1 abc` and  `xxxxx abc`.
```
$ seqkit seq -ni --id-regexp '^(\S+?)(/[12]|\s)'  1.fq 
M01026:40:000000000-J7WJ3:1:1101:22243:1697
M01026:40:000000000-J7WJ3:1:1101:22247:1697
M01026:40:000000000-J7WJ3:1:1101:22243:1699
```

**Comment by kabilov** [comment]
Thank you for your help!
