### ISSUE TITLE
[ERR0] no more than one file needed (2) - seqkit sub sampling

### ISSUE THREAD

**Issue by Thomas-EnvA** [shenwei356/seqkit#466]
Hello everyone,

I'm trying to sub sample one of my fastq file with the -s flag but it keeps telling me that I am giving more than one file with this error 
[ERRO] no more than one file needed (2). The code I'm using is the following one :
"seqkit sample -s 1 NY18_mapped_l2000_q12.fastq.gz 5293"
I have checked, that the path is the good one, there is only one file called like that etc. If someone has an idea how to solve this problem ? Thanks !

**Comment by shenwei356** [comment]
You give files `NY18_mapped_l2000_q12.fastq.gz` and `5293`.

You might use

```
seqkit sample -s 1 NY18_mapped_l2000_q12.fastq.gz -n 5293
```

But it's no recommended:

```
Attention:
1. Do not use '-n' on large FASTQ files, it loads all seqs into memory!
   use 'seqkit sample -p 0.1 seqs.fq.gz | seqkit head -n N' instead!

```
