### ISSUE TITLE
rna2dna to convert the sequence 'U' to 'T'

### ISSUE THREAD

**Issue by wydty** [shenwei356/seqkit#468]
Dealing with a very large aligned fasta file (length 149999bp), want to use the parameter --rna2dna to convert the sequence 'U' to 'T', the prompt '[WARN] it's already DNA, no need to convert', But the sequence still contains' U ', may I ask is the use of the wrong way, or bug?

中文描述: 处理一个很大的对齐fasta文件，（长度为149999bp），想使用参数 --rna2dna 将序列中的`U`转化为`T`, 提示`[WARN] it's already DNA, no need to convert`，但序列还是包含`U`, 请问是使用方法不对，还是bug 呢？

```
zcat in.fasta.gz  |  seqkit seq --rna2dna --only-id   > silva_138_1align.fa
[WARN] it's already DNA, no need to convert
```
data from:
https://www.arb-silva.de/fileadmin/silva_databases/release_138.1/Exports/SILVA_138.1_LSURef_NR99_tax_silva_full_align_trunc.fasta.gz
```
#file                 format  type  num_seqs         sum_len  min_len  avg_len  max_len
#silva_138_1align.fa  FASTA   DNA     95,286  14,292,804,714  149,999  149,999  149,999
```

seqkit Version: 2.0.0

**Comment by shenwei356** [comment]
There's a global flag:

```
Flags:
      --alphabet-guess-seq-length int   length of sequence prefix of the first FASTA record based on
                                        which seqkit guesses the sequence type (0 for whole seq)
                                        (default 10000)

```

While, in your case, there are lots of `.` in the beginning of the sequence, so seqkit thought it's a DNA. So just set a bigger value.

```
zcat SILVA_138.1_LSURef_NR99_tax_silva_full_align_trunc.fasta.gz \
    | seqkit seq --rna2dna --only-id --alphabet-guess-seq-length 100000000 \
    | seqkit head -n 1 \
    | seqkit replace -s -p '[\.\-]'  \
    | more

>LK021130.235690.238580
GGTTAAGTGACTAAGCGTACACGGTGGATGCCTTGGCAGTCAGAGGCGATGAAGGACGTA
GTAACTTGCGATAAGCGTAGATTAGGCAGTAACAGCCACTTGAGTCTACGATTTCCGAAT
GGGGAAACCCACGTGCATAAGCACGTATCCTTACCTGAATACATAGGGTAAGGAGGCAAA
CCGGGGGAACTGAAACATCTAAGTACCCCGAGGAGAAGAAATCAACAGAGATTCCGAAAG
TAGCGGCGAGCGAAATTGGACTAGCCCTTAAGCTTTTAATGATGCAGGTGAAGCCTCTGG
AAAGTGGCGCAATAAAGGGTGATAGCCCCGTAACTGTTCCATCATTATAAGTGAAATCGA

```

**Comment by wydty** [comment]
Thanks for your quick response and solving my problem, seqkit is really a great tool.
