### ISSUE TITLE
[feature suggestion] check "paired end" pairs

### ISSUE THREAD

**Issue by maxmaronna** [shenwei356/seqkit#469]
Dear Wei Shen,

Maybe my suggestion is quite naive or simple, but stats command would include an option to check percentage of real condition (paired, unpaired) for a certain paired end dataset. Same option would be nice to add after using the sample option.

Thanks
max maronna

**Comment by shenwei356** [comment]
Dear Max, 

Sorry, I missed this issue for a few days. "stats" was designed for single fasta/fastq files. 

For paired/unpaired reads, if you do not trust the data, [`seqkit pair`](https://bioinf.shenwei.me/seqkit/usage/#pair)  can help to match up paired-end reads from two fastq files.

Wei.

**Comment by maxmaronna** [comment]
Dear Wei,
Thank you very much for your answer. Your suggestion about the seqkit pair command will resolve my interest about paired end reads. 

Best,
max
