### ISSUE TITLE
Improvement for concat

### ISSUE THREAD

**Issue by kabilov** [shenwei356/seqkit#470]
Hi Wei,

I have PE reading (R1 and R2). R2 is modified with the "seqkit concat" command. As a result, the order of the names in R1 and R2 is different.
It would be useful to have a flag that would preserve the order of names after concatenations even if this would result in a performance penalty or increased memory usage.

Best wishes,
Marsel

**Comment by shenwei356** [comment]
`seqkit concat` is for concatenating sequences with the same IDs from multiple files, which would consume a lot of RAM. I'm not sure of the purpose of using it for paired-end data.

Anyway, you can use [seqkit pair](https://bioinf.shenwei.me/seqkit/usage/#pair) to match up paired-end reads from two fastq files.

**Comment by kabilov** [comment]
Thanks
