### ISSUE TITLE
CPU usage issues in WSL

### ISSUE THREAD

**Issue by user-tq** [shenwei356/seqkit#471]
I use seqkit in WSL2，The system is ubantu，and i install seqkit by`mamba install seqkit -c bioconda`
I want to know why the load on running seqkit is very low.From the top view, only 8% of the load.Windows Task Manager also supports this conclusion.
and I run `seqkit sample -n 1000 -s 12 -j 18 $R1  -2  > tmp_merge_$name.fq`
![006d593f52002147c011cad2e4dfe60](https://github.com/shenwei356/seqkit/assets/72878144/23180764-013e-4311-ab2c-e9486f40c84f)

Following copilot's advice, I tested the CPUs using `stress` to see if they are functioning properly
```
sudo apt-get install -y stress  # insatll  stress
stress --cpu $(nproc) --timeout 60 
```
![690e4a18969348c8395e482fa32223f](https://github.com/shenwei356/seqkit/assets/72878144/0d502045-540e-41f5-a70a-83326a90eae9)
This seems to indicate that the CPUs are running normally

Thank you for all the suggestions

**Comment by shenwei356** [comment]
Hi there,

1. Using a lot of threads does not always accelerate seqkit (see the `Multi-threads` column in the [table](https://github.com/shenwei356/seqkit?tab=readme-ov-file#subcommands)), as most commands are I/O bound, which means file reading and writing is the bottleneck, not CPUs. Therefore, just use the default value 4 for -j, for most commands.

3. `seqkit sample -n` is not recommended, as described in the help message:


        $ seqkit sample  -h
        sample sequences by number or proportion.
        
        Attention:
        1. Do not use '-n' on large FASTQ files, it loads all seqs into memory!
           use 'seqkit sample -p 0.1 seqs.fq.gz | seqkit head -n N' instead!

    This also might be the reason that you did not see any output and wanted to check the CPU usage.

4. You might use `-o output.fq.gz` for specifying the **gzipped**-compressed output file.
