### ISSUE TITLE
seqkit concat: out of memory

### ISSUE THREAD

**Issue by kabilov** [shenwei356/seqkit#473]
Hi Wei,

I use seqkit (2.8.2) on ubuntu LST 18.04 with 500Gb of memory.

seqkit concat barcode1.fq F300012313_L01_discarded_1.fq.gz >F300012313_L01_discarded_1_edit.fq

Is it possible to make memory usage more efficient?

-------------------------------------------------
fatal error: runtime: out of memory

runtime stack:
runtime.throw({0xb5482b?, 0xc000103e38?})
        /usr/local/go/src/runtime/panic.go:1023 +0x5c fp=0xc000103e10 sp=0xc000103de0 pc=0x43b81c
runtime.sysMapOS(0x13aeac00000, 0x400000)
        /usr/local/go/src/runtime/mem_linux.go:167 +0x11b fp=0xc000103e50 sp=0xc000103e10 pc=0x41ba5b
runtime.sysMap(0x13aeac00000, 0x400000, 0x1?)
        /usr/local/go/src/runtime/mem.go:155 +0x34 fp=0xc000103e70 sp=0xc000103e50 pc=0x41b4d4
runtime.(*mheap).grow(0x15c5200, 0x2000?)
        /usr/local/go/src/runtime/mheap.go:1534 +0x236 fp=0xc000103ee0 sp=0xc000103e70 pc=0x42e216
runtime.(*mheap).allocSpan(0x15c5200, 0x1, 0x0, 0xb)
        /usr/local/go/src/runtime/mheap.go:1246 +0x1b0 fp=0xc000103f80 sp=0xc000103ee0 pc=0x42d8f0
runtime.(*mheap).alloc.func1()
        /usr/local/go/src/runtime/mheap.go:964 +0x5c fp=0xc000103fc8 sp=0xc000103f80 pc=0x42d39c
runtime.systemstack(0x0)
        /usr/local/go/src/runtime/asm_amd64.s:509 +0x4a fp=0xc000103fd8 sp=0xc000103fc8 pc=0x46f24a

goroutine 58 gp=0xc000503dc0 m=3 mp=0xc0000ef008 [running]:
runtime.systemstack_switch()
        /usr/local/go/src/runtime/asm_amd64.s:474 +0x8 fp=0x11e774d6a40 sp=0x11e774d6a30 pc=0x46f1e8
runtime.(*mheap).alloc(0x41afa8?, 0x79e588c450?, 0x0?)
        /usr/local/go/src/runtime/mheap.go:958 +0x5b fp=0x11e774d6a88 sp=0x11e774d6a40 pc=0x42d2fb
runtime.(*mcentral).grow(0x2000?)
        /usr/local/go/src/runtime/mcentral.go:254 +0x52 fp=0x11e774d6ac8 sp=0x11e774d6a88 pc=0x41af72
runtime.(*mcentral).cacheSpan(0x15d5cc8)
        /usr/local/go/src/runtime/mcentral.go:170 +0x418 fp=0x11e774d6b40 sp=0x11e774d6ac8 pc=0x41add8
runtime.(*mcache).refill(0x7f84a23c25b8, 0xb?)
        /usr/local/go/src/runtime/mcache.go:182 +0x153 fp=0x11e774d6b80 sp=0x11e774d6b40 pc=0x41a3f3
runtime.(*mcache).nextFree(0x7f84a23c25b8, 0xb)
        /usr/local/go/src/runtime/malloc.go:948 +0x85 fp=0x11e774d6bb8 sp=0x11e774d6b80 pc=0x411205
runtime.mallocgc(0x22, 0x0, 0x0)
        /usr/local/go/src/runtime/malloc.go:1149 +0x4a5 fp=0x11e774d6c40 sp=0x11e774d6bb8 pc=0x411825
runtime.slicebytetostring(0x11e774d6cf0?, 0xc00002c2c0, 0x22)
        /usr/local/go/src/runtime/string.go:112 +0x77 fp=0x11e774d6c70 sp=0x11e774d6c40 pc=0x458af7
github.com/shenwei356/bio/seq.(*Alphabet).Clone(...)
        /home/shenwei/go/pkg/mod/github.com/shenwei356/bio@v0.13.3/seq/alphabet.go:174
github.com/shenwei356/bio/seq.(*Seq).Clone(0xdab52813b0)
        /home/shenwei/go/pkg/mod/github.com/shenwei356/bio@v0.13.3/seq/seq.go:101 +0x277 fp=0x11e774d6e28 sp=0x11e774d6c70 pc=0x776ff7
github.com/shenwei356/bio/seqio/fastx.(*Record).Clone(...)
        /home/shenwei/go/pkg/mod/github.com/shenwei356/bio@v0.13.3/seqio/fastx/records.go:26
github.com/shenwei356/bio/seqio/fastx.(*Reader).ChunkChan.func1()
        /home/shenwei/go/pkg/mod/github.com/shenwei356/bio@v0.13.3/seqio/fastx/reader.go:591 +0x17e fp=0x11e774d6fe0 sp=0x11e774d6e28 pc=0x77f01e
runtime.goexit({})
        /usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0x11e774d6fe8 sp=0x11e774d6fe0 pc=0x471081
created by github.com/shenwei356/bio/seqio/fastx.(*Reader).ChunkChan in goroutine 1
        /home/shenwei/go/pkg/mod/github.com/shenwei356/bio@v0.13.3/seqio/fastx/reader.go:572 +0xad

goroutine 1 gp=0xc0000061c0 m=nil [chan receive]:
runtime.gopark(0x12aad09d260?, 0xac08c0?, 0x0?, 0x3?, 0x0?)
        /usr/local/go/src/runtime/proc.go:402 +0xce fp=0xc0005ab688 sp=0xc0005ab668 pc=0x43e70e
runtime.chanrecv(0xc00010b6e0, 0xc0005ab7b0, 0x1)
        /usr/local/go/src/runtime/chan.go:583 +0x3bf fp=0xc0005ab700 sp=0xc0005ab688 pc=0x40a77f
runtime.chanrecv2(0x13477f80000?, 0x13835ce4000?)
        /usr/local/go/src/runtime/chan.go:447 +0x12 fp=0xc0005ab728 sp=0xc0005ab700 pc=0x40a3b2
github.com/shenwei356/bio/seqio/fastx.GetSeqs({0x7fff62216bad?, 0x4?}, 0xc00003c010?, 0x4, 0x400, {0xb4beb4?, 0x9?})
        /home/shenwei/go/pkg/mod/github.com/shenwei356/bio@v0.13.3/seqio/fastx/util.go:61 +0x12e fp=0xc0005ab7f0 sp=0xc0005ab728 pc=0x78042e
github.com/shenwei356/seqkit/v2/seqkit/cmd.init.func20(0x1599160, {0xc000109500, 0x2, 0x2})
        /home/shenwei/go/src/github.com/shenwei356/seqkit/seqkit/cmd/concat.go:92 +0x3e9 fp=0xc0005adc98 sp=0xc0005ab7f0 pc=0x9c3f69
github.com/spf13/cobra.(*Command).execute(0x1599160, {0xc0001094a0, 0x2, 0x2})
        /home/shenwei/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:987 +0xab1 fp=0xc0005ade20 sp=0xc0005adc98 pc=0x7d62b1
github.com/spf13/cobra.(*Command).ExecuteC(0x159c800)
        /home/shenwei/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1115 +0x3ff fp=0xc0005adef8 sp=0xc0005ade20 pc=0x7d6b9f
github.com/spf13/cobra.(*Command).Execute(...)
        /home/shenwei/go/pkg/mod/github.com/spf13/cobra@v1.8.0/command.go:1039
github.com/shenwei356/seqkit/v2/seqkit/cmd.Execute()
        /home/shenwei/go/src/github.com/shenwei356/seqkit/seqkit/cmd/root.go:73 +0x1a fp=0xc0005adf40 sp=0xc0005adef8 pc=0xa0e25a
main.main()
        /home/shenwei/go/src/github.com/shenwei356/seqkit/seqkit/main.go:58 +0xf fp=0xc0005adf50 sp=0xc0005adf40 pc=0xa2276f
runtime.main()
        /usr/local/go/src/runtime/proc.go:271 +0x29d fp=0xc0005adfe0 sp=0xc0005adf50 pc=0x43e2dd
runtime.goexit({})
        /usr/local/go/src/runtime/asm_amd64.s:1695 +0x1 fp=0xc0005adfe8 sp=0xc0005adfe0 pc=0x471081

And so on for other goroutines.

**Comment by shenwei356** [comment]
`seqkit concat` reads all data into memory, it's mainly for fasta files.

If you intend to add ONE specific barcode to the reads (barcode1.fq has only one sequence), you can use `seqkit replace`. 

```
$ echo -ne ">s1\na\n>s2\nc\n"
>s1
a
>s2
c

$ echo -ne ">s1\na\n>s2\nc\n" | seqkit replace -s -p "^" -r "NNNN"
>s1
NNNNa
>s2
NNNNc
```

**Comment by kabilov** [comment]
The problem is that each sequence has its own unique barcode. For instance for s1 is GGG, but for s2 is CCC and so on. So I'm not sure that seqkit replace can help.

**Comment by shenwei356** [comment]
I won't help. And you might consider if it's right to do this, sort of the reverse of deduplex?

**Comment by kabilov** [comment]
This is not a problem, I’ll write a script in Python. It just seemed to me that such a seqkit feature would be useful for other users.
