### ISSUE TITLE
Difference between patternName and pattern with locate function? Can I only output one of the columns?

### ISSUE THREAD

**Issue by johanthebiologist** [shenwei356/seqkit#476]
The [locate function](https://bioinf.shenwei.me/seqkit/usage/#locate) shows two columns that seems the same, the second column which is "patternName" and the third column which is "pattern". 

In all examples in the [quick guide](https://bioinf.shenwei.me/seqkit/usage/#locate) these two columns show the same text. In my usage, they also always show the same text.

1. What is the difference between these two columns? In what use case will they have different text?
2. Can I customise the output from the locate function? Since they are always the same in my usage, I would like to hide one of them to get a clearer and more minimal output.

**Comment by shenwei356** [comment]
> What is the difference between these two columns? In what use case will they have different text?

It would be different when the patterns are given by a pattern file.

```
$ cat r.fasta 
>r
ACTGACGAGACGAG

$ cat q.fasta 
>q1
ACTG
>q2
CATG

$ seqkit locate -f q.fasta r.fasta | csvtk pretty -t
seqID   patternName   pattern   strand   start   end   matched
-----   -----------   -------   ------   -----   ---   -------
r       q1            ACTG      +        1       4     ACTG 
```
> Can I customise the output from the locate function? Since they are always the same in my usage, I would like to hide one of them to get a clearer and more minimal output.

No, it can not be changed. Only the column `matched` can optionally removed with `-M, --hide-matched` as it might be very long.

But you can delete it with other tools like my [csvtk](https://github.com/shenwei356/csvtk), which is powerful.

```
$ seqkit locate -f q.fasta r.fasta | csvtk cut -t -f -patternName | csvtk pretty -t
seqID   pattern   strand   start   end   matched
-----   -------   ------   -----   ---   -------
r       ACTG      +        1       4     ACTG 
```

**Comment by johanthebiologist** [comment]
Thanks for the quick reply.

You perfectly described the difference, and your solution using csvtk works perfect, thanks for also providing the code for it with your example command.
