### ISSUE TITLE
Fail to build FMIndex for sequence

### ISSUE THREAD

**Issue by nsyzrantsev** [shenwei356/seqkit#479]
Hi! Thank you very much for your tool! Seqkit always makes me happy :)

But I found a small bug. 

### Prerequisites
OS: ubuntu20.04, amd64 (personal computer)
Command:
```bash
seqkit grep -s -f barcodes.txt input.fastq -o output.fastq -m 1 -R -30:-1
```
`barcodes.txt` file contains such sequences:

```
AGTAGGCT
GTAGGCTC
CTGTACGA
TGTACGAC
GCACCAAG
CACCAAGC
TACGTTTC
ACGTTTCC
```

`input.fastq` contains such read:

```
@1
NNNNNNNNNNNNNNNNNNNNNNNNNNNN
+
############################
```

### Bug

This command successfully be done without any problems:
```
seqkit grep -s -f barcodes.txt input.fq -o output.fq -m 1 -R 1:30
```

But this command fails:
```
seqkit grep -s -f barcodes.txt input.fq -o out.fq -m 1 -R -30:-1

[INFO] 8 patterns loaded from file
[ERRO] fail to build FMIndex for sequence: 1
```

**Comment by shenwei356** [comment]
Actually, it's a bug in sequence region parsing.

For `-R -30:-1`, it returns an empty sequence if the sequence is shorter than 30 (28 for sequence 1).

- [seqkit_darwin_arm64.tar.gz](https://github.com/user-attachments/files/16231776/seqkit_darwin_arm64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/user-attachments/files/16231773/seqkit_linux_amd64.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/user-attachments/files/16231777/seqkit_darwin_amd64.tar.gz)
