### ISSUE TITLE
seqkit faidx with multiple regions on same sequence does not work

### ISSUE THREAD

**Issue by Bjoernsen** [shenwei356/seqkit#48]
With version `0.9.0` (and `0.8.0`), it is not possible to extract multiple sub-sequences from the same sequence.

`samtools` works as expected.

To reproduce this 🐛

`test.fasta`
```
>test1
actgatgcggctagcatcgtatatgctagc
>test2
ggctagctagctagctagatgctagctagctgatcg
```

`test.fasta.fai`
```
test1	30	7	30	31
test2	36	45	36	37
```

✔️ Multiple regions on different sequences
```bash
seqkit faidx test.fasta test1:1-5 test2:5-10

>test1:1-5
actga
>test2:5-10
agctag

```

❌ Multiple regions on same sequence
```bash
seqkit faidx test.fasta test1:1-5 test1:5-10

>test1:5-10
atgcgg
>test1:5-10
atgcgg
```

**Comment by shenwei356** [comment]
sorry, didn't consider this situation. i'll fix this soon.

**Comment by Bjoernsen** [comment]
I never saw go code, but I think the 🐛 comes from https://github.com/shenwei356/seqkit/blob/master/seqkit/cmd/faidx.go#L139

```go
regions[id] = [2]int{begin, end}
```

I think `regions` is something like a hash. The problem might be that the `id` is identical for both selected regions and the second region overwrites the first entry in the hash.

Does this make sense?

**Comment by shenwei356** [comment]
Yes, you're right.

**Comment by shenwei356** [comment]
@Bjoernsen ,it's fixed. [v0.9.1-dev](https://github.com/shenwei356/seqkit/releases/tag/v0.9.1-dev)
