### ISSUE TITLE
fx2tab produced hash different from GATK ?

### ISSUE THREAD

**Issue by tetedange13** [shenwei356/seqkit#480]
Please check the items below before submitting an issue.
They help to improve the communication efficiency between us.
Thanks!

### Prerequisites

- [x] Make sure you've installed the correct executable binary file.
    For Mac users, Please download
    - `seqkit_darwin_amd64.tar.gz` for Mac with Intel CPUs.
    - `seqkit_darwin_arm64.tar.gz` for Mac with M series CPUs.
- [x] Make sure you are using the latest version by `seqkit version -u`.
- [x] Read the [usage and examples](http://bioinf.shenwei.me/seqkit/usage/) for the specific subcommand.

### Describe your question in detail
I used `seqkit fx2tab --seq-hash --name --only-id` on Human genome FASTA (hg19) and compared it to ones described in "Reference Comparison Table" section of [this GATK page](https://gatk.broadinstitute.org/hc/en-us/articles/360035890711-GRCh37-hg19-b37-humanG1Kv37-Human-Reference-Discrepancies)
=> But obtained hashes are different, for every contig
=> Even though this is supposed to be "md5" algorithm too

Is there a reason for that ?

And is there a way to "convert" hash produced by `fx2tab` to match GATK ones ?
<br>

Thanks a lot for your help !
Kind regards,
Felix.

**Comment by shenwei356** [comment]
Maybe it's because of capitalization. `seqkit fx2tab -s` ignores cases of sequences. Please try to use `-I, --case-sensitive`:

    -I, --case-sensitive         calculate case sensitive base content/sequence hash

Similar issue: https://github.com/shenwei356/seqkit/issues/444

**Comment by shenwei356** [comment]
I tried [HumanG1Kv37](http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz). (BTW, the file is corrupted, but I can still extract chr1).

```
wget http://ftp.1000genomes.ebi.ac.uk/vol1/ftp/technical/reference/human_g1k_v37.fasta.gz

seqkit grep -p 1 human_g1k_v37.fasta.gz  > 1.fasta
```

md5sum with `-I` is the same as the value (`1b22b98cdeb4a9304cb5d48026a85128`) on the website.
```
$ seqkit fx2tab -ni -s 1.fasta 
1       ef610636ace2fbbc5d97431e2a9f289a
$ seqkit fx2tab -ni -s 1.fasta -I 
1       1b22b98cdeb4a9304cb5d48026a85128
```

**Comment by tetedange13** [comment]
Oh my, I guess I will go investigate my local genome !

Thanks again, now I know that case matters for having md5 matching GATK's

Have a nnice day,
Felix.
