### ISSUE TITLE
bam split error

### ISSUE THREAD

**Issue by jh4yd** [shenwei356/seqkit#483]
I had a small pro-virus genome which my fastq files were aligned to. When I tried to split the aligned bam file, I got the error.
command line:
**seqkit bam -N 50000 MBLN01_reads_aln_sorted.bam -o  bam_bundles/**
output lines:
**[INFO] Creating BAM bundles from file: MBLN01_reads_aln_sorted.bam
[INFO] Minimum reads per bundle: 50000
[INFO] Output directory: bam_bundles/
Bundle	Chrom	Start	End	NrRecs	NrLoci
[ERRO] open bam_bundles/000000000_pHR5604/05:0:9213_bundle.bam: no such file or directory**

Do you know the reason? Thank you so much!

**Comment by botond-sipos** [comment]
Hello! Can you please try using `-N -1` and see what happens?
