### ISSUE TITLE
seqkit sana issues

### ISSUE THREAD

**Issue by awesomedeer** [shenwei356/seqkit#485]
Dear Shen @shenwei356 
After run `sana` function by default parameter that when I `wc -l` the rescured file it's still not the times of 4 and somes files increase the number of lines after `sana`. Although no ERROR message appeared, I was curious about why this happened.

Best regards
Song

**Comment by botond-sipos** [comment]
Hi @awesomedeer ! Could you please upload an example input which shows the problem? 

Best,
Botond
