### ISSUE TITLE
subseq --chr does not work with fasta headers containing spaces

### ISSUE THREAD

**Issue by tolot27** [shenwei356/seqkit#49]
Input is:
```
cat test.fa
>seq1   sample sequence 1
ACGT
>seq2   sample sequence 2
TGCA
```

`seqkit subseq test.fa -r 1:3` works as expected:
```
>seq1   sample sequence 1
ACG
>seq2   sample sequence 2
TGC
```

`seqkit subseq test.fa -r 1:3 --chr seq1` does not work because it does not skip after ID:
```
>seq1_1-3 seq1
sam
```

**Comment by shenwei356** [comment]
I only take effect with --gtf or --bed, I did not write clearly.

Instead, you can use 'seqkit grep' or 'seqkit faidx' to limit to one ID and pipe to 'seqkit subseq'
