### ISSUE TITLE
[Feature request] Add number of ambiguous characters in `seqkit stats`

### ISSUE THREAD

**Issue by apcamargo** [shenwei356/seqkit#490]
The number of ambiguous characters is often a good metric for genome quality. As far as I know, there's no way to add the number of counts of a given character to `seqkit stats`. I'm using `-G "Nn"` to fool `seqkit` to think that `N` is a gap character, but it would be nice to have that as an additional (optional) column.

**Comment by shenwei356** [comment]
Do ambiguous characters mean "N" for DNA/RNA and "N/X" for amino acids?

**Comment by apcamargo** [comment]
Yes. Sorry, the title is indeed confusing.

**Comment by shenwei356** [comment]
OK, so it means we just need to count "N" for DNA/RNA, and "N"+"X" for proteins.

**Comment by apcamargo** [comment]
Yep!

**Comment by shenwei356** [comment]
added, just count N/n/X/x for any kind of sequences.

**Comment by kakuk9** [comment]
Hi Wei. Could you also add a feature that allows us to filter nt/aa sequences based on the number and/or proportion of ambiguous characters of individual sequence (i.e. N/X) for fasta files? Thanks :D

**Comment by shenwei356** [comment]
@kakuk9 

```
$ echo -ne ">s\nactgn\n" | seqkit fx2tab -B NX
s       actgn           20.00

$ echo -ne ">s\nactgn\n" | seqkit fx2tab -B NX | awk -F'\t' '$4 >= 20' | seqkit tab2fx 
>s
actgn
```
