### ISSUE TITLE
Would seekable zstd speed up seqkit?

### ISSUE THREAD

**Issue by fdecarpentier** [shenwei356/seqkit#496]
I don't really know how seqkit works with compressed fasta files. But I ran into this seekable zstd fasta format developed for the amazing Logan project.
Here is the paper : https://www.biorxiv.org/content/10.1101/2024.07.30.605881v1
And the code : https://github.com/asl/f2sz

The command help also gives more information :
```
f2sz: FASTA 2 seekable zstd.
It compress a file into a seekable zstd, splitting the file into multiple frames.
The compressed archive can be decompressed with any Zstandard tool, including zstd.

To take advantage of seeking see the following projects:
	C/C++ library:  https://github.com/martinellimarco/libzstd-seek
	Python library: https://github.com/martinellimarco/indexed_zstd
```

I hope this comment is relevant to seqkit.
Cheers!

**Comment by shenwei356** [comment]
Hi, thanks for the message.  So, currently bzip2 (seems there's a go version?) and zstd are seekable, but extra tools are needed to generate these special files.
