### ISSUE TITLE
seqkit stats calculates and shows GC content for amino acid sequences

### ISSUE THREAD

**Issue by stas-malavin** [shenwei356/seqkit#497]
v. 2.9.0 using ```-a``` flag

**Comment by shenwei356** [comment]
Thanks, fixed. It does not compute the number of N's now.

**Comment by stas-malavin** [comment]
Great!
What about X's? Should be computed instead of N's, right?

**Comment by shenwei356** [comment]
Right.  It counted both N and X, which is not right, will fix it later. https://github.com/shenwei356/seqkit/blob/d36e7851be68cf83a8ef96b4be2177e08b4b6495/seqkit/cmd/stat.go#L113

**Comment by shenwei356** [comment]
Fixed. 
[seqkit_darwin_arm64.tar.gz](https://github.com/user-attachments/files/17902061/seqkit_darwin_arm64.tar.gz)
[seqkit_linux_amd64.tar.gz](https://github.com/user-attachments/files/17902063/seqkit_linux_amd64.tar.gz)

**Comment by stas-malavin** [comment]
Great, thanks!
