### ISSUE TITLE
The subcommands 'amplicon' will duplicate and change the target reads

### ISSUE THREAD

**Issue by 326reborn** [shenwei356/seqkit#499]
Hello, 

There is a problem when I use the subcommands 'amplicon':

When I use a pair of primers to extract the target sequence, some target reads  will be duplicated and modified. It only happends on some specific sequences.
My code: seqkit amplicon -F CGGGTTCCGGCGGCATTTTGCCTTCCTGT -R TATGTATCGTCTGAAAATCTTCTCTCATCCGCC -j 4 aff2493d-ba7a-4613-94b4-9e4e7e7b513d.txt -o test_aff2493d-ba7a-4613-94b4-9e4e7e7b513d.txt
[aff2493d-ba7a-4613-94b4-9e4e7e7b513d.txt](https://github.com/user-attachments/files/18251368/aff2493d-ba7a-4613-94b4-9e4e7e7b513d.txt)
[test_aff2493d-ba7a-4613-94b4-9e4e7e7b513d.txt](https://github.com/user-attachments/files/18251371/test_aff2493d-ba7a-4613-94b4-9e4e7e7b513d.txt)

I test it both on v2.6.1 and v2.9.0.

**Comment by shenwei356** [comment]
I looks good to me with v2.9.0


    $ seqkit amplicon -F CGGGTTCCGGCGGCATTTTGCCTTCCTGT -R TATGTATCGTCTGAAAATCTTCTCTCATCCGCC \
        aff2493d-ba7a-4613-94b4-9e4e7e7b513d.txt \
        | seqkit replace -p .+ -r 'a{nr}' -o r.fa

    
    # amplicons
    
    $ seqkit locate -M -f r.fa aff2493d-ba7a-4613-94b4-9e4e7e7b513d.txt \
         | csvtk cut -t -f 1,2,4-6 | csvtk pretty -t
    seqID                                  patternName   strand   start   end 
    ------------------------------------   -----------   ------   -----   ----
    aff2493d-ba7a-4613-94b4-9e4e7e7b513d   a1            +        1       890 
    aff2493d-ba7a-4613-94b4-9e4e7e7b513d   a2            -        927     1809

    
    # forward primer
    
    $ seqkit locate -M aff2493d-ba7a-4613-94b4-9e4e7e7b513d.txt -p CGGGTTCCGGCGGCATTTTGCCTTCCTGT \
        |  csvtk cut -t -f 1,2,4-6 | csvtk pretty -t
    seqID                                  patternName                     strand   start   end 
    ------------------------------------   -----------------------------   ------   -----   ----
    aff2493d-ba7a-4613-94b4-9e4e7e7b513d   CGGGTTCCGGCGGCATTTTGCCTTCCTGT   +        1       29  
    aff2493d-ba7a-4613-94b4-9e4e7e7b513d   CGGGTTCCGGCGGCATTTTGCCTTCCTGT   -        1781    1809

    # backward primer
    
    $ seqkit locate -M aff2493d-ba7a-4613-94b4-9e4e7e7b513d.txt -p TATGTATCGTCTGAAAATCTTCTCTCATCCGCC \
        |  csvtk cut -t -f 1,2,4-6 | csvtk pretty -t
    seqID                                  patternName                         strand   start   end
    ------------------------------------   ---------------------------------   ------   -----   ---
    aff2493d-ba7a-4613-94b4-9e4e7e7b513d   TATGTATCGTCTGAAAATCTTCTCTCATCCGCC   +        927     959
    aff2493d-ba7a-4613-94b4-9e4e7e7b513d   TATGTATCGTCTGAAAATCTTCTCTCATCCGCC   -        858     890

**Comment by 326reborn** [comment]
Thanks for your reply! I have known what happened on this sequence. 

And is this means that only one (the longest) matching location is returned in each strand for every primer pair?

**Comment by shenwei356** [comment]
Yes, it's the pitfall.

>   1. Only one (the longest) matching location is returned for every primer pair.

**Comment by 326reborn** [comment]
OK, thank you very much!
