### ISSUE TITLE
mask fasta

### ISSUE THREAD

**Issue by finswimmer** [shenwei356/seqkit#50]
Hello,

it would be nice if `seqkit` could implement something similar to [bedtools maskfasta](https://bedtools.readthedocs.io/en/latest/content/tools/maskfasta.html), but also support streaming of input fasta and output fasta.

fin swimmer

**Comment by shenwei356** [comment]
Dear Fin, what don't you just use bedtools╰😎╮

**Comment by shenwei356** [comment]
Dear Fin, what don't you just use bedtools╰😎╮

**Comment by shenwei356** [comment]
oh, you can fork bedtools2 and change the [outfile](https://github.com/arq5x/bedtools2/blob/master/src/maskFastaFromBed/maskFastaFromBed.cpp#L52) to stdout, or create a issue there. ╰😎╮

**Comment by shenwei356** [comment]
oh, you can fork bedtools2 and change the [outfile](https://github.com/arq5x/bedtools2/blob/master/src/maskFastaFromBed/maskFastaFromBed.cpp#L52) to stdout, or create a issue there. ╰😎╮

**Comment by finswimmer** [comment]
Hello @shenwei356 ,

I'm not familiar with C++ so forking isn't an option for now. I'm pretty sure I could write something in python, but I thought this function would fit quite nice into seqkit. If not feel free to close this feature request and I will create an issue on bedtools.

fin swimmer
