### ISSUE TITLE
"[ERRO] fastx: bad fastq format" when sampling fastq by proportion

### ISSUE THREAD

**Issue by JunHuang023** [shenwei356/seqkit#51]
This is the version of Seqkit I am using right now. 
SeqKit -- a cross-platform and ultrafast toolkit for FASTA/Q file manipulation

Version: 0.9.0

the current stable view installed by conda

I am not sure that this is the issue of seqkit, probably my data files are problematic. 

Here is the problem which I had:

I was trying to sample sequence from a fastq file ( the original files have very large sizes), 
the original files 
```
cat original1.fastq | seqkit sample -p 0.001 -o new1_0.001.fastq &
cat original2.fastq | seqkit sample -p 0.001 -o new2_0.001.fastq &
```
it worked in the beginning,
```
[INFO] sample by proportion
[INFO] sample by proportion
```
but exited with an error:
```
[ERRO] fastx: bad fastq format
[ERRO] fastx: bad fastq format
```

```
[2]  + Broken pipe                   cat original1.fastq |
       Exit 255                      seqkit sample -p 0.001 -o original1_0.001.fastq
```
I searched with the term "fastx: bad fastq format", 
found something like [https://github.com/shenwei356/bio/blob/master/seqio/fastx/reader.go ](url),
but could no make sense what went wrong. 
Any idea about what went wrong or suggestion for solving the problem?

Thanks!

**Comment by shenwei356** [comment]
check the input file

    head read_1.fq

**Comment by JunHuang023** [comment]
> check the input file
> 
> ```
> head read_1.fq
> ```

Here is result of the "head" command, 
sorry that I still have no idea what went wrong ...

```
@J00179:39:HV3N5BBXX:5:1101:24992:1437 1:N:0:4
GGGNAATAGAGGTGTGGTGGGGTGATGGTGGGGTGAAGGTGGGGTGGGTGGAAGGGTGGGGGTTGTGGGTTAGTTTGGGGGCAGATCGGAAGANCACACG
+
AA7#FFFJJJFFFAJJJJAJJJFFJ7AFJFJJJ7AJJJA-JJFJAJFF7FJ<FFFJ<JJJJJ-A7-7F-77<FA-A-7FFJ-AAJ-FJJF7<-#AAF<F)
@J00179:39:HV3N5BBXX:5:1101:25012:1437 1:N:0:4
ATANTAGTTAGAAAGGTTAAGATTAAAAATTGAGGTGATAGTAGATGTTGGCGAGGATGTGGATAAAGAGGAATATTTGTGAATTGTTGGGGGNAGATCG
+
```
Thanks for any further idea or suggestion.

**Comment by shenwei356** [comment]
your reads file may be incomplete.

firstly, count the lines

    wc -l *.fq

**Comment by JunHuang023** [comment]
> your reads file may be incomplete.
> 
> firstly, count the lines
> 
> ```
> wc -l *.fq
> ```
Hi Shenwei,
Thanks for your suggestion and sorry for my late reply.
Here is the result of "wc" command:
```
wc -l original1.fastq
5384553449 original1.fastq
```
If you have any idea about it, please kindly let me know.

**Comment by shenwei356** [comment]
The `original1.fastq` is indeed incomplete, please check it.

You know, one FASTQ record has 4 lines, but 5384553449 is not times of 4.

**Comment by yangyxt** [comment]
I had the same error and the line number of my fastq file is 62671088

**Comment by shenwei356** [comment]
try sana before xxx. https://bioinf.shenwei.me/seqkit/usage/#sana

    sana sanitize broken single line fastq files
