### ISSUE TITLE
--two-pass flag only uses two sequnces in sort 

### ISSUE THREAD

**Issue by Snerken** [shenwei356/seqkit#52]
### Prerequisites
I am using v0.9.1-dev and have read "seqkit sort --help"
### Describe your issue

I am following the examples given in the chapter on SEQKIT in the Biostar Handbook Bioinformatics course. 
When I use the --two-pass (-2) flag with the sort function the program just returns two sequences. This does not happen when the two-pass flag is omitted.

Example with two-pass flag:
Fri Oct 05 snerx@kali-linux:~/BioPython/biostar-handbook-September-2017/Lectures/seqkit_fastq 
$ seqkit sort --by-length --two-pass viral.1.1.genomic.fna.gz > viral.genomic.sorted_2pass.fa
[INFO] read and write sequences to tempory file: viral.1.1.genomic.fna.gz.fastx ...
[INFO] create and read FASTA index ...
[INFO] create FASTA index for viral.1.1.genomic.fna.gz.fastx
[INFO] read sequence IDs and lengths from FASTA index ...
[INFO] 2 sequences loaded
[INFO] sorting ...
[INFO] output ...

Example without two-pass flag:
$ seqkit sort --by-length viral.1.1.genomic.fna.gz > viral.genomic.sorted.fa
[INFO] read sequences ...
[INFO] 7 sequences loaded
[INFO] sorting ...
[INFO] output ...

Seems like a bug of some kind to me.

Regards

TEF
Bodø
Norway

**Comment by shenwei356** [comment]
Hi @Snerken ,  it is a BUG existed for almost 2 years.

Affected commands include `sort`, `shuffle`, `split`, it occurs when using `-2/--two-pass` to process `.gz` files.

Fixed now: [v0.9.1-dev2](https://github.com/shenwei356/seqkit/releases/tag/v0.9.1-dev2)
