### ISSUE TITLE
sliding -g added empty characters to the last sequence.

### ISSUE THREAD

**Issue by songtaogui** [shenwei356/seqkit#54]
Hi, dear shenwei

Your `seqkit` does help me a lot.

However, when using `sliding`  command with greedy options (`-g`), it seems that the program added some `null` characters to the end of the last sequence ( in order to fill the sequence to the windows size? ). 

For example: ( I am using `seqkit v0.9.1` )
By runing 
`seqkit sliding -g  -s 1000 -W 1000 chr7.fa -o - | seqkit fx2tab | tail -n 1 | seqkit tab2fx | less`
I got:
```
>chr7_sliding:177932001-177933000
GGGCTTTAGGGTTTGGGGCTCGGGATTTAGAGTTTTGGATTTTGGGGTTCGAGGTTTAGG
GTTTCGGTTTGAGGGTTAGCGTCTTGGGTTTAATGTTTAGGGTTTGGAGTTTGGGATTTG
AGATTTTGTGTTTTGGGTGTCGGATTTTAGTTTTAGGGTTCGGTGTTTGGGGTTTATGCT
TTAGTATTTGGGGCTCGAGGATAAGGATTTTGGGGTTTGGGGTTTAGTGTGATGTAGCTC
ACATGAGGCTAAAAACTTGTTTCAGTGGCCAAAACATGGGTGGCAGGCGCGAGGCGTGAA
TTTTTTGTTCGACGACGAAAACATGTGTCGCGGGAGATCAAATTTGGAGTTTGGGGTTTG
GAGTTTTGTTTTCTGGTGATCGGGTTTTTGTTTTAGGGTTCGAGGTATAGGGTTCATAAT
TTAGGGTTCGGGGTTCAGGGTTTGGGCTTTAGGGTTTGGGGCTCGGTGTTTGGCGTTCGA
GGTTTAGGGTTTCGGTTTGAGGGTTAGCGTTTGGGGATTAAGGTTTAGGGTTTGGAGTTT
GGCATTTAAGATTTTGTGTTTTGGGGGTCAGATTTTAGTTTTAGGGTTCGGTGTTTTATG
GTTTAGGGTTTGGTGCTCGAGGTTTAGGGTTTTGGGGTTTAGGGTTTGCTGTGATGTAGC
TCATGGGAGGCCAAAACCAGCCTTACCTGTTTCAGTGGTGAAAATATGGGTGGCCGACGA
GAGGCATGAAATCTTTGTTCGATGACAAAAACATGTGTCGCAGAAGGCCAAAAATAGTAT
TACCGGCCTCCTCGGACCAAAACGTGTACTATGGTTTGGACAATAAAATTATACTGTCTT
GAAATTTACAGAAT^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@
```
This "^@" in the `less` command seems to be some null character, it may not influence the downstream analysis, but it caused several empty lines.  Any idea to avoid this?

Thank you.

Best wishes,
SongtaoGui

**Comment by shenwei356** [comment]
Dear @songtaogui , it's fixed.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2583536/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2583537/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/2583538/seqkit_windows_amd64.exe.tar.gz)

**Comment by songtaogui** [comment]
Dear @shenwei356 , excellent ! thank you for the update.
