### ISSUE TITLE
seqkit translate: error message for frames -1,-2,-3

### ISSUE THREAD

**Issue by BreNa787** [shenwei356/seqkit#55]
Dear shenwei356,

thank you for the great tool it helps a lot. 

I tried to translate sequences in a multi fasta file using seqkit translate (seqkit v0.9.1).  According to the help all 6 frames ( 1, 2, 3, -1, -2, -3) could be used and frames  1,2 and 3 work nicely. 

E.g. 
seqkit translate  --frame 1 --transl-table 2 test.fa > test_translated_1.txt; 

However, the other three frames (-1, -2, -3) produce an error message.

E.g.   
seqkit translate  --frame -1 --transl-table 2 test.fa > test_translated_-1.txt;
[ERRO] seq: invalid frame: -1. available: 1, 2, 3

Any idea what went wrong or suggestion for solving the problem?
Thanks!

[test.txt](https://github.com/shenwei356/seqkit/files/2585159/test.txt)

**Comment by shenwei356** [comment]
Sorry, my fault. 

Please use these preview version before next release.

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2586168/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2586169/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/2586170/seqkit_windows_amd64.exe.tar.gz)

**Comment by BreNa787** [comment]
Thank you very much for fixing it!!!!

**Comment by BreNa787** [comment]
Hi, I am sorry. Just one last question. Is it supposed to work for multi-fasta files or just for files with one sequence. It seems that the translations between frame 1 and frame -1 (or 2/-2, 3/-3) differ only for the first sequence but are identical for all following sequences. 
Thank you.

**Comment by shenwei356** [comment]
So sorry, I'm too careless! Wait me 3 hours!

**Comment by shenwei356** [comment]
So sorry, I'm too careless! Wait me 3 hours!

**Comment by shenwei356** [comment]
@BreNa787 
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2589140/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2589141/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/2589142/seqkit_windows_amd64.exe.tar.gz)

**Comment by BreNa787** [comment]
Looks good! Thank you very much for the fix and the very fast response.

**Comment by shenwei356** [comment]
[v0.9.2](https://github.com/shenwei356/seqkit/releases/tag/v0.9.2) including this fix is out.
