### ISSUE TITLE
seqkit translate: Error when any N in the sequence

### ISSUE THREAD

**Issue by jamesseekings** [shenwei356/seqkit#56]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

**Comment by jamesseekings** [comment]
Hi,
Firstly, thanks for a fantastic tool.

I am trying to use seqkit to translate nucleotide sequence into amino acid but if my amino acid sequence has any n in it then seqkit fails with a warning message 
seqkit translate --frame 1 'MySequence.fasta' 
[ERRO] seq: invalid codon

MySequence.fasta is a consensus sequence generated by samtools from illumina data and often does contain n characters. Please can you suggest any way around this?
Could seqkit translate still translate the sequence but give an X if an n character means it can't decide which amino acid should be at that location?

Many thanks
James

**Comment by shenwei356** [comment]
Sure, I'll add an option `--ignore-invalid-condon`.

**Comment by shenwei356** [comment]
Dear @jamesseekings , a new flag added:

```
  -x, --allow-unknown-codon   translate unknown code to 'X'. And you may not use flag --trim which removes 'X'
```
Now:

```
$ echo -ne ">t\nACGGTN\n" | seqkit translate
[ERRO] unknown codon detected, you can use flag -x/--allow-unknown-codon to translate it to 'X'.

$ echo -ne ">t\nACGGTN\n" | seqkit translate -x
>t
TX
```

Pre-release:

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2620069/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2620070/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/2620071/seqkit_windows_amd64.exe.tar.gz)

**Comment by jamesseekings** [comment]
Fantastic. Thank you
