### ISSUE TITLE
Don't change the seq_id generate by « seqkit subseq --bed » subcommand

### ISSUE THREAD

**Issue by arnome** [shenwei356/seqkit#58]
### Prerequisites

- [x ] make sure you're are using the latest version by `seqkit version`
- [x ] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue
I use `seqkit subseq` subcommand in a workflow within I need to extract subsequences describe in a bed file. The problem is that this command rewrite the seq_id with the values in the bed file and this lead to error later in the workflow (it's important to keep the same seq_id). 
I didn't find any option to avoid this and so I try to handle the legacy seq_id with the `--id-regexp` option
but I can't succeed to express the right regex in re2 (and don't know if it's the right way to do this).

for example the legacy seq_id is
`>J0-D0-1_886`
and the new seq_id generate by the subcommand is 
`>J0-D0-1_886_3-85:+ giqhia-ffe`

   First of all, I don't know if the --id-regexp embrace all the fasta seq header (I guess not) or just the id ( `J0-D0-1_886` and `J0-D0-1_886_3-85:+` in my case).

In the just-the-id case I couldn't find a way to handle the legacy id. The default regex (`"^([^\\s]+)\\s?"`) keep the seq_id 
```
seqkit subseq --bed test_subseq.bed test.fasta --quiet --id-regexp "^([^\\s]+)\\s?"
>J0-D0-1_513_3-90:+ giqhia-ffe
giqhiacgardiygtvetlradglpfmpsppltyfekidarlpchgedvarlqrdgilid
gegvvegghtkvllqifsanaigpiffe
```
and if I try to capture all the caracters before `:` The script faill:
```
seqkit subseq --bed test_subseq.bed test.fasta --quiet --id-regexp "^([^\\s]+):\\s?"
[WARN] sequence () not found in file: test.fasta
```

What is the right way to not change seq_id and so keep the leagcy ?

Thank's 
arnome

**Comment by shenwei356** [comment]
Before I add a new option to keep the original id, you can use seq to define id to keep

    seqkit subseq --bed test_subseq.bed test.fasta --quiet  \
        | seqkit seq -i --id-regexp '^(.+?)_\d+\-\d+\:'

**Comment by arnome** [comment]
Hi Wei Shen,
it works like a charm. Thank you for this very useful kit !
arnome.
