### ISSUE TITLE
Possible bug seqkit stats?

### ISSUE THREAD

**Issue by lakhujanivijay** [shenwei356/seqkit#6]
**Tool used:** [seqkit][1]

Dummy fasta file (fasta.fa):

    >test1
    GCATCGATCAGCTACGATCATCACTA
    GNNNNNNTACATCAGCACTACATCACTNNNNN
    >test2
    GTACGCTACGANNNGCTACGACTACGATATATATATATATATATATATATATATATATATATAT
    GCTACGATCACNTACATCGACTA
    >test3
    GTGTGCTACATCATCACTACGTACTACAT
    >test4
    AA

**Command:** 

    ./seqkit stat fasta.fa

**Output:**

    file      format  type  num_seqs  sum_len  min_len  avg_len  max_len
    fasta.fa  FASTA   DNA          4      176        0       44       87

**Problem:**
**min_len** =0 (however, minimum length should be 2; sequence id "test4")

**Validation using seqkit:**

**Command:**

    ./seqkit fx2tab -l fasta.fa

**Output:**

    test1	GCATCGATCAGCTACGATCATCACTAGNNNNNNTACATCAGCACTACATCACTNNNNN		58
    test2	GTACGCTACGANNNGCTACGACTACGATATATATATATATATATATATATATATATATATATATGCTACGATCACNTACATCGACTA		87
    test3	GTGTGCTACATCATCACTACGTACTACAT		29
    test4	AA		2

**Notice: length of sequence test4 is "2"**

Is it a bug or I misunderstood something?

  [1]: https://github.com/shenwei356/seqkit
  [2]: https://www.biostars.org/u/4664/

**Comment by shenwei356** [comment]
Sorry for that, it's fixed in the latest version, please update.

**Comment by lakhujanivijay** [comment]
Thanks! Perfect!

One more question please - How can I get contigs from scaffolds (use seqkit). Please see below

**input scaffolds file**
```
>test1
GCATCGATCAGCTACGATCATCACTA
GNNNNNNTACATCAGCACTACATCACTNNNNN
>test2
GTACGCTACGANNNGCTACGACTACGATATATATATATATATATATATATATATATATATATAT
GCTACGATCACNTACATCGACTA
>test3
GTGTGCTACATCATCACTACGTACTACAT
>test4
AA
```
**output contigs file**
```
>test1
GCATCGATCAGCTACGATCATCACTA
G
>test1_2
ACATCAGCACTACATCACT
>test2
GTACGCTACGA
>test2_1
GCTACGACTACGATATATATATATATATATATATATATATATATATATAT
GCTACGATCACNTACATCGACTA
>test3
GTGTGCTACATCATCACTACGTACTACAT
>test4
AA
```
i.e. essentially splitting the sequences by n/N.

**Comment by shenwei356** [comment]
We talked about this: https://www.biostars.org/p/211400/
