### ISSUE TITLE
Feature request: fx2tab average read quality

### ISSUE THREAD

**Issue by MichelMoser** [shenwei356/seqkit#60]
Dear seqkit developers, 

I would like to get average read quality for each read (long-read nanopore data). 
Is it possible to implement this as an option in fx2tab tool? 

In python it would look something like this
```
def ave_qual(quals):
    """Calculate average basecall quality of a read.
    Get integer quality scores of a read and return the average quality for that read
    Convert Phred scores to probabilities and calculate average error probability, then
    convert average back to Phred scale
    """
    if quals:
        return -10 * log(sum([10**(q / -10) for q in quals]) / len(quals), 10)
    else:
        return None

```

Would be a great to get this implemented in C for larger datasets and speed up for long-read users and to do fast filtering and statistic overview of the data.

Thank you, 
Michel

**Comment by shenwei356** [comment]
Looks easy to implement.

BTW, seqkit was written in Go not C.

**Comment by MichelMoser** [comment]
that would be great!
Oh, sorry for the confusion. 
looks like i have to look into Go for better performance then :)

**Comment by shenwei356** [comment]
Is the  formula right?

```
$ echo -ne "@a\nAAA\n+\nIII\n" | ./seqkit fx2tab -q -b 33
a       AAA     III     39
$ echo -ne "@a\nAAA\n+\nHHH\n" | ./seqkit fx2tab -q -b 33
a       AAA     HHH     30
$ echo -ne "@a\nAAA\n+\nGGG\n" | ./seqkit fx2tab -q -b 33
a       AAA     GGG     30
$ echo -ne "@a\nAAA\n+\nFFF\n" | ./seqkit fx2tab -q -b 33
a       AAA     FFF     30
```

Try
[seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2779068/seqkit_linux_amd64.tar.gz)
[seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/2779069/seqkit_windows_amd64.exe.tar.gz)

[seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2779065/seqkit_darwin_amd64.tar.gz)

**Comment by MichelMoser** [comment]
Hi, 

I think to conversion is not correct yet. 
But i can try and tweak to code myself.

I attached example fastq-file with resulting quality scores. 

[test.fq.gz](https://github.com/shenwei356/seqkit/files/2779308/test.fq.gz)
[test.fq.len.qual.txt](https://github.com/shenwei356/seqkit/files/2779310/test.fq.len.qual.txt)
