### ISSUE TITLE
Feature request: Degenerate amino acid sequence

### ISSUE THREAD

**Issue by shiva1387** [shenwei356/seqkit#61]
Seqkit has a degenerate character for nucleotide 'N': "[ACGT]", can something similar be considered for amino acids? 'X': "[ARNDCEQGHILKMFPSTWYV]"

**Comment by shenwei356** [comment]
which command? It's not supported now. How about using regular expression

**Comment by shiva1387** [comment]
This is for grep and locate. Regular expression works, just curious as currently SeqKit supports N for nucleotides. A similar option for amino acids would be X. 

Believe the expansions are called in from https://github.com/shenwei356/bio/blob/310b5d47a7b940f81a267b56a3d02c575531f2a8/seq/seq.go

```
echo '>seq\nAUGGACUG' | seqkit locate -i -d -p ACUN
```

Similar one for amino acids does not work

```
echo '>seq\nSDLSIHWVR' | seqkit locate --seq-type protein -i -d -p XLSIH
```

However, the workaround can be using '.' and regex

```
echo '>seq\nSDLSIHWVR' | seqkit locate --seq-type protein -i -p .LSIH
```

**Comment by shenwei356** [comment]
Oh, solved, I supported this long time ago, but forgot to setting `X`.

Use this pre-version

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2787529/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2787530/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/2787531/seqkit_windows_amd64.exe.tar.gz)

**Comment by shiva1387** [comment]
Thanks, thats awesome, this works fine! Glad to have found this tool:) Save's hours of bioinformaticians time.
