### ISSUE TITLE
Consider gaps in translation

### ISSUE THREAD

**Issue by fungs** [shenwei356/seqkit#63]
Hi, here is another useful suggestion, IMO.

Translation supports unknown codons via the -x command line switch already which is near perfect. However, if translating entire multiple sequence alignments from nucleotide to protein space, it would be good to preserve gap symbols, e.g. '---' becomes '-' instead of 'X'. Note, this is only a tiny exception to test.

The only decision remaining would be how to treat partial codons (codons containing gaps), I would be fine with either decision ('-' or 'X'), but IMO the 'X' could maybe make a little more sense here because the codon is partially defined.

How are you feeling about this issue?

Best,
Johannes

**Comment by shenwei356** [comment]
Good suggestions.

**Comment by fungs** [comment]
You are correct, gapped translation should be treated carefully in some cases.

I would love to see that feature because I could then replace a simple part of a pipeline currently based on fhcrc/seqmagick with seqkit, easily.

Thx!
