### ISSUE TITLE
Partial codon translation

### ISSUE THREAD

**Issue by fungs** [shenwei356/seqkit#64]
Hi @shenwei356, this is a tiny enhancement suggestion related to #63.

Many nucleotide sequences contain ambiguous characters (most importantly N). A codon which contains an N is currently always translated to X using the 'translate -x' parameter. However, many nucleotide sequence with partial codons containing e.g. Ns can be unambigously translated into a corresponding amino acid, and that is routinely being done in the databases at NCBI etc. Adding those codons would simply mean to extend the translation tables with codons using the N (or maybe other ambiguous) characters.

Example: GGN -> G in standard genetic code

This change would increase the number of protein sequences for which de-novo translation with seqkit differs from the corresponding database entries and would reduce the number of X characters in the translated sequences.

Thx and keep on going with this great program!

Best,
Johannes

**Comment by shenwei356** [comment]
Try it:

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2864731/seqkit_darwin_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/2864733/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2864732/seqkit_linux_amd64.tar.gz)

I add this feature by [automatically detecting these kind of codons](https://github.com/shenwei356/bio/commit/84af64d2633e03e09344fed4e16f9da00aedce2c#diff-d7cd597c7e3735bf185107a381e065a4R312), so don't worry the completeness and accuracy. E.g., these in table 1 include:

```
ACN	T
CCN	P
CGN	R
CTN	L
GCN	A
GGN	G
GTN	V
TCN	S
```

**Comment by fungs** [comment]
I will test it this week and report back to you!

**Comment by fungs** [comment]
I tested the program and it seems to work just fine.

The only difference I get now are due to other ambiguous bases, for instance GCR->A and TGY->C. I think this is only a minor issue and might or might not be implemented in seqkit.

To give you an impresseion, in my current set of coding nucleotide sequences, the statistics about ambiguous characters besides ACGTN are as follows:

   3018 Y
   1626 R
   1374 S
    835 K
    672 M
    388 W
     10 V
      9 H
      4 D
      3 B

Best,
Johannes

**Comment by fungs** [comment]
See https://en.wikipedia.org/wiki/FASTA_format for a table of possible characters, I think some of them are almost never used. If you don't want to support them, you can maybe add an easy option in `seqkit seq` to convert them to N.

**Comment by shenwei356** [comment]
Since ambiguous bases are common in CDS, I'll implement this, it's not hard.

**Comment by shenwei356** [comment]
Ambiguous bases

```
base    bases
A       A
C       C
G       G
T/U     T
M       A/C
R       A/G
W       A/T
S       C/G
Y       C/T
K       G/T
V       A/C/G
H       A/C/T
D       A/G/T
B       C/G/T
N       A/C/G/T
```

One example

```
b1      b2      b3      aa
A       T       A       I
A       T       C       I
A       T       G       M
A       T       T       I
```

Rules:

```
ATG -> M

ATH -> I # A/C/T

ATM -> I # A/C
ATW -> I # A/T
ATY -> I # C/T
```

**Comment by shenwei356** [comment]
@fungs All ambiguous bases in codon supported. 

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2897169/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2897170/seqkit_linux_amd64.tar.gz)

```
$ echo -ne ">seq\nACN---CCN---- ----ATG---ATH---ATM---ATW---aty---ATN\n" \
   | seqkit translate -t dna
>seq
T-P-X-M-I-I-I-I-X
```

**Comment by shenwei356** [comment]
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2897714/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/2897715/seqkit_linux_amd64.tar.gz)

You can list details of translate tables:

```
$ seqkit translate -l 0
1       The Standard Code
2       The Vertebrate Mitochondrial Code
3       The Yeast Mitochondrial Code
4       The Mold, Protozoan, and Coelenterate Mitochondrial Code and the Mycoplasma/Spiroplasma Code
5       The Invertebrate Mitochondrial Code 
6       The Ciliate, Dasycladacean and Hexamita Nuclear Code
9       The Echinoderm and Flatworm Mitochondrial Code
10      The Euplotid Nuclear Code
11      The Bacterial, Archaeal and Plant Plastid Code
12      The Alternative Yeast Nuclear Code
13      The Ascidian Mitochondrial Code
14      The Alternative Flatworm Mitochondrial Code
16      Chlorophycean Mitochondrial Code
21      Trematode Mitochondrial Code
22      Scenedesmus obliquus Mitochondrial Code
23      Thraustochytrium Mitochondrial Code
24      Pterobranchia Mitochondrial Code
25      Candidate Division SR1 and Gracilibacteria Code
26      Pachysolen tannophilus Nuclear Code
27      Karyorelict Nuclear
28      Condylostoma Nuclear
29      Mesodinium Nuclear
30      Peritrich Nuclear
31      Blastocrithidia Nuclear
```

```
$ seqkit translate -l 1
The Standard Code (transl_table=1)
Source: https://www.ncbi.nlm.nih.gov/Taxonomy/taxonomyhome.html/index.cgi?chapter=tgencodes#SG1

Initiation Codons:
  ATG, CTG, TTG

Stop Codons:
  TAA, TAG, TGA

Stranslate Table:
  AAA: K, AAC: N, AAG: K, AAT: N
  ACA: T, ACC: T, ACG: T, ACT: T
  AGA: R, AGC: S, AGG: R, AGT: S
  ATA: I, ATC: I, ATG: M, ATT: I

  CAA: Q, CAC: H, CAG: Q, CAT: H
  CCA: P, CCC: P, CCG: P, CCT: P
  CGA: R, CGC: R, CGG: R, CGT: R
  CTA: L, CTC: L, CTG: L, CTT: L

  GAA: E, GAC: D, GAG: E, GAT: D
  GCA: A, GCC: A, GCG: A, GCT: A
  GGA: G, GGC: G, GGG: G, GGT: G
  GTA: V, GTC: V, GTG: V, GTT: V

  TAA: *, TAC: Y, TAG: *, TAT: Y
  TCA: S, TCC: S, TCG: S, TCT: S
  TGA: *, TGC: C, TGG: W, TGT: C
  TTA: L, TTC: F, TTG: L, TTT: F

```

```
$ seqkit translate -L 1
The Standard Code (transl_table=1)
Source: https://www.ncbi.nlm.nih.gov/Taxonomy/taxonomyhome.html/index.cgi?chapter=tgencodes#SG1

Initiation Codons:
  ATG, CTG, TTG

Stop Codons:
  TAA, TAG, TGA

Stranslate Table:
  AAA: K, AAC: N, AAG: K, AAR: K, AAT: N, AAY: N
  ACA: T, ACC: T, ACM: T, ACG: T, ACR: T, ACS: T, ACV: T, ACT: T, ACW: T, ACY: T, ACH: T, ACK: T, ACD: T, ACB: T, ACN: T
  AGA: R, AGC: S, AGG: R, AGR: R, AGT: S, AGY: S
  ATA: I, ATC: I, ATM: I, ATG: M, ATT: I, ATW: I, ATY: I, ATH: I

  CAA: Q, CAC: H, CAG: Q, CAR: Q, CAT: H, CAY: H
  CCA: P, CCC: P, CCM: P, CCG: P, CCR: P, CCS: P, CCV: P, CCT: P, CCW: P, CCY: P, CCH: P, CCK: P, CCD: P, CCB: P, CCN: P
  CGA: R, CGC: R, CGM: R, CGG: R, CGR: R, CGS: R, CGV: R, CGT: R, CGW: R, CGY: R, CGH: R, CGK: R, CGD: R, CGB: R, CGN: R
  CTA: L, CTC: L, CTM: L, CTG: L, CTR: L, CTS: L, CTV: L, CTT: L, CTW: L, CTY: L, CTH: L, CTK: L, CTD: L, CTB: L, CTN: L

  MGA: R, MGG: R, MGR: R

  GAA: E, GAC: D, GAG: E, GAR: E, GAT: D, GAY: D
  GCA: A, GCC: A, GCM: A, GCG: A, GCR: A, GCS: A, GCV: A, GCT: A, GCW: A, GCY: A, GCH: A, GCK: A, GCD: A, GCB: A, GCN: A
  GGA: G, GGC: G, GGM: G, GGG: G, GGR: G, GGS: G, GGV: G, GGT: G, GGW: G, GGY: G, GGH: G, GGK: G, GGD: G, GGB: G, GGN: G
  GTA: V, GTC: V, GTM: V, GTG: V, GTR: V, GTS: V, GTV: V, GTT: V, GTW: V, GTY: V, GTH: V, GTK: V, GTD: V, GTB: V, GTN: V

  TAA: *, TAC: Y, TAG: *, TAR: *, TAT: Y, TAY: Y
  TCA: S, TCC: S, TCM: S, TCG: S, TCR: S, TCS: S, TCV: S, TCT: S, TCW: S, TCY: S, TCH: S, TCK: S, TCD: S, TCB: S, TCN: S
  TGA: *, TGC: C, TGG: W, TGT: C, TGY: C
  TRA: *
  TTA: L, TTC: F, TTG: L, TTR: L, TTT: F, TTY: F

  YTA: L, YTG: L, YTR: L

```

**Comment by fungs** [comment]
Thanks, I did not test this in depth but the binaries seem to be functional in my tests.

Great job!

**Comment by shenwei356** [comment]
If no more bugs or feature requests, I'd like to release a new version (v0.10.1) soon.

SeqKit v0.10.1

- `seqkit fx2tab`: new option `-q/--avg-qual` for outputting average read quality. [#60](https://github.com/shenwei356/seqkit/issues/60)
- `seqkit grep/locate`: fix support of `X` when using `-d/--degenerate`. [#61](https://github.com/shenwei356/seqkit/issues/61)
- `seqkit translate`:
    - new flag `-M/--init-codon-as-M` to translate initial codon at beginning to 'M'. [#62](https://github.com/shenwei356/seqkit/issues/62)
    - translates `---` to `-` for aligned DNA/RNA, `-X` needed. [#63](https://github.com/shenwei356/seqkit/issues/63)
    - supports codons containing ambiguous base', e.g., `GGN->G`, `ATH->I`. [#64](https://github.com/shenwei356/seqkit/issues/64)
    - new flag `-l/--list-transl-table` to show details of translate table N
    - new flag `-l/--list-transl-table-with-amb-codons` to show details of translate table N (including ambigugous codons)
