### ISSUE TITLE
seqkit split ignores the -O option when input is stdin

### ISSUE THREAD

**Issue by tomas-pluskal** [shenwei356/seqkit#65]
### Prerequisites

Using seqkit v0.9.2

### Describe your issue

```
$ cat transcriptome.fasta | seqkit split -O myoutdir -s 100
[ERRO] outdir not empty: stdin.split, use -f (--force) to overwrite
```

seqkit tries to write output to "stdin.split", even though I provided the "-O myoutdir" option.

**Comment by shenwei356** [comment]
Thanks for reporting this It's [fixed](https://github.com/shenwei356/seqkit/commit/30337a10aae36ab39fc3ec767d16596e09b41cbc), but not released yet. 

Please use this [pre-release](https://github.com/shenwei356/seqkit/issues/64#issuecomment-463591965).

**Comment by tomas-pluskal** [comment]
Ok, thanks!
