### ISSUE TITLE
Reg: Support for Named pipes

### ISSUE THREAD

**Issue by harish0201** [shenwei356/seqkit#67]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version` : Version: 0.10.1
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem

No issue, but curious about usage of named pipes.

I'm planning to merge and split a couple of fasta files for whatever reason my boss wants. Unfortunately some of the datasets are split across multiple runs like so:

>S1_L4_R1.fq.gz
>S1_L4_R2.fq.gz
>S1_L5_R1.fq.gz
>S1_L5_R2.fq.gz

What I'm planning to do:

mkfifo R1 R2
cat \*R1\*.gz > R1 &
cat \*R2\*.gz > R2 &

seqkit split2 -p 4 -O S -1 R1 -2 R2

I tried this for a sample, but unfortunately I seem to be encountering the following error:
fastx: bad fastq format

Which is what made me curious, does seqkit split2 support named pipes in linux?

* [ ] provide a reproducible example

**Comment by shenwei356** [comment]
seqkit split2 -p 4 -O S -1 <(gzip -dc *R1*.fq.gz ) -2 <( gzip -dc *R2*.fq.gz )

**Comment by harish0201** [comment]
Awesome, I'll try this out!
