### ISSUE TITLE
feature request- to reach patterns from two files

### ISSUE THREAD

**Issue by Jigyasa3** [shenwei356/seqkit#68]
Hey 

Is it possible to read patterns from two files and extract the fasta headers matching both patterns in the same header?
For example,
file1.txt
272-01
229-03
301-56

file2.txt
NODE34400number566_1
NODE56677number7899_1_1
NODE45666number34555_1_2

sequence.fasta
>272-01__<text>__<text>__NODE34400number566_1
>229-03__<text>__<text>__NODE56677number7899_1_1

**Comment by shenwei356** [comment]
Try
    
    cat seqs.fa | seqkit grep -r -f file1.txt | seqkit grep -r -f file2.txt

**Comment by shenwei356** [comment]
A stricter and faster way:

    cat seqs.fa \
        | seqkit grep --id-regexp '^(.+)__'  -f file1.txt \
        | seqkit grep --id-regexp '__(.+)$'  -f file2.txt

**Comment by Jigyasa3** [comment]
thank you!
