### ISSUE TITLE
count the patterns

### ISSUE THREAD

**Issue by Jigyasa3** [shenwei356/seqkit#69]
Hey Shen!

Grep allows to count the number of hits to a pattern. But the output is zero and non-zero counts.
Is it a way in seqkit to only print non-zero hits to a pattern?

eg- 
$pattern.txt
file1
file2
file2

$fastafile1.fasta
>file1
>file1
>file1
>file2
>file3

$fastafile2.fasta
>file2
>file2
>file3

$grep -c -F -f pattern.txt fasta* #this gives the total count
fastafile1.fasta:5
fastafile2.fasta:3

$grep -c "file1" fasta* #gives zero counts too
fastafile1.fasta:3
fastafile1.fasta:0

<what I want>
file1-
fastafile1.fasta:3 #skipping zero counts

file2-
fastafile1.fasta:1
fastafile2.fasta:2

**Comment by shenwei356** [comment]
The given examples are not FASTA files and `seqkit` is not used. Besides, the code snippets are not well formatted. 

To skip zero counts, just use `grep -v :0`.

    grep -c "file1" fasta* | grep -v :0
