### ISSUE TITLE
one possible function

### ISSUE THREAD

**Issue by wjidea** [shenwei356/seqkit#7]
Hi Shenwei,

I really like your seqkit tool, a really neat implement in golang. I was using pyfaidx for some simple sequence query work, such as obtain sequence record based on the sequence ID. I am sure you should have this function implemented in your package, but I could not find the function description after skimming through your documentation. Could you please show me how to use this function in seqkit?

Thanks,

Jie

**Comment by shenwei356** [comment]
`seqkit grep`: search sequences by pattern(s) of name or sequence motifs

Examples (more on http://bioinf.shenwei.me/seqkit/usage/#grep)

```
# based on sequence ID
seqkit grep -p id1 seqs.fa

# based on whole sequence header
seqkit grep -n -p "id comment" seqs.fa

# using regular expression
seqkit grep -r -p "^hsa" seqs.fa

# multiple queries
seqkit grep -p id1 -p id2 seqs.fa

# id files
seqkit grep -f id_list_with_one_record_per_line.txt seqs.fa
```

**Comment by wjidea** [comment]
Thanks
