### ISSUE TITLE
could it be possible to use seqkit to filter fasta files based on a value in the fasta header.

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/seqkit#70]
Hi, 
could it be possible to use seqkit to filter fasta files based on values in the fasta header.
Details:
The fasta header of the output contigs of the assembler I am using looks like this 
`>NODE_100_length_628_cov_0.818363_ID_199`
based on this coverage value `cov_0.818363`, I need to extract only the contigs that have **at least** a value of cov = 3 (`cov_3.0`).

Thanks

**Comment by shenwei356** [comment]
using `seqkit fx2tab` and filtering using `awk` or `csvtk mutate` and `csvtk filter`, `seqkit tab2fx` in the end

**Comment by shenwei356** [comment]
```
$ seqkit fx2tab s.fa \
    | csvtk mutate -H -t -p 'cov_([\d\.]+)_' \
    | awk '$3 > 0 {print $1"\t"$2}' \
    | seqkit tab2fx
```
