### ISSUE TITLE
Could it be possible to filter a multifasta file based on a vlalue in the fasta header?

### ISSUE THREAD

**Issue by MostafaYA** [shenwei356/seqkit#71]
Hello, 

the fasta header of the output contigs of the assembler I am using looks like this `>NODE_100_length_628_cov_0.818363_ID_199`. 
Based on this value `cov_0.818363` , could it be possible to use `seqkit` to extract the contigs that **at least** have cov =3 (`cov_3.0`)?

Thanks,

**Comment by shenwei356** [comment]
duplicated issue
