### ISSUE TITLE
Feature request/query

### ISSUE THREAD

**Issue by Jigyasa3** [shenwei356/seqkit#72]
Hey Shen

I am using 'seqkit common' and 'seqkit grep' command to find common fasta headers among 32 files. 
I have tried both of it as mentioned in the documentation-
a) seqkit common file*.fa -o common.fasta
output- Nothing common . As I have different combinations of common headers  in different files. Not all headers are present in all files.
b)seqkit grep -f <(seqkit seq -n -i small.fq.gz) big.fq.gz
output- This works! As it is able to find the combinations of headers common in a list of "small.fasta" files in comparison to one big.fasta file.

Current code (with a simple for loop)-
eg- for i in *fasta;do seqkit grep -f <(seqkit seq -n -i ${i}) big.fq.gz

Improved code- where the 'seqkit grep' goes through first file against second file, finds common header. Then, takes the common headers and searches the third file. Then, takes the headers common with the third file and compares the fourth file, and so on..

**Comment by shenwei356** [comment]
would you please upload some test files?

**Comment by shenwei356** [comment]
I don't get what your "combinations" are, and the `seqkit common` works as you suggest.

**Comment by Jigyasa3** [comment]
[https://drive.google.com/drive/folders/1ZmZykEh4HV5LkCF2U1Z1Rk65xvd8Bxo_?usp=sharing](url)

I have added a link to the folder containing 5 files.
Combination means that if I start with comparison of file1.fasta with file2.fasta. And if there are 10 common headers, I would like to compare those 10 common headers (output file) with file3.fasta, and so on..
At the same time, compare file1.fasta with file3.fasta. And repeat the above step.
And, compare file1.fasta with all other files present, and repeat the steps.. Until I have a "final" file that has the "best" combination of common headers among all fasta files present.

**Comment by shenwei356** [comment]
`seqkit common` does what you want, but your sequences indeed have no common sequences. 

You can export the IDs and compute their intersection using tools like `csvtk inter`([usage](https://bioinf.shenwei.me/csvtk/usage/#inter)) or [online venn plotting tool](http://bioinfogp.cnb.csic.es/tools/venny/index.html).

I tested with files you upload:

```
$ seqkit common *.fasta | seqkit stats
[INFO] read file: seds-above500-sequenceCOG0092_Treponema_genus.fasta
[INFO] read file: seds-above500-sequenceCOG0201_Treponema_genus.fasta
[INFO] read file: seds-above500-sequenceCOG0533_Treponema_genus.fasta
[INFO] read file: seds-above500-sequenceCOG0541_Treponema_genus.fasta
[INFO] read file: seds-above500-sequenceCOG0552_Treponema_genus.fasta
[INFO] find common seqs ...
[INFO] no common sequence IDs found
file  format  type  num_seqs  sum_len  min_len  avg_len  max_len
-                          0        0        0        0        0

```

Well, let's just compare the first two files:

```
$ seqkit common $(ls *.fasta | head -n 2 | paste -s -d " " ) | seqkit stats
[INFO] read file: seds-above500-sequenceCOG0092_Treponema_genus.fasta
[INFO] read file: seds-above500-sequenceCOG0201_Treponema_genus.fasta
[INFO] find common seqs ...
[INFO] 190 unique sequence IDs found in 2 files, which belong to 190 records in the first file: seds-above500-sequenceCOG0092_Treponema_genus.fasta
[INFO] retrieve seqs from the first file: seds-above500-sequenceCOG0092_Treponema_genus.fasta
file  format  type  num_seqs  sum_len  min_len  avg_len  max_len
-     FASTA   DNA        190  134,613      642    708.5      882
```

Three files:

```
$ seqkit common $(ls *.fasta | head -n 3 | paste -s -d " " ) | seqkit stats                        
[INFO] read file: seds-above500-sequenceCOG0092_Treponema_genus.fasta
[INFO] read file: seds-above500-sequenceCOG0201_Treponema_genus.fasta
[INFO] read file: seds-above500-sequenceCOG0533_Treponema_genus.fasta
[INFO] find common seqs ...
[INFO] 2 unique sequence IDs found in 3 files, which belong to 2 records in the first file: seds-above500-sequenceCOG0092_Treponema_genus.fasta
[INFO] retrieve seqs from the first file: seds-above500-sequenceCOG0092_Treponema_genus.fasta
file  format  type  num_seqs  sum_len  min_len  avg_len  max_len
-     FASTA   DNA          2    1,410      705      705      705
```

Four files:

```
$ seqkit common $(ls *.fasta | head -n 4 | paste -s -d " " ) | seqkit stats 
[INFO] read file: seds-above500-sequenceCOG0092_Treponema_genus.fasta
[INFO] read file: seds-above500-sequenceCOG0201_Treponema_genus.fasta
[INFO] read file: seds-above500-sequenceCOG0533_Treponema_genus.fasta
[INFO] read file: seds-above500-sequenceCOG0541_Treponema_genus.fasta
[INFO] find common seqs ...
[INFO] no common sequence IDs found
file  format  type  num_seqs  sum_len  min_len  avg_len  max_len
-                          0        0        0        0        0
```

By the way, it seems the FASTA headers have redundant information, `NODE_XXXXnumberYYYY`, 
the `XXXX` and `YYYY` are the same. I tried removing `numberYYYY` and got same result.

```
$ seqkit seq -n seds-above500-sequenceCOG0201_Treponema_genus.fasta | head -n 3
229-01-NODE_1008number1008
229-01-NODE_109198number109198
229-01-NODE_121573number121573
```

```
