### ISSUE TITLE
Your email address

### ISSUE THREAD

**Issue by jmbraverman** [shenwei356/seqkit#75]
These pages display your email address:  "Email me for any problem when using seqkit. shenwei356(at)gmail.com" . However, when I wrote to seqkit.shenwei356@gmail.com, a message came back stating that account does not exist.

**Comment by shenwei356** [comment]
no 'seqkit' of cause.

**Comment by shenwei356** [comment]
> Email me for any problem when using seqkit. shenwei356(at)gmail.com

There's a space between them.
