### ISSUE TITLE
Advanced regex supported?

### ISSUE THREAD

**Issue by 0ssH** [shenwei356/seqkit#76]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
* [x] provide a reproducible example

Hi,
love the tool! 
I tried extracting some seqeunces from protein fastas using the grep function with regex and negative lookahead:
`seqkit grep test.faa -r -p contig(?!.+varpep) -o test.fasta`
It gives me: `[ERRO] error parsing regexp: invalid or unsupported Perl syntax: "(?!" `
Am I just using the regex wrong or is it not supported?
The headers look like this:
>generic|10000001|G_contig_gene80559_1
>generic|10000043|G_contig_gene379_2.varpep.1

Cheers!

**Comment by shenwei356** [comment]
Sorry, it's not supported.

> The syntax of the regular expressions accepted is the same general syntax used by Perl, Python, and other languages. More precisely, it is the syntax accepted by RE2 and described at https://golang.org/s/re2syntax, except for \C. 

    (?!re) | before text not matching re (NOT SUPPORTED)



[Syntax](https://github.com/google/re2/wiki/Syntax)

**Comment by 0ssH** [comment]
Ok, thanks for the swift answer!
