### ISSUE TITLE
seqkit concat for unidentical sequence IDs

### ISSUE THREAD

**Issue by codymowery** [shenwei356/seqkit#77]
Is there a variation of seqkit concat that will work with fastqs with unidentical read IDs? We are trying to combine read1 sequences with the i5 index sequences cluster by cluster, and the different reads have different sequence IDs off the NovaSeq. Thanks!

File1.fq
```
@SIM:1:FCX:1:15:6329:1045 **1**:N:0:2
TCGCACTCAACGCCCTGCATATGACAAGACAGAATC
+
<>;##=><9=AAAAAAAAAA9#:<#<;<<<????#=
```

File2.fq
```
@SIM:1:FCX:1:15:6329:1045 **2**:N:0:2
TCGC
+
<>;#
```

    seqkit concat File1.fq File2.fq [unidentical ID flag]

output.fq
```
@SIM:1:FCX:1:15:6329:1045
TCGCACTCAACGCCCTGCATATGACAAGACAGAATCTCGC
+
<>;##=><9=AAAAAAAAAA9#:<#<;<<<????#=<>;#
```

**Comment by shenwei356** [comment]
try using `seqkit mutate -i `  to insert one sequence at beginning or end of all records.

https://bioinf.shenwei.me/seqkit/usage/#mutate

**Comment by codymowery** [comment]
Thank you for your response! Sorry for not being fully clear, though.. I do not want to insert a single sequence at the beginning of all reads, but rather want perform the same operation as with `seqkit concat`: combine read1 and i5 index read files on a cluster-by-cluster basis. 

Thus, I’d be adding one of several sequences to the beginning of every read1 sequence. 

Thanks again!

**Comment by shenwei356** [comment]
I get confused now.

The example `File1.fq` and `File2.f`q you gave have SAME sequence IDs `SIM:1:FCX:1:15:6329:1045` . The default concat operation can outputs exactly what you want same as that in `output.fq`.

``` text
[shenwei@BioS tmp]$ cat File1.fq 
@SIM:1:FCX:1:15:6329:1045 **1**:N:0:2
TCGCACTCAACGCCCTGCATATGACAAGACAGAATC
+
<>;##=><9=AAAAAAAAAA9#:<#<;<<<????#=

[shenwei@BioS tmp]$ cat File2.fq 
@SIM:1:FCX:1:15:6329:1045 **2**:N:0:2
TCGC
+
<>;#

[shenwei@BioS tmp]$ seqkit concat File1.fq File2.fq 
[INFO] read file: File1.fq
[INFO] 1 records loaded
[INFO] read file: File2.fq
[INFO] 1 records loaded
@SIM:1:FCX:1:15:6329:1045
TCGCACTCAACGCCCTGCATATGACAAGACAGAATCTCGC
+
<>;##=><9=AAAAAAAAAA9#:<#<;<<<????#=<>;#
```

**Comment by codymowery** [comment]
My apologies! I really should've tested before asking.. I didn't expect seqkit to tolerate the additional header info that includes read number, but it works just fine for me. Sorry for the trouble, and thanks for a great package!
