### ISSUE TITLE
seqkit seq filter (-m/-M and maybe others) for paired-end files

### ISSUE THREAD

**Issue by matrs** [shenwei356/seqkit#79]
Hey Wei Shen, thanks for your software, as usual works as expected and it's pretty well documented.

This is a feature request.
I was trying to filter sequences by length using `seqkit seq -m N` and reading the documentation, I noticed that there isn't any guarantee about working with paired-end sequences. I would like to use this kind of filtering on paired-end sequences and to have discarded both reads in cases where the filter is applied to only one read of the pair, hence I can get  properly paired files at the end of the process, or more precisely, the output should be a pair of files as properly/improperly paired as the input files, I do not expect `seqkit` to help me with wrongly-paired input files, that would be another entire problem.

I don't know if this kind of problem is in the "radar" of `seqkit`, what do you think?

**Comment by shenwei356** [comment]
Hi,  `seqkit` was originally designed for FASTA format, so most of the commands mainly handle FASTA or single FASTQ files, but we can process paired FASTQ files simultaneously.

For these processes that can output unpaired-end FASTQ files, including `seqkit grep -m/-M`, we can filter two files separately and [retrieve paired-ends at the end](https://bioinf.shenwei.me/seqkit/faq/#how-to-extract-paired-reads-from-two-paired-end-reads-file).

**Comment by matrs** [comment]
I see, thanks for your answer :)
