### ISSUE TITLE
sliding command 

### ISSUE THREAD

**Issue by germelcar** [shenwei356/seqkit#8]
Hi there:

I have been using seqkit for a couple of days and I have to say that it works like a charm, works very well. I have an issue for the "sliding" command. Would be great to add a parameter to the sliding command in order to skeep over those windows with length less than the windows size specified. For example, por the given sequence:

> GHTELKAVTPDVSSMAMNHKADVEALVGATFSTFEPVSYSTQVVAGTNYKILVNVGNDMQ
VDMVVHKTLPHAGGNTSLTSAAHLPVQVQANVNLGVGIGL

A slidiing with windows size = 2 and step = 1, the last window will be only the letter "L".

I think that a simple condition would be enough for that option (and adding the argument). Maybe something like `if e > l { continue }` before the condition of line 114 works well.

Thanks in advance.

**Comment by shenwei356** [comment]
Thank @germelcar for your valuable advice, I've added a option `-g/--greedy` to export last subsequences even shorter than windows size. It will act as you want in default stat.

Two flags `-m/--min-len` and `-M/--max-len` are also added to `seqkit seq`, which can also be used to filter subsequences shorter than the window size.

The pre-release version [v0.5.0-dev](https://github.com/shenwei356/seqkit/releases/tag/v0.5.0-dev) is available now.

**Comment by shenwei356** [comment]
Please check the latest version, [v0.5.0](https://github.com/shenwei356/seqkit/releases/tag/v0.5.0)+
