### ISSUE TITLE
seqkit amplicon missing from version 0.10.2

### ISSUE THREAD

**Issue by ChristinaGalonska** [shenwei356/seqkit#82]
Hi there, 

I'd love to use seqkit amplicon which is nicely described in the usage section. However, it's not part of the current version 0.10.2 (downloaded from Anaconda cloud). Will it be added soon? Please help! :)

**Comment by shenwei356** [comment]
Glad you like it. This command is ready for but not released yet.

Try the pre-release:

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3574026/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/3574027/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3574025/seqkit_darwin_amd64.tar.gz)

**Comment by shenwei356** [comment]
BTW, primers containing degenerate base are not supported yet.

**Comment by ChristinaGalonska** [comment]
Cool got it! Tested the pre-release and it works like a charm. Many thanks! :)

**Comment by ChristinaGalonska** [comment]
Perhaps one tiny suggestion: When you specify flanking regions using -r x:y
-f the output fastq contains also sequences where x and y can be shorter
than what you specified through the settings. E.g. -r 50:70 -f would also
give you reads where the amplicon is only flanked by 49 positions 5' and 60
positions 3'. Woud be nice to include a flag that prevents this.

Am Mi., 4. Sept. 2019 um 12:28 Uhr schrieb Wei Shen <
notifications@github.com>:

**Comment by shenwei356** [comment]
a new flag `-s/--strict-mode`  added

- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3575340/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3575342/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/3575343/seqkit_windows_amd64.exe.tar.gz)

**Comment by ChristinaGalonska** [comment]
Awesome :)

Am Mi., 4. Sept. 2019 um 17:36 Uhr schrieb Wei Shen <
notifications@github.com>:

**Comment by ChristinaGalonska** [comment]
How do you have to define the --strict-mode flag? Just adding it gives the error "flag accessed but not definied: strict

**Comment by shenwei356** [comment]
Oh, sorry, such a silly bug.
-  [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3589814/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/3589815/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3589817/seqkit_darwin_amd64.tar.gz)
