### ISSUE TITLE
TODO: seqkit amplicon: support primers containing degenerate base

### ISSUE THREAD

**Issue by shenwei356** [shenwei356/seqkit#83]

**Comment by tseemann** [comment]
How will you score degenerate matches with the %identity cut-off?

eg.  R vs A  ,   R vs R  etc

**Comment by shenwei356** [comment]
How about , 1/x * 1/y, where x/y is number of bases belong to a degenerate base.

e.g.,

```
R vs A: 1/2 * 1 = 0.5
R vs R: 1/2 * 1/2 = 0.25

N vs A: 1/4 * 1 = 0.25
```

Wait, in a PCR reaction, when primer and templates are sufficient, they should be matched. Is scoring needed?

**Comment by tseemann** [comment]
Primer to template matching is complicated.   The 3'-end and 5'-end have different weight of importance in binding.  Might be good to have a linear weight match model. But for naive matching, 80% threshold is often used.

**Comment by shenwei356** [comment]
Degenerate base is supported now. 

The scoring is too complicated and beyond the scope of this tool.  I won't dig deeper.
