### ISSUE TITLE
MAX sequence length 

### ISSUE THREAD

**Issue by wangdi2014** [shenwei356/seqkit#84]
I got the following error when I tried to locate some motifs in a very long sequence.

panic: runtime error: index out of range

goroutine 38 [running]:
github.com/shenwei356/bio/seq.(*Seq).ComplementInplace.func1(0xc0000a60f0, 0xc000070000, 0xc000026130, 0xc0000c46e0, 0xc3871, 0x1870e3)
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seq/seq.go:372 +0xaf
created by github.com/shenwei356/bio/seq.(*Seq).ComplementInplace
	/home/shenwei/shenwei/scripts/go/src/github.com/shenwei356/bio/seq/seq.go:369 +0x1b6
[ERRO] xopen: no content
panic: runtime error: index out of range

Then, I made the sequence shorter. The seqkit works fine and I got what I need.

My question is, is there any limitation for the length of the sequence for seqkit?

Thanks!

**Comment by shenwei356** [comment]
How long and what's the command?

**Comment by shenwei356** [comment]
I think it because of some invalid DNA letters, check with

    seqkit seq -t DNA seq.fa > /dev/null

**Comment by shenwei356** [comment]
Fixed the panic:

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3586834/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/3586835/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3586833/seqkit_darwin_amd64.tar.gz)

**Comment by wangdi2014** [comment]
Thanks. The fixed version works very well. Sorry for my slow response!
