### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by bsipos** [shenwei356/seqkit#86]
Hi,

Would it be much trouble to issue a release for seqkit and csvtk? It would be much easier to distribute the new functionality to user from bioconda.

Cheers,
Botond

**Comment by shenwei356** [comment]
I was really busy rencently, will release them tonight.

**Comment by bsipos** [comment]
Thanks a lot!

**Comment by shenwei356** [comment]
Would you like to add some examples to [usage.md](https://github.com/shenwei356/seqkit/blob/master/doc/docs/usage.md) for  these commands? fish, watch, sana, bam.

**Comment by bsipos** [comment]
Oops! It seems I forgot to commit a merge resolution. Will do a PR with those examples in a second.
