### ISSUE TITLE
subseq return fasta with feature name from GFF

### ISSUE THREAD

**Issue by timedreamer** [shenwei356/seqkit#89]
Hi Wei,

 I wonder whether the `seqkit subseq` can return fasta files with the **feature** name in the fasta name.

 For example, run `seqkit subseq --gtf Osativa_323_v7.0.gene.gff3.gz --chr Chr5 --feature gene Osativa_323_v7.0.fa.gz>test.fa` will return fasta files with the gene name in the fasta name.  Something like `>GENENAME_LOCATION`

 Currently, it returned the location as the fasta name.

```
>Chr5_4003-4356:+
```

 Anyhow, very nice tool!

Best,
Ji

**Comment by shenwei356** [comment]
gff file is not supported, you may need to convert feature files.

**Comment by timedreamer** [comment]
Thank you for the quick response. I will try to convert gff3 to gtf after I'm back to work.

**Comment by timedreamer** [comment]
Solved. You are right. It works after converting gff3 to gtf and doing some modifications on the gtf file.
Thanks!
