### ISSUE TITLE
Feature request for `seqkit seq -m` - Do not remove gaps

### ISSUE THREAD

**Issue by vmikk** [shenwei356/seqkit#90]
Hello!

I would like to propose to add a new flag for `seqkit seq` for filtering sequences by length with `-m` or `-M` that will not remove gaps.
For example, this feature will be very useful for removing small sequences (without consideration of gaps) from alignments.

Currently, seqkit will drop all gaps and distort the alignment:

```
seqkit seq -m 100 aln.fasta
  [INFO] flag -g (--remove-gaps) is switched on when using -m (--min-len) or -M (--max-len)
```

Thank you for the great software!
With best regards,
Vladimir

### Prerequisites
- [x] make sure you're are using the latest version by `seqkit version` - `v0.11.0`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

**Comment by shenwei356** [comment]
changed: 
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3820566/seqkit_darwin_amd64.tar.gz)
- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3820567/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/3820568/seqkit_windows_amd64.exe.tar.gz)

**Comment by vmikk** [comment]
That's great thank you! You are very fast!
