### ISSUE TITLE
Handling of duplicate names in fasta (seqkit locate)

### ISSUE THREAD

**Issue by SheaML** [shenwei356/seqkit#94]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
`seqkit v0.11.0`

- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem

For `seqkit locate`, if the pattern file fasta (`-f`) has duplicated names, seqkit will (silently) use the last sequence with the duplicate name. Would be good to either allow duplicate names or warn/error if the fasta contains duplicate names. 

* [x] provide a reproducible example

`pattern.fasta` :
```
>Name1
ATT
>Name1
TAT
```

```
$ seqkit locate -f pattern.fasta <(printf '>Aseq\nATTAT')
seqID	patternName	pattern	strand	start	end	matched
Aseq	Name1	TAT	+	3	5	TAT
```

```
$ seqkit locate -f <(head -n 2 pattern.fasta) <(printf '>Aseq\nATTAT')
seqID	patternName	pattern	strand	start	end	matched
Aseq	Name1	ATT	+	1	3	ATT
```

**Comment by shenwei356** [comment]
useing 'seqkit rename' first to make names unique.

**Comment by shenwei356** [comment]
```
$ seqkit locate -f <(seqkit rename pattern.fasta | seqkit seq -i ) <(printf '>Aseq\nATTAT\n') -i \
    | csvtk pretty -t
seqID   patternName   pattern   strand   start   end   matched
Aseq    Name1         ATT       +        1       3     ATT
Aseq    Name1_2       TAT       +        3       5     TAT
```
