### ISSUE TITLE
Question: Six frame translate at once

### ISSUE THREAD

**Issue by alienzj** [shenwei356/seqkit#96]
### Prerequisites

- [x] make sure you're are using the latest version by `seqkit version`
- [x] read the [usage](http://bioinf.shenwei.me/seqkit/usage/)

### Describe your issue

* [x] describe the problem
Hi, Shen,
Does seqkit support six frame translate at once?
According to my observation, the `transeq` (`EMBOSS`) support this feature.

* [ ] provide a reproducible example
When I master go programming language, I will try to add this feature.

So great tool!
So nice!

**Comment by shenwei356** [comment]
Supported now:

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3875439/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/3875440/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/3875437/seqkit_darwin_amd64.tar.gz)
