### ISSUE TITLE
fqidx feature

### ISSUE THREAD

**Issue by jamesthegiantpeach** [shenwei356/seqkit#97]
Greetings! 

The most recent release of samtools has a fastq index/extract function called fqidx that acts similarly to faidx. Is this implemented in this package? If not, I would be interested in helping implement this.

**Comment by shenwei356** [comment]
Not supported here, it would be great if you can implement this.

**Comment by jamesthegiantpeach** [comment]
Hi Shen,

Circling back to this. I had tested this idea out, and on full genomes I found it to be wildly impractical producing an index almost the size of the genome.
