### ISSUE TITLE
seqkit locate column length error

### ISSUE THREAD

**Issue by devonorourke** [shenwei356/seqkit#98]
Hello Wei Shen,
Thank you for creating and maintaining seqkit. I am experiencing an error message when running the `seqkit location` function:

```
column: line too long
```

The error message appears many times in the .log file. My goal is to identify the start/end positions of the ambiguous **N** characters in a fasta file. This vertebrate genome contains tens of thousands of multi-N substrings (among approximately 60,000 scaffolds in the fasta file), some of which have lengths of **N** characters exceeding 2kb.

It looks like the [print output is set](https://github.com/shenwei356/seqkit/blob/master/seqkit/cmd/locate.go#L182) to always include the same columns of information: seqID, patternName, pattern, strand, start, end, and matched. I was wondering if there would be a way to turn off the **matched** substring - perhaps this would avoid the column error I'm seeing?

I've tried to determine if it truly is just a length of string issue, but this tiny reprex doesn't appear to suggest that even a 20kb long string of **N**'s will cause any issue: _the job finishes just fine without error_. I'm therefore entirely unclear what they `column: line too long` error may indicate. 

```
val1=">seq1_tenN"
val2=$(printf 'N%.0s' {1..10})
val3=">seq2_hundredN"
val4=$(printf 'N%.0s' {1..100})
val5=">seq3_thousandN"
val6=$(printf 'N%.0s' {1..1000})
val7=">seq4_tenthousandN"
val8=$(printf 'N%.0s' {1..10000})
val9=">seq5_twentythousandN"
val10=$(printf 'N%.0s' {1..20000})

printf "$val1\n$val2\n$val3\n$val4\n$val5\n$val6\n$val7\n$val8\n$val9\n$val10" > test.fasta

cat test.fasta | $SEQKIT locate --ignore-case --only-positive-strand --pattern "N+" > outfile
```

Thanks for any thoughts you might share,
Devon

**Comment by shenwei356** [comment]
I can't figure out what caused `column: line too long` neither.

Anyway, printing matched sequence should be optional. For backward compatibility, a flag is added to disable showing matched seqs:

      -M, --hide-matched              do not show matched sequences

Please use the pre-releases:

- [seqkit_linux_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4008110/seqkit_linux_amd64.tar.gz)
- [seqkit_windows_amd64.exe.tar.gz](https://github.com/shenwei356/seqkit/files/4008111/seqkit_windows_amd64.exe.tar.gz)
- [seqkit_darwin_amd64.tar.gz](https://github.com/shenwei356/seqkit/files/4008109/seqkit_darwin_amd64.tar.gz)
