### ISSUE TITLE
seqkit split2 error for paired end fastq files

### ISSUE THREAD

**Issue by WortJohn** [shenwei356/seqkit#99]
@shenwei356 
When i run "seqkit split2" command in slurm cluster management system, the following error occurs. And when i run it in local, the error also occurs. But when i run it only with single end read (like 'seqkit split2 -p 40 -1 R04389ASS1N1_R1.fastq.gz -O R04389ASS1N1.split'),  the error does not occur.

```
$ rm -rf R04389ASS1N1.split2
$ sbatch -J split2 -N 1 -n 20 -o log2.o -e log2.e --wrap "seqkit split2 -p 40 -1 R04389ASS1N1_R1.fastq.gz -2 R04389ASS1N1_R2.fastq.gz -O R04389ASS1N1.split2"
$ cat log2.e 
[INFO] flag -1/--read1 and -2/--read2 given, ignore: -
[INFO] split seqs from R04389ASS1N1_R1.fastq.gz and R04389ASS1N1_R2.fastq.gz
[INFO] split into 40 parts
[ERRO] unlinkat ./R04389ASS1N1.split2: directory not empty

$ seqkit version
seqkit v0.11.0
Checking new version...
You are using the latest version of seqkit
```

**Comment by shenwei356** [comment]
I can't reproduce this, please try again by adding `--force`.

**Comment by WortJohn** [comment]
It works well according to your advice. Thank you very much.

**Comment by bioinfoMMS** [comment]
I am also getting the error but it only occurs sometimes. I have used the same command on the same data multiple times and quite often I get this error. I have been using '--force' parameter. I am using v0.11.0 and the slurm cluster management system as well.

**Comment by shenwei356** [comment]
v0.11.0 is too old (2019-09-25), please update to the latest version (v2.3.1).

**Comment by bioinfoMMS** [comment]
Trying the most recent version now, thanks! I realized after I commented that there were more recent version..sorry about that
